# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome } : Mana yang lebih baik?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Kami membandingkan { -brand-name-mozilla } { -brand-name-firefox } dengan { -brand-name-google } { -brand-name-chrome } dalam hal privasi, utilitas, dan portabilitas

# Main title.
compare-chrome-comparing-firefox-browser = Membandingkan { -brand-name-firefox-browser } dengan { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Di { -brand-name-firefox } , kami memiliki sejumlah besar pengguna berdedikasi yang menghargai dedikasi teguh kami terhadap privasi daring. Misalnya, versi terbaru { -brand-name-firefox } menyertakan fitur yang disebut Enhanced Tracking Protection (ETP) yang diaktifkan secara bawaan untuk semua pengguna di seluruh dunia. ETP memblokir lebih dari 2.000 pelacak, termasuk pelacak sosial dari perusahaan seperti { -brand-name-facebook } , { -brand-name-twitter } , dan LinkedIn. Ia juga memiliki fitur terintegrasi yang disebut <a { $attrs }>{ -brand-name-firefox-monitor }</a> yang secara otomatis memberi tahu Anda jika sandi Anda telah dilanggar atau perlu diperbarui. Selain perlindungan ini, mode Penjelajahan Pribadi di { -brand-name-firefox } secara otomatis menghapus informasi penjelajahan Anda seperti riwayat dan cookie, tidak meninggalkan jejak setelah Anda menyelesaikan sesi.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Di { -brand-name-firefox } , kami memiliki sejumlah besar pengguna berdedikasi yang menghargai dedikasi teguh kami terhadap privasi daring. Misalnya, versi terbaru { -brand-name-firefox } menyertakan fitur yang disebut Enhanced Tracking Protection (ETP) yang diaktifkan secara bawaan untuk semua pengguna di seluruh dunia. ETP memblokir lebih dari 2.000 pelacak, termasuk pelacak sosial dari perusahaan seperti { -brand-name-facebook } , { -brand-name-twitter } , dan LinkedIn. Ia juga memiliki fitur terintegrasi yang disebut <a { $attrs }>{ -brand-name-firefox-monitor }</a> yang secara otomatis memberi tahu Anda jika sandi Anda telah dilanggar atau perlu diperbarui. Selain perlindungan ini, mode Penjelajahan Pribadi { -brand-name-firefox } secara otomatis menghapus informasi penjelajahan Anda seperti riwayat dan cookie, tidak meninggalkan jejak setelah Anda menyelesaikan sesi.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Kami juga baru-baru ini menyatakan kembali komitmen kami terhadap privasi dan transparansi terkait data pengguna dalam <a { $attrs }>Pemberitahuan Privasi</a> terbaru kami yang menyatakan, &quot;Di Mozilla, kami percaya bahwa privasi adalah hal mendasar untuk internet yang sehat.&quot;
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } pada semua akun adalah peramban yang aman, dengan fitur seperti { -brand-name-google } Penjelajahan Aman, yang membantu melindungi pengguna dengan menampilkan peringatan yang tidak mungkin terlewatkan saat mereka mencoba menavigasi ke situs berbahaya atau mengunduh file berbahaya.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Pada akhirnya, terserah Anda untuk memutuskan apakah atau tidak atau di mana harus menarik garis dengan berbagi hal-hal seperti riwayat pencarian dan riwayat belanja. Tetapi jika Anda seperti kebanyakan orang, Anda mungkin telah mencari beberapa hal di internet yang ingin Anda rahasiakan.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Maju cepat hingga hari ini, lanskap kompetitif untuk browser telah berubah dengan banyak orang mulai mempertanyakan apa yang terjadi dengan data online mereka seperti riwayat penelusuran, sandi, dan informasi sensitif lainnya. Banyak yang telah berubah sejak 2008 ketika { -brand-name-chrome } muncul. Di { -brand-name-firefox } , kami sedang menundukkan kepala, bekerja untuk mendesain ulang antarmuka kami dan menyediakan pengguna dengan privasi dan kinerja yang terus bertambah serta banyak alat peramban yang berguna.
compare-chrome-and-so-here-we-are-the-browser = Dan di sinilah kita, perang peramban memanas sekali lagi dan inilah waktunya untuk mengevaluasi ulang dan membandingkan { -brand-name-firefox-browser } vs { -brand-name-google } { -brand-name-chrome } .
compare-chrome-in-2008-google-introduced = Pada tahun 2008, { -brand-name-google } diperkenalkan { -brand-name-chrome } , dan dampaknya sebagai inovasi dalam teknologi peramban langsung terlihat. Itu lebih cepat untuk memuat situs, mengambil ruang layar minimal dan menawarkan antarmuka pengguna yang sederhana.
compare-chrome-in-fact-both-chrome-and-firefox = Faktanya, { -brand-name-chrome } dan { -brand-name-firefox } memiliki keamanan yang ketat. Keduanya menyertakan hal yang disebut "kotak pasir" yang memisahkan proses browser sehingga sesuatu seperti situs web berbahaya tidak menginfeksi bagian lain dari laptop atau perangkat Anda.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Meskipun { -brand-name-chrome } terbukti sebagai peramban web yang aman, catatan privasinya patut dipertanyakan. { -brand-name-google } sebenarnya mengumpulkan data dalam jumlah besar yang mengganggu dari penggunanya termasuk lokasi, riwayat penelusuran, dan kunjungan situs. { -brand-name-google } membuat kasus pengumpulan data mengatakan bahwa mereka melakukannya untuk meningkatkan layanan - seperti membantu Anda menemukan sweter atau kedai kopi seperti yang Anda beli atau kunjungi sebelumnya. Namun, orang lain mungkin tidak setuju, dengan menegaskan bahwa { -brand-name-google } sebenarnya mengumpulkan data dalam jumlah yang belum pernah terjadi sebelumnya untuk tujuan pemasarannya sendiri. Mereka menggembar-gemborkan bahwa mereka merahasiakan informasi Anda dari peretas, tetapi itu tidak penting. { -brand-name-google } sendiri menjalankan jaringan periklanan terbesar di dunia, sebagian besar berkat data yang mereka kumpulkan dari pengguna mereka.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Dari segi fitur, { -brand-name-firefox } dan { -brand-name-chrome } menawarkan pustaka besar ekstensi dan pengaya, dengan katalog { -brand-name-chrome } jauh melebihi jumlah peramban lain sementara terintegrasi dengan baik dengan layanan { -brand-name-google } , seperti Gmail dan { -brand-name-google } Dokumen.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } juga memiliki fitur sinkronisasi untuk melihat tab terbuka dan terkini, riwayat perambanan, dan bookmark di semua perangkat Anda.
compare-chrome-while-chrome-gets-the-nod = Sementara { -brand-name-chrome } mendapat anggukan dengan pengaya dan ekstensi, { -brand-name-firefox } memiliki serangkaian fitur bawaan yang dikurasi dengan baik, seperti alat penangkap layar yang sangat berguna, dan fitur mode membaca yang menghapus segala sesuatu dari laman kecuali teks dari artikel yang Anda baca.
compare-chrome-although-not-as-extensive = Meskipun tidak seluas pustaka pengaya { -brand-name-chrome } , { -brand-name-firefox } , sebagai perangkat lunak sumber terbuka dengan kontributor aktif dalam jumlah besar, juga dilengkapi dengan banyak sekali ekstensi yang berguna.
compare-chrome-if-having-tons-of-open-tabs = Jika memiliki banyak tab terbuka adalah urusan Anda, maka itu benar-benar tergantung pada preferensi UI Anda. { -brand-name-firefox } menampilkan gulir horizontal pada semua tab terbuka Anda daripada mengecilkannya dan semakin kecil dengan setiap tab baru. { -brand-name-google } { -brand-name-chrome } lebih suka mengecilkannya sehingga hanya favicon yang terlihat. Satu-satunya masalah adalah saat Anda membuka banyak tab dari situs web yang sama, jadi Anda melihat favicon yang sama di seluruh tab Anda.
compare-chrome-almost-needless-to-say-versions = Hampir tidak perlu dikatakan lagi, versi { -brand-name-firefox } dan { -brand-name-chrome } tersedia untuk sistem operasi seluler dan desktop terpopuler ( { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ).
compare-chrome-both-chrome-and-firefox-also = Baik { -brand-name-chrome } dan { -brand-name-firefox } juga memungkinkan Anda untuk menyinkronkan hal-hal seperti sandi, bookmark, dan tab terbuka di semua perangkat Anda. Jika Anda memiliki akun { -brand-name-firefox } , Anda dapat secara manual mengirim tab terbuka di desktop ke perangkat seluler Anda atau sebaliknya. Dengan { -brand-name-chrome } , ini dilakukan secara otomatis jika Anda telah memilih pengaturan itu dalam preferensi Anda. Tidak perlu mengirim tab secara manual dari satu perangkat ke perangkat lainnya adalah nyaman ketika Anda ingin melakukan sesuatu seperti melanjutkan membaca artikel yang belum Anda selesaikan sebelumnya. Namun ada kalanya sinkronisasi otomatis mungkin tidak ideal jika ada kemungkinan beberapa pengguna meramban saat masuk ke akun { -brand-name-google } .

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Kami pikir adil untuk mengatakan { -brand-name-firefox } dan { -brand-name-chrome } benar-benar leher dan leher dalam hal portabilitas dan utilitas, dengan { -brand-name-chrome } memiliki sedikit keunggulan dalam utilitas karena perpustakaan besar ekstensi dan fitur pengaya. Namun dalam hal Privasi, { -brand-name-firefox } memenangkan hari dengan komitmen kami untuk menjaga data online pengguna kami dan menyediakan layanan gratis seperti pengelola kata sandi yang juga mengingatkan Anda jika terjadi pelanggaran data yang melibatkan kredensial Anda.
compare-chrome-as-for-customization-our = Untuk penyesuaian, penggemar kami akan memberi tahu Anda salah satu hal yang paling mereka sukai dari browser kami adalah kemampuannya untuk memungkinkan Anda memindahkan dan mengatur sebagian besar elemen UI agar sesuai dengan kebutuhan Anda. { -brand-name-chrome } memungkinkan Anda menyembunyikan elemen UI tertentu tetapi tidak banyak kelonggaran, jika ada, untuk memindahkan berbagai hal berdasarkan preferensi Anda. Namun, harus diperhatikan bahwa { -brand-name-chrome } dan { -brand-name-firefox } membuatnya sangat mudah untuk mengubah tampilan dan tema peramban Anda.
compare-chrome-for-practical-purposes-theres = Untuk tujuan praktis, jelas tidak ada yang menghalangi Anda untuk menggunakan kedua peramban— { -brand-name-firefox } untuk momen-momen dalam hidup ketika privasi benar-benar penting, dan { -brand-name-chrome } jika Anda masih berinvestasi dalam ekosistem { -brand-name-google } . Namun dengan semakin banyaknya penyusupan ke data pribadi kita, { -brand-name-firefox } mungkin terbukti menjadi pilihan yang tepat dalam jangka panjang bagi kita yang menghargai perlindungan privasi pribadi kita secara online.
