# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Tujuh dari browser terbaik dalam perbandingan langsung
compare-index-six-of-the-best-browsers-fallback = Enam dari browser terbaik dalam perbandingan langsung

# Sub-headline
compare-index-privacy-utility-portability = Pribadi. Utilitas. Portabilitas.

# HTML page description
compare-index-a-great-internet-browser-should = Browser internet yang hebat harus memiliki fungsionalitas yang Anda butuhkan, portabilitas di seluruh perangkat, dan privasi yang layak Anda dapatkan.
compare-index-which-browser-is-best-at-keeping = Peramban mana yang paling baik dalam menjaga kerahasiaan?
compare-index-its-not-unreasonable-to-expect = Bukan tidak masuk akal untuk mengharapkan perlindungan data dan privasi tingkat tinggi dari produk yang biasa kami gunakan untuk online. Minimal, browser harus menawarkan beberapa versi "mode penjelajahan pribadi" yang secara otomatis menghapus riwayat dan riwayat penelusuran Anda sehingga pengguna lain di komputer yang sama tidak dapat mengaksesnya. Di area ini, ketujuh browser yang dibandingkan di sini mencetak poin.
compare-index-its-not-unreasonable-to-expect-fallback = Bukan tidak masuk akal untuk mengharapkan perlindungan data dan privasi tingkat tinggi dari produk yang biasa kami gunakan untuk online. Minimal, browser harus menawarkan beberapa versi "mode penjelajahan pribadi" yang secara otomatis menghapus riwayat dan riwayat penelusuran Anda sehingga pengguna lain di komputer yang sama tidak dapat mengaksesnya. Di area ini, keenam browser yang dibandingkan di sini mencetak poin.
compare-index-what-you-do-online-literally = Apa yang Anda lakukan secara online seharusnya tidak menjadi urusan orang lain.
compare-index-another-browser-feature-that = Fitur browser lain yang harus diberikan adalah kemampuan untuk mencegah situs web dan perusahaan melacak data penjelajahan dan belanja Anda - bahkan dalam mode penjelajahan normal.
compare-index-another-browser-feature-fallback = Fitur browser lain yang harus diberikan adalah kemampuan untuk mencegah situs web dan perusahaan melacak data penjelajahan dan belanja Anda - bahkan dalam mode penjelajahan normal. Namun sebenarnya tidak demikian: faktanya, satu-satunya peramban yang memblokir kuki pelacakan pihak ketiga secara bawaan adalah { -brand-name-firefox } dan { -brand-name-safari } .
compare-index-using-a-browser-that-blocks = Menggunakan peramban yang memblokir pelacak pihak ketiga tidak hanya penting untuk privasi - ini biasanya berarti peramban juga berjalan lebih cepat. Kebanyakan pelacak hanyalah skrip yang berjalan di latar belakang di sejumlah situs web. Anda tidak dapat melihatnya, tetapi Anda dapat merasakannya memperlambat browser Anda. Mulai versi 67 { -brand-name-firefox } , sidik jari dan cryptominers juga diblokir. Jika Anda tidak terbiasa dengan cryptominers, berikut adalah contoh bagaimana mereka dapat mempengaruhi Anda: mungkin Anda pernah mengalami komputer Anda tiba-tiba menjadi lebih panas atau baterai habis lebih cepat dari biasanya. Itu sering kali merupakan produk sampingan dari cryptominers yang merayap di perangkat Anda.
compare-index-what-has-your-browser-done = Apa yang telah dilakukan browser Anda akhir-akhir ini?
compare-index-in-addition-to-privacy-protection = Selain perlindungan privasi, yang sebagian besar terjadi di latar belakang browser, bahan utama lain untuk browser yang dibuat dengan baik adalah antarmuka dan fungsionalitas pengguna yang sebenarnya. Hampir ketujuh browser sama dalam hal penjelajahan tab, manajemen bookmark, pelengkapan otomatis, koreksi, dan ekstensi. { -brand-name-firefox } , { -brand-name-edge } dan { -brand-name-opera } juga menawarkan fungsi tangkapan layar cepat yang terbukti sangat berguna dan pasti ada sesuatu yang Anda perhatikan hilang saat Anda beralih ke peramban tanpanya.
compare-index-in-addition-to-privacy-protection-fallback = Selain perlindungan privasi, yang sebagian besar terjadi di latar belakang browser, bahan utama lain untuk browser yang dibuat dengan baik adalah antarmuka dan fungsionalitas pengguna yang sebenarnya. Hampir semua enam browser sama dalam hal penjelajahan tab, manajemen bookmark, pelengkapan otomatis, koreksi, dan ekstensi. { -brand-name-firefox } , { -brand-name-edge } dan { -brand-name-opera } juga menawarkan fungsi tangkapan layar cepat yang terbukti sangat berguna dan pasti ada sesuatu yang Anda perhatikan hilang saat Anda beralih ke peramban tanpanya.
compare-index-how-well-does-your-browser = Seberapa baik browser Anda bekerja di seluruh perangkat Anda?
compare-index-almost-all-of-the-browsers = Hampir semua browser yang dibandingkan di sini memungkinkan sinkronisasi antara desktop dan perangkat seluler. Anda memerlukan akun untuk melakukannya, yang dapat Anda gunakan untuk masuk ke browser di semua perangkat dan menyinkronkan hal-hal seperti kata sandi, riwayat penelusuran, bookmark, dan pengaturan.
compare-index-conclusion = Kesimpulan:
compare-index-and-the-winner-is = Dan pemenangnya adalah…
compare-index-find-out-how-firefox-chrome = Cari tahu bagaimana perbedaan { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } dan { -brand-name-ie } dalam hal privasi, utilitas, dan portabilitas.
compare-index-find-out-how-firefox-fallback = Cari tahu bagaimana { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } dan { -brand-name-ie } berbeda dalam hal privasi, utilitas, dan portabilitas.
compare-index-looking-for-a-better-browser = Mencari browser yang lebih baik? Kami akan membandingkan { -brand-name-firefox } dengan { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } dan { -brand-name-ie } untuk membantu Anda membuat keputusan.
compare-index-looking-for-a-better-fallback = Mencari browser yang lebih baik? Kami akan membandingkan { -brand-name-firefox } dengan { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } dan { -brand-name-ie } untuk membantu Anda membuat keputusan.
compare-index-so-is-your-browser-the-best = Jadi, apakah browser Anda yang terbaik untuk aktivitas online Anda? Browser yang tepat dapat membuat perbedaan besar dalam cara Anda menikmati web. Jadi, tanpa basa-basi lagi, mari bandingkan { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } , { -brand-name-microsoft } { -brand-name-ie } dan { -brand-name-edge } - dan lihat mana yang paling sesuai dengan kebutuhan Anda.
compare-index-so-is-your-browser-the-fallback = Jadi, apakah browser Anda yang terbaik untuk aktivitas online Anda? Browser yang tepat dapat membuat perbedaan besar dalam cara Anda menikmati web. Jadi, tanpa basa-basi lagi, mari bandingkan { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-microsoft } { -brand-name-ie } dan { -brand-name-edge } - dan lihat mana yang paling sesuai dengan kebutuhan Anda.
compare-index-since-your-browser-is-your = Karena browser Anda adalah gerbang Anda ke internet, kecepatan, keamanan, privasi, dan utilitas adalah yang terpenting. Dalam beberapa tahun terakhir, { -brand-name-google } { -brand-name-chrome } telah menjadi peramban pilihan banyak orang. Tetapi pada saat iklan online tampaknya mengikuti kita kemana-mana dan pelanggaran data menjadi bagian utama dari berita utama, banyak orang mulai menuntut lebih banyak privasi dan rasa hormat dari browser mereka.
compare-index-the-first-thing-to-point-out = Hal pertama yang perlu diperhatikan tentang portabilitas adalah bahwa tidak semua browser berjalan di semua sistem operasi. Meskipun { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-brave } dan { -brand-name-opera } bekerja pada semua sistem utama dan mudah dipasang, { -brand-name-ie } dan { -brand-name-safari } hanya bekerja pada { -brand-name-microsoft } dan sistem Apple sendiri. Versi seluler { -brand-name-safari } sudah terpasang sebelumnya di perangkat seluler Apple, dan sebagian besar { -brand-name-android } perangkat dilengkapi dengan peramban terpasang sebelumnya yang dimodifikasi oleh produsen untuk perangkat tersebut. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-brave } , { -brand-name-edge } dan { -brand-name-opera } dapat dengan mudah dipasang dan bahkan digunakan berdampingan.
compare-index-the-first-thing-to-point-fallback = Hal pertama yang perlu diperhatikan tentang portabilitas adalah bahwa tidak semua browser berjalan di semua sistem operasi. Meskipun { -brand-name-firefox } , { -brand-name-chrome } dan { -brand-name-opera } bekerja pada semua sistem utama dan mudah dipasang, { -brand-name-ie } , { -brand-name-edge } dan { -brand-name-safari } hanya bekerja pada { -brand-name-microsoft } dan sistem Apple sendiri. Versi seluler { -brand-name-safari } sudah terpasang sebelumnya di perangkat seluler Apple, dan sebagian besar { -brand-name-android } perangkat dilengkapi dengan peramban terpasang sebelumnya yang dimodifikasi oleh produsen untuk perangkat tersebut. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } dan { -brand-name-opera } dapat dengan mudah dipasang dan bahkan digunakan berdampingan.
compare-index-browsers-have-come-a-long = Peramban telah berkembang pesat sejak { -brand-name-chrome } diperkenalkan dan mengambil alih pangsa pasar. Sebagian besar peramban modern telah menutup celah pada portabilitas dan fungsionalitas, dan di beberapa area, seperti kecepatan dan privasi, sebenarnya telah melampaui { -brand-name-chrome } . Namun, menentukan browser mana yang tepat untuk Anda akan selalu bergantung pada kebutuhan pribadi Anda dan apa yang paling Anda hargai saat Anda menavigasi online.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } didukung oleh organisasi nirlaba { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } mengutamakan privasi Anda - dalam segala hal yang kami buat dan lakukan. Kami yakin Anda memiliki hak untuk memutuskan bagaimana dan dengan siapa Anda membagikan informasi pribadi Anda. { -brand-name-firefox } mengumpulkan data sesedikit mungkin dan tidak pernah menjualnya. Sedikit data yang kami kumpulkan hanya digunakan untuk membuat produk dan fitur menjadi lebih baik. Tidak ada rahasia. Tetapi banyak transparansi dan privasi nyata.
compare-index-based-on-the-criteria-we-outlined = Berdasarkan kriteria yang kami uraikan - privasi, utilitas, dan portabilitas - hanya ada satu browser yang memenuhi kriteria tersebut, dan itu adalah { -brand-name-firefox } . Area perbedaan sebenarnya bukanlah pada fungsionalitas, melainkan privasi. { -brand-name-firefox } adalah peramban paling pribadi yang tidak mengunci Anda ke dalam suatu ekosistem. Gunakan di sistem operasi apa pun, di semua perangkat Anda, dan rasakan aman saat melakukannya.
