# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari } : Peramban manakah yang lebih baik untuk Anda?

# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } adalah peramban yang telah terpasang sebelumnya di { -brand-name-mac } dan { -brand-name-iphone } . Bandingkan { -brand-name-safari } dengan { -brand-name-firefox-browser } untuk mengetahui peramban mana yang lebih baik untuk Anda.

# Main title.
compare-safari-comparing-firefox-browser = Membandingkan { -brand-name-firefox-browser } dengan { -brand-name-apple } { -brand-name-safari }

# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Jika Anda menggunakan Mac atau memiliki { -brand-name-iphone } , kemungkinan Anda sudah tidak asing lagi dengan { -brand-name-safari } peramban web. Fakta bahwa ini telah dipasang sebelumnya sebagai peramban bawaan untuk { -brand-name-apple } pengguna produk benar-benar memberinya keuntungan awal, tetapi { -brand-name-firefox } memiliki serangkaian fitur berguna sendiri yang menjadikannya alternatif yang menarik. Di sini kita akan menjelajahi perbedaan utama antara peramban kita dan { -brand-name-safari } dalam hal privasi, utilitas, dan portabilitas antar perangkat.

# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Privasi telah menjadi topik hangat bagi perusahaan teknologi karena mereka menyadari semakin banyak orang merasa rentan terhadap hal-hal seperti pelanggaran data, pelacak iklan, dan peretas. Tetapi ketika datang ke alat nyata yang digunakan orang untuk menavigasi antar-web yang sebenarnya, apakah itu semua bicara atau mereka benar-benar mengambil tindakan untuk menjaga keamanan data Anda?
compare-safari-as-alluded-to-before-apple-fallback = Seperti disebutkan sebelumnya, { -brand-name-apple } adalah salah satu perusahaan yang baru-baru ini memutuskan untuk meningkatkan permainan privasi mereka. Belum lama ini, { -brand-name-apple } menerapkan pencegahan pelacakan lintas situs di { -brand-name-safari } , yang mencegah iklan mengikuti Anda di internet. { -brand-name-safari } juga menawarkan saran sandi yang kuat saat Anda mendaftar akun baru di situs web mana pun. Dan jika Anda berinvestasi di ekosistem iCloud, itu akan menyinkronkan kata sandi itu dengan aman dengan perangkat Anda yang lain, jadi Anda tidak perlu mengingatnya.

# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Seperti { -brand-name-safari } , kami di { -brand-name-firefox } telah berfokus pada privasi dan keamanan. Tetapi tidak seperti { -brand-name-safari } , kami telah berdiri di kotak sabun privasi untuk waktu yang lama. Faktanya, { -brand-name-mozilla } (perusahaan induk kami) adalah salah satu orang pertama dalam komunitas teknologi yang membunyikan alarm untuk privasi online.

# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Mode Penjelajahan Pribadi kami memblokir pelacak dan menghapus kata sandi, cookie, dan riwayat Anda setiap kali Anda menutupnya. Tetapi Anda juga dapat menikmati fitur privasi lanjutan kami bahkan dalam mode penelusuran biasa. Dengan edisi terbaru { -brand-name-firefox } , pencegahan pelacakan yang ditingkatkan dihidupkan secara bawaan. Ini mencegah hal-hal seperti pelacak lintas situs mengikuti Anda saat Anda menjelajahi web. Selain itu, dengan { -brand-name-facebook } ditangkap hampir setiap hari karena masalah privasi, ekstensi <a { $attrs }>{ -brand-name-facebook-container }</a> kami sangat masuk akal. Ini mempersulit { -brand-name-facebook } untuk melacak Anda di seluruh web - mirip dengan apa yang { -brand-name-safari } lakukan untuk mencegah pelacakan lintas situs - tetapi { -brand-name-firefox } sebenarnya mengisolasi sesi { -brand-name-facebook } ke dalam penampung terpisah yang memblokir { -brand-name-facebook } dari pelacakan apa yang Anda lakukan di situs web lain. Mengapa mereka perlu tahu apa yang Anda cari di WebMD?

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Sejauh keamanan berjalan, { -brand-name-firefox } juga solid di sana. Kapan pun Anda berada di { -brand-name-firefox } , Anda dapat mengeklik kanan di bidang sandi untuk membuat sandi yang kuat dengan aman menggunakan opsi Isi Sandi. Saat Anda menyimpan sandi baru, kami akan meminta Anda untuk menyimpan ke pengelola sandi yang ada di dalamnya, <a { $lockwise }>{ -brand-name-lockwise }</a> . Kami juga melayani pengguna dan pemegang akun dengan produk gratis dan berguna lainnya yang disebut <a { $monitor }>{ -brand-name-monitor }</a> yang secara otomatis memberi tahu Anda jika data Anda termasuk dalam pelanggaran data yang diketahui.
compare-safari-if-you-choose-to-use-safari = Jika Anda memilih untuk menggunakan { -brand-name-safari } , Anda berada di tangan yang aman selama Anda menggunakan perangkat { -brand-name-apple } . Tetapi { -brand-name-safari } hanya bekerja pada { -brand-name-apple } perangkat, sedangkan { -brand-name-firefox } bekerja pada { -brand-name-windows } , { -brand-name-mac } , { -brand-name-ios } , { -brand-name-android } dan { -brand-name-linux } . Jadi, apa pun sistem operasi yang Anda pilih, { -brand-name-firefox } telah melindungi Anda dengan perlindungan keamanan dan privasi kami.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } dikenal luas dengan ekosistem tertutupnya yang berkaitan dengan pembuatan perangkat lunak untuk produknya. Namun di dalam { -brand-name-app-store } , itu memang menawarkan bagian kepada pengembang untuk membuat pengaya dan pengaya untuk membuat peramban lebih kuat. Ekstensi ini juga dapat diramban melalui { -brand-name-app-store } dan dengan mudah ditambahkan ke { -brand-name-safari } .
compare-safari-in-addition-to-the-regular = Selain rangkaian fitur biasa yang Anda harapkan pada peramban, seperti penjelajahan dengan tab dan penjelajahan pribadi, { -brand-name-safari } memiliki beberapa fitur yang tidak diharapkan. Misalnya, jika pengguna mengklik kanan kata di mana pun pada halaman di dalam { -brand-name-safari } , lalu mengklik Cari, mereka akan mendapatkan definisi kamus plus entri dari tesaurus, { -brand-name-app-store } , film, dan lainnya. Kontrol Orang Tua { -brand-name-safari } mudah untuk diubahsuaikan, memungkinkan orang dewasa bernapas sedikit lebih lega saat anak-anak mulai penasaran tentang internet.

# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Seperti { -brand-name-safari } , { -brand-name-firefox } mendorong komunitas pengembangnya yang antusias untuk membuat <a { $attrs }>pengaya dan ekstensi</a> ke peramban. Dan karena platform kami adalah sumber terbuka, ada banyak pilihan yang menambahkan banyak fungsi.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Selain itu, saat Anda mendaftar untuk akun { -brand-name-firefox } Anda mendapatkan akses ke layanan unik seperti <a { $pocket }>{ -brand-name-pocket }</a> dan <a { $send }>{ -brand-name-send }</a> yang terintegrasi langsung ke dalam peramban. Tombol { -brand-name-pocket } untuk { -brand-name-firefox } memungkinkan Anda menyimpan laman web dan video ke { -brand-name-pocket } hanya dengan satu klik, sehingga Anda dapat membaca versi yang bersih dan bebas gangguan kapan pun dan di mana pun Anda mau - bahkan saat offline. Dengan { -brand-name-send } Anda dapat berbagi file besar dengan enkripsi ujung ke ujung dengan berbagai kontrol keamanan, seperti kemampuan untuk menyetel waktu kedaluwarsa untuk tautan file kedaluwarsa, jumlah unduhan, dan apakah akan menambahkan opsional sandi untuk lapisan keamanan ekstra.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Selain itu, saat Anda mendaftar untuk akun { -brand-name-firefox } , Anda mendapatkan akses ke beberapa layanan unik seperti Tangkapan Layar, <a { $pocket }>{ -brand-name-pocket }</a> dan <a { $send }>{ -brand-name-send }</a> yang terintegrasi langsung ke dalam peramban. Tangkapan layar adalah fitur yang terpasang langsung di { -brand-name-firefox } peramban, memungkinkan Anda menyalin atau mengunduh sebagian atau semua bagian laman web. Saat Anda menyimpan tangkapan layar, Anda juga dapat memilih folder tempat Anda ingin menemukannya, daripada mengacaukan desktop Anda. Tombol { -brand-name-pocket } untuk { -brand-name-firefox } memungkinkan Anda menyimpan laman web dan video ke { -brand-name-pocket } hanya dengan satu klik, sehingga Anda dapat membaca versi yang bersih dan bebas gangguan kapan pun dan di mana pun Anda mau - bahkan saat offline. Dengan { -brand-name-send } , Anda dapat berbagi file besar dengan enkripsi ujung ke ujung dan berbagai kontrol keamanan, seperti kemampuan untuk menyetel waktu kedaluwarsa untuk tautan file kedaluwarsa, jumlah unduhan, dan apakah akan menambahkan kata sandi opsional untuk lapisan keamanan ekstra.

# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Tangkapan layar</a> adalah fitur populer lainnya yang terpasang langsung ke dalam { -brand-name-firefox } peramban, memungkinkan Anda dengan mudah menangkap gambar layar Anda. Saat Anda mengambil tangkapan layar, Anda dapat memilih untuk menyalin file atau memilih folder mana yang ingin Anda temukan, daripada mengacaukan desktop Anda.

# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } dan { -brand-name-safari } keduanya memberikan pengalaman yang mulus saat berpindah dari desktop ke perambanan seluler atau sebaliknya. Untuk { -brand-name-safari } , salah satu kekuatan utamanya adalah fitur kontinuitasnya. Ini menyinkronkan bookmark, tab, riwayat, dan lainnya ke iCloud sehingga tersedia di semua perangkat Anda. Itu berarti Anda dapat membuka tab di { -brand-name-iphone } dan membuatnya juga muncul di { -brand-name-mac } laptop Anda hanya dengan sekali klik.
compare-safari-both-browsers-have-a-lot = Kedua browser memiliki banyak fitur persilangan, serta beberapa fungsi unik. Perlu disebutkan, jika Anda mengambil banyak tangkapan layar, Anda akan bertanya-tanya bagaimana Anda pernah hidup tanpa fitur praktis yang terpasang langsung di { -brand-name-firefox } . Tetapi jika Anda hanya mencari peramban pribadi yang cepat untuk berselancar dan berbelanja, maka Anda mungkin ingin mencoba { -brand-name-firefox } - terutama jika Anda hanya menggunakan { -brand-name-safari } secara eksklusif karena peramban itu sudah dimuat sebelumnya sebagai peramban bawaan di komputer Anda. Akhirnya, Anda akan menemukan mana yang lebih sesuai dengan kebutuhan Anda.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } juga menawarkan fitur sinkronisasi serupa saat Anda mendaftar secara gratis <a { $attrs }>{ -brand-name-firefox-account }</a> yang memungkinkan pengguna dengan mudah menyinkronkan bookmark, riwayat perambanan, preferensi, sandi, formulir yang diisi, add-on, dan 25 tab terakhir yang dibuka di beberapa komputer. Yang membedakan { -brand-name-firefox } dari { -brand-name-safari } adalah bahwa ini tersedia di desktop atau platform seluler apa pun, { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } atau { -brand-name-macos } , meningkatkan portabilitasnya di semua perangkat yang mungkin Anda miliki.

# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Aplikasi { -brand-name-firefox } untuk <a { $ios }>{ -brand-name-ios }</a> dan <a { $android }>{ -brand-name-android }</a> adalah salah satu peramban tercepat yang tersedia dan juga memiliki fitur keamanan dan anti-pelacakan yang kokoh - nilai tambah yang sangat besar jika Anda terus berpindah-pindah antara laptop dan perangkat seluler.
compare-safari-since-safari-is-apples-proprietary = Karena { -brand-name-safari } adalah peramban web milik { -brand-name-apple } , sinkronisasi iCloud-nya bekerja secara eksklusif dengan produk { -brand-name-apple } . Ini bisa agak membatasi jika, misalnya, Anda adalah pengguna { -brand-name-android } dan { -brand-name-iphone } atau jika Anda memiliki PC berbasis { -brand-name-windows } untuk bekerja tetapi menggunakan { -brand-name-iphone } sebagai perangkat pribadi Anda.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } melakukan pekerjaan yang hebat dalam membuat pengalaman perambanan sederhana, cepat, dan mulus jika Anda adalah { -brand-name-apple } pengguna dengan banyak { -brand-name-apple } produk. Seperti { -brand-name-safari } , { -brand-name-firefox } adalah peramban yang cepat dan bermanfaat, tetapi privasi dan kompatibilitas lintas platform adalah fitur penentu kami. { -brand-name-firefox } pembaruan setiap bulan dengan fitur dan fungsi baru. Misalnya, satu pembaruan terkini mengaktifkan <a { $attrs }>Enhanced Tracking Protection (ETP) kami</a> secara default untuk pengguna baru, yang secara efektif memblokir cookie dan pelacak lintas situs.
compare-safari-in-the-end-it-just-boils = Pada akhirnya, itu hanya intinya pada apa yang Anda hargai di browser Anda. Jika Anda terintegrasi dengan { -brand-name-apple } ekosistem, { -brand-name-safari } masih merupakan pilihan yang bagus. Namun jika Anda menghargai perlindungan privasi terbaru dan terhebat serta dapat bekerja di beberapa sistem operasi, menurut kami { -brand-name-firefox } adalah pilihan terbaik Anda. { -brand-name-firefox } juga merupakan pilihan yang solid sebagai peramban sekunder bagi { -brand-name-apple } pengguna -pengguna eksklusif yang mungkin ingin beralih ke peramban lain untuk momen daring yang membutuhkan lapisan tambahan perlindungan privasi.
