# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs { -brand-name-microsoft } { -brand-name-edge } : quel est le meilleur navigateur pour vous?

# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Comparez { -brand-name-microsoft } { -brand-name-edge } au { -brand-name-firefox-browser } pour découvrir quel est le meilleur navigateur pour vous.

# Main title.
compare-edge-comparing-firefox-browser-with = Comparaison de { -brand-name-firefox-browser } avec { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = Avec { -brand-name-windows } 10, { -brand-name-microsoft } introduit son navigateur { -brand-name-edge } pour concurrencer { -brand-name-firefox } et { -brand-name-chrome } ce qui en fait le navigateur par défaut préinstallé sur des millions de PC vendus. Malgré tout, les utilisateurs ont tardé à l'adopter et { -brand-name-microsoft } finalement annoncé son intention de relancer { -brand-name-edge } tant que navigateur { -brand-name-chromium } ( { -brand-name-chromium } étant bien sûr le projet de navigateur Open Source de { -brand-name-google } ).
compare-edge-here-well-compare-our-firefox = Nous comparerons ici notre { -brand-name-firefox-browser } à celui { -brand-name-chromium } { -brand-name-microsoft } { -brand-name-edge } en termes de confidentialité, d'utilité et de portabilité, pour vous aider à mieux comprendre quel navigateur correspond le mieux à vos besoins et à vos préférences.

# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } est intégré à la plate-forme { -brand-name-windows } 10 et s'exécute dans un environnement sandbox, ce qui signifie qu'il isole les programmes et empêche les programmes malveillants d'espionner votre ordinateur. Il dispose d'un SmartScreen intégré qui analyse la réputation des sites que vous visitez et bloque les sites suspects. Pour améliorer la confidentialité, { -brand-name-edge } vous permet d'utiliser la biométrie ou un code PIN avec { -brand-name-edge } Hello au lieu de mots de passe pour l'authentification en ligne.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Chez { -brand-name-firefox } , nous sommes fiers de protéger la sécurité et la confidentialité de nos utilisateurs. Notre <a { $attrs }>politique de confidentialité</a> est transparente et dans un langage simple. Nous avons en fait beaucoup travaillé pour nous assurer qu'il était simple et facile à lire. Avec la protection améliorée contre le suivi désormais activée par défaut, nous bloquons automatiquement plus de 2000 trackers. Les trackers sont ces petits morceaux de code qui essaient de reconstituer ce que vous faites sur plusieurs sites Internet pour créer une image composite et détaillée de qui vous êtes, compromettant votre vie privée juste pour cibler de meilleures publicités.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Chez { -brand-name-firefox } , notre <a { $attrs }>politique de confidentialité</a> est transparente et rédigée dans un langage simple. Nous avons en fait beaucoup travaillé pour nous assurer qu'il était simple et facile à lire. Nous sommes fiers de protéger la sécurité et la confidentialité de nos utilisateurs. Avec la protection améliorée contre le suivi désormais activée par défaut, nous bloquons automatiquement plus de 2000 trackers. Les trackers sont ces petits morceaux de code qui essaient de reconstituer ce que vous faites sur plusieurs sites Internet pour créer une image composite et détaillée de qui vous êtes, compromettant votre vie privée juste pour cibler de meilleures publicités.

# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Vos <a { $attrs }>protections de confidentialité</a> vous indiquent les trackers et les cookies que les pages ont tenté de laisser, ainsi que le nombre de { -brand-name-firefox } bloqués pour vous.

# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = En { -brand-name-firefox } , le mode de navigation privée efface automatiquement vos informations de navigation telles que les mots de passe, les cookies et l'historique, ne laissant aucune trace après la clôture de la session. { -brand-name-edge } en revanche, enregistre en fait l'historique de navigation dans son mode privé (appelé "InPrivate") et il est relativement facile pour quelqu'un de reconstruire votre historique de navigation complet, que votre navigation ait été effectuée en mode normal ou InPrivate.
compare-edge-both-browsers-are-relatively = Les deux navigateurs sont relativement égaux en termes de cryptage des données. Cependant, si la confidentialité et la transparence en ligne sont importantes pour vous, { -brand-name-firefox } est clairement un meilleur choix ici.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } est un navigateur rapide et open source, ce qui signifie que les utilisateurs peuvent personnaliser leur expérience de navigation de toutes les manières possibles. { -brand-name-firefox } permet également à l'utilisateur occasionnel de personnaliser l'interface utilisateur de plusieurs façons différentes en appliquant différents thèmes et configurations de barre d'outils. Puisque notre navigateur a toujours été open source, nous avons un grand nombre de développeurs dévoués qui ont créé une vaste bibliothèque d'add-ons et d'extensions de navigateur.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } est un navigateur rapide et open source, ce qui signifie que les utilisateurs peuvent personnaliser leur expérience de navigation de toutes les manières possibles. { -brand-name-firefox } permet également à l'utilisateur occasionnel de personnaliser l'interface utilisateur de plusieurs façons différentes en appliquant différents thèmes et configurations de barre d'outils. Puisque notre navigateur a toujours été open source, nous avons un grand nombre de développeurs dévoués qui ont créé une vaste bibliothèque d'add-ons et d'extensions de navigateur.
compare-edge-since-edge-has-moved-to-the = Étant donné que { -brand-name-edge } est passé à la plate-forme { -brand-name-chromium } gourmande en processeur, vous pouvez vous attendre à ce qu'il s'exécute un peu plus lentement, en particulier si vous avez plusieurs programmes en cours d'exécution à la fois. Cependant, la plate-forme { -brand-name-chromium } comprend une bibliothèque massive d'extensions ainsi qu'un niveau décent de personnalisation de l'interface utilisateur que { -brand-name-edge } n'avait pas avant son passage à { -brand-name-chromium } .
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } dispose de fonctionnalités d'interface utilisateur intéressantes, telles que les aperçus des onglets, qui peuvent faciliter la recherche des bons onglets ouverts si vous en avez beaucoup. Une autre fonctionnalité utile liée aux onglets vous permet de mettre de côté les onglets actifs que vous n'utilisez pas mais que vous ne souhaitez pas fermer.

# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } dispose d'une interface à onglets défilants, qui permet de visualiser les informations des onglets et de les faire défiler horizontalement au lieu de les réduire à la taille des favicon. De même, chaque fois que vous ouvrez un nouvel onglet, notre fonction <a { $attrs }>{ -brand-name-pocket }</a> suggère des articles et du contenu pertinents. De plus, avec { -brand-name-pocket } , vous pouvez également enregistrer des articles, des vidéos et d'autres contenus en un seul clic, pour les lire ultérieurement.
compare-edge-firefox-and-edge-both-offer = { -brand-name-firefox } et { -brand-name-edge } offrent tous deux d'excellents modes de lecture. Avec { -brand-name-firefox } , il vous suffit d'appuyer sur la petite icône dans la barre de recherche et le navigateur supprime tous les éléments inutiles et vous présente un article propre. Dans { -brand-name-edge } vous suffit d'appuyer sur l'icône du petit livre et le navigateur pour obtenir une interface utilisateur claire et facile à lire.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } et { -brand-name-edge } offrent tous deux d'excellents modes de lecture. Avec { -brand-name-firefox } vous appuyez simplement sur la petite icône dans la barre de recherche et le navigateur supprime tous les éléments inutiles et vous présente un article propre. Dans { -brand-name-edge } vous suffit d'appuyer sur l'icône du petit livre et le navigateur pour obtenir une interface utilisateur claire et facile à lire.

# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } inclut également de nombreuses fonctionnalités intégrées pratiques par défaut, telles que la <a { $attrs }>protection améliorée contre le suivi</a> , un outil de capture d'écran intégré, l'envoi de fichiers volumineux, etc.

# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Hors de la porte, { -brand-name-firefox } a plus de fonctionnalités et d'intégrations intégrées dans le navigateur et facilement disponibles en téléchargement. Et alors que les deux navigateurs ont un très grand nombre d'add-ons et extensions disponibles, { -brand-name-edge } « la compatibilité avec { -brand-name-google } » s { -brand-name-chromium } plate - forme lui donne l'avantage en termes de nombre.

compare-edge-with-internet-explorer-microsoft = Avec { -brand-name-ie } , { -brand-name-microsoft } appris de son manque de disponibilité sur toutes les plates-formes et a rendu { -brand-name-edge } facilement disponible sur { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } , { -brand-name-mac } et bientôt { -brand-name-linux } .
compare-edge-with-internet-explorer-fallback = Avec { -brand-name-ie } , { -brand-name-microsoft } appris de son manque de disponibilité sur les plates-formes et a rendu { -brand-name-edge } disponible pour { -brand-name-mac } et { -brand-name-android } . Le logiciel est désormais facilement disponible sur { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } et { -brand-name-mac } .

# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } est disponible sur { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } , { -brand-name-mac } et { -brand-name-linux } depuis des années. Et comme vous vous en doutez avec n'importe quel navigateur moderne, { -brand-name-firefox } vous permet de vous connecter avec un <a { $attrs }>compte gratuit</a> et de synchroniser des données telles que les mots de passe, l'historique de navigation, les favoris et les onglets ouverts entre votre ordinateur, votre tablette et votre téléphone. Il vous permet également de synchroniser entre les plates-formes.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } vous permet également de connecter votre compte { -brand-name-microsoft } associé et de vous connecter pour synchroniser vos favoris, votre historique, vos mots de passe et plus encore entre votre ordinateur et { -brand-name-ios } ou { -brand-name-android } appareils.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } vous permet également de connecter votre compte { -brand-name-microsoft } associé et de vous connecter pour synchroniser vos favoris, votre historique, vos mots de passe et plus encore entre votre ordinateur et { -brand-name-ios } ou { -brand-name-android } appareils, bien que certaines { -brand-name-android } tablettes ne le soient pas actuellement prise en charge.

# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = En plus d'absorber beaucoup de puissance de calcul, { -brand-name-edge } s'exécuter sur { -brand-name-chromium } a répondu à de nombreux besoins des utilisateurs en termes de fonctionnalités et de fonctionnalités. Mais il reste encore beaucoup à prendre en compte en termes de protection de la vie privée du navigateur. Nous estimons que { -brand-name-firefox } reste un meilleur choix pour la plupart des gens à utiliser dans leur vie quotidienne, sur la base non seulement de la fonctionnalité, mais surtout de notre transparence dans la façon dont nous collectons les données utilisateur, ce que nous collectons exactement et ce que nous faisons il. Étant donné que notre société mère est <a { $attrs }>{ -brand-name-mozilla }</a> , une organisation à but non lucratif dédiée à la confidentialité et à la liberté sur Internet, nous avons simplement un ensemble de priorités différent en ce qui concerne les données des utilisateurs.
compare-edge-the-bottom-line-is-that-while = L'essentiel est que, même si nous suggérons d'utiliser { -brand-name-firefox } , le meilleur navigateur pour vous sera finalement celui qui répondra à vos besoins individuels avec la prise en charge des extensions, la personnalisation des outils de navigation, la vitesse, la confidentialité et la sécurité.
