# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/ie/

# HTML page title
compare-ie-firefox-vs-internet-explorer = { -brand-name-firefox } vs { -brand-name-ie } : quel est le meilleur navigateur pour vous?

# HTML page description
compare-ie-compare-internet-explorer-to = Comparez { -brand-name-ie } au { -brand-name-firefox-browser } pour découvrir quel est le meilleur navigateur pour vous.

# Main title
compare-ie-comparing-firefox-browser-with = Comparaison de { -brand-name-firefox-browser } avec { -brand-name-microsoft } { -brand-name-ie }
compare-ie-while-microsofts-internet-explorer = Bien que { -brand-name-microsoft } de { -brand-name-ie } toujours préinstallé sur la plupart des PC Windows, { -brand-name-microsoft } préférerait clairement que vous utilisiez son navigateur { -brand-name-edge } , qui est défini par défaut lors de l'achat.
compare-ie-here-well-compare-our-firefox = Nous comparerons ici notre { -brand-name-firefox-browser } à { -brand-name-ie } en termes de sécurité, d'utilité et de portabilité. Nous vous aiderons à comprendre les différences entre la façon dont un navigateur moderne tel que { -brand-name-firefox } qui adhère aux normes du Web se compare au navigateur que vous utilisez peut-être à des fins professionnelles ou à partir de vieilles habitudes qui meurent.

compare-ie-microsoft-is-no-longer-supporting = { -brand-name-microsoft } ne prend plus en charge le nouveau développement pour { -brand-name-ie } , ce qui signifie que les problèmes de sécurité sont endémiques. { -brand-name-microsoft } reconnaît ouvertement le fait que des vulnérabilités existent dans pratiquement toutes les versions de { -brand-name-ie } .

# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/legacy-browser-support-extension-windows with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your = Alors, quelle est la solution si votre entreprise exécute des applications héritées qui ne fonctionnent que sur { -brand-name-ie } ? Notre meilleur conseil est de ne pas mélanger affaires et plaisir. Nous vous recommandons en fait d'utiliser l' <a { $attrs }>extension Legacy Browser Support</a> pour { -brand-name-windows } . Cette extension permet aux utilisateurs d'ouvrir automatiquement un ensemble prédéfini d'URL dans { -brand-name-ie } et de revenir à { -brand-name-firefox } lors de la navigation vers un autre domaine.

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $privacy (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-ie-so-whats-the-solution-if-your-fallback = Alors, quelle est la solution si votre entreprise exécute des applications obsolètes qui ne fonctionnent que sur { -brand-name-ie } ? Notre meilleur conseil pour vous personnellement est de ne pas mélanger les affaires et le plaisir. La chose simple à faire est de télécharger et d'utiliser un navigateur plus sécurisé comme { -brand-name-firefox } . Ensuite, si vous devez faire des choses comme vérifier votre messagerie personnelle ou faire des achats en ligne, vous pouvez simplement passer au navigateur le plus sécurisé. En fin de compte, si { -brand-name-microsoft } avertit les gens de ne pas utiliser { -brand-name-ie } , ne l'utilisez pas. Votre vie privée et votre sécurité en ligne ne valent pas la peine d'être mises en danger car vous (ou votre entreprise) avez du mal à briser une vieille habitude. Nous créons { -brand-name-firefox } avec des fonctionnalités de sécurité et de confidentialité telles que <a { $lockwise }>{ -brand-name-lockwise }</a> , notre gestionnaire de mots de passe, la navigation privée et de nombreux autres modules complémentaires qui nous aident à rendre le Web plus sûr pour vous. De plus, notre <a { $privacy }>politique de confidentialité</a> est simple: nous vous disons ce que nous savons de vous et pourquoi nous recueillons ces informations. Toutes ces choses vont évidemment au-delà de ce que { -brand-name-ie } propose, et même de ce que proposent d'autres navigateurs modernes comme { -brand-name-google } { -brand-name-chrome } et { -brand-name-microsoft } { -brand-name-edge } .

compare-ie-alarmingly-4-to-5-of-all-desktop = Il est alarmant de constater que 4 à 5% de tout le trafic Web pour ordinateur de bureau a transité { -brand-name-ie } aussi récemment qu'en 2019. Cela peut ne pas sembler beaucoup, mais en réalité, cela signifie que des millions de personnes bénéficient d'une mauvaise expérience Internet avec des temps de chargement et de rendu lents , des pages qui ne s'affichent pas correctement - le tout en plus des problèmes de sécurité déjà abordés.
compare-ie-alarmingly-4-to-5-of-all-desktop-fallback = De façon alarmante, 4 à 5% de tout le trafic Web des ordinateurs de bureau transitent par { -brand-name-ie } . Cela peut ne pas sembler beaucoup, mais en réalité, cela signifie que des millions de personnes bénéficient d'une mauvaise expérience Internet avec des temps de chargement et de rendu lents, des pages qui ne s'affichent pas correctement - le tout en plus des problèmes de sécurité déjà discutés.
compare-ie-really-the-only-reasons-to-use = En réalité, les seules raisons d'utiliser { -brand-name-ie } sont pour les développeurs de tester à quoi ressemblent leurs sites sur un navigateur plus ancien ou si une entreprise possède des applications stratégiques fonctionnant uniquement avec le navigateur { -brand-name-ie } .

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum = À l'autre bout du spectre, { -brand-name-firefox } est l'un des navigateurs les plus fréquemment mis à jour et est livré avec de nombreuses fonctionnalités utiles et intéressantes, comme <a { $pocket }>{ -brand-name-pocket }</a> qui suggère un contenu intéressant chaque fois que vous ouvrez un nouvel onglet. Notre barre d'adresse Web et de recherche unifiée, ou <em>Quantum Bar</em> comme nous l'appelons, vous propose également des suggestions basées sur vos signets et balises existants, l'historique, les onglets ouverts et les recherches populaires. Et avec un compte { -brand-name-firefox } gratuit, vous avez également accès à tous vos paramètres et à <a { $products }>nos autres produits { -brand-name-firefox }</a> sur n'importe quel appareil simplement en vous connectant. De plus, la tranquillité d'esprit de savoir que votre navigateur travaille de manière proactive pour protéger vos données personnelles.

# Variables:
#   $pocket (string) - link to /firefox/pocket/ with additional attributes for analytics
#   $products (string) - link to /firefox/products/ with additional attributes for analytics
compare-ie-on-the-other-end-of-the-spectrum-fallback = À l'autre bout du spectre, { -brand-name-firefox } est l'un des navigateurs les plus fréquemment mis à jour et est livré avec de nombreuses fonctionnalités utiles et intéressantes, comme <a { $pocket }>{ -brand-name-pocket }</a> qui suggère un contenu intéressant chaque fois que vous ouvrez un nouvel onglet. Notre barre d'adresse Web et de recherche unifiée, ou <em>Awesome Bar</em> comme nous l'appelons, vous propose également des suggestions basées sur vos favoris et vos balises existants, votre historique, vos onglets ouverts et vos recherches populaires. Et avec un compte { -brand-name-firefox } gratuit, vous avez également accès à tous vos paramètres et à <a { $products }>nos autres produits { -brand-name-firefox }</a> sur n'importe quel appareil simplement en vous connectant. De plus, la tranquillité d'esprit de savoir que votre navigateur travaille de manière proactive pour protéger vos données personnelles.

# "sunset" here means Microsoft is officially ending production of Internet Explorer. Alternative: "retire"
compare-ie-as-microsoft-has-made-the-move = Comme { -brand-name-microsoft } a décidé de désactiver le navigateur { -brand-name-ie } , il n'est plus compatible avec aucune version pour { -brand-name-ios } et n'a jamais été disponible pour { -brand-name-android } . Ce qui signifie que, sauf si vous utilisez un ordinateur portable ou un ordinateur de bureau Windows, vous n'aurez pas accès à vos signets, à votre historique de navigation, à vos mots de passe enregistrés et à d'autres informations que les navigateurs modernes synchronisent entre les appareils.
compare-ie-firefox-works-on-any-platform = { -brand-name-firefox } fonctionne sur n'importe quelle plate-forme, y compris { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } et { -brand-name-ios } . Ce qui signifie également que vous pouvez synchroniser toutes vos informations sur les plates-formes. Ainsi, si vous naviguez sur un ordinateur portable { -brand-name-windows } , vous pouvez reprendre là où vous vous étiez arrêté lorsque vous passez à la navigation sur votre appareil { -brand-name-iphone } ou { -brand-name-android } . Cette commodité devrait être fournie en standard avec tout navigateur Web moderne et fait cruellement défaut avec { -brand-name-ie } .
compare-ie-there-was-a-time-not-so-long = Il n'y a pas si longtemps, { -brand-name-ie } était le navigateur le plus populaire et le plus utilisé au monde. Les temps ont changé, tout comme la technologie, mais malheureusement { -brand-name-ie } est resté à peu près le même. { -brand-name-microsoft } implore ouvertement les utilisateurs d'arrêter d'utiliser { -brand-name-ie } et de passer à leur nouveau navigateur { -brand-name-chromium } { -brand-name-edge } .

# Variables:
#   $attrs (string) - link to /firefox/download/thanks/ with additional attributes for analytics
# "Nana" is a common nickname for a grandmother in many English-speaking countries. Use a similar name for a grandmother in your language or culture.
# "firing up" is slang for starting an engine, and here means starting a web browser. Alternative: "starting up"
compare-ie-our-opinion-is-just-to-go-with = Notre avis est simplement d'opter pour un navigateur privé de confiance qui a fait ses preuves en matière de fourniture d'une excellente expérience sur tous les appareils. Dans une comparaison directe, ce n'est vraiment pas du tout un concours. { -brand-name-firefox } est de loin le gagnant dans toutes les catégories d'évaluation. Si vous vous retrouvez chez Nana en train de flamboyer { -brand-name-ie } , vous voudrez peut-être rendre service à Nana et <a { $attrs }>télécharger { -brand-name-firefox }</a> pour elle.
