# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/opera/

# HTML page title
compare-opera-firefox-vs-opera-which-is = { -brand-name-firefox } vs { -brand-name-opera } : quel est le meilleur navigateur pour vous?

# HTML page description
compare-opera-compare-opera-to-the-firefox = Comparez { -brand-name-opera } au { -brand-name-firefox-browser } pour découvrir quel est le meilleur navigateur pour vous.

# Main title
compare-opera-comparing-firefox-browser = Comparaison de { -brand-name-firefox-browser } avec { -brand-name-opera }

compare-opera-operas-privacy-policy-lacks = La politique de confidentialité de { -brand-name-opera } manque de spécificité dans son explication sur les types d'informations qu'elle collecte et comment. Dans certaines sections, il est indiqué qu'ils collectent les noms des titulaires de compte, les adresses IP et les termes de recherche. Ce qui semble déroutant et troublant, c'est la section sur les transferts internationaux de données; quand, à quelle fréquence et pourquoi ils doivent transférer vos données à l'international ne sont pas expliqués.
compare-opera-operas-privacy-policy-lacks-fallback = La politique de confidentialité de { -brand-name-opera } manque de spécificité dans son explication des types d'informations qu'elle collecte et de la manière dont, dans certaines sections, elle indique qu'ils collectent les noms des titulaires de compte, les adresses IP et les termes de recherche. Ce qui semble déroutant et troublant, c'est la section sur les transferts internationaux de données; quand, à quelle fréquence et pourquoi ils doivent transférer vos données à l'international ne sont pas expliqués.
compare-opera-the-firefox-browser-and-opera = Le { -brand-name-firefox-browser } et le { -brand-name-opera } sont deux des premiers navigateurs du marché à publier des mises à jour fréquentes. Bien que { -brand-name-opera } n'ait pas atteint le même niveau d'adoption par les utilisateurs que { -brand-name-firefox } ou { -brand-name-google } { -brand-name-chrome } , il a maintenu une base relativement stable et fidèle sur une période prolongée. Dans cet examen, nous comparerons le navigateur { -brand-name-opera } avec notre navigateur { -brand-name-firefox } en termes de sécurité et de confidentialité, d'utilité et de portabilité pour vous aider à choisir le navigateur qui vous convient le mieux.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-opera-firefoxs-privacy-policy-is = La <a { $attrs }>politique de confidentialité de</a> { -brand-name-firefox } est très transparente dans la description des informations personnelles que nous collectons, le seul objectif final étant de vous donner un meilleur contrôle sur les informations que vous partagez en ligne.
compare-opera-as-far-as-actual-privacy-protections = En ce qui concerne les véritables protections de confidentialité dans le navigateur { -brand-name-opera } , il offre un mode privé robuste qui vous permet de surfer sur le Web sans que le navigateur ne suive votre activité. Toujours en mode de navigation normal, vous pouvez également désactiver certaines fonctionnalités de collecte de données en creusant dans les paramètres pour activer le bloqueur de publicités et ajuster d'autres fonctionnalités de sécurité.

compare-opera-we-make-firefox-for-people = Nous faisons { -brand-name-firefox } pour des personnes comme vous, qui se soucient profondément de la confidentialité et de la sécurité personnelles. C'est pourquoi nous collectons si peu d'informations sur les utilisateurs et sommes transparents sur la façon dont nous utilisons ces informations. Il est difficile de savoir comment { -brand-name-opera } fonctionne du point de vue de la confidentialité. Bien qu'il existe des fonctionnalités de confidentialité robustes, la façon dont elles collectent et partagent vos données est trouble. { -brand-name-firefox } reste cohérent dans ce que nous disons et ce que nous faisons pour protéger votre vie privée.

# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-opera-theres-no-debate-that-opera = Il ne fait aucun doute que { -brand-name-opera } est un navigateur riche en fonctionnalités avec une interface utilisateur claire et de solides options de personnalisation. Étant donné que { -brand-name-opera } est basé sur { -brand-name-chromium } , il peut tirer parti de la plupart de la vaste bibliothèque d'extensions de { -brand-name-google } { -brand-name-chrome } . { -brand-name-firefox } propose également une grande <a { $attrs }>bibliothèque d'extensions à parcourir</a> , mais pas aussi grande que celle de { -brand-name-chrome } .
compare-opera-like-firefox-opera-delivers = Comme { -brand-name-firefox } , { -brand-name-opera } offre une expérience d'onglets défilants, ce qui signifie que lorsque vous ouvrez plus d'onglets qu'il n'en tient à l'écran, il les fait défiler hors de l'écran au lieu de simplement les réduire en continu. De plus, { -brand-name-firefox } et { -brand-name-opera } disposent d'un outil de capture d'écran qui vous permet de capturer un instantané de votre écran ou d'une partie de la page. Cependant, l'outil { -brand-name-opera } ne vous donne pas la possibilité de créer une seule capture énorme de la page Web entière, seulement la partie visible.

# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
# "Facebook Messenger" is a brand name.
compare-opera-opera-provides-a-lot-of-hidden = { -brand-name-opera } fournit de nombreux utilitaires cachés dans son interface simple et gérable. Par exemple, il existe une prise en charge intégrée des applications de messagerie, telles que { -brand-name-facebook } Messenger. Il existe également un lecteur de nouvelles qui regroupe les articles de votre choix de sites et de médias. La fonctionnalité parallèle à cela sur { -brand-name-firefox } est appelée <a { $attrs }>{ -brand-name-pocket }</a> . { -brand-name-pocket } est un service gratuit pour { -brand-name-firefox } titulaires de compte qui facilite la recherche et l'enregistrement d'articles et de vidéos intéressants sur tout le Web. En outre, il recommande une variété d'articles qui élargissent votre base de connaissances organisée par de vrais humains réfléchis.
compare-opera-in-terms-of-head-to-head-utility = En termes d'utilité face à face, { -brand-name-opera } et { -brand-name-firefox } sont de proches concurrents. { -brand-name-opera } peut avoir un avantage dans un aspect avec sa compatibilité et son accès à l'énorme bibliothèque d'extensions de { -brand-name-chrome } . Mais un facteur important à considérer est le fait que { -brand-name-opera } , parce qu'il est construit sur { -brand-name-chromium } , est un navigateur gourmand en processeur avec sa consommation de RAM comparable à { -brand-name-chrome } , qui est connu pour son utilisation élevée du processeur.

# "Ex" is a former partner or spouse, as in "ex-boyfriend" or "ex-wife." Alternative: "former partner"
compare-opera-both-firefox-and-opera-are = { -brand-name-firefox } et { -brand-name-opera } sont tous deux compatibles sur toutes les plates-formes, y compris { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } et { -brand-name-ios } . { -brand-name-firefox } titulaires de compte peuvent facilement synchroniser leurs favoris, leurs mots de passe, leurs onglets ouverts et leur historique de navigation sur tous leurs appareils connectés. Il en va de même pour { -brand-name-opera } utilisateurs disposant d'un compte. Cependant, de nombreux sites, en particulier les anciens sites qui n'ont pas été mis à jour depuis des années, bloquent entièrement la dernière version de { -brand-name-opera } . Donc, s'il est important de visiter des endroits comme l'ancien blog de votre ex, faites attention, vous ne pourrez peut-être pas accéder à certains des coins les plus poussiéreux d'Internet si vous utilisez { -brand-name-opera } .

# "Touch" and "Mini" are brand names.
compare-opera-in-addition-to-the-regular = En plus de l'application mobile standard, { -brand-name-opera } propose deux autres versions mobiles de son navigateur: Touch et Mini. Le toucher est léger sur les fonctionnalités, mais il est conçu pour être utilisé en déplacement avec une seule main. La version Mini vise à réduire l'utilisation des données et à augmenter les vitesses sur les connexions lentes en rétrogradant les images et en supprimant le contenu.

# Variables:
#   $attrs (string) - link to https://play.google.com/store/apps/details?id=org.mozilla.fenix with additional attributes for analytics
compare-opera-we-also-offer-an-additional = Nous proposons également une version supplémentaire, quoique expérimentale, de notre { -brand-name-firefox } application mobile, <a { $attrs }>{ -brand-name-firefox } Preview</a> , qui met l'accent sur la vitesse et la sécurité.
compare-opera-most-major-browsers-these = La plupart des principaux navigateurs de nos jours, à l'exception de { -brand-name-safari } , fonctionnent de manière transparente sur les plates-formes et les navigateurs. { -brand-name-opera } et { -brand-name-firefox } ne font pas exception, les deux navigateurs offrant une excellente portabilité sur tous les appareils.
compare-opera-overall-opera-is-a-solid-browser = Dans l'ensemble, { -brand-name-opera } est un navigateur solide, avec une interface claire et de nombreuses fonctionnalités utiles disponibles. Il existe cependant de sérieux problèmes de confidentialité ainsi qu'un problème d'utilisation d'une grande puissance de traitement. Bien que { -brand-name-opera } offre des fonctionnalités de convivialité vraiment formidables, nous pensons toujours que { -brand-name-firefox } reste un navigateur de qualité supérieure basé sur les performances, avec une position transparente en matière de confidentialité des utilisateurs et des protections de confidentialité strictes.
