# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs { -brand-name-safari } : quel est le meilleur navigateur pour vous?

# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } est le navigateur préinstallé sur { -brand-name-mac } et { -brand-name-iphone } . Comparez { -brand-name-safari } au { -brand-name-firefox-browser } pour découvrir quel est le meilleur navigateur pour vous.

# Main title.
compare-safari-comparing-firefox-browser = Comparaison de { -brand-name-firefox-browser } avec { -brand-name-apple } { -brand-name-safari }

# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Si vous utilisez un Mac ou possédez un { -brand-name-iphone } , il est probable que vous connaissiez le navigateur Web { -brand-name-safari } . Le fait qu'il soit préinstallé comme navigateur par défaut pour les utilisateurs de produits { -brand-name-apple } lui donne certainement un avantage précoce, mais { -brand-name-firefox } possède son propre ensemble de fonctionnalités utiles qui en font une alternative intéressante. Nous allons explorer ici les principales différences entre notre navigateur et { -brand-name-safari } en termes de confidentialité, d'utilité et de portabilité entre les appareils.

# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = La confidentialité est devenue un sujet brûlant pour les entreprises de technologie, car elles réalisent que de plus en plus de personnes se sentent vulnérables à des éléments tels que les violations de données, les traqueurs publicitaires et les pirates. Mais en ce qui concerne les vrais outils que les gens utilisent pour naviguer dans les interwebs réels, est-ce que tout parle ou prend-il réellement des mesures pour sécuriser vos données?
compare-safari-as-alluded-to-before-apple-fallback = Comme évoqué précédemment, { -brand-name-apple } fait partie de ces entreprises qui ont récemment décidé d'intensifier leur jeu de confidentialité. Il n'y a pas si longtemps, { -brand-name-apple } mis en œuvre la prévention du suivi intersites dans { -brand-name-safari } , qui empêche les annonces de vous suivre sur Internet. { -brand-name-safari } propose également une suggestion de mot de passe fort lorsque vous créez un nouveau compte sur n'importe quel site Web. Et si vous êtes investi dans l'écosystème iCloud, il synchronise ce mot de passe en toute sécurité avec vos autres appareils, vous n'avez donc jamais à vous en souvenir.


# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Notre mode de navigation privée bloque les trackers et efface vos mots de passe, cookies et historique chaque fois que vous le fermez. Mais vous pouvez également profiter de nos fonctionnalités avancées de confidentialité même en mode de navigation normal. Avec la dernière édition de { -brand-name-firefox } , la prévention améliorée du suivi est activée par défaut. Cela empêche des éléments tels que les trackers intersites de vous suivre lorsque vous naviguez sur le Web. De plus, étant donné que { -brand-name-facebook } est presque quotidiennement pris au piège de problèmes de confidentialité, notre extension <a { $attrs }>{ -brand-name-facebook-container }</a> a beaucoup de sens. Il est plus difficile pour { -brand-name-facebook } de vous suivre sur le Web, comme { -brand-name-safari } fait pour empêcher le suivi intersites, mais { -brand-name-firefox } isole en fait votre { -brand-name-facebook } session dans un conteneur distinct bloquant { -brand-name-facebook } du suivi ce que vous faites sur d'autres sites Web. Pourquoi ont-ils besoin de savoir ce que vous recherchez sur WebMD de toute façon?

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = En ce qui concerne la sécurité, { -brand-name-firefox } est également solide. Chaque fois que vous êtes dans { -brand-name-firefox } , vous pouvez cliquer avec le bouton droit de la souris dans le champ du mot de passe pour générer en toute sécurité un mot de passe fort à l'aide de l'option Remplir le mot de passe. Lorsque vous enregistrez votre nouveau mot de passe, nous vous invitons à l'enregistrer dans son gestionnaire de mots de passe intégré, <a { $lockwise }>{ -brand-name-lockwise }</a> . Nous proposons également aux utilisateurs et aux titulaires de compte un autre produit gratuit et utile appelé <a { $monitor }>{ -brand-name-monitor }</a> qui vous alerte automatiquement si vos données sont incluses dans une violation de données connue.
compare-safari-if-you-choose-to-use-safari = Si vous choisissez d'utiliser { -brand-name-safari } , vous êtes entre de bonnes mains tant que vous utilisez un appareil { -brand-name-apple } . Mais { -brand-name-safari } ne fonctionne que sur les appareils { -brand-name-apple } , tandis que { -brand-name-firefox } fonctionne sur { -brand-name-windows } , { -brand-name-mac } , { -brand-name-ios } , { -brand-name-android } et { -brand-name-linux } . Quel que soit le système d'exploitation que vous choisissez, { -brand-name-firefox } vous offre nos protections en matière de sécurité et de confidentialité.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } est largement connu pour son écosystème fermé en ce qui concerne la création de logiciels pour ses produits. Mais à l'intérieur du { -brand-name-app-store } , il offre une section aux développeurs pour créer des plugins et des modules complémentaires pour rendre le navigateur plus robuste. Ces extensions peuvent également être consultées via { -brand-name-app-store } et facilement ajoutées à { -brand-name-safari } .
compare-safari-in-addition-to-the-regular = En plus de l'ensemble normal de fonctionnalités que vous attendez d'un navigateur, telles que la navigation par onglets et la navigation privée, { -brand-name-safari } possède également des fonctionnalités inattendues. Par exemple, si un utilisateur faisait un clic droit sur un mot n'importe où sur une page à l'intérieur de { -brand-name-safari } , puis cliquez sur Rechercher, il obtiendrait une définition de dictionnaire ainsi que des entrées du thésaurus, { -brand-name-app-store } , des films et plus encore. Le contrôle parental de { -brand-name-safari } est facile à personnaliser, permettant aux adultes de respirer un peu plus facilement lorsque les enfants commencent à s'intéresser à Internet.

# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Comme { -brand-name-safari } , { -brand-name-firefox } encourage sa communauté de développeurs enthousiaste à créer des <a { $attrs }>modules complémentaires et des extensions</a> pour le navigateur. Et comme notre plate-forme est open-source, il existe une vaste sélection qui ajoute une multitude de fonctionnalités.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = De plus, lorsque vous créez un compte { -brand-name-firefox } , vous avez accès à des services uniques tels que <a { $pocket }>{ -brand-name-pocket }</a> et <a { $send }>{ -brand-name-send }</a> qui s'intègrent directement dans le navigateur. Le bouton { -brand-name-pocket } pour { -brand-name-firefox } vous permet d'enregistrer des pages Web et des vidéos dans { -brand-name-pocket } en un seul clic. Vous pouvez ainsi lire une version propre et sans distraction quand et où vous le souhaitez, même hors connexion. Avec { -brand-name-send } vous pouvez partager des fichiers volumineux avec un chiffrement de bout en bout avec une variété de contrôles de sécurité, tels que la possibilité de définir une heure d'expiration pour un lien de fichier à expirer, le nombre de téléchargements et l'ajout facultatif mot de passe pour une couche de sécurité supplémentaire.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = De plus, lorsque vous créez un compte { -brand-name-firefox } , vous avez accès à certains services uniques tels que les captures d'écran, <a { $pocket }>{ -brand-name-pocket }</a> et <a { $send }>{ -brand-name-send }</a> qui s'intègrent directement dans le navigateur. Les captures d'écran sont une fonctionnalité intégrée directement au navigateur { -brand-name-firefox } , vous permettant de copier ou de télécharger une partie ou la totalité d'une page Web. Lorsque vous enregistrez la capture d'écran, vous pouvez également choisir le dossier dans lequel vous souhaitez la trouver, au lieu d'encombrer votre bureau. Le bouton { -brand-name-pocket } pour { -brand-name-firefox } vous permet d'enregistrer des pages Web et des vidéos dans { -brand-name-pocket } en un seul clic, afin que vous puissiez lire une version propre et sans distraction quand et où vous le souhaitez, même hors connexion. Avec { -brand-name-send } , vous pouvez partager des fichiers volumineux avec un chiffrement de bout en bout et une variété de contrôles de sécurité, tels que la possibilité de définir un délai d'expiration pour un lien de fichier, le nombre de téléchargements et l'ajout d'un mot de passe optionnel pour une couche de sécurité supplémentaire.

# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Les captures d'écran</a> sont une autre fonctionnalité populaire intégrée directement dans le navigateur { -brand-name-firefox } , vous permettant de capturer facilement une image de votre écran. Lorsque vous prenez une capture d'écran, vous pouvez choisir de copier le fichier ou de choisir le dossier dans lequel vous souhaitez le trouver, au lieu d'encombrer votre bureau.

# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } et { -brand-name-safari } offrent tous deux une expérience fluide lors du passage de la navigation sur ordinateur à la navigation sur mobile ou vice versa. Pour { -brand-name-safari } , l'une de ses principales forces est ses fonctionnalités de continuité. Il synchronise vos favoris, vos onglets, votre historique et plus encore sur iCloud afin qu'ils soient disponibles sur tous vos appareils. Cela signifie que vous pouvez ouvrir un onglet sur votre { -brand-name-iphone } et l'afficher également sur votre ordinateur portable { -brand-name-mac } un seul clic.
compare-safari-both-browsers-have-a-lot = Les deux navigateurs ont de nombreuses fonctionnalités de croisement, ainsi que des fonctions uniques. Il convient de mentionner que si vous prenez beaucoup de captures d'écran, vous vous demanderez comment vous avez pu vivre sans cette fonctionnalité pratique intégrée à { -brand-name-firefox } . Mais si vous recherchez simplement un navigateur privé et rapide pour surfer et faire des achats, vous pouvez essayer { -brand-name-firefox } , surtout si vous avez utilisé exclusivement { -brand-name-safari } car il était préchargé comme navigateur par défaut sur ton ordinateur. Finalement, vous découvrirez lequel est le plus adapté à vos besoins.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } propose également une fonctionnalité de synchronisation similaire lorsque vous vous inscrivez à un <a { $attrs }>{ -brand-name-firefox-account }</a> gratuit qui permet aux utilisateurs de synchroniser facilement leurs favoris, leur historique de navigation, leurs préférences, leurs mots de passe, leurs formulaires remplis, leurs modules complémentaires et les 25 derniers onglets ouverts sur plusieurs des ordinateurs. Ce qui distingue { -brand-name-firefox } de { -brand-name-safari } c'est qu'il est disponible sur n'importe quelle plate-forme de bureau ou mobile, { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } ou { -brand-name-macos } , ce qui améliore sa portabilité sur tout appareil que vous possédez.

# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = L'application { -brand-name-firefox } pour <a { $ios }>{ -brand-name-ios }</a> et <a { $android }>{ -brand-name-android }</a> est l'un des navigateurs les plus rapides disponibles et dispose également de fonctionnalités de sécurité et d'anti-tracking solides, un avantage considérable si vous passez constamment entre un ordinateur portable et des appareils mobiles.
compare-safari-since-safari-is-apples-proprietary = Étant donné que { -brand-name-safari } est le navigateur Web propriétaire de { -brand-name-apple } , sa synchronisation iCloud fonctionne exclusivement avec les produits { -brand-name-apple } . Cela peut être quelque peu restrictif si, par exemple, vous êtes à la fois un utilisateur { -brand-name-android } et un utilisateur { -brand-name-iphone } ou si vous disposez d'un PC basé sur { -brand-name-windows } pour le travail, mais utilisez un { -brand-name-iphone } comme appareil personnel.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } fait un excellent travail pour rendre l'expérience de navigation simple, rapide et transparente si vous êtes un { -brand-name-apple } utilisateur avec plusieurs { -brand-name-apple } produits. Comme { -brand-name-safari } , { -brand-name-firefox } est un navigateur rapide et utilitaire, mais la confidentialité et la compatibilité multiplateforme sont nos caractéristiques déterminantes. { -brand-name-firefox } met à jour chaque mois de nouvelles fonctionnalités et fonctionnalités. Par exemple, une mise à jour récente a activé notre <a { $attrs }>protection renforcée contre le suivi (ETP)</a> par défaut pour les nouveaux utilisateurs, ce qui bloque efficacement les cookies et les trackers intersites.
compare-safari-in-the-end-it-just-boils = En fin de compte, cela se résume à ce que vous appréciez dans votre navigateur. Si vous êtes intégré à l ' { -brand-name-apple } écosystème, { -brand-name-safari } reste un excellent choix. Mais si vous appréciez de disposer des dernières et meilleures protections de confidentialité et de pouvoir travailler sur plusieurs systèmes d'exploitation, nous pensons que { -brand-name-firefox } est votre meilleur choix. { -brand-name-firefox } est également une option solide en tant que navigateur secondaire pour les utilisateurs exclusifs { -brand-name-apple } qui souhaitent passer à un autre navigateur pour les moments en ligne qui nécessitent des couches supplémentaires de protection de la confidentialité.
