# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome } : Qual é melhor?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Comparamos { -brand-name-mozilla } { -brand-name-firefox } com { -brand-name-google } { -brand-name-chrome } em termos de privacidade, utilidade e portabilidade

# Main title.
compare-chrome-comparing-firefox-browser = Comparando { -brand-name-firefox-browser } com { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Na { -brand-name-firefox } , temos um grande número de usuários dedicados que apreciam nossa dedicação inabalável à privacidade online. Por exemplo, a versão mais recente do { -brand-name-firefox } inclui um recurso chamado Enhanced Tracking Protection (ETP) que é ativado por padrão para todos os usuários em todo o mundo. O ETP bloqueia mais de 2.000 rastreadores, incluindo rastreadores sociais de empresas como { -brand-name-facebook } , { -brand-name-twitter } e LinkedIn. Ele também possui um recurso integrado chamado <a { $attrs }>{ -brand-name-firefox-monitor }</a> que notifica você automaticamente se sua senha foi violada ou precisa ser atualizada. Além dessas proteções, o modo de navegação privada em { -brand-name-firefox } exclui automaticamente suas informações de navegação, como histórico e cookies, não deixando rastros após o término da sessão.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Na { -brand-name-firefox } , temos um grande número de usuários dedicados que apreciam nossa dedicação inabalável à privacidade online. Por exemplo, a versão mais recente do { -brand-name-firefox } inclui um recurso chamado Enhanced Tracking Protection (ETP) que é ativado por padrão para todos os usuários em todo o mundo. O ETP bloqueia mais de 2.000 rastreadores, incluindo rastreadores sociais de empresas como { -brand-name-facebook } , { -brand-name-twitter } e LinkedIn. Ele também possui um recurso integrado chamado <a { $attrs }>{ -brand-name-firefox-monitor }</a> que notifica você automaticamente se sua senha foi violada ou precisa ser atualizada. Além dessas proteções, o modo de navegação privada do { -brand-name-firefox } exclui automaticamente suas informações de navegação, como histórico e cookies, não deixando rastros após o término da sessão.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Também recentemente reafirmamos nosso compromisso com a privacidade e a transparência em relação aos dados do usuário em nosso mais recente <a { $attrs }>Aviso de Privacidade,</a> que afirma: “Na Mozilla, acreditamos que a privacidade é fundamental para uma Internet saudável”.
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } é para todas as contas um navegador seguro, com recursos como { -brand-name-google } Navegação segura, que ajuda a proteger os usuários exibindo um aviso impossível de ignorar quando eles tentam navegar para sites perigosos ou baixar arquivos perigosos.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Em última análise, cabe a você decidir se deve ou não estabelecer limites ao compartilhar itens como seu histórico de pesquisa e de compras. Mas se você for como a maioria das pessoas, provavelmente já pesquisou algumas coisas na Internet que prefere manter privadas.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Avançando até hoje, o cenário competitivo para navegadores mudou, com muitas pessoas começando a questionar o que está acontecendo com seus dados online, como histórico de navegação, senhas e outras informações confidenciais. Muita coisa mudou desde 2008, quando { -brand-name-chrome } entrou em cena. Em { -brand-name-firefox } , estamos trabalhando para reprojetar nossa interface e fornecer aos usuários um número cada vez maior de aprimoramentos de privacidade e desempenho, bem como muitas ferramentas úteis de navegador.
compare-chrome-and-so-here-we-are-the-browser = E então aqui estamos, a guerra dos navegadores está escalando mais uma vez e é hora de reavaliar e comparar { -brand-name-firefox-browser } vs { -brand-name-google } { -brand-name-chrome } .
compare-chrome-in-2008-google-introduced = Em 2008, { -brand-name-google } lançado { -brand-name-chrome } e seu impacto como inovação na tecnologia de navegadores foi imediato. Era mais rápido para carregar sites, ocupava um espaço mínimo na tela e oferecia uma interface de usuário inegavelmente simples.
compare-chrome-in-fact-both-chrome-and-firefox = Na verdade, tanto { -brand-name-chrome } quanto { -brand-name-firefox } possuem segurança rigorosa. Ambos incluem uma coisa chamada “sandboxing” que separa os processos do navegador para que algo como um site nocivo não infecte outras partes do seu laptop ou outro dispositivo.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Embora { -brand-name-chrome } prove ser um navegador seguro, seu registro de privacidade é questionável. { -brand-name-google } na verdade, coleta uma quantidade perturbadoramente grande de dados de seus usuários, incluindo localização, histórico de pesquisa e visitas a sites. { -brand-name-google } defende a coleta de dados dizendo que está fazendo isso para melhorar seus serviços - como ajudá-lo a encontrar um suéter ou um café como aquele que você comprou ou visitou anteriormente. No entanto, outros podem discordar, ressaltando que { -brand-name-google } está, na verdade, reunindo uma quantidade de dados sem precedentes para seus próprios fins de marketing. Eles afirmam que estão mantendo suas informações privadas dos hackers, mas isso não vem ao caso. { -brand-name-google } administra a maior rede de publicidade do mundo, em grande parte graças aos dados que coletam de seus usuários.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Em termos de recursos, tanto { -brand-name-firefox } quanto { -brand-name-chrome } oferecem uma grande biblioteca de extensões e plug-ins, com o catálogo de { -brand-name-chrome } superando em muito qualquer outro navegador, ao mesmo tempo que se integra perfeitamente a outros { -brand-name-google } serviços, como Gmail e { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } também tem um recurso de sincronização para ver suas guias abertas e recentes, histórico de navegação e favoritos em todos os seus dispositivos.
compare-chrome-while-chrome-gets-the-nod = Enquanto { -brand-name-chrome } recebe o aceno com complementos e extensões, { -brand-name-firefox } tem um conjunto bem organizado de recursos integrados, como a ferramenta de captura de tela incrivelmente útil e recurso de modo de leitura que remove tudo da página, exceto o texto do artigo que você está lendo.
compare-chrome-although-not-as-extensive = Embora não seja tão extensa quanto a biblioteca de complementos de { -brand-name-chrome } , { -brand-name-firefox } , como software de código aberto com um grande número de colaboradores ativos, também apresenta um número incrível de extensões úteis.
compare-chrome-if-having-tons-of-open-tabs = Se você gosta de muitas abas abertas, o que importa é sua preferência de IU. { -brand-name-firefox } apresenta uma rolagem horizontal em todas as suas guias abertas, em vez de reduzi-las cada vez mais a cada nova. { -brand-name-google } { -brand-name-chrome } prefere reduzi-los para que apenas o favicon fique visível. O único problema com isso é quando você tem várias guias abertas no mesmo site, então vê o mesmo favicon em todas as suas guias.
compare-chrome-almost-needless-to-say-versions = Quase desnecessário dizer, as versões de { -brand-name-firefox } e { -brand-name-chrome } estão disponíveis para os sistemas operacionais de desktop e móveis mais populares ( { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ).
compare-chrome-both-chrome-and-firefox-also = Tanto { -brand-name-chrome } quanto { -brand-name-firefox } também permitem que você sincronize itens como senhas, favoritos e guias abertas em todos os seus dispositivos. Se você tiver uma conta { -brand-name-firefox } , poderá enviar manualmente uma guia aberta da área de trabalho para o dispositivo móvel ou vice-versa. Com o { -brand-name-chrome } , isso é feito automaticamente se você tiver escolhido essa configuração em suas preferências. Não ter que enviar manualmente a guia de um dispositivo para o outro é conveniente quando você deseja fazer algo como continuar lendo um artigo que não terminou antes. Mas pode haver momentos em que a sincronização automática não seja ideal se houver a chance de vários usuários navegarem enquanto estiverem conectados à sua conta do { -brand-name-google }

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Achamos que é justo dizer que { -brand-name-firefox } e { -brand-name-chrome } são realmente idênticos em termos de portabilidade e utilidade, com { -brand-name-chrome } tendo uma ligeira vantagem em utilidade por causa de sua enorme biblioteca de extensões e recursos complementares. Mas, em termos de privacidade, { -brand-name-firefox } ganha o dia com nosso compromisso de preservar os dados online de nossos usuários e fornecer serviços integrados gratuitos, como gerenciadores de senha, que também alertam se houver uma violação de dados envolvendo suas credenciais.
compare-chrome-as-for-customization-our = Quanto à personalização, nossos fãs dirão que uma das coisas que mais amam em nosso navegador é sua capacidade de permitir que você mova e organize a maioria dos elementos da IU para melhor atender às suas necessidades. { -brand-name-chrome } permite que você oculte certos elementos da IU, mas não há muita permissão, se houver, para mover as coisas com base em suas preferências. No entanto, deve-se observar que { -brand-name-chrome } e { -brand-name-firefox } facilitam bastante a alteração da aparência e do tema do seu navegador.
compare-chrome-for-practical-purposes-theres = Para fins práticos, obviamente não há nada realmente impedindo você de usar os dois navegadores - { -brand-name-firefox } para aqueles momentos da vida em que a privacidade é realmente importante e { -brand-name-chrome } se você ainda estiver investido no { -brand-name-google } ecossistema. No entanto, com o crescente número de incursões em nossos dados pessoais, { -brand-name-firefox } pode provar ser a escolha certa no longo prazo para aqueles de nós que valorizam a proteção de nossa privacidade online.
