# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Sete dos melhores navegadores em comparação direta
compare-index-six-of-the-best-browsers-fallback = Seis dos melhores navegadores em comparação direta

# Sub-headline
compare-index-privacy-utility-portability = Privacidade. Utilitário. Portabilidade.

# HTML page description
compare-index-a-great-internet-browser-should = Um ótimo navegador de internet deve ter a funcionalidade de que você precisa, portabilidade entre dispositivos e a privacidade que você merece.
compare-index-which-browser-is-best-at-keeping = Qual navegador é melhor para manter a confidencialidade?
compare-index-its-not-unreasonable-to-expect = É razoável esperar um alto nível de proteção de dados e privacidade dos produtos que usamos regularmente para ficar online. No mínimo, um navegador deve oferecer alguma versão do “modo de navegação privada” que exclui automaticamente seu histórico e histórico de pesquisa para que outros usuários no mesmo computador não possam acessá-lo. Nesta área, todos os sete navegadores comparados aqui marcam pontos.
compare-index-its-not-unreasonable-to-expect-fallback = É razoável esperar um alto nível de proteção de dados e privacidade dos produtos que usamos regularmente para ficar online. No mínimo, um navegador deve oferecer alguma versão do “modo de navegação privada” que exclui automaticamente seu histórico e histórico de pesquisa para que outros usuários no mesmo computador não possam acessá-lo. Nesta área, todos os seis navegadores comparados aqui marcam pontos.
compare-index-what-you-do-online-literally = O que você faz online literalmente não deve ser da conta de ninguém.
compare-index-another-browser-feature-that = Outro recurso do navegador que deve ser oferecido é a capacidade de impedir que sites e empresas rastreiem seus dados de navegação e compras - mesmo no modo de navegação normal.
compare-index-another-browser-feature-fallback = Outro recurso do navegador que deve ser oferecido é a capacidade de impedir que sites e empresas rastreiem seus dados de navegação e compras - mesmo no modo de navegação normal. Mas esse não é o caso: na verdade, os únicos navegadores que bloqueiam cookies de rastreamento de terceiros por padrão são { -brand-name-firefox } e { -brand-name-safari } .
compare-index-using-a-browser-that-blocks = Usar um navegador que bloqueia rastreadores de terceiros não é importante apenas para a privacidade - geralmente significa que ele é executado muito mais rápido também. A maioria dos rastreadores são apenas scripts executados em segundo plano em vários sites. Você não pode vê-los, mas pode senti-los desacelerando seu navegador. A partir da versão 67 de { -brand-name-firefox } , impressão digital e criptominadores também são bloqueados. Se você não está familiarizado com criptomineradores, aqui está um exemplo de como eles podem afetá-lo: talvez você tenha experimentado seu computador ficar mais quente de repente ou a bateria esgotar mais rápido do que o normal. Isso geralmente é o subproduto de criptomineradores rastejando em seu dispositivo.
compare-index-what-has-your-browser-done = O que seu navegador fez por você ultimamente?
compare-index-in-addition-to-privacy-protection = Além da proteção da privacidade, que ocorre em grande parte no plano de fundo do navegador, outro ingrediente importante para um navegador bem feito é a interface do usuário e a funcionalidade reais. Quase todos os sete navegadores são iguais quando se trata de navegação por guias, gerenciamento de favoritos, preenchimento automático, revisão e extensões. { -brand-name-firefox } , { -brand-name-edge } e { -brand-name-opera } também oferecem uma função de captura de tela rápida que prova ser bastante útil e é definitivamente algo que você percebe que está faltando quando muda para um navegador sem ela.
compare-index-in-addition-to-privacy-protection-fallback = Além da proteção da privacidade, que ocorre em grande parte no plano de fundo do navegador, outro ingrediente importante para um navegador bem feito é a interface do usuário e a funcionalidade reais. Quase todos os seis navegadores são iguais quando se trata de navegação em guias, gerenciamento de favoritos, preenchimento automático, revisão e extensões. { -brand-name-firefox } , { -brand-name-edge } e { -brand-name-opera } também oferecem uma função de captura de tela rápida que prova ser bastante útil e é definitivamente algo que você percebe que está faltando quando muda para um navegador sem ela.
compare-index-how-well-does-your-browser = O seu navegador funciona bem em todos os seus dispositivos?
compare-index-almost-all-of-the-browsers = Quase todos os navegadores comparados aqui permitem a sincronização entre desktops e dispositivos móveis. Você precisará de uma conta para fazer isso, que pode ser usada para fazer login no navegador em todos os dispositivos e sincronizar coisas como senhas, histórico de navegação, favoritos e configurações.
compare-index-conclusion = Conclusão:
compare-index-and-the-winner-is = E o vencedor é…
compare-index-find-out-how-firefox-chrome = Descubra como { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } e { -brand-name-ie } diferem em termos de privacidade, utilidade e portabilidade.
compare-index-find-out-how-firefox-fallback = Descubra como { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } e { -brand-name-ie } diferem em termos de privacidade, utilidade e portabilidade.
compare-index-looking-for-a-better-browser = Procurando um navegador melhor? Compararemos { -brand-name-firefox } com { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } e { -brand-name-ie } para ajudá-lo a tomar sua decisão.
compare-index-looking-for-a-better-fallback = Procurando um navegador melhor? Compararemos { -brand-name-firefox } com { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } e { -brand-name-ie } para ajudá-lo a tomar sua decisão.
compare-index-so-is-your-browser-the-best = Então, o seu navegador é o melhor para o que você faz online? O navegador certo pode fazer uma grande diferença em como você usa a web. Portanto, sem mais delongas, vamos comparar { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } , { -brand-name-microsoft } { -brand-name-ie } e { -brand-name-edge } - e ver qual atende melhor às suas necessidades.
compare-index-so-is-your-browser-the-fallback = Então, o seu navegador é o melhor para o que você faz online? O navegador certo pode fazer uma grande diferença em como você usa a web. Portanto, sem mais delongas, vamos comparar { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-microsoft } { -brand-name-ie } e { -brand-name-edge } - e ver qual atende melhor às suas necessidades.
compare-index-since-your-browser-is-your = Como seu navegador é o seu portal para a internet, velocidade, segurança, privacidade e utilidade são fundamentais. Nos últimos anos, { -brand-name-google } { -brand-name-chrome } tem sido o navegador preferido de muitos. Mas em uma época em que os anúncios online parecem nos seguir em todos os lugares e as violações de dados são uma característica das manchetes de notícias, muitas pessoas estão começando a exigir mais privacidade e respeito de seus navegadores.
compare-index-the-first-thing-to-point-out = A primeira coisa a destacar sobre a portabilidade é que nem todos os navegadores são executados em todos os sistemas operacionais. Embora { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-brave } e { -brand-name-opera } funcionem em todos os sistemas principais e sejam fáceis de instalar, { -brand-name-ie } e { -brand-name-safari } funcionam apenas em { -brand-name-microsoft } e nos próprios sistemas da Apple. A versão móvel do { -brand-name-safari } é pré-instalada nos dispositivos móveis da Apple e a maioria dos dispositivos { -brand-name-android } vem com um navegador pré-instalado modificado pelo fabricante para o dispositivo. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-brave } , { -brand-name-edge } e { -brand-name-opera } podem ser facilmente instalados e até usados lado a lado.
compare-index-the-first-thing-to-point-fallback = A primeira coisa a destacar sobre a portabilidade é que nem todos os navegadores são executados em todos os sistemas operacionais. Enquanto { -brand-name-firefox } , { -brand-name-chrome } e { -brand-name-opera } funcionam em todos os principais sistemas e são fáceis de instalar, { -brand-name-ie } , { -brand-name-edge } e { -brand-name-safari } funcionam apenas em { -brand-name-microsoft } e nos próprios sistemas da Apple. A versão móvel do { -brand-name-safari } é pré-instalada nos dispositivos móveis da Apple e a maioria dos dispositivos { -brand-name-android } vem com um navegador pré-instalado modificado pelo fabricante para o dispositivo. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } e { -brand-name-opera } podem ser facilmente instalados e até usados lado a lado.
compare-index-browsers-have-come-a-long = Os navegadores já percorreram um longo caminho desde que o { -brand-name-chrome } foi lançado e conquistou a participação no mercado. A maioria dos navegadores modernos eliminou a lacuna em termos de portabilidade e funcionalidade e, em algumas áreas, como velocidade e privacidade, superou { -brand-name-chrome } . Ainda assim, determinar qual navegador é certo para você sempre dependerá de suas necessidades individuais e do que você mais valoriza ao navegar online.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } é apoiado pela organização sem fins lucrativos { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } coloca a sua privacidade em primeiro lugar - em tudo o que fazemos e fazemos. Acreditamos que você tem o direito de decidir como e com quem compartilha suas informações pessoais. { -brand-name-firefox } coleta o mínimo de dados possível e nunca os vende. Os poucos dados que coletamos são usados apenas para melhorar os produtos e recursos. Sem segredos. Mas muita transparência e privacidade real.
compare-index-based-on-the-criteria-we-outlined = Com base nos critérios que descrevemos - privacidade, utilidade e portabilidade - há apenas um navegador que atende à marca, e esse é { -brand-name-firefox } . A verdadeira diferença não está na funcionalidade, mas na privacidade. { -brand-name-firefox } é o navegador mais privado que não bloqueia você em um ecossistema. Use-o em qualquer sistema operacional, em todos os seus dispositivos e sinta-se seguro ao fazer isso.
