# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } против { -brand-name-microsoft } { -brand-name-edge } : какой браузер вам больше подходит?

# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Сравните { -brand-name-microsoft } { -brand-name-edge } с { -brand-name-firefox-browser } чтобы выбрать лучший браузер для вас.

# Main title.
compare-edge-comparing-firefox-browser-with = Сравнение { -brand-name-firefox-browser } с { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = С { -brand-name-windows } 10, { -brand-name-microsoft } представила { -brand-name-edge } браузер , чтобы конкурировать с { -brand-name-firefox } и { -brand-name-chrome } , что делает его браузером по умолчанию , предварительно установленная на миллионах компьютеров , проданных. Несмотря на это, пользователи не спешили его внедрять, и { -brand-name-microsoft } конце концов объявили о планах перезапустить { -brand-name-edge } в качестве браузера на основе { -brand-name-chromium } ( { -brand-name-chromium } конечно, является проектом браузера с открытым исходным кодом { -brand-name-google } ).
compare-edge-here-well-compare-our-firefox = Здесь мы сравним наши { -brand-name-firefox-browser } с { -brand-name-chromium } { -brand-name-microsoft } { -brand-name-edge } с точки зрения конфиденциальности, полезности и переносимости, чтобы помочь вам лучше понять, какой браузер лучше соответствует вашим потребностям и предпочтениям.

# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } интегрирован в платформу { -brand-name-windows } 10 и работает в изолированной среде, что означает, что он изолирует программы и предотвращает слежку за вашим компьютером со стороны вредоносных программ. Он имеет встроенный SmartScreen, который проверяет репутацию посещаемых вами сайтов и блокирует подозрительные сайты. Для повышения конфиденциальности { -brand-name-edge } позволяет использовать биометрические данные или PIN-код с { -brand-name-edge } Hello вместо паролей для сетевой аутентификации.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = В { -brand-name-firefox } мы гордимся тем, что защищаем безопасность и конфиденциальность наших пользователей. Наша <a { $attrs }>политика конфиденциальности</a> прозрачна и изложена простым языком. Мы действительно приложили немало усилий, чтобы сделать его понятным и легким для чтения. Теперь, когда по умолчанию включена улучшенная защита от отслеживания, мы автоматически блокируем более 2000 трекеров. Трекеры - это те небольшие фрагменты кода, которые пытаются собрать воедино то, что вы делаете на нескольких интернет-сайтах, чтобы создать составное и подробное представление о том, кто вы есть, ставя под угрозу вашу конфиденциальность, просто чтобы нацелить лучшую рекламу.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = В { -brand-name-firefox } наша <a { $attrs }>политика конфиденциальности</a> прозрачна и изложена простым языком. Мы действительно приложили немало усилий, чтобы сделать его понятным и легким для чтения. Мы гордимся тем, что защищаем безопасность и конфиденциальность наших пользователей. Теперь, когда по умолчанию включена улучшенная защита от отслеживания, мы автоматически блокируем более 2000 трекеров. Трекеры - это те небольшие фрагменты кода, которые пытаются собрать воедино то, что вы делаете на нескольких интернет-сайтах, чтобы создать составное и подробное представление о том, кто вы есть, ставя под угрозу вашу конфиденциальность, просто чтобы нацелить лучшую рекламу.

# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = В ваших средствах <a { $attrs }>защиты конфиденциальности</a> указаны средства отслеживания и файлы cookie, которые страницы пытались покинуть, и сколько { -brand-name-firefox } заблокировал для вас.

# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = В { -brand-name-firefox } режим частного просмотра автоматически удаляет информацию о просмотре, такую как пароли, файлы cookie и историю, не оставляя следов после закрытия сеанса. { -brand-name-edge } с другой стороны, на самом деле записывает историю просмотров в своем частном режиме (называемом «InPrivate»), и для кого-то относительно легко восстановить полную историю просмотров, независимо от того, выполнялся ли просмотр в обычном или в режиме InPrivate.
compare-edge-both-browsers-are-relatively = Оба браузера относительно равны с точки зрения шифрования данных. Однако, если для вас важны конфиденциальность и прозрачность в Интернете, тогда { -brand-name-firefox } , безусловно, лучший выбор.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } - это быстрый браузер с открытым исходным кодом, что означает, что пользователи могут настраивать свои действия в Интернете всеми возможными способами. { -brand-name-firefox } также позволяет обычному пользователю несколькими способами настроить пользовательский интерфейс с применением различных тем и конфигураций панелей инструментов. Поскольку наш браузер всегда был с открытым исходным кодом, у нас есть большое количество преданных разработчиков, которые создали обширную библиотеку надстроек и расширений браузера.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } - это быстрый браузер с открытым исходным кодом, что означает, что пользователи могут настраивать свои действия в Интернете всеми возможными способами. { -brand-name-firefox } также позволяет обычному пользователю несколькими способами настроить пользовательский интерфейс с применением различных тем и конфигураций панелей инструментов. Поскольку наш браузер всегда был с открытым исходным кодом, у нас есть большое количество преданных разработчиков, которые создали обширную библиотеку надстроек и расширений браузера.
compare-edge-since-edge-has-moved-to-the = Поскольку { -brand-name-edge } перешел на платформу { -brand-name-chromium } , интенсивно использующую процессор, можно ожидать, что он будет работать немного медленнее, особенно если у вас одновременно работает несколько программ. Однако платформа { -brand-name-chromium } включает огромную библиотеку расширений, а также приличный уровень настройки пользовательского интерфейса, которого у { -brand-name-edge } не было до перехода на { -brand-name-chromium } .
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } есть несколько приятных функций пользовательского интерфейса, например предварительный просмотр вкладок, который позволяет легко находить нужные открытые вкладки, если у вас их много. Еще одна полезная функция, связанная с вкладками, позволяет вам отложить любые активные вкладки, которые вы не используете, но не хотите закрывать.

# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } имеет интерфейс вкладок с прокруткой, который позволяет просматривать информацию о вкладках и прокручивать их по горизонтали, а не уменьшать до размера значка значка. Кроме того, всякий раз, когда вы открываете новую вкладку, наша <a { $attrs }>функция { -brand-name-pocket }</a> предлагает вам соответствующие статьи и контент. Кроме того, с помощью { -brand-name-pocket } вы также можете одним щелчком мыши сохранять статьи, видео и другой контент для последующего чтения.
compare-edge-firefox-and-edge-both-offer = { -brand-name-firefox } и { -brand-name-edge } предлагают отличные режимы чтения. Используя { -brand-name-firefox } , вы просто нажимаете на маленький значок в строке поиска, и браузер удаляет все ненужные элементы и представляет вам статью, которая выглядит аккуратно. В { -brand-name-edge } вы просто нажимаете на маленький значок книги и браузер, чтобы получить чистый, легко читаемый интерфейс.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } и { -brand-name-edge } предлагают отличные режимы чтения. С помощью { -brand-name-firefox } вы просто нажимаете на маленький значок в строке поиска, и браузер удаляет все ненужные элементы и представляет вам статью, которая выглядит аккуратно. В { -brand-name-edge } вы просто нажимаете на маленький значок книги и браузер, чтобы получить чистый, легко читаемый интерфейс.

# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } также по умолчанию включает множество удобных встроенных функций, таких как <a { $attrs }>улучшенная защита от отслеживания</a> , встроенный инструмент для создания снимков экрана, отправка больших файлов и многое другое.

# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Совершенно неожиданно { -brand-name-firefox } имеет больше функций и интеграций, встроенных в браузер и легко доступных для загрузки. И в то время как браузеры имеют огромное количество дополнений и расширений , доступных, { -brand-name-edge } «сек Совместимость с { -brand-name-google } » s { -brand-name-chromium } платформа дает ему преимущество с точки зрения абсолютных цифрах.

compare-edge-with-internet-explorer-microsoft = С { -brand-name-ie } , { -brand-name-microsoft } учился на его недостаточной доступности на разных платформах и сделал { -brand-name-edge } доступным на { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } , { -brand-name-mac } , а вскоре и на { -brand-name-linux } .
compare-edge-with-internet-explorer-fallback = С { -brand-name-ie } , { -brand-name-microsoft } учился на его недоступности на разных платформах и сделал { -brand-name-edge } доступным для { -brand-name-mac } и { -brand-name-android } . Программное обеспечение теперь доступно на { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } и { -brand-name-mac } .

# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } много лет доступен на { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } , { -brand-name-mac } и { -brand-name-linux } . И, как и следовало ожидать от любого современного браузера, { -brand-name-firefox } позволяет вам войти в систему с помощью <a { $attrs }>бесплатной учетной записи</a> и синхронизировать данные, такие как пароли, историю просмотров, закладки и открытые вкладки между вашим компьютером, планшетом и телефоном. Это также позволяет синхронизировать между платформами.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } также позволяет подключить связанный аккаунт { -brand-name-microsoft } и выполнить вход для синхронизации избранного, истории, паролей и других данных между вашим компьютером и устройствами { -brand-name-ios } или { -brand-name-android } .
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } также позволяет подключить связанный аккаунт { -brand-name-microsoft } и выполнить вход для синхронизации избранного, истории, паролей и других данных между вашим компьютером и устройствами { -brand-name-ios } или { -brand-name-android } , хотя некоторые планшеты { -brand-name-android } в настоящее время не поддерживается.

# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Помимо использования большой вычислительной мощности, { -brand-name-edge } запуск на { -brand-name-chromium } ответил множеству потребностей пользователей в функциональности и функциях. Но еще многое нужно учитывать с точки зрения защиты конфиденциальности браузера. По нашей оценке, { -brand-name-firefox } по-прежнему является лучшим выбором для большинства людей в повседневной жизни, основываясь не только на функциональности, но, что более важно, на нашей прозрачности в том, как мы собираем данные пользователей, что именно мы собираем и что мы делаем с Это. Поскольку наша материнская компания является <a { $attrs }>{ -brand-name-mozilla }</a> некоммерческой организацией, занимающейся вопросами конфиденциальности и свободы в Интернете, у нас просто другой набор приоритетов, когда дело касается данных пользователей.
compare-edge-the-bottom-line-is-that-while = Суть в том, что, хотя мы предлагаем использовать { -brand-name-firefox } , лучший браузер для вас в конечном итоге будет тот, который соответствует вашим индивидуальным потребностям с поддержкой расширений, настройкой инструментов просмотра, скоростью, конфиденциальностью и безопасностью.
