# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } против { -brand-name-safari } : какой браузер вам больше подходит?

# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } - это предварительно установленный браузер в { -brand-name-mac } и { -brand-name-iphone } . Сравните { -brand-name-safari } с { -brand-name-firefox-browser } чтобы выбрать лучший браузер для вас.

# Main title.
compare-safari-comparing-firefox-browser = Сравнение { -brand-name-firefox-browser } с { -brand-name-apple } { -brand-name-safari }

# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Если вы используете Mac или { -brand-name-iphone } , скорее всего, вы знакомы с веб-браузером { -brand-name-safari } . Тот факт, что он предварительно установлен в качестве браузера по умолчанию для пользователей продукта { -brand-name-apple } определенно дает ему преимущество на раннем этапе, но { -brand-name-firefox } имеет свой собственный набор полезных функций, которые делают его привлекательной альтернативой. Здесь мы рассмотрим основные различия между нашим браузером и { -brand-name-safari } с точки зрения конфиденциальности, полезности и переносимости между устройствами.

# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Конфиденциальность стала горячей темой для технологических компаний, поскольку они понимают, что все больше и больше людей чувствуют себя уязвимыми для таких вещей, как утечки данных, рекламные трекеры и хакеры. Но когда дело доходит до реальных инструментов, которые люди используют для навигации по реальной сети, все ли это разговоры или они на самом деле принимают меры для защиты ваших данных?
compare-safari-as-alluded-to-before-apple-fallback = Как упоминалось ранее, { -brand-name-apple } - одна из тех компаний, которые недавно решили активизировать свою политику конфиденциальности. Не так давно { -brand-name-apple } реализовал предотвращение межсайтового отслеживания в { -brand-name-safari } , которое предотвращает отслеживание вашей рекламы в Интернете. { -brand-name-safari } также предлагает надежный пароль при регистрации новой учетной записи на любом веб-сайте. И если вы инвестировали в экосистему iCloud, она надежно синхронизирует этот пароль с другими вашими устройствами, поэтому вам никогда не придется его запоминать.

# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Как и { -brand-name-safari } , мы в { -brand-name-firefox } сделали упор на конфиденциальность и безопасность. Но в отличие от { -brand-name-safari } , мы давно стоим на мыльнице. Фактически, { -brand-name-mozilla } (наша материнская компания) была одним из первых представителей технического сообщества, которые забили тревогу в отношении конфиденциальности в Интернете.

# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Наш режим приватного просмотра блокирует трекеры и стирает ваши пароли, файлы cookie и историю каждый раз, когда вы закрываете его. Но вы также можете испытать наши расширенные функции конфиденциальности даже в обычном режиме просмотра. В последней версии { -brand-name-firefox } расширенная защита от отслеживания включена по умолчанию. Это предотвращает отслеживание вас такими вещами, как межсайтовые трекеры, когда вы прыгаете по сети. Кроме того, поскольку { -brand-name-facebook } почти ежедневно выявляется из-за проблем с конфиденциальностью, наше расширение <a { $attrs }>{ -brand-name-facebook-container }</a> имеет большой смысл. { -brand-name-facebook } усложняет отслеживание вас в Интернете - аналогично тому, как { -brand-name-safari } предотвращает межсайтовое отслеживание, - но { -brand-name-firefox } фактически изолирует ваш сеанс { -brand-name-facebook } в отдельный контейнер, блокируя { -brand-name-facebook } отслеживание что вы делаете на других сайтах. Зачем им вообще нужно знать, что вы смотрите на WebMD?

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Что касается безопасности, { -brand-name-firefox } здесь тоже надежен. Каждый раз, когда вы находитесь в { -brand-name-firefox } , вы можете щелкнуть правой кнопкой мыши в поле пароля, чтобы безопасно сгенерировать надежный пароль с помощью параметра «Введите пароль». Когда вы сохраните новый пароль, мы предложим вам сохранить его во встроенном диспетчере паролей, <a { $lockwise }>{ -brand-name-lockwise }</a> . Мы также обслуживаем пользователей и владельцев аккаунтов с помощью другого бесплатного и полезного продукта под названием <a { $monitor }>{ -brand-name-monitor }</a> который автоматически предупреждает вас, если ваши данные попадают в известную утечку данных.
compare-safari-if-you-choose-to-use-safari = Если вы решите использовать { -brand-name-safari } , вы в надежных руках, пока используете устройство { -brand-name-apple } . Но { -brand-name-safari } работает только на { -brand-name-apple } устройствах, тогда как { -brand-name-firefox } работает на { -brand-name-windows } , { -brand-name-mac } , { -brand-name-ios } , { -brand-name-android } и { -brand-name-linux } . Независимо от того, какую операционную систему вы выберете, { -brand-name-firefox } предоставит вам наши меры безопасности и защиты конфиденциальности.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } широко известна своей закрытой экосистемой, связанной с созданием программного обеспечения для своих продуктов. Но внутри { -brand-name-app-store } он предлагает разработчикам раздел для создания подключаемых модулей и надстроек, чтобы сделать браузер более надежным. Эти расширения также доступны для просмотра через { -brand-name-app-store } и легко добавляются в { -brand-name-safari } .
compare-safari-in-addition-to-the-regular = В дополнение к обычному набору функций, которые вы ожидаете от браузера, таким как просмотр с вкладками и частный просмотр, { -brand-name-safari } имеет некоторые неожиданные функции. Например, если пользователь щелкнет правой кнопкой мыши слово в любом месте страницы внутри { -brand-name-safari } , а затем нажмите «Поиск», он получит определение словаря плюс записи из тезауруса, { -brand-name-app-store } , фильмов и т. Д. Родительский контроль { -brand-name-safari } легко настраивается, позволяя взрослым вздохнуть с облегчением, когда дети начинают интересоваться Интернетом.

# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Как и { -brand-name-safari } , { -brand-name-firefox } призывает свое сообщество разработчиков с энтузиазмом создавать <a { $attrs }>надстройки и расширения</a> для браузера. А поскольку наша платформа с открытым исходным кодом, существует огромный выбор, добавляющий множество функций.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Кроме того, когда вы регистрируете учетную запись { -brand-name-firefox } вы получаете доступ к уникальным службам, таким как <a { $pocket }>{ -brand-name-pocket }</a> и <a { $send }>{ -brand-name-send }</a> которые интегрируются непосредственно в браузер. Кнопка { -brand-name-pocket } для { -brand-name-firefox } позволяет вам сохранять веб-страницы и видео в { -brand-name-pocket } одним щелчком мыши, так что вы можете читать чистую версию без отвлекающих факторов в любое время и в любом месте - даже в автономном режиме. С { -brand-name-send } вы можете обмениваться большими файлами с помощью сквозного шифрования с различными элементами управления безопасностью, такими как возможность установить время истечения срока действия ссылки на файл, количество загрузок и необходимость добавления дополнительного пароль для дополнительного уровня безопасности.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Кроме того, когда вы регистрируете учетную запись { -brand-name-firefox } вы получаете доступ к некоторым уникальным сервисам, таким как «Снимки экрана», <a { $pocket }>{ -brand-name-pocket }</a> и <a { $send }>{ -brand-name-send }</a> которые интегрируются непосредственно в браузер. Скриншоты - это функция, встроенная прямо в браузер { -brand-name-firefox } , позволяющая копировать или загружать любую или всю часть веб-страницы. Когда вы сохраняете снимок экрана, вы также можете выбрать, в какой папке вы хотите его найти, вместо того, чтобы загромождать рабочий стол. Кнопка { -brand-name-pocket } для { -brand-name-firefox } позволяет вам сохранять веб-страницы и видео в { -brand-name-pocket } одним щелчком мыши, так что вы можете читать чистую версию без отвлекающих факторов в любое время и в любом месте - даже в автономном режиме. С помощью { -brand-name-send } вы можете обмениваться большими файлами с помощью сквозного шифрования и различных мер безопасности, таких как возможность установить время истечения срока действия ссылки на файл, количество загрузок и необходимость добавления необязательный пароль для дополнительного уровня безопасности.

# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Скриншоты</a> - еще одна популярная функция, встроенная прямо в браузер { -brand-name-firefox } , позволяющая легко делать снимки экрана. Когда вы делаете снимок экрана, вы можете скопировать файл или выбрать, в какой папке вы хотите его найти, вместо того, чтобы загромождать рабочий стол.

# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } и { -brand-name-safari } обеспечивают беспроблемный переход с настольного компьютера на просмотр на мобильном устройстве и наоборот. Для { -brand-name-safari } одной из основных сильных сторон является его непрерывность. Он синхронизирует ваши закладки, вкладки, историю и многое другое с iCloud, поэтому они доступны на всех ваших устройствах. Это означает, что вы можете открыть вкладку на вашем { -brand-name-iphone } и она также появится на вашем ноутбуке { -brand-name-mac } одним щелчком мыши.
compare-safari-both-browsers-have-a-lot = Оба браузера имеют множество перекрестных функций, а также некоторые уникальные функции. Стоит отметить, что если вы сделаете много снимков экрана, вы удивитесь, как вы когда-либо жили без этой удобной функции, встроенной прямо в { -brand-name-firefox } . Но если вы просто ищете быстрый частный браузер для просмотра веб-страниц и покупок, вы можете попробовать { -brand-name-firefox } - особенно если вы использовали исключительно { -brand-name-safari } потому что он был предварительно загружен в качестве браузера по умолчанию на твой компьютер. В конце концов вы обнаружите, какой из них больше подходит для ваших нужд.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } также предлагает аналогичную функцию синхронизации при подписке на бесплатный <a { $attrs }>{ -brand-name-firefox-account }</a> который позволяет пользователям легко синхронизировать свои закладки, историю просмотров, настройки, пароли, заполненные формы, надстройки и последние 25 открытых вкладок на нескольких компьютеры. Что отличает { -brand-name-firefox } от { -brand-name-safari } это то, что он доступен на любой настольной или мобильной платформе, { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } или { -brand-name-macos } , что повышает его мобильность на любом устройстве, которым вы можете владеть.

# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Приложение { -brand-name-firefox } для <a { $ios }>{ -brand-name-ios }</a> и <a { $android }>{ -brand-name-android }</a> является одним из самых быстрых доступных браузеров, а также имеет надежные функции безопасности и защиты от слежения - огромный плюс, если вы постоянно переключаетесь между ноутбуком и мобильными устройствами.
compare-safari-since-safari-is-apples-proprietary = Поскольку { -brand-name-safari } является проприетарным веб-браузером { -brand-name-apple } , его синхронизация с iCloud работает исключительно с продуктами { -brand-name-apple } . Это может быть несколько ограничивающим, если, например, вы одновременно являетесь пользователем { -brand-name-android } пользователем { -brand-name-iphone } или если у вас есть ПК на базе { -brand-name-windows } для работы, но вы используете { -brand-name-iphone } качестве личного устройства.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } отлично справляется с задачей упрощения, скорости и бесперебойности работы в Интернете, если вы { -brand-name-apple } пользуетесь несколькими продуктами { -brand-name-apple } . Как и { -brand-name-safari } , { -brand-name-firefox } - это быстрый и практичный браузер, но конфиденциальность и кроссплатформенная совместимость - наши определяющие особенности. { -brand-name-firefox } обновляет каждый месяц новые функции и возможности. Например, одно недавнее обновление включило нашу <a { $attrs }>улучшенную защиту от отслеживания (ETP)</a> по умолчанию для новых пользователей, которая эффективно блокирует файлы cookie и межсайтовые трекеры.
compare-safari-in-the-end-it-just-boils = В конце концов, все сводится к тому, что вы цените в своем браузере. Если вы интегрированы в экосистему { -brand-name-apple } , { -brand-name-safari } по-прежнему будет отличным выбором. Но если вы цените новейшие и самые надежные средства защиты конфиденциальности и возможность работать в нескольких операционных системах, мы думаем, что { -brand-name-firefox } - ваш лучший выбор. { -brand-name-firefox } также является надежным вариантом в качестве дополнительного браузера для тех { -brand-name-apple } -эксклюзивных пользователей, которые могут захотеть переключиться на другой браузер для тех моментов в сети, которые требуют дополнительных уровней защиты конфиденциальности.
