# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = سبعة من أفضل المتصفحات في المقارنة المباشرة
compare-index-six-of-the-best-browsers-fallback = ستة من أفضل المتصفحات في المقارنة المباشرة

# Sub-headline
compare-index-privacy-utility-portability = خصوصية. خدمة. قابلية التنقل.

# HTML page description
compare-index-a-great-internet-browser-should = يجب أن يتمتع متصفح الإنترنت الرائع بالوظائف التي تحتاجها ، وإمكانية النقل عبر الأجهزة ، والخصوصية التي تستحقها.
compare-index-which-browser-is-best-at-keeping = أي متصفح هو الأفضل في الحفاظ على سرية الأشياء؟
compare-index-its-not-unreasonable-to-expect = ليس من غير المعقول توقع مستوى عالٍ من حماية البيانات والخصوصية من المنتجات التي نستخدمها بانتظام للاتصال بالإنترنت. كحد أدنى ، يجب أن يقدم المتصفح إصدارًا من "وضع التصفح الخاص" الذي يحذف محفوظاتك وسجل البحث تلقائيًا حتى لا يتمكن المستخدمون الآخرون على نفس الكمبيوتر من الوصول إليه. في هذا المجال ، تسجل جميع المتصفحات السبعة التي تمت مقارنتها هنا نقاطًا.
compare-index-its-not-unreasonable-to-expect-fallback = ليس من غير المعقول توقع مستوى عالٍ من حماية البيانات والخصوصية من المنتجات التي نستخدمها بانتظام للاتصال بالإنترنت. كحد أدنى ، يجب أن يقدم المتصفح إصدارًا من "وضع التصفح الخاص" الذي يحذف محفوظاتك وسجل البحث تلقائيًا حتى لا يتمكن المستخدمون الآخرون على نفس الكمبيوتر من الوصول إليه. في هذا المجال ، تسجل جميع المتصفحات الستة التي تمت مقارنتها هنا نقاطًا.
compare-index-what-you-do-online-literally = ما تفعله عبر الإنترنت لا ينبغي أن يكون من اختصاص أي شخص آخر.
compare-index-another-browser-feature-that = ميزة متصفح أخرى يجب أن تكون معطاة وهي القدرة على منع مواقع الويب والشركات من تتبع بيانات التصفح والتسوق - حتى في وضع التصفح العادي.
compare-index-another-browser-feature-fallback = ميزة متصفح أخرى يجب أن تكون معطاة وهي القدرة على منع مواقع الويب والشركات من تتبع بيانات التصفح والتسوق - حتى في وضع التصفح العادي. ولكن هذا ليس هو الحال في الواقع: في الواقع ، المتصفحات الوحيدة التي تحظر ملفات تعريف ارتباط تتبع الجهات الخارجية بشكل افتراضي هي { -brand-name-firefox } و { -brand-name-safari } .
compare-index-using-a-browser-that-blocks = إن استخدام متصفح يحظر متتبعات الجهات الخارجية ليس مهمًا فقط للخصوصية - فهو يعني عادةً أنه يعمل بشكل أسرع أيضًا. معظم أدوات التتبع عبارة عن نصوص برمجية تعمل في الخلفية على عدد من مواقع الويب. لا يمكنك رؤيتها ، لكن يمكنك أن تشعر أنها تبطئ متصفحك. اعتبارًا من الإصدار 67 من { -brand-name-firefox } ، تم أيضًا حظر بصمات الأصابع وأدوات التشفير. إذا لم تكن معتادًا على أدوات التشفير ، فإليك مثالاً على كيفية تأثيرها عليك: ربما تكون قد جربت أن جهاز الكمبيوتر الخاص بك أصبح ساخنًا فجأة أو أن البطارية تنفد بشكل أسرع من المعتاد. غالبًا ما يكون هذا ناتجًا ثانويًا عن عوامل التشفير التي تتسلل على جهازك.
compare-index-what-has-your-browser-done = ما الذي فعله متصفحك من أجلك مؤخرًا؟
compare-index-in-addition-to-privacy-protection = بالإضافة إلى حماية الخصوصية ، والتي تحدث بشكل كبير في خلفية المتصفح ، هناك عنصر رئيسي آخر لمتصفح جيد الصنع وهو واجهة المستخدم الفعلية ووظائفه. تتساوى جميع المتصفحات السبعة تقريبًا عندما يتعلق الأمر بتصفح علامات التبويب وإدارة الإشارات المرجعية والإكمال التلقائي والتدقيق اللغوي والإضافات. { -brand-name-firefox } و { -brand-name-edge } و { -brand-name-opera } أيضًا وظيفة لقطة شاشة سريعة تثبت أنها سهلة الاستخدام وهي بالتأكيد شيء تلاحظ أنه مفقود عند التبديل إلى متصفح بدونه.
compare-index-in-addition-to-privacy-protection-fallback = بالإضافة إلى حماية الخصوصية ، والتي تحدث بشكل كبير في خلفية المتصفح ، هناك عنصر رئيسي آخر لمتصفح جيد الصنع وهو واجهة المستخدم الفعلية ووظائفه. جميع المتصفحات الستة تقريبًا متساوية عندما يتعلق الأمر بتصفح علامات التبويب وإدارة الإشارات المرجعية والإكمال التلقائي والتدقيق اللغوي والإضافات. { -brand-name-firefox } و { -brand-name-edge } و { -brand-name-opera } أيضًا وظيفة لقطة شاشة سريعة تثبت أنها سهلة الاستخدام وهي بالتأكيد شيء تلاحظ أنه مفقود عند التبديل إلى متصفح بدونه.
compare-index-how-well-does-your-browser = ما مدى جودة عمل متصفحك عبر أجهزتك؟
compare-index-almost-all-of-the-browsers = تسمح جميع المتصفحات التي تمت مقارنتها هنا تقريبًا بالمزامنة بين أجهزة سطح المكتب والأجهزة المحمولة. ستحتاج إلى حساب للقيام بذلك ، والذي يمكنك استخدامه لتسجيل الدخول إلى المتصفح على جميع الأجهزة ومزامنة أشياء مثل كلمات المرور وسجل التصفح والإشارات المرجعية والإعدادات.
compare-index-conclusion = خاتمة:
compare-index-and-the-winner-is = و الفائز هو…
compare-index-find-out-how-firefox-chrome = اكتشف كيف تختلف { -brand-name-firefox } و { -brand-name-chrome } و { -brand-name-edge } و { -brand-name-safari } و { -brand-name-opera } و { -brand-name-brave } و { -brand-name-ie } من حيث الخصوصية والأداة وإمكانية النقل.
compare-index-find-out-how-firefox-fallback = اكتشف كيف تختلف { -brand-name-firefox } و { -brand-name-chrome } و { -brand-name-edge } و { -brand-name-safari } و { -brand-name-opera } و { -brand-name-ie } من حيث الخصوصية والأداة وإمكانية النقل.
compare-index-looking-for-a-better-browser = هل تبحث عن متصفح أفضل؟ سنقارن { -brand-name-firefox } بـ { -brand-name-chrome } و { -brand-name-edge } و { -brand-name-safari } و { -brand-name-opera } و { -brand-name-brave } و { -brand-name-ie } لمساعدتك في اتخاذ قرارك.
compare-index-looking-for-a-better-fallback = هل تبحث عن متصفح أفضل؟ سنقارن { -brand-name-firefox } بـ { -brand-name-chrome } و { -brand-name-edge } و { -brand-name-safari } و { -brand-name-opera } و { -brand-name-ie } لمساعدتك في اتخاذ قرارك.
compare-index-so-is-your-browser-the-best = فهل متصفحك هو الأفضل لما تفعله على الإنترنت؟ يمكن للمتصفح الصحيح أن يُحدث فرقًا كبيرًا في كيفية تجربتك للويب. لذلك ، بدون مزيد من اللغط ، دعنا نقارن { -brand-name-google } { -brand-name-chrome } و { -brand-name-firefox } و { -brand-name-safari } و { -brand-name-opera } و { -brand-name-brave } و { -brand-name-microsoft } { -brand-name-ie } و { -brand-name-edge } - ونرى أيها يناسب احتياجاتك.
compare-index-so-is-your-browser-the-fallback = فهل متصفحك هو الأفضل لما تفعله على الإنترنت؟ يمكن للمتصفح الصحيح أن يُحدث فرقًا كبيرًا في كيفية تجربتك للويب. لذلك ، بدون مزيد من اللغط ، دعنا نقارن { -brand-name-google } { -brand-name-chrome } و { -brand-name-firefox } و { -brand-name-safari } و { -brand-name-opera } و { -brand-name-microsoft } { -brand-name-ie } و { -brand-name-edge } - ونرى أيها يناسب احتياجاتك.
compare-index-since-your-browser-is-your = نظرًا لأن متصفحك هو بوابتك إلى الإنترنت ، فإن السرعة والأمان والخصوصية والمرافق لها أهمية قصوى. في السنوات الأخيرة ، كان { -brand-name-google } { -brand-name-chrome } المتصفح المفضل للكثيرين. ولكن في الوقت الذي يبدو فيه أن الإعلانات عبر الإنترنت تتبعنا في كل مكان وكانت انتهاكات البيانات عنصرًا أساسيًا في عناوين الأخبار ، بدأ الكثير من الأشخاص في المطالبة بمزيد من الخصوصية والاحترام من متصفحهم.
compare-index-the-first-thing-to-point-out = أول شيء يجب الإشارة إليه حول قابلية النقل هو أنه لا تعمل جميع المتصفحات على جميع أنظمة التشغيل. بينما تعمل { -brand-name-firefox } و { -brand-name-chrome } و { -brand-name-edge } و { -brand-name-brave } و { -brand-name-opera } على جميع الأنظمة الرئيسية وسهلة التثبيت ، { -brand-name-ie } و { -brand-name-safari } تعمل فقط على { -brand-name-microsoft } وأنظمة Apple الخاصة. إصدار الجوال { -brand-name-safari } مثبت مسبقًا على أجهزة Apple المحمولة ، وتأتي معظم { -brand-name-android } الأجهزة مزودة بمتصفح مثبت مسبقًا تم تعديله بواسطة الشركة المصنعة للجهاز. { -brand-name-firefox } و { -brand-name-chrome } و { -brand-name-brave } و { -brand-name-edge } و { -brand-name-opera } يمكن بسهولة تثبيتها واستخدامها جنبًا إلى جنب.
compare-index-the-first-thing-to-point-fallback = أول شيء يجب الإشارة إليه حول قابلية النقل هو أنه لا تعمل جميع المتصفحات على جميع أنظمة التشغيل. بينما تعمل { -brand-name-firefox } و { -brand-name-chrome } و { -brand-name-opera } على جميع الأنظمة الرئيسية ويسهل تثبيتها ، { -brand-name-ie } و { -brand-name-edge } و { -brand-name-safari } تعمل فقط على { -brand-name-microsoft } وأنظمة Apple الخاصة. تم تثبيت إصدار الجوال من { -brand-name-safari } مسبقًا على أجهزة Apple المحمولة ، وتأتي معظم { -brand-name-android } الأجهزة مزودة بمتصفح مثبت مسبقًا تم تعديله بواسطة الشركة المصنعة للجهاز. يمكن بسهولة تثبيت { -brand-name-firefox } و { -brand-name-chrome } و { -brand-name-edge } و { -brand-name-opera } واستخدامهما جنبًا إلى جنب.
compare-index-browsers-have-come-a-long = قطعت المتصفحات شوطًا طويلاً منذ تقديم { -brand-name-chrome } واستحوذت على حصة السوق. أغلقت معظم المتصفحات الحديثة الفجوة في إمكانية النقل والوظائف ، وفي بعض المجالات ، مثل السرعة والخصوصية ، تجاوزت بالفعل { -brand-name-chrome } . ومع ذلك ، فإن تحديد المتصفح المناسب لك سيعتمد دائمًا على احتياجاتك الفردية وما تقدره أكثر أثناء تنقلك عبر الإنترنت.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } مدعوم من مؤسسة غير هادفة للربح { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } يضع خصوصيتك في المقام الأول - في كل ما نصنعه ونفعله. نعتقد أن لديك الحق في تحديد كيفية مشاركة معلوماتك الشخصية ومع من. يجمع { -brand-name-firefox } أقل قدر ممكن من البيانات ولا يبيعها مطلقًا. يتم استخدام البيانات الصغيرة التي نجمعها فقط لتحسين المنتجات والميزات. لا اسرار. لكن الكثير من الشفافية والخصوصية الحقيقية.
compare-index-based-on-the-criteria-we-outlined = استنادًا إلى المعايير التي حددناها - الخصوصية والأداة وإمكانية النقل - هناك متصفح واحد فقط يلبي العلامة ، وهو { -brand-name-firefox } . الاختلاف الحقيقي ليس في الوظائف ، بل الخصوصية. { -brand-name-firefox } هو أكثر المستعرضات خصوصية التي لا تحبسك في نظام بيئي. استخدمه على أي نظام تشغيل ، وعلى جميع أجهزتك ، واشعر بالأمان عند القيام بذلك.
