# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } versus { -brand-name-chrome } : wat is beter?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = We vergelijken { -brand-name-mozilla } { -brand-name-firefox } met { -brand-name-google } { -brand-name-chrome } in termen van privacy, bruikbaarheid en draagbaarheid

# Main title.
compare-chrome-comparing-firefox-browser = Vergelijk { -brand-name-firefox-browser } met { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Bij { -brand-name-firefox } hebben we een groot aantal toegewijde gebruikers die onze onwankelbare toewijding aan online privacy op prijs stellen. De nieuwste versie van { -brand-name-firefox } bevat bijvoorbeeld een functie genaamd Enhanced Tracking Protection (ETP) die standaard is ingeschakeld voor alle gebruikers wereldwijd. ETP blokkeert meer dan 2.000 trackers, waaronder sociale trackers van bedrijven als { -brand-name-facebook } , { -brand-name-twitter } en LinkedIn. Het heeft ook een geïntegreerde functie genaamd <a { $attrs }>{ -brand-name-firefox-monitor }</a> die u automatisch op de hoogte stelt als uw wachtwoord is geschonden of moet worden bijgewerkt. Naast deze beveiligingen verwijdert de modus voor privé browsen in { -brand-name-firefox } automatisch uw browsegegevens, zoals geschiedenis en cookies, zonder dat er een spoor achterblijft nadat u uw sessie hebt beëindigd.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Bij { -brand-name-firefox } hebben we een groot aantal toegewijde gebruikers die onze onwankelbare toewijding aan online privacy op prijs stellen. De nieuwste versie van { -brand-name-firefox } bevat bijvoorbeeld een functie genaamd Enhanced Tracking Protection (ETP) die standaard is ingeschakeld voor alle gebruikers wereldwijd. ETP blokkeert meer dan 2.000 trackers, waaronder sociale trackers van bedrijven als { -brand-name-facebook } , { -brand-name-twitter } en LinkedIn. Het heeft ook een geïntegreerde functie genaamd <a { $attrs }>{ -brand-name-firefox-monitor }</a> die u automatisch op de hoogte stelt als uw wachtwoord is geschonden of moet worden bijgewerkt. Naast deze beveiligingen verwijdert de privénavigatiemodus van { -brand-name-firefox } automatisch uw browsegegevens, zoals geschiedenis en cookies, zonder dat er een spoor achterblijft nadat u uw sessie hebt beëindigd.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = We hebben onlangs ook onze toewijding aan privacy en transparantie met betrekking tot gebruikersgegevens herhaald in onze meest recente <a { $attrs }>privacyverklaring</a> waarin staat: &quot;Bij Mozilla geloven we dat privacy fundamenteel is voor een gezond internet.&quot;
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } is door alle accounts een veilige browser, met functies zoals { -brand-name-google } Safe Browsing, dat gebruikers helpt te beschermen door een onmisbare waarschuwing weer te geven wanneer ze proberen naar gevaarlijke sites te navigeren of gevaarlijke bestanden te downloaden.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Uiteindelijk is het aan jou om te beslissen of en waar je de grens wilt trekken door zaken als je zoekgeschiedenis en winkelgeschiedenis te delen. Maar als je op de meeste mensen lijkt, heb je waarschijnlijk naar dingen op internet gezocht die je liever privé houdt.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Snel vooruit naar vandaag, het concurrentielandschap voor browsers is veranderd en veel mensen beginnen zich af te vragen wat er precies gebeurt met hun online gegevens, zoals browsegeschiedenis, wachtwoorden en andere gevoelige informatie. Er is veel veranderd sinds 2008, toen { -brand-name-chrome } op het toneel verscheen. Bij { -brand-name-firefox } hebben we hard gewerkt om onze interface opnieuw te ontwerpen en gebruikers een steeds groeiend aantal privacy- en prestatieverbeteringen te bieden, evenals tal van handige browsertools.
compare-chrome-and-so-here-we-are-the-browser = En hier zijn we dan, de browseroorlogen escaleren opnieuw en het is tijd om { -brand-name-firefox-browser } versus { -brand-name-google } { -brand-name-chrome } opnieuw te evalueren en te vergelijken.
compare-chrome-in-2008-google-introduced = In 2008 { -brand-name-google } geïntroduceerd { -brand-name-chrome } , en de impact ervan als innovatie in browsertechnologie was onmiddellijk. Het was sneller voor het laden van sites, nam minimale schermruimte in beslag en bood een onmiskenbaar eenvoudige gebruikersinterface.
compare-chrome-in-fact-both-chrome-and-firefox = In feite hebben zowel { -brand-name-chrome } als { -brand-name-firefox } een strikte beveiliging. Beide bevatten iets dat "sandboxing" wordt genoemd en dat de processen van de browser scheidt, zodat zoiets als een schadelijke website geen andere delen van uw laptop of ander apparaat infecteert.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Hoewel { -brand-name-chrome } een veilige webbrowser blijkt te zijn, is de privacyverklaring twijfelachtig. { -brand-name-google } verzamelt eigenlijk een verontrustend grote hoeveelheid gegevens van zijn gebruikers, waaronder locatie, zoekgeschiedenis en sitebezoeken. { -brand-name-google } pleit voor gegevensverzameling en zegt dat het dit doet om de services te verbeteren, zoals u helpen bij het vinden van een trui of een coffeeshop zoals u eerder kocht of bezocht. Anderen zijn het daar echter misschien niet mee eens en stellen dat { -brand-name-google } in feite een ongekende hoeveelheid gegevens verzamelt voor zijn eigen marketingdoeleinden. Ze beweren dat ze uw informatie privé houden voor hackers, maar dat doet er niet toe. { -brand-name-google } beheert zelf 's werelds grootste advertentienetwerk, grotendeels dankzij de gegevens die ze van hun gebruikers verzamelen.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Qua functies bieden zowel { -brand-name-firefox } als { -brand-name-chrome } een grote bibliotheek met extensies en plug-ins, waarbij de catalogus van { -brand-name-chrome } veel groter is dan elke andere browser, terwijl deze goed integreert met andere { -brand-name-google } services, zoals Gmail en { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } ook een synchronisatiefunctie om uw geopende en recente tabbladen, browsegeschiedenis en bladwijzers op al uw apparaten te bekijken.
compare-chrome-while-chrome-gets-the-nod = Hoewel { -brand-name-chrome } de aandacht trekt met add-ons en extensies, { -brand-name-firefox } heeft een mooi samengestelde set ingebouwde functies, zoals de ongelooflijk handige tool voor schermopnamen en de leesmodusfunctie die alles van de pagina verwijdert, behalve de tekst uit het artikel dat u leest.
compare-chrome-although-not-as-extensive = Hoewel niet zo uitgebreid als { -brand-name-chrome } 's add-on bibliotheek, { -brand-name-firefox } , zoals open-source software met een groot aantal actieve donateurs, beschikt ook over een ongelooflijk aantal nuttige uitbreidingen.
compare-chrome-if-having-tons-of-open-tabs = Als het hebben van tonnen open tabbladen jouw ding is, dan komt het echt neer op je UI-voorkeur. { -brand-name-firefox } biedt een horizontaal scrollen op al uw geopende tabbladen in plaats van ze steeds kleiner te maken bij elke nieuwe tab. { -brand-name-google } { -brand-name-chrome } geeft er de voorkeur aan ze te verkleinen, zodat alleen de favicon zichtbaar is. Het enige probleem hiermee is wanneer je meerdere tabbladen hebt geopend vanaf dezelfde website, dus je ziet dezelfde favicon op al je tabbladen.
compare-chrome-almost-needless-to-say-versions = Het behoeft bijna geen betoog dat er versies van zowel { -brand-name-firefox } als { -brand-name-chrome } beschikbaar zijn voor de meest populaire desktop- en mobiele besturingssystemen ( { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ).
compare-chrome-both-chrome-and-firefox-also = Met zowel { -brand-name-chrome } als { -brand-name-firefox } kunt u zaken als wachtwoorden, bladwijzers en geopende tabbladen op al uw apparaten synchroniseren. Als u een { -brand-name-firefox } -account heeft, kunt u handmatig een geopend tabblad op uw desktop naar uw mobiele apparaat sturen of vice versa. Met { -brand-name-chrome } gebeurt dit automatisch als u die instelling in uw voorkeuren heeft gekozen. Het niet handmatig hoeven verzenden van het tabblad van het ene apparaat naar het andere is handig als u bijvoorbeeld een artikel wilt lezen dat u niet eerder hebt afgemaakt. Het kan echter voorkomen dat automatische synchronisatie niet ideaal is als de kans bestaat dat meerdere gebruikers browsen terwijl ze zijn aangemeld bij uw { -brand-name-google } -account.

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = We denken dat het redelijk is om te zeggen dat { -brand-name-firefox } en { -brand-name-chrome } echt nek aan nek zijn in termen van draagbaarheid en bruikbaarheid, met { -brand-name-chrome } een kleine voorsprong in bruikbaarheid vanwege de enorme bibliotheek met extensies en add-on-functies. Maar op het gebied van privacy wint { -brand-name-firefox } de dag met onze toewijding om de online gegevens van onze gebruikers te behouden en gratis ingebakken services aan te bieden, zoals wachtwoordbeheerders die u ook waarschuwen als er toevallig een datalek is met betrekking tot uw inloggegevens.
compare-chrome-as-for-customization-our = Wat betreft maatwerk, onze fans zullen je vertellen dat een van de dingen die ze het leukst vinden aan onze browser, is dat je de mogelijkheid hebt om een meerderheid van de UI-elementen te verplaatsen en in te delen om het beste aan je behoeften te voldoen. { -brand-name-chrome } kunt u bepaalde UI-elementen verbergen, maar er is niet veel ruimte om dingen te verplaatsen op basis van uw voorkeuren. Houd er echter rekening mee dat zowel { -brand-name-chrome } als { -brand-name-firefox } het vrij eenvoudig maken om het uiterlijk en het thema van uw browser te wijzigen.
compare-chrome-for-practical-purposes-theres = Voor praktische doeleinden is er natuurlijk niets dat u ervan weerhoudt om beide browsers te gebruiken { -brand-name-firefox } voor die momenten in het leven waarop privacy er echt toe doet, en { -brand-name-chrome } als u nog steeds in het { -brand-name-google } ecosysteem investeert. Maar met het groeiende aantal inbreuken op onze persoonlijke gegevens, { -brand-name-firefox } kan op de lange termijn de juiste keuze blijken te zijn voor diegenen onder ons die waarde hechten aan het beschermen van onze persoonlijke privacy online.
