# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs. { -brand-name-microsoft } { -brand-name-edge } : welke is de betere browser voor u?

# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Vergelijk { -brand-name-microsoft } { -brand-name-edge } met de { -brand-name-firefox-browser } om erachter te komen welke de betere browser voor u is.

# Main title.
compare-edge-comparing-firefox-browser-with = Vergelijk { -brand-name-firefox-browser } met { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = Met { -brand-name-windows } 10 { -brand-name-microsoft } introduceerde hij zijn { -brand-name-edge } browser om te concurreren met { -brand-name-firefox } en { -brand-name-chrome } waardoor deze de standaardbrowser werd die vooraf is geïnstalleerd op miljoenen verkochte pc's. Toch waren gebruikers traag om het te adopteren en { -brand-name-microsoft } kondigde uiteindelijk plannen aan om { -brand-name-edge } opnieuw te lanceren als een { -brand-name-chromium } -gebaseerde browser ( { -brand-name-chromium } natuurlijk het Open Source-browserproject van { -brand-name-google } ).
compare-edge-here-well-compare-our-firefox = Hier vergelijken we onze { -brand-name-firefox-browser } met de { -brand-name-chromium } gebaseerde { -brand-name-microsoft } { -brand-name-edge } in termen van privacy, bruikbaarheid en draagbaarheid, zodat u beter begrijpt welke browser het beste aansluit op uw behoeften en voorkeuren.

# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } is geïntegreerd in het { -brand-name-windows } 10-platform en wordt uitgevoerd in een sandbox-omgeving, wat betekent dat het programma's isoleert en voorkomt dat schadelijke programma's uw computer bespioneren. Het heeft een ingebouwd SmartScreen dat de reputatie van sites die u bezoekt, scant en verdachte sites blokkeert. Om de privacy te verbeteren, kunt u met { -brand-name-edge } biometrische gegevens of een pincode gebruiken met { -brand-name-edge } Hallo in plaats van wachtwoorden voor online authenticatie.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = Bij { -brand-name-firefox } zijn we er trots op dat we de veiligheid en privacy van onze gebruikers beschermen. Ons <a { $attrs }>privacybeleid</a> is transparant en in duidelijke taal. We hebben echt veel werk gestoken om ervoor te zorgen dat het duidelijk en gemakkelijk te lezen was. Nu Enhanced Tracking Protection standaard is ingeschakeld, blokkeren we automatisch 2000+ trackers. Trackers zijn die kleine stukjes code die proberen te combineren wat u doet op meerdere internetsites om een samengesteld en gedetailleerd beeld te krijgen van wie u bent, waarbij uw privacy in gevaar wordt gebracht, alleen maar om betere advertenties te targeten.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = Bij { -brand-name-firefox } is ons <a { $attrs }>privacybeleid</a> transparant en in duidelijke taal. We hebben echt veel werk gestoken om ervoor te zorgen dat het duidelijk en gemakkelijk te lezen was. We zijn er trots op dat we de veiligheid en privacy van onze gebruikers beschermen. Nu Enhanced Tracking Protection standaard is ingeschakeld, blokkeren we automatisch 2000+ trackers. Trackers zijn die kleine stukjes code die proberen te combineren wat u doet op meerdere internetsites om een samengesteld en gedetailleerd beeld te krijgen van wie u bent, waarbij uw privacy in gevaar wordt gebracht, alleen maar om betere advertenties te targeten.

# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Uw <a { $attrs }>privacybescherming</a> toont u de trackers en cookies die pagina's hebben geprobeerd te verlaten, en hoeveel { -brand-name-firefox } voor u hebben geblokkeerd.

# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = In { -brand-name-firefox } wist de modus voor privé browsen automatisch uw browsegegevens, zoals wachtwoorden, cookies en geschiedenis, zonder dat er een spoor achterblijft nadat u de sessie heeft afgesloten. { -brand-name-edge } daarentegen legt de browsegeschiedenis feitelijk vast in hun privémodus ("InPrivate" genaamd) en het is relatief eenvoudig voor iemand om uw volledige browsegeschiedenis te reconstrueren, ongeacht of u in de normale modus of in de InPrivate-modus hebt gebladerd.
compare-edge-both-browsers-are-relatively = Beide browsers zijn relatief gelijk in termen van gegevensversleuteling. Als online privacy en transparantie echter belangrijk voor u zijn, is { -brand-name-firefox } hier duidelijk een betere keuze.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } is een snelle en open source-browser, wat betekent dat gebruikers hun browse-ervaring op alle mogelijke manieren kunnen aanpassen. { -brand-name-firefox } biedt de gewone gebruiker ook verschillende manieren om de gebruikersinterface aan te passen door verschillende thema's en werkbalkconfiguraties toe te passen. Omdat onze browser altijd open source is geweest, hebben we een groot aantal toegewijde ontwikkelaars die een uitgebreide bibliotheek met add-ons en browserextensies hebben gemaakt.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } is een snelle en open source-browser, wat betekent dat gebruikers hun browse-ervaring op alle mogelijke manieren kunnen aanpassen. { -brand-name-firefox } biedt de gewone gebruiker ook verschillende manieren om de gebruikersinterface aan te passen door verschillende thema's en werkbalkconfiguraties toe te passen. Omdat onze browser altijd open source is geweest, hebben we een groot aantal toegewijde ontwikkelaars die een uitgebreide bibliotheek met add-ons en browserextensies hebben gemaakt.
compare-edge-since-edge-has-moved-to-the = Aangezien { -brand-name-edge } is overgeschakeld naar het processorintensieve { -brand-name-chromium } -platform, kunt u verwachten dat het iets langzamer werkt, vooral als u meerdere programma's tegelijk heeft uitgevoerd. Met het { -brand-name-chromium } -platform komt echter een enorme bibliotheek met extensies en een behoorlijk niveau van UI-aanpassing die { -brand-name-edge } niet had voordat het naar { -brand-name-chromium } verhuisde.
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } heeft een aantal leuke UI-functies, zoals hun tabbladvoorbeelden, waarmee u gemakkelijk de juiste geopende tabbladen kunt vinden als u er veel heeft geopend. Met een andere handige tabgerelateerde functie kunt u actieve tabbladen opzij zetten die u niet gebruikt, maar die u niet wilt sluiten.

# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } beschikt over een scrollende tab-interface, waardoor de tab-informatie zichtbaar blijft en ze horizontaal scrolt in plaats van ze te verkleinen tot slechts favicon-grootte. Ook wanneer u een nieuw tabblad opent, stelt onze functie <a { $attrs }>{ -brand-name-pocket }</a> relevante artikelen en inhoud voor. Bovendien kunt u met { -brand-name-pocket } ook artikelen, video's en andere inhoud met één klik opslaan om op een later tijdstip te lezen.
compare-edge-firefox-and-edge-both-offer = { -brand-name-firefox } en { -brand-name-edge } bieden beide uitstekende leesmodi. Met { -brand-name-firefox } tik je gewoon op het kleine pictogram in de zoekbalk en de browser verwijdert alle onnodige elementen en presenteert je een schoon uitziend artikel. In { -brand-name-edge } tikt u gewoon op het kleine boekpictogram en de browser om een schone, gemakkelijk te lezen gebruikersinterface te krijgen.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } en { -brand-name-edge } bieden beide uitstekende leesmodi. Met { -brand-name-firefox } tik je gewoon op het kleine pictogram in de zoekbalk en de browser verwijdert alle onnodige elementen en presenteert je een schoon uitziend artikel. In { -brand-name-edge } tikt u gewoon op het kleine boekpictogram en de browser om een schone, gemakkelijk te lezen gebruikersinterface te krijgen.

# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } bevat standaard ook veel handige ingebouwde functies, zoals <a { $attrs }>Verbeterde bescherming tegen volgen</a> , een ingebouwde tool voor schermafbeeldingen, het verzenden van grote bestanden en meer.

# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Buiten de deur heeft { -brand-name-firefox } meer functies en integraties ingebouwd in de browser en direct beschikbaar om te downloaden. En terwijl beide browsers hebben een enorme aantal add-ons en uitbreidingen beschikbaar, { -brand-name-edge } 's compatibiliteit met { -brand-name-google } ' s { -brand-name-chromium } platform geeft hem het voordeel in termen van grote aantallen.

compare-edge-with-internet-explorer-microsoft = Met { -brand-name-ie } heeft { -brand-name-microsoft } geleerd van het gebrek aan beschikbaarheid op verschillende platforms en { -brand-name-edge } direct beschikbaar gemaakt op { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } , { -brand-name-mac } en binnenkort { -brand-name-linux } .
compare-edge-with-internet-explorer-fallback = Met { -brand-name-ie } heeft { -brand-name-microsoft } geleerd van het gebrek aan beschikbaarheid op verschillende platforms en { -brand-name-edge } beschikbaar gemaakt voor { -brand-name-mac } en { -brand-name-android } . De software is nu direct beschikbaar op { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } en { -brand-name-mac } .

# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } is al jaren beschikbaar op { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } , { -brand-name-mac } en { -brand-name-linux } . En zoals u zou verwachten van elke moderne browser, kunt u met { -brand-name-firefox } inloggen met een <a { $attrs }>gratis account</a> en gegevens zoals wachtwoorden, browsegeschiedenis, bladwijzers en geopende tabbladen synchroniseren tussen uw computer, tablet en telefoon. Het stelt u ook in staat om tussen platforms te synchroniseren.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } kunt u ook uw gekoppelde { -brand-name-microsoft } -account verbinden en inloggen om uw favorieten, geschiedenis, wachtwoorden en meer tussen uw computer en { -brand-name-ios } of { -brand-name-android } apparaten te synchroniseren.
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } kunt u ook uw gekoppelde { -brand-name-microsoft } account verbinden en inloggen om uw favorieten, geschiedenis, wachtwoorden en meer te synchroniseren tussen uw computer en { -brand-name-ios } of { -brand-name-android } apparaten, hoewel sommige { -brand-name-android } tablets momenteel niet zijn ondersteund.

# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Behalve dat het veel rekenkracht opslokt, heeft { -brand-name-edge } running on { -brand-name-chromium } beantwoord aan de behoeften van veel gebruikers aan functionaliteit en functies. Maar er is nog veel te doen in termen van de privacybescherming van de browser. Wij zijn van mening dat { -brand-name-firefox } voor de meeste mensen nog steeds een betere keuze is om in hun dagelijks leven te gebruiken, niet alleen op basis van functionaliteit, maar nog belangrijker op onze transparantie over hoe we gebruikersgegevens verzamelen, wat we precies verzamelen en wat we ermee doen het. Omdat ons moederbedrijf <a { $attrs }>{ -brand-name-mozilla }</a> , een non-profitorganisatie die zich inzet voor privacy en vrijheid op internet, hebben we gewoon een andere reeks prioriteiten als het gaat om de gegevens van gebruikers.
compare-edge-the-bottom-line-is-that-while = Het komt erop neer dat hoewel we het gebruik van { -brand-name-firefox } aanraden, de beste browser voor u uiteindelijk de browser is die aan uw individuele behoeften voldoet met ondersteuning voor extensies, aanpassing van browsertools, snelheid, privacy en beveiliging.
