# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Zeven van de beste browsers in directe vergelijking
compare-index-six-of-the-best-browsers-fallback = Zes van de beste browsers in directe vergelijking

# Sub-headline
compare-index-privacy-utility-portability = Privacy. Nut. Draagbaarheid.

# HTML page description
compare-index-a-great-internet-browser-should = Een geweldige internetbrowser moet de functionaliteit hebben die u nodig hebt, draagbaarheid op verschillende apparaten en de privacy die u verdient.
compare-index-which-browser-is-best-at-keeping = Welke browser kan de zaken het beste vertrouwelijk houden?
compare-index-its-not-unreasonable-to-expect = Het is niet onredelijk om een hoog niveau van gegevensbescherming en privacy te verwachten van de producten die we regelmatig gebruiken om online te gaan. Een browser zou minimaal een versie van de "privé-browsingmodus" moeten bieden die automatisch uw geschiedenis en zoekgeschiedenis verwijdert, zodat andere gebruikers op dezelfde computer er geen toegang toe hebben. Op dit gebied scoren alle zeven hier vergeleken browsers punten.
compare-index-its-not-unreasonable-to-expect-fallback = Het is niet onredelijk om een hoog niveau van gegevensbescherming en privacy te verwachten van de producten die we regelmatig gebruiken om online te gaan. Een browser zou minimaal een versie van de "privé-browsingmodus" moeten bieden die automatisch uw geschiedenis en zoekgeschiedenis verwijdert, zodat andere gebruikers op dezelfde computer er geen toegang toe hebben. Op dit gebied scoren alle zes de hier vergeleken browsers punten.
compare-index-what-you-do-online-literally = Wat u online doet, mag letterlijk niet de zaak van iemand anders zijn.
compare-index-another-browser-feature-that = Een andere browserfunctie die een gegeven zou moeten zijn, is de mogelijkheid om te voorkomen dat websites en bedrijven uw browse- en winkelgegevens volgen - zelfs in de normale browsemodus.
compare-index-another-browser-feature-fallback = Een andere browserfunctie die een gegeven zou moeten zijn, is de mogelijkheid om te voorkomen dat websites en bedrijven uw browse- en winkelgegevens volgen - zelfs in de normale browsemodus. Maar dat is eigenlijk niet het geval: de enige browsers die trackingcookies van derden standaard blokkeren, zijn { -brand-name-firefox } en { -brand-name-safari } .
compare-index-using-a-browser-that-blocks = Het gebruik van een browser die trackers van derden blokkeert, is niet alleen belangrijk voor de privacy - het betekent meestal ook dat het veel sneller werkt. De meeste trackers zijn slechts scripts die op een aantal websites op de achtergrond worden uitgevoerd. U kunt ze niet zien, maar u voelt dat ze uw browser vertragen. Vanaf versie 67 van { -brand-name-firefox } worden vingerafdrukken en cryptominers ook geblokkeerd. Als u niet bekend bent met cryptominers, is hier een voorbeeld van hoe ze u kunnen beïnvloeden: misschien heeft u ervaren dat uw computer plotseling heter wordt of dat de batterij sneller leeg raakt dan normaal. Dat is vaak het bijproduct van cryptominers die op uw apparaat rondsluipen.
compare-index-what-has-your-browser-done = Wat heeft uw browser de laatste tijd voor u gedaan?
compare-index-in-addition-to-privacy-protection = Naast privacybescherming, die grotendeels op de achtergrond van de browser plaatsvindt, is een ander belangrijk ingrediënt van een goed gemaakte browser de daadwerkelijke gebruikersinterface en functionaliteit. Bijna alle zeven browsers zijn gelijk als het gaat om bladeren door tabbladen, bladwijzerbeheer, automatisch aanvullen, proeflezen en extensies. { -brand-name-firefox } , { -brand-name-edge } en { -brand-name-opera } bieden ook een snelle schermafdrukfunctie die erg handig blijkt te zijn en waarvan je zeker merkt dat deze ontbreekt wanneer je overschakelt naar een browser zonder deze functie.
compare-index-in-addition-to-privacy-protection-fallback = Naast privacybescherming, die grotendeels op de achtergrond van de browser plaatsvindt, is een ander belangrijk ingrediënt van een goed gemaakte browser de daadwerkelijke gebruikersinterface en functionaliteit. Bijna alle zes browsers zijn gelijk als het gaat om bladeren door tabbladen, bladwijzerbeheer, automatisch aanvullen, proeflezen en extensies. { -brand-name-firefox } , { -brand-name-edge } en { -brand-name-opera } bieden ook een snelle schermafdrukfunctie die erg handig blijkt te zijn en waarvan je zeker merkt dat deze ontbreekt wanneer je overschakelt naar een browser zonder deze functie.
compare-index-how-well-does-your-browser = Hoe goed werkt uw browser op al uw apparaten?
compare-index-almost-all-of-the-browsers = Bijna alle browsers die hier worden vergeleken, maken synchronisatie tussen desktop- en mobiele apparaten mogelijk. Hiervoor heb je een account nodig, waarmee je op alle apparaten in de browser kunt inloggen en zaken als wachtwoorden, browsegeschiedenis, bladwijzers en instellingen kunt synchroniseren.
compare-index-conclusion = Gevolgtrekking:
compare-index-and-the-winner-is = En de winnaar is…
compare-index-find-out-how-firefox-chrome = Ontdek hoe { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } en { -brand-name-ie } verschillen in termen van privacy, bruikbaarheid en draagbaarheid.
compare-index-find-out-how-firefox-fallback = Ontdek hoe { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } en { -brand-name-ie } verschillen in termen van privacy, bruikbaarheid en draagbaarheid.
compare-index-looking-for-a-better-browser = Op zoek naar een betere browser? We vergelijken { -brand-name-firefox } met { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } en { -brand-name-ie } om u te helpen bij het nemen van uw beslissing.
compare-index-looking-for-a-better-fallback = Op zoek naar een betere browser? We vergelijken { -brand-name-firefox } met { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } en { -brand-name-ie } om u te helpen bij het nemen van uw beslissing.
compare-index-so-is-your-browser-the-best = Dus is uw browser de beste voor wat u online doet? De juiste browser kan een groot verschil maken in hoe u internet ervaart. Laten we dus zonder meer { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } , { -brand-name-microsoft } { -brand-name-ie } en { -brand-name-edge } en kijken welke het beste bij u past.
compare-index-so-is-your-browser-the-fallback = Dus is uw browser de beste voor wat u online doet? De juiste browser kan een groot verschil maken in hoe u internet ervaart. Laten we dus zonder verder oponthoud { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-microsoft } { -brand-name-ie } en { -brand-name-edge } en kijken welke het beste bij u past.
compare-index-since-your-browser-is-your = Omdat uw browser uw toegangspoort tot internet is, staan snelheid, veiligheid, privacy en bruikbaarheid voorop. In de afgelopen jaren is { -brand-name-google } { -brand-name-chrome } voor velen de favoriete browser geweest. Maar in een tijd waarin online advertenties ons overal lijken te volgen en datalekken een vast onderdeel zijn van nieuwskoppen, beginnen veel mensen meer privacy en respect van hun browser te eisen.
compare-index-the-first-thing-to-point-out = Het eerste dat u moet opmerken over draagbaarheid is dat niet alle browsers op alle besturingssystemen werken. Hoewel { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-brave } en { -brand-name-opera } op alle belangrijke systemen werken en eenvoudig te installeren zijn, { -brand-name-ie } en { -brand-name-safari } alleen werken op { -brand-name-microsoft } en Apple's eigen systemen. De mobiele versie van { -brand-name-safari } is vooraf geïnstalleerd op de mobiele apparaten van Apple en de meeste { -brand-name-android } apparaten worden geleverd met een vooraf geïnstalleerde browser die door de fabrikant is aangepast voor het apparaat. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-brave } , { -brand-name-edge } en { -brand-name-opera } kunnen eenvoudig worden geïnstalleerd en zelfs naast elkaar worden gebruikt.
compare-index-the-first-thing-to-point-fallback = Het eerste dat u moet opmerken over draagbaarheid is dat niet alle browsers op alle besturingssystemen werken. Hoewel { -brand-name-firefox } , { -brand-name-chrome } en { -brand-name-opera } op alle belangrijke systemen werken en eenvoudig te installeren zijn, { -brand-name-ie } , { -brand-name-edge } en { -brand-name-safari } werken ze alleen op { -brand-name-microsoft } en Apple's eigen systemen. De mobiele versie van { -brand-name-safari } is vooraf geïnstalleerd op de mobiele apparaten van Apple en de meeste { -brand-name-android } apparaten worden geleverd met een vooraf geïnstalleerde browser die door de fabrikant is aangepast voor het apparaat. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } en { -brand-name-opera } kunnen gemakkelijk naast elkaar worden geïnstalleerd en zelfs gebruikt.
compare-index-browsers-have-come-a-long = Browsers hebben een lange weg afgelegd sinds de introductie van { -brand-name-chrome } en hebben het marktaandeel overgenomen. De meeste moderne browsers hebben de kloof op het gebied van draagbaarheid en functionaliteit gedicht, en op sommige gebieden, zoals snelheid en privacy, hebben ze { -brand-name-chrome } overtroffen. Het bepalen welke browser de juiste voor u is, hangt echter altijd af van uw individuele behoeften en wat u het meest waardeert terwijl u online navigeert.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } wordt ondersteund door de non-profit { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } stelt uw privacy voorop, bij alles wat we maken en doen. Wij vinden dat u het recht heeft om te beslissen hoe en met wie u uw persoonlijke gegevens deelt. { -brand-name-firefox } verzamelt zo min mogelijk gegevens en verkoopt deze nooit. De weinige gegevens die we verzamelen, worden alleen gebruikt om producten en functies te verbeteren. Geen geheimen. Maar veel transparantie en echte privacy.
compare-index-based-on-the-criteria-we-outlined = Op basis van de criteria die we hebben uiteengezet - privacy, bruikbaarheid en draagbaarheid - is er eigenlijk maar één browser die aan de eisen voldoet, en dat is { -brand-name-firefox } . Het echte verschil zit hem niet in functionaliteit, het is privacy. { -brand-name-firefox } is de meest persoonlijke browser die u niet in een ecosysteem opsluit. Gebruik het op elk besturingssysteem, op al uw apparaten, en voel u veilig wanneer u dat doet.
