# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs { -brand-name-chrome } : quel est le meilleur?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Nous comparons { -brand-name-mozilla } { -brand-name-firefox } à { -brand-name-google } { -brand-name-chrome } en termes de confidentialité, d'utilité et de portabilité

# Main title.
compare-chrome-comparing-firefox-browser = Comparaison de { -brand-name-firefox-browser } avec { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Chez { -brand-name-firefox } , nous avons un grand nombre d'utilisateurs dévoués qui apprécient notre dévouement constant à la confidentialité en ligne. Par exemple, la dernière version de { -brand-name-firefox } inclut une fonctionnalité appelée Enhanced Tracking Protection (ETP), qui est activée par défaut pour tous les utilisateurs du monde entier. ETP bloque plus de 2 000 trackers, y compris les trackers sociaux d'entreprises telles que { -brand-name-facebook } , { -brand-name-twitter } et LinkedIn. Il possède également une fonctionnalité intégrée appelée <a { $attrs }>{ -brand-name-firefox-monitor }</a> qui vous avertit automatiquement si votre mot de passe a été violé ou doit être mis à jour. En plus de ces protections, le mode de navigation privée de { -brand-name-firefox } supprime automatiquement vos informations de navigation telles que l'historique et les cookies, ne laissant aucune trace une fois votre session terminée.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Chez { -brand-name-firefox } , nous avons un grand nombre d'utilisateurs dévoués qui apprécient notre dévouement constant à la confidentialité en ligne. Par exemple, la dernière version de { -brand-name-firefox } inclut une fonctionnalité appelée Enhanced Tracking Protection (ETP), qui est activée par défaut pour tous les utilisateurs du monde entier. ETP bloque plus de 2 000 trackers, y compris les trackers sociaux d'entreprises telles que { -brand-name-facebook } , { -brand-name-twitter } et LinkedIn. Il possède également une fonctionnalité intégrée appelée <a { $attrs }>{ -brand-name-firefox-monitor }</a> qui vous avertit automatiquement si votre mot de passe a été violé ou doit être mis à jour. En plus de ces protections, le mode de navigation privée de { -brand-name-firefox } supprime automatiquement vos informations de navigation telles que l'historique et les cookies, ne laissant aucune trace une fois votre session terminée.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Nous avons également récemment réaffirmé notre engagement en matière de confidentialité et de transparence concernant les données des utilisateurs dans notre plus récent <a { $attrs }>avis de confidentialité</a> qui déclare: «Chez Mozilla, nous pensons que la confidentialité est fondamentale pour un Internet sain.»
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } est par tous les comptes un navigateur sécurisé, avec des fonctionnalités telles que la { -brand-name-google } navigation sécurisée, qui aide à protéger les utilisateurs en affichant un avertissement impossible à manquer lorsqu'ils tentent de naviguer vers des sites dangereux ou de télécharger des fichiers dangereux.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = En fin de compte, c'est à vous de décider si ou non ou où tracer la ligne avec le partage d'éléments tels que votre historique de recherche et votre historique d'achat. Mais si vous ressemblez à la plupart des gens, vous avez probablement recherché des choses sur Internet que vous préférez garder privées.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Jusqu'à aujourd'hui, le paysage concurrentiel des navigateurs a changé et de nombreuses personnes commencent à se demander ce qu'il advient de leurs données en ligne telles que l'historique de navigation, les mots de passe et d'autres informations sensibles. Beaucoup de choses ont changé depuis 2008, lorsque { -brand-name-chrome } est entré en scène. Chez { -brand-name-firefox } , nous nous sommes efforcés de repenser notre interface et d'offrir aux utilisateurs un nombre toujours croissant d'améliorations de la confidentialité et des performances, ainsi que de nombreux outils de navigation pratiques.
compare-chrome-and-so-here-we-are-the-browser = Et voilà, la guerre des navigateurs s'intensifie à nouveau et il est temps de réévaluer et de comparer { -brand-name-firefox-browser } vs { -brand-name-google } { -brand-name-chrome } .
compare-chrome-in-2008-google-introduced = En 2008, { -brand-name-google } lancé { -brand-name-chrome } , et son impact en tant qu'innovation dans la technologie des navigateurs a été immédiat. Il était plus rapide pour le chargement des sites, occupait un espace d'écran minimal et offrait une interface utilisateur indéniablement simple.
compare-chrome-in-fact-both-chrome-and-firefox = En fait, { -brand-name-chrome } et { -brand-name-firefox } disposent tous deux d'une sécurité rigoureuse. Les deux incluent une chose appelée «bac à sable» qui sépare les processus du navigateur afin que quelque chose comme un site Web nuisible n'infecte pas d'autres parties de votre ordinateur portable ou d'un autre appareil.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Bien que { -brand-name-chrome } révèle être un navigateur Web sûr, son niveau de confidentialité est discutable. { -brand-name-google } collecte en fait une quantité déroutante de données auprès de ses utilisateurs, notamment l'emplacement, l'historique de recherche et les visites du site. { -brand-name-google } plaide pour la collecte de données en disant qu'il le fait pour améliorer ses services, comme vous aider à trouver un pull ou un café comme celui que vous avez acheté ou visité précédemment. Cependant, d'autres pourraient ne pas être d'accord, faisant valoir que { -brand-name-google } recueille en fait une quantité sans précédent de données à ses propres fins de marketing. Ils vantent qu'ils gardent vos informations privées des pirates, mais ce n'est pas la question. { -brand-name-google } gère lui-même le plus grand réseau publicitaire au monde, en grande partie grâce aux données collectées auprès de ses utilisateurs.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = En termes de fonctionnalités, { -brand-name-firefox } et { -brand-name-chrome } offrent une large bibliothèque d'extensions et de plug-ins, le catalogue de { -brand-name-chrome } dépassant largement en nombre tous les autres navigateurs tout en s'intégrant parfaitement à d'autres services { -brand-name-google } , tels que Gmail et { -brand-name-google } Docs.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } dispose également d'une fonction de synchronisation pour voir vos onglets ouverts et récents, votre historique de navigation et vos favoris sur tous vos appareils.
compare-chrome-while-chrome-gets-the-nod = Alors que { -brand-name-chrome } obtient le feu vert avec des modules complémentaires et des extensions, { -brand-name-firefox } dispose d'un ensemble bien organisé de fonctionnalités intégrées, telles que l'outil de capture d'écran incroyablement pratique et la fonctionnalité de mode de lecture qui supprime tout de la page, sauf le texte de l'article que vous lisez.
compare-chrome-although-not-as-extensive = Bien qu'il ne soit pas aussi complet que la bibliothèque de modules complémentaires de { -brand-name-chrome } , { -brand-name-firefox } , en tant que logiciel open source avec un grand nombre de contributeurs actifs, propose également un nombre incroyable d'extensions utiles.
compare-chrome-if-having-tons-of-open-tabs = Si vous aimez avoir des tonnes d'onglets ouverts, cela dépend vraiment de vos préférences d'interface utilisateur. { -brand-name-firefox } présente un défilement horizontal sur tous vos onglets ouverts plutôt que de les réduire de plus en plus à chaque nouvel onglet. { -brand-name-google } { -brand-name-chrome } préfère les réduire pour que seul le favicon soit visible. Le seul problème avec cela est lorsque vous avez plusieurs onglets ouverts à partir du même site Web, de sorte que vous voyez le même favicon sur vos onglets.
compare-chrome-almost-needless-to-say-versions = Il va sans dire que les versions de { -brand-name-firefox } et de { -brand-name-chrome } sont disponibles pour les systèmes d'exploitation de bureau et mobiles les plus courants ( { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ).
compare-chrome-both-chrome-and-firefox-also = { -brand-name-chrome } et { -brand-name-firefox } vous permettent également de synchroniser des éléments tels que les mots de passe, les favoris et les onglets ouverts sur tous vos appareils. Si vous possédez un compte { -brand-name-firefox } , vous pouvez envoyer manuellement un onglet ouvert sur votre ordinateur vers votre appareil mobile ou vice versa. Avec { -brand-name-chrome } , cela se fait automatiquement si vous avez choisi ce paramètre dans vos préférences. Ne pas avoir à envoyer manuellement l'onglet d'un appareil à l'autre est pratique lorsque vous voulez faire quelque chose comme continuer à lire un article que vous n'avez pas terminé plus tôt. Mais il peut arriver que la synchronisation automatique ne soit pas idéale s'il est possible que plusieurs utilisateurs naviguent alors qu'ils sont connectés à votre compte { -brand-name-google } .

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Nous pensons qu'il est juste de dire que { -brand-name-firefox } et { -brand-name-chrome } sont vraiment au coude à coude en termes de portabilité et d'utilité, { -brand-name-chrome } ayant un léger avantage en termes d'utilité en raison de son énorme bibliothèque d'extensions et de fonctionnalités complémentaires. Mais en termes de confidentialité, { -brand-name-firefox } gagne la journée avec notre engagement à préserver les données en ligne de nos utilisateurs et à fournir des services intégrés gratuits tels que des gestionnaires de mots de passe qui vous alertent également en cas de violation de données impliquant vos informations d'identification.
compare-chrome-as-for-customization-our = En ce qui concerne la personnalisation, nos fans vous diront que l'une des choses qu'ils aiment le plus dans notre navigateur est sa capacité à vous permettre de déplacer et d'organiser une majorité des éléments de l'interface utilisateur pour mieux répondre à vos besoins. { -brand-name-chrome } vous permet de masquer certains éléments de l'interface utilisateur, mais il n'y a pas beaucoup de marge, le cas échéant, pour déplacer des éléments en fonction de vos préférences. Cependant, il convient de noter que { -brand-name-chrome } et { -brand-name-firefox } permettent de modifier assez facilement l'apparence et le thème de votre navigateur.
compare-chrome-for-practical-purposes-theres = Pour des raisons pratiques, rien ne vous empêche évidemment d'utiliser les deux navigateurs. { -brand-name-firefox } pour les moments de la vie où la confidentialité compte vraiment, et { -brand-name-chrome } si vous êtes toujours investi dans l'écosystème { -brand-name-google } . Pourtant, avec le nombre croissant d'incursions dans nos données personnelles, { -brand-name-firefox } peut s'avérer être le bon choix à long terme pour ceux d'entre nous qui apprécient la protection de notre vie privée en ligne.
