# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Sept des meilleurs navigateurs en comparaison directe
compare-index-six-of-the-best-browsers-fallback = Six des meilleurs navigateurs en comparaison directe

# Sub-headline
compare-index-privacy-utility-portability = Intimité. Utilitaire. Portabilité.

# HTML page description
compare-index-a-great-internet-browser-should = Un bon navigateur Internet doit avoir les fonctionnalités dont vous avez besoin, la portabilité sur tous les appareils et la confidentialité que vous méritez.
compare-index-which-browser-is-best-at-keeping = Quel navigateur est le meilleur pour garder les choses confidentielles?
compare-index-its-not-unreasonable-to-expect = Il n'est pas déraisonnable de s'attendre à un niveau élevé de protection des données et de confidentialité des produits que nous utilisons régulièrement pour nous mettre en ligne. Au minimum, un navigateur doit proposer une version du «mode de navigation privée» qui supprime automatiquement votre historique et votre historique de recherche afin que les autres utilisateurs du même ordinateur ne puissent pas y accéder. Dans ce domaine, les sept navigateurs comparés ici marquent des points.
compare-index-its-not-unreasonable-to-expect-fallback = Il n'est pas déraisonnable de s'attendre à un niveau élevé de protection des données et de confidentialité des produits que nous utilisons régulièrement pour nous mettre en ligne. Au minimum, un navigateur doit proposer une version du «mode de navigation privée» qui supprime automatiquement votre historique et votre historique de recherche afin que les autres utilisateurs du même ordinateur ne puissent pas y accéder. Dans ce domaine, les six navigateurs comparés ici marquent des points.
compare-index-what-you-do-online-literally = Ce que vous faites en ligne ne devrait littéralement être l'affaire de personne d'autre.
compare-index-another-browser-feature-that = Une autre fonctionnalité du navigateur qui devrait être une donnée est la capacité d'empêcher les sites Web et les entreprises de suivre vos données de navigation et d'achat, même en mode de navigation normal.
compare-index-another-browser-feature-fallback = Une autre fonctionnalité du navigateur qui devrait être une donnée est la capacité d'empêcher les sites Web et les entreprises de suivre vos données de navigation et d'achat, même en mode de navigation normal. Mais ce n'est en fait pas le cas: en fait, les seuls navigateurs qui bloquent par défaut les cookies de suivi tiers sont { -brand-name-firefox } et { -brand-name-safari } .
compare-index-using-a-browser-that-blocks = L'utilisation d'un navigateur qui bloque les traqueurs tiers n'est pas seulement importante pour la confidentialité - cela signifie généralement qu'il fonctionne aussi beaucoup plus rapidement. La plupart des trackers ne sont que des scripts qui s'exécutent en arrière-plan sur un certain nombre de sites Web. Vous ne pouvez pas les voir, mais vous pouvez les sentir ralentir votre navigateur. À partir de la version 67 de { -brand-name-firefox } , les empreintes digitales et les cryptomineurs sont également bloqués. Si vous n'êtes pas familier avec les cryptomineurs, voici un exemple de la façon dont ils peuvent vous affecter: peut-être avez-vous vu votre ordinateur devenir soudainement plus chaud ou la batterie s'épuisant plus rapidement que d'habitude. C'est souvent le sous-produit des cryptomineurs qui rampent sur votre appareil.
compare-index-what-has-your-browser-done = Qu'est-ce que votre navigateur a fait pour vous ces derniers temps?
compare-index-in-addition-to-privacy-protection = En plus de la protection de la vie privée, qui se déroule en grande partie en arrière-plan du navigateur, un autre ingrédient clé d'un navigateur bien conçu est l'interface utilisateur et les fonctionnalités réelles. Presque les sept navigateurs sont égaux en ce qui concerne la navigation par onglets, la gestion des signets, la saisie semi-automatique, la relecture et les extensions. { -brand-name-firefox } , { -brand-name-edge } et { -brand-name-opera } offrent également une fonction de capture d'écran rapide qui s'avère très pratique et qui manque certainement lorsque vous passez à un navigateur sans elle.
compare-index-in-addition-to-privacy-protection-fallback = En plus de la protection de la vie privée, qui se déroule en grande partie en arrière-plan du navigateur, un autre ingrédient clé d'un navigateur bien conçu est l'interface utilisateur et les fonctionnalités réelles. Presque tous les six navigateurs sont égaux en ce qui concerne la navigation par onglets, la gestion des signets, la saisie semi-automatique, la relecture et les extensions. { -brand-name-firefox } , { -brand-name-edge } et { -brand-name-opera } offrent également une fonction de capture d'écran rapide qui s'avère très pratique et qui manque certainement lorsque vous passez à un navigateur sans elle.
compare-index-how-well-does-your-browser = Dans quelle mesure votre navigateur fonctionne-t-il sur vos appareils?
compare-index-almost-all-of-the-browsers = Presque tous les navigateurs comparés ici permettent la synchronisation entre les ordinateurs de bureau et les appareils mobiles. Vous aurez besoin d'un compte pour le faire, que vous pourrez utiliser pour vous connecter au navigateur sur tous les appareils et synchroniser des éléments tels que les mots de passe, l'historique de navigation, les signets et les paramètres.
compare-index-conclusion = Conclusion:
compare-index-and-the-winner-is = Et le gagnant est…
compare-index-find-out-how-firefox-chrome = Découvrez en quoi { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } et { -brand-name-ie } diffèrent en termes de confidentialité, d'utilité et de portabilité.
compare-index-find-out-how-firefox-fallback = Découvrez en quoi { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } et { -brand-name-ie } diffèrent en termes de confidentialité, d'utilité et de portabilité.
compare-index-looking-for-a-better-browser = Vous recherchez un meilleur navigateur? Nous comparerons { -brand-name-firefox } avec { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } et { -brand-name-ie } pour vous aider à prendre votre décision.
compare-index-looking-for-a-better-fallback = Vous recherchez un meilleur navigateur? Nous comparerons { -brand-name-firefox } avec { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } et { -brand-name-ie } pour vous aider à prendre votre décision.
compare-index-so-is-your-browser-the-best = Votre navigateur est-il donc le meilleur pour ce que vous faites en ligne? Le bon navigateur peut faire une grande différence dans votre expérience du Web. Alors, sans plus tarder, comparons { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } , { -brand-name-microsoft } { -brand-name-ie } et { -brand-name-edge } - et voyons celui qui répond le mieux à vos besoins.
compare-index-so-is-your-browser-the-fallback = Votre navigateur est-il donc le meilleur pour ce que vous faites en ligne? Le bon navigateur peut faire une grande différence dans votre expérience du Web. Alors, sans plus tarder, comparons { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-microsoft } { -brand-name-ie } et { -brand-name-edge } - et voyons celui qui répond le mieux à vos besoins.
compare-index-since-your-browser-is-your = Puisque votre navigateur est votre passerelle vers Internet, la vitesse, la sécurité, la confidentialité et l'utilité sont primordiales. Ces dernières années, { -brand-name-google } { -brand-name-chrome } a été le navigateur de choix pour beaucoup. Mais à un moment où les publicités en ligne semblent nous suivre partout et les violations de données font la une des journaux, de nombreuses personnes commencent à exiger plus de confidentialité et de respect de leur navigateur.
compare-index-the-first-thing-to-point-out = La première chose à souligner à propos de la portabilité est que tous les navigateurs ne fonctionnent pas sur tous les systèmes d'exploitation. Bien que { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-brave } et { -brand-name-opera } fonctionnent sur tous les principaux systèmes et soient faciles à installer, { -brand-name-ie } et { -brand-name-safari } ne fonctionnent que sur { -brand-name-microsoft } et les propres systèmes d'Apple. La version mobile de { -brand-name-safari } est préinstallée sur les appareils mobiles d'Apple et la plupart des appareils { -brand-name-android } sont livrés avec un navigateur préinstallé modifié par le fabricant de l'appareil. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-brave } , { -brand-name-edge } et { -brand-name-opera } peuvent facilement être installés et même utilisés côte à côte.
compare-index-the-first-thing-to-point-fallback = La première chose à souligner à propos de la portabilité est que tous les navigateurs ne fonctionnent pas sur tous les systèmes d'exploitation. Bien que { -brand-name-firefox } , { -brand-name-chrome } et { -brand-name-opera } fonctionnent sur tous les principaux systèmes et soient faciles à installer, { -brand-name-ie } , { -brand-name-edge } et { -brand-name-safari } ne fonctionnent que sur { -brand-name-microsoft } et les propres systèmes d'Apple. La version mobile de { -brand-name-safari } est préinstallée sur les appareils mobiles d'Apple, et la plupart des appareils { -brand-name-android } sont livrés avec un navigateur préinstallé modifié par le fabricant de l'appareil. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } et { -brand-name-opera } peuvent facilement être installés et même utilisés côte à côte.
compare-index-browsers-have-come-a-long = Les navigateurs ont parcouru un long chemin depuis que { -brand-name-chrome } été introduit et a pris la part de marché. La plupart des navigateurs modernes ont comblé le fossé en matière de portabilité et de fonctionnalité, et dans certains domaines, comme la vitesse et la confidentialité, ont dépassé { -brand-name-chrome } . Néanmoins, la détermination du navigateur qui vous convient dépendra toujours de vos besoins individuels et de ce que vous appréciez le plus lorsque vous naviguez en ligne.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } est soutenu par l'organisation à but non lucratif { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } accorde la priorité à votre vie privée - dans tout ce que nous faisons et faisons. Nous pensons que vous avez le droit de décider comment et avec qui vous partagez vos informations personnelles. { -brand-name-firefox } collecte le moins de données possible et ne les vend jamais. Le peu de données que nous recueillons ne sert qu'à améliorer les produits et les fonctionnalités. Pas de secrets. Mais beaucoup de transparence et une vraie confidentialité.
compare-index-based-on-the-criteria-we-outlined = Sur la base des critères que nous avons définis - confidentialité, utilité et portabilité - il n'y a vraiment qu'un seul navigateur qui répond à la marque, et c'est { -brand-name-firefox } . La vraie différence n'est pas la fonctionnalité, c'est la confidentialité. { -brand-name-firefox } est le navigateur le plus privé qui ne vous enferme pas dans un écosystème. Utilisez-le sur n'importe quel système d'exploitation, sur tous vos appareils, et soyez en sécurité lorsque vous le faites.
