# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari } : Qual é o melhor navegador para você?

# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } é o navegador pré-instalado em { -brand-name-mac } e { -brand-name-iphone } . Compare { -brand-name-safari } com o { -brand-name-firefox-browser } para descobrir qual é o melhor navegador para você.

# Main title.
compare-safari-comparing-firefox-browser = Comparando { -brand-name-firefox-browser } com { -brand-name-apple } { -brand-name-safari }

# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Se você usa um Mac ou tem um { -brand-name-iphone } , é provável que esteja familiarizado com o { -brand-name-safari } navegador da web. O fato de estar pré-instalado como navegador padrão para { -brand-name-apple } usuários do produto definitivamente oferece uma vantagem inicial, mas { -brand-name-firefox } tem seu próprio conjunto de recursos úteis que o tornam uma alternativa atraente. Aqui, exploraremos as principais diferenças entre nosso navegador e { -brand-name-safari } em termos de privacidade, utilidade e portabilidade entre dispositivos.

# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = A privacidade se tornou um assunto em alta para as empresas de tecnologia à medida que percebem que mais e mais pessoas estão se sentindo vulneráveis a coisas como violações de dados, rastreadores de anúncios e hackers. Mas quando se trata das ferramentas reais que as pessoas usam para navegar nas interwebs reais, é tudo conversa ou eles estão realmente tomando medidas para manter seus dados seguros?
compare-safari-as-alluded-to-before-apple-fallback = Como mencionado antes, { -brand-name-apple } é uma daquelas empresas que recentemente decidiu intensificar seu jogo de privacidade. Não muito tempo atrás, { -brand-name-apple } implementou a prevenção de rastreamento entre sites em { -brand-name-safari } , que evita que os anúncios sigam você na Internet. { -brand-name-safari } também oferece uma sugestão de senha forte quando você se inscreve em uma nova conta em qualquer site. E se você investiu no ecossistema do iCloud, ele sincroniza essa senha com segurança com seus outros dispositivos, para que você nunca precise realmente se lembrar dela.

# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Como { -brand-name-safari } , nós em { -brand-name-firefox } fizemos questão de nos concentrar na privacidade e segurança. Mas, ao contrário de { -brand-name-safari } , há muito tempo que defendemos a caixa de sabão da privacidade. Na verdade, { -brand-name-mozilla } (nossa empresa controladora) foi uma das primeiras vozes na comunidade de tecnologia a soar o alarme pela privacidade online.

# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Nosso modo de navegação privada bloqueia rastreadores e apaga suas senhas, cookies e histórico toda vez que você o fecha. Mas você também pode experimentar nossos recursos avançados de privacidade, mesmo no modo de navegação normal. Com a edição mais recente do { -brand-name-firefox } , a prevenção de rastreamento aprimorada é ativada por padrão. Isso evita que coisas como rastreadores entre sites o sigam enquanto você navega pela web. Além disso, como { -brand-name-facebook } é pego quase diariamente por problemas de privacidade, nossa extensão <a { $attrs }>{ -brand-name-facebook-container }</a> faz muito sentido. Torna mais difícil para { -brand-name-facebook } rastreá-lo na web - semelhante ao que { -brand-name-safari } faz para impedir o rastreamento entre sites - mas { -brand-name-firefox } realmente isola sua { -brand-name-facebook } sessão em um contêiner separado bloqueando { -brand-name-facebook } do rastreamento o que você faz em outros sites. Por que eles precisam saber o que você procura no WebMD?

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = No que diz respeito à segurança, { -brand-name-firefox } é sólido. Sempre que estiver em { -brand-name-firefox } , você poderá clicar com o botão direito no campo da senha para gerar com segurança uma senha forte usando a opção Preencher senha. Quando você salvar sua nova senha, solicitaremos que salve em seu gerenciador de senhas integrado, <a { $lockwise }>{ -brand-name-lockwise }</a> . Também atendemos usuários e titulares de contas com outro produto útil e gratuito chamado <a { $monitor }>{ -brand-name-monitor }</a> que o alerta automaticamente se seus dados forem incluídos em uma violação de dados conhecida.
compare-safari-if-you-choose-to-use-safari = Se optar por usar { -brand-name-safari } , você estará em boas mãos contanto que use um dispositivo { -brand-name-apple } . Mas { -brand-name-safari } só funciona em { -brand-name-apple } dispositivos, enquanto { -brand-name-firefox } funciona em { -brand-name-windows } , { -brand-name-mac } , { -brand-name-ios } , { -brand-name-android } e { -brand-name-linux } . Portanto, não importa o sistema operacional que você escolher, { -brand-name-firefox } você terá a cobertura de nossas proteções de segurança e privacidade.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } é amplamente conhecido por seu ecossistema fechado no que se refere à criação de software para seus produtos. Mas dentro do { -brand-name-app-store } , ele oferece uma seção para que os desenvolvedores criem plug-ins e complementos para tornar o navegador mais robusto. Essas extensões também são navegáveis por meio de { -brand-name-app-store } e facilmente adicionadas a { -brand-name-safari } .
compare-safari-in-addition-to-the-regular = Além do conjunto regular de recursos que você espera de um navegador, como navegação por guias e navegação privada, { -brand-name-safari } possui alguns recursos inesperados. Por exemplo, se um usuário clicasse com o botão direito em uma palavra em qualquer lugar de uma página dentro de { -brand-name-safari } , em seguida, clicasse em Pesquisar, ele obteria uma definição de dicionário e entradas do dicionário de sinônimos, { -brand-name-app-store } , filmes e muito mais. Os controles dos pais de { -brand-name-safari } são fáceis de personalizar, permitindo que os adultos respirem um pouco mais facilmente quando as crianças começam a ficar curiosas sobre a internet.

# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Como { -brand-name-safari } , { -brand-name-firefox } incentiva sua entusiasmada comunidade de desenvolvedores a criar <a { $attrs }>complementos e extensões</a> para o navegador. E como nossa plataforma é de código aberto, há uma vasta seleção que adiciona uma riqueza de funcionalidades.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Além disso, quando você se inscreve em uma conta do { -brand-name-firefox } , obtém acesso a serviços exclusivos como <a { $pocket }>{ -brand-name-pocket }</a> e <a { $send }>{ -brand-name-send }</a> que se integram diretamente no navegador. O botão { -brand-name-pocket } para { -brand-name-firefox } permite salvar páginas da web e vídeos em { -brand-name-pocket } com apenas um clique, para que você possa ler uma versão limpa e sem distrações quando e onde quiser - mesmo offline. Com o { -brand-name-send } você pode compartilhar arquivos grandes com criptografia de ponta a ponta com uma variedade de controles de segurança, como a capacidade de definir um tempo de expiração para um link de arquivo expirar, o número de downloads e adicionar um opcional senha para uma camada extra de segurança.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Além disso, quando você se inscreve em uma conta do { -brand-name-firefox } , obtém acesso a alguns serviços exclusivos, como capturas de tela, <a { $pocket }>{ -brand-name-pocket }</a> e <a { $send }>{ -brand-name-send }</a> que se integram diretamente ao navegador. Capturas de tela é um recurso integrado ao navegador { -brand-name-firefox } , permitindo que você copie ou baixe parte ou parte de uma página da web. Ao salvar a captura de tela, você também pode escolher em qual pasta deseja encontrá-la, em vez de bagunçar sua área de trabalho. O botão { -brand-name-pocket } para { -brand-name-firefox } permite que você salve páginas da web e vídeos no { -brand-name-pocket } com apenas um clique, para que possa ler uma versão limpa e sem distrações quando e onde quiser - mesmo offline. Com o { -brand-name-send } , você pode compartilhar arquivos grandes com criptografia de ponta a ponta e uma variedade de controles de segurança, como a capacidade de definir um tempo de expiração para um link de arquivo expirar, o número de downloads e adicionar um senha opcional para uma camada extra de segurança.

# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Capturas de tela</a> é outro recurso popular integrado ao navegador { -brand-name-firefox } , permitindo que você capture facilmente uma imagem de sua tela. Ao fazer uma captura de tela, você pode escolher copiar o arquivo ou escolher em qual pasta deseja encontrá-lo, em vez de desordenar sua área de trabalho.

# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } e { -brand-name-safari } ambos fornecem uma experiência perfeita ao mudar da navegação do desktop para o celular ou vice-versa. Para { -brand-name-safari } , um de seus principais pontos fortes são os recursos de continuidade. Ele sincroniza seus favoritos, guias, histórico e muito mais com o iCloud para que estejam disponíveis em todos os seus dispositivos. Isso significa que você pode abrir uma guia em seu { -brand-name-iphone } e fazer com que ela também apareça em seu { -brand-name-mac } laptop com apenas um clique.
compare-safari-both-browsers-have-a-lot = Ambos os navegadores têm muitos recursos de crossover, bem como algumas funções exclusivas. Vale a pena mencionar que, se você fizer muitas capturas de tela, se perguntará como já viveu sem esse recurso útil integrado ao { -brand-name-firefox } . Mas se você está apenas procurando um navegador rápido e privado para navegar e fazer compras, convém { -brand-name-firefox } tentar - especialmente se você estiver usando exclusivamente { -brand-name-safari } porque ele veio pré-carregado como o navegador padrão em seu computador. Eventualmente, você descobrirá qual é o mais adequado às suas necessidades.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } também oferece um recurso de sincronização semelhante quando você se inscreve em um <a { $attrs }>{ -brand-name-firefox-account }</a> gratuito que permite aos usuários sincronizar facilmente seus favoritos, histórico de navegação, preferências, senhas, formulários preenchidos, complementos e as últimas 25 guias abertas em vários computadores. O que diferencia { -brand-name-firefox } de { -brand-name-safari } é que ele está disponível em qualquer desktop ou plataforma móvel, { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } ou { -brand-name-macos } , aumentando sua portabilidade em qualquer dispositivo que você tenha.

# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = O { -brand-name-firefox } aplicativo para <a { $ios }>{ -brand-name-ios }</a> e <a { $android }>{ -brand-name-android }</a> é um dos navegadores mais rápidos disponíveis e também possui recursos sólidos de segurança e anti-rastreamento - uma grande vantagem se você está constantemente mudando de um laptop para dispositivos móveis.
compare-safari-since-safari-is-apples-proprietary = Como { -brand-name-safari } é o navegador proprietário de { -brand-name-apple } , a sincronização do iCloud funciona exclusivamente com os produtos { -brand-name-apple } . Isso pode ser um pouco limitante se, por exemplo, você for um { -brand-name-android } usuário e um { -brand-name-iphone } usuário ou se tiver um { -brand-name-windows } PC para trabalhar, mas usar um { -brand-name-iphone } como seu dispositivo pessoal.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } faz um ótimo trabalho em tornar a experiência de navegação simples, rápida e contínua se você for um { -brand-name-apple } usuário com vários { -brand-name-apple } produtos. Assim como { -brand-name-safari } , { -brand-name-firefox } é um navegador rápido e utilitário, mas a privacidade e a compatibilidade entre plataformas são nossos recursos definidores. { -brand-name-firefox } atualizado a cada mês com novos recursos e funcionalidades. Por exemplo, uma atualização recente ativou nossa <a { $attrs }>Proteção Avançada de Rastreamento (ETP)</a> por padrão para novos usuários, o que bloqueia com eficácia cookies e rastreadores entre sites.
compare-safari-in-the-end-it-just-boils = No final, tudo se resume ao que você valoriza em seu navegador. Se você estiver integrado ao { -brand-name-apple } ecossistema, { -brand-name-safari } ainda é uma ótima escolha. Mas se você valoriza ter as melhores e mais recentes proteções de privacidade e poder trabalhar em vários sistemas operacionais, achamos que { -brand-name-firefox } é sua melhor aposta. { -brand-name-firefox } também é uma opção sólida como navegador secundário para aqueles { -brand-name-apple } usuários exclusivos que podem querer mudar para um navegador diferente para aqueles momentos online que exigem camadas extras de proteção de privacidade.
