# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } frente a { -brand-name-safari } : ¿Cuál es el mejor navegador para usted?

# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } es el navegador preinstalado en { -brand-name-mac } y { -brand-name-iphone } . Compare { -brand-name-safari } con { -brand-name-firefox-browser } para averiguar cuál es el mejor navegador para usted.

# Main title.
compare-safari-comparing-firefox-browser = Comparando { -brand-name-firefox-browser } con { -brand-name-apple } { -brand-name-safari }

# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Si usa una Mac o tiene una { -brand-name-iphone } , es probable que esté familiarizado con el navegador web { -brand-name-safari } . El hecho de que esté preinstalado como navegador predeterminado para los usuarios del producto { -brand-name-apple } definitivamente le da una ventaja inicial, pero { -brand-name-firefox } tiene su propio conjunto de características útiles que lo convierten en una alternativa atractiva. Aquí exploraremos las principales diferencias entre nuestro navegador y { -brand-name-safari } en términos de privacidad, utilidad y portabilidad entre dispositivos.

# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = La privacidad se ha convertido en un tema candente para las empresas de tecnología, ya que se dan cuenta de que cada vez más personas se sienten vulnerables a cosas como violaciones de datos, rastreadores de anuncios y piratas informáticos. Pero cuando se trata de las herramientas reales que la gente usa para navegar por las interwebs reales, ¿se trata de hablar o realmente están tomando medidas para mantener sus datos seguros?
compare-safari-as-alluded-to-before-apple-fallback = Como se mencionó anteriormente, { -brand-name-apple } es una de esas empresas que recientemente decidió intensificar su juego de privacidad. No hace mucho, { -brand-name-apple } implementó la prevención de seguimiento entre sitios en { -brand-name-safari } , lo que evita que los anuncios lo sigan por Internet. { -brand-name-safari } también ofrece una sugerencia de contraseña segura cuando se registra para obtener una nueva cuenta en cualquier sitio web. Y si invierte en el ecosistema de iCloud, sincroniza esa contraseña de forma segura con sus otros dispositivos, por lo que nunca tendrá que recordarla.

# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Como { -brand-name-safari } , en { -brand-name-firefox } hemos centrado en la privacidad y la seguridad. Pero a diferencia de { -brand-name-safari } , hemos estado en la caja de jabón de privacidad durante mucho tiempo. De hecho, { -brand-name-mozilla } (nuestra empresa matriz) fue una de las primeras voces de la comunidad tecnológica en hacer sonar la alarma de la privacidad en línea.

# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Nuestro modo de navegación privada bloquea los rastreadores y borra sus contraseñas, cookies e historial cada vez que lo cierra. Pero también puede experimentar nuestras funciones de privacidad avanzadas incluso en el modo de navegación normal. Con la última edición de { -brand-name-firefox } , la prevención de seguimiento mejorada está activada de forma predeterminada. Esto evita que elementos como los rastreadores entre sitios lo sigan mientras navega por la web. Además, con { -brand-name-facebook } siendo detectado casi a diario por problemas de privacidad, nuestra extensión <a { $attrs }>{ -brand-name-facebook-container }</a> tiene mucho sentido. Hace que sea más difícil para { -brand-name-facebook } rastrearlo en la Web, similar a lo que hace { -brand-name-safari } para evitar el seguimiento entre sitios, pero { -brand-name-firefox } realidad aísla su sesión { -brand-name-facebook } en un contenedor separado que bloquea { -brand-name-facebook } seguimiento. lo que haces en otros sitios web. ¿Por qué necesitan saber lo que buscas en WebMD de todos modos?

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = En lo que respecta a la seguridad, { -brand-name-firefox } es sólido allí. Siempre que esté en { -brand-name-firefox } , puede hacer clic con el botón derecho en el campo de la contraseña para generar de forma segura una contraseña segura mediante la opción Completar contraseña. Cuando guarde su nueva contraseña, le pediremos que la guarde en su administrador de contraseñas integrado, <a { $lockwise }>{ -brand-name-lockwise }</a> . También brindamos a los usuarios y titulares de cuentas otro producto gratuito y útil llamado <a { $monitor }>{ -brand-name-monitor }</a> que le alerta automáticamente si sus datos están incluidos en una violación de datos conocida.
compare-safari-if-you-choose-to-use-safari = Si eliges usar { -brand-name-safari } , estás en buenas manos siempre que uses un dispositivo { -brand-name-apple } . Pero { -brand-name-safari } solo funciona en { -brand-name-apple } dispositivos, mientras que { -brand-name-firefox } funciona en { -brand-name-windows } , { -brand-name-mac } , { -brand-name-ios } , { -brand-name-android } y { -brand-name-linux } . Por lo tanto, independientemente del sistema operativo que elija, { -brand-name-firefox } tiene cubierto con nuestras protecciones de seguridad y privacidad.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } es ampliamente conocido por su ecosistema cerrado en lo que respecta a la creación de software para sus productos. Pero dentro de { -brand-name-app-store } , ofrece una sección a los desarrolladores para crear complementos y complementos para hacer que el navegador sea más robusto. Estas extensiones también se pueden explorar a través de { -brand-name-app-store } y se pueden agregar fácilmente a { -brand-name-safari } .
compare-safari-in-addition-to-the-regular = Además del conjunto habitual de funciones que esperaría de un navegador, como la navegación con pestañas y la navegación privada, { -brand-name-safari } tiene algunas características inesperadas. Por ejemplo, si un usuario hiciera clic con el botón derecho en una palabra en cualquier lugar de una página dentro de { -brand-name-safari } y luego haga clic en Buscar, obtendría una definición de diccionario más entradas del diccionario de sinónimos, { -brand-name-app-store } , películas y más. Los controles parentales de { -brand-name-safari } son fáciles de personalizar, lo que permite a los adultos respirar un poco mejor cuando los niños comienzan a sentir curiosidad por Internet.

# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Al igual que { -brand-name-safari } , { -brand-name-firefox } anima a su entusiasta comunidad de desarrolladores a crear <a { $attrs }>complementos y extensiones</a> para el navegador. Y dado que nuestra plataforma es de código abierto, hay una amplia selección que agrega una gran cantidad de funcionalidades.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Además, cuando se registra para obtener una cuenta de { -brand-name-firefox } , obtiene acceso a servicios únicos como <a { $pocket }>{ -brand-name-pocket }</a> y <a { $send }>{ -brand-name-send }</a> que se integran directamente en el navegador. El botón { -brand-name-pocket } para { -brand-name-firefox } te permite guardar páginas web y videos en { -brand-name-pocket } con un solo clic, para que puedas leer una versión limpia y sin distracciones cuando y donde quieras, incluso sin conexión. Con { -brand-name-send } puede compartir archivos grandes con encriptación de un extremo a otro con una variedad de controles de seguridad, como la capacidad de establecer un tiempo de vencimiento para que caduque un enlace de archivo, la cantidad de descargas y si agregar un contraseña para una capa adicional de seguridad.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Además, cuando se registra para obtener una cuenta de { -brand-name-firefox } , obtiene acceso a algunos servicios únicos como capturas de pantalla <a { $pocket }>{ -brand-name-pocket }</a> y <a { $send }>{ -brand-name-send }</a> que se integran directamente en el navegador. Capturas de pantalla es una función integrada en el navegador { -brand-name-firefox } , que le permite copiar o descargar parte o parte de una página web. Cuando guarda la captura de pantalla, también puede elegir en qué carpeta desea encontrarla, en lugar de abarrotar su escritorio. El botón { -brand-name-pocket } para { -brand-name-firefox } te permite guardar páginas web y videos en { -brand-name-pocket } con un solo clic, para que puedas leer una versión limpia y sin distracciones cuando y donde quieras, incluso sin conexión. Con { -brand-name-send } , puede compartir archivos grandes con encriptación de un extremo a otro y una variedad de controles de seguridad, como la capacidad de establecer un tiempo de vencimiento para que caduque un enlace de archivo, la cantidad de descargas y si agregar un contraseña opcional para una capa adicional de seguridad.

# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Las capturas de pantalla</a> es otra característica popular integrada en el navegador { -brand-name-firefox } , que le permite capturar fácilmente una imagen de su pantalla. Cuando toma una captura de pantalla, puede elegir copiar el archivo o elegir la carpeta en la que desea encontrarlo, en lugar de abarrotar su escritorio.

# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } y { -brand-name-safari } brindan una experiencia perfecta al pasar de la navegación de escritorio a la navegación móvil o viceversa. Para { -brand-name-safari } , una de sus principales fortalezas son sus características de continuidad. Sincroniza tus marcadores, pestañas, historial y más con iCloud para que estén disponibles en todos tus dispositivos. Eso significa que puede abrir una pestaña en su { -brand-name-iphone } y hacer que también aparezca en su { -brand-name-mac } computadora portátil con solo un clic.
compare-safari-both-browsers-have-a-lot = Ambos navegadores tienen muchas características cruzadas, así como algunas funciones únicas. Vale la pena mencionar que, si toma muchas capturas de pantalla, se preguntará cómo pudo vivir sin esta práctica función que está integrada en { -brand-name-firefox } . Pero si solo está buscando un navegador privado y rápido para navegar y comprar, entonces le recomendamos que pruebe { -brand-name-firefox } , especialmente si ha estado usando exclusivamente { -brand-name-safari } porque venía precargado como el navegador predeterminado en tu computadora. Con el tiempo, descubrirás cuál se adapta mejor a tus necesidades.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } también ofrece una función de sincronización similar cuando te registras para obtener un <a { $attrs }>{ -brand-name-firefox-account }</a> gratuito que permite a los usuarios sincronizar fácilmente sus marcadores, historial de navegación, preferencias, contraseñas, formularios llenos, complementos y las últimas 25 pestañas abiertas en varios ordenadores. Lo que distingue a { -brand-name-firefox } de { -brand-name-safari } es que está disponible en cualquier plataforma de escritorio o móvil, { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } o { -brand-name-macos } , lo que aumenta su portabilidad en cualquier dispositivo que tenga.

# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = La aplicación { -brand-name-firefox } para <a { $ios }>{ -brand-name-ios }</a> y <a { $android }>{ -brand-name-android }</a> es uno de los navegadores más rápidos disponibles y también tiene características sólidas de seguridad y anti-rastreo, una gran ventaja si está constantemente rebotando entre una computadora portátil y dispositivos móviles.
compare-safari-since-safari-is-apples-proprietary = Dado que { -brand-name-safari } es el navegador web propietario de { -brand-name-apple } , su sincronización de iCloud funciona exclusivamente con los productos de { -brand-name-apple } . Esto puede ser algo limitante si, por ejemplo, es un usuario { -brand-name-android } y un usuario { -brand-name-iphone } o si tiene una PC basada en { -brand-name-windows } para trabajar pero usa un { -brand-name-iphone } como dispositivo personal.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } hace un gran trabajo al hacer que la experiencia de navegación sea simple, rápida y fluida si eres un { -brand-name-apple } usuario con varios { -brand-name-apple } productos. Al igual que { -brand-name-safari } , { -brand-name-firefox } es un navegador rápido y utilitario, pero la privacidad y la compatibilidad entre plataformas son nuestras características definitorias. { -brand-name-firefox } actualiza cada mes con nuevas funciones y funciones. Por ejemplo, una actualización reciente activó nuestra <a { $attrs }>Protección de seguimiento mejorada (ETP)</a> de forma predeterminada para los nuevos usuarios, que bloquea de manera efectiva las cookies y los rastreadores entre sitios.
compare-safari-in-the-end-it-just-boils = Al final, todo se reduce a lo que valora en su navegador. Si está integrado con el ecosistema { -brand-name-apple } , { -brand-name-safari } sigue siendo una excelente opción. Pero si valora tener las últimas y mejores protecciones de privacidad y poder trabajar en varios sistemas operativos, creemos que { -brand-name-firefox } es su mejor opción. { -brand-name-firefox } también es una opción sólida como navegador secundario para aquellos { -brand-name-apple } usuarios exclusivos que quieran cambiar a un navegador diferente para esos momentos en línea que requieren capas adicionales de protección de la privacidad.
