# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } frente a { -brand-name-chrome } : ¿cuál es mejor?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Comparamos { -brand-name-mozilla } { -brand-name-firefox } con { -brand-name-google } { -brand-name-chrome } en términos de privacidad, utilidad y portabilidad.

# Main title.
compare-chrome-comparing-firefox-browser = Comparando { -brand-name-firefox-browser } con { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = En { -brand-name-firefox } , tenemos una gran cantidad de usuarios dedicados que aprecian nuestra firme dedicación a la privacidad en línea. Por ejemplo, la última versión de { -brand-name-firefox } incluye una función llamada Protección de seguimiento mejorada (ETP) que está activada de forma predeterminada para todos los usuarios en todo el mundo. ETP bloquea más de 2000 rastreadores, incluidos rastreadores sociales de empresas como { -brand-name-facebook } , { -brand-name-twitter } y LinkedIn. También tiene una función integrada llamada <a { $attrs }>{ -brand-name-firefox-monitor }</a> que le notifica automáticamente si su contraseña ha sido violada o necesita ser actualizada. Además de estas protecciones, el modo de navegación privada en { -brand-name-firefox } elimina automáticamente su información de navegación, como el historial y las cookies, sin dejar rastro después de que finaliza su sesión.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = En { -brand-name-firefox } , tenemos una gran cantidad de usuarios dedicados que aprecian nuestra firme dedicación a la privacidad en línea. Por ejemplo, la última versión de { -brand-name-firefox } incluye una función llamada Protección de seguimiento mejorada (ETP) que está activada de forma predeterminada para todos los usuarios en todo el mundo. ETP bloquea más de 2000 rastreadores, incluidos rastreadores sociales de empresas como { -brand-name-facebook } , { -brand-name-twitter } y LinkedIn. También tiene una función integrada llamada <a { $attrs }>{ -brand-name-firefox-monitor }</a> que le notifica automáticamente si su contraseña ha sido violada o necesita ser actualizada. Además de estas protecciones, el modo de navegación privada de { -brand-name-firefox } elimina automáticamente su información de navegación, como el historial y las cookies, sin dejar rastro una vez que finaliza la sesión.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = También hemos reiterado recientemente nuestro compromiso con la privacidad y la transparencia con respecto a los datos de los usuarios en nuestro <a { $attrs }>Aviso de privacidad</a> más reciente que dice: &quot;En Mozilla, creemos que la privacidad es fundamental para una Internet saludable&quot;.
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } es, según todas las cuentas, un navegador seguro, con funciones como { -brand-name-google } Navegación segura, que ayuda a proteger a los usuarios al mostrar una advertencia imposible de perder cuando intentan navegar a sitios peligrosos o descargar archivos peligrosos.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = En última instancia, depende de usted decidir si debe o no trazar la línea al compartir cosas como su historial de búsqueda y su historial de compras. Pero si eres como la mayoría de las personas, probablemente hayas buscado algunas cosas en Internet que preferirías mantener en privado.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Avance rápido hasta el día de hoy, el panorama competitivo para los navegadores ha cambiado y muchas personas comienzan a cuestionarse qué está sucediendo con sus datos en línea, como el historial de navegación, las contraseñas y otra información confidencial. Mucho ha cambiado desde 2008 cuando { -brand-name-chrome } entró en escena. En { -brand-name-firefox } , hemos estado trabajando para rediseñar nuestra interfaz y brindar a los usuarios un número cada vez mayor de mejoras de privacidad y rendimiento, así como muchas herramientas de navegador útiles.
compare-chrome-and-so-here-we-are-the-browser = Y aquí estamos, las guerras de navegadores están aumentando una vez más y es hora de reevaluar y comparar { -brand-name-firefox-browser } vs { -brand-name-google } { -brand-name-chrome } .
compare-chrome-in-2008-google-introduced = En 2008, { -brand-name-google } presentó { -brand-name-chrome } y su impacto como innovación en la tecnología de los navegadores fue inmediato. Era más rápido para cargar sitios, ocupaba un espacio de pantalla mínimo y ofrecía una interfaz de usuario innegablemente simple.
compare-chrome-in-fact-both-chrome-and-firefox = De hecho, tanto { -brand-name-chrome } como { -brand-name-firefox } cuentan con una seguridad rigurosa. Ambos incluyen algo llamado “sandboxing” que separa los procesos del navegador para que algo como un sitio web dañino no infecte otras partes de su computadora portátil u otro dispositivo.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Si bien { -brand-name-chrome } demuestra ser un navegador web seguro, su historial de privacidad es cuestionable. { -brand-name-google } realidad recopila una cantidad inquietantemente grande de datos de sus usuarios, incluida la ubicación, el historial de búsqueda y las visitas al sitio. { -brand-name-google } defiende la recopilación de datos diciendo que lo hace para mejorar sus servicios, como ayudarlo a encontrar un suéter o una cafetería como la que compró o visitó anteriormente. Sin embargo, otros pueden no estar de acuerdo, señalando que { -brand-name-google } realidad está recopilando una cantidad de datos sin precedentes para sus propios fines de marketing. Ellos pregonan que están manteniendo su información privada de los piratas informáticos, pero eso no viene al caso. { -brand-name-google } administra la red publicitaria más grande del mundo, gracias en gran parte a los datos que recopilan de sus usuarios.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = En términos de funciones, tanto { -brand-name-firefox } como { -brand-name-chrome } ofrecen una gran biblioteca de extensiones y complementos, y el catálogo de { -brand-name-chrome } supera ampliamente en número a cualquier otro navegador, mientras que se integra muy bien con otros servicios de { -brand-name-google } , como Gmail y { -brand-name-google } Documentos.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } también tiene una función de sincronización para ver las pestañas abiertas y recientes, el historial de navegación y los marcadores en todos sus dispositivos.
compare-chrome-while-chrome-gets-the-nod = Si bien { -brand-name-chrome } obtiene el visto bueno con complementos y extensiones, { -brand-name-firefox } tiene un conjunto de funciones integradas muy bien seleccionadas, como la herramienta de captura de pantalla increíblemente útil y la función de modo de lectura que elimina todo lo que aparece en la página, excepto el texto del artículo que estás leyendo.
compare-chrome-although-not-as-extensive = Aunque no es tan extenso como la biblioteca de complementos de { -brand-name-chrome } , { -brand-name-firefox } , como software de código abierto con una gran cantidad de colaboradores activos, también presenta una increíble cantidad de extensiones útiles.
compare-chrome-if-having-tons-of-open-tabs = Si lo tuyo es tener toneladas de pestañas abiertas, entonces realmente se reduce a tus preferencias de interfaz de usuario. { -brand-name-firefox } incluye un desplazamiento horizontal en todas las pestañas abiertas en lugar de reducirlas cada vez más con cada nueva. { -brand-name-google } { -brand-name-chrome } prefiere reducirlos para que solo el favicon sea visible. El único problema con esto es cuando tiene varias pestañas abiertas desde el mismo sitio web, por lo que ve el mismo favicon en todas sus pestañas.
compare-chrome-almost-needless-to-say-versions = Casi no hace falta decir que las versiones de { -brand-name-firefox } y { -brand-name-chrome } están disponibles para los sistemas operativos móviles y de escritorio más populares ( { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ).
compare-chrome-both-chrome-and-firefox-also = Tanto { -brand-name-chrome } como { -brand-name-firefox } también te permiten sincronizar cosas como contraseñas, marcadores y pestañas abiertas en todos tus dispositivos. Si tiene una cuenta de { -brand-name-firefox } , puede enviar manualmente una pestaña abierta en su escritorio a su dispositivo móvil o viceversa. Con { -brand-name-chrome } , se hace automáticamente si ha elegido esa configuración en sus preferencias. No tener que enviar manualmente la pestaña de un dispositivo a otro es conveniente cuando desea hacer algo como continuar leyendo un artículo que no terminó antes. Pero puede haber ocasiones en las que la sincronización automática no sea ideal si existe la posibilidad de que varios usuarios estén navegando mientras están conectados a su cuenta { -brand-name-google } .

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Creemos que es justo decir que { -brand-name-firefox } y { -brand-name-chrome } están realmente codo a codo en términos de portabilidad y utilidad, y que { -brand-name-chrome } tiene una ligera ventaja en utilidad debido a su enorme biblioteca de extensiones y funciones complementarias. Pero en términos de privacidad, { -brand-name-firefox } gana el día con nuestro compromiso de preservar los datos en línea de nuestros usuarios y brindar servicios integrados gratuitos como administradores de contraseñas que también le alertan si se produce una violación de datos que involucre sus credenciales.
compare-chrome-as-for-customization-our = En cuanto a la personalización, nuestros fans le dirán que una de las cosas que más les gusta de nuestro navegador es su capacidad para permitirle mover y organizar la mayoría de los elementos de la interfaz de usuario para que se adapten mejor a sus necesidades. { -brand-name-chrome } te permite ocultar ciertos elementos de la interfaz de usuario, pero no hay mucho margen, si lo hay, para mover cosas según tus preferencias. Sin embargo, debe tenerse en cuenta que tanto { -brand-name-chrome } como { -brand-name-firefox } hacen que sea bastante fácil cambiar la apariencia y el tema de su navegador.
compare-chrome-for-practical-purposes-theres = A efectos prácticos, es evidente que no hay nada que le impida utilizar ambos navegadores: { -brand-name-firefox } para esos momentos de la vida en los que la privacidad es realmente importante y { -brand-name-chrome } si todavía está interesado en el ecosistema { -brand-name-google } . Sin embargo, con el creciente número de incursiones en nuestros datos personales, { -brand-name-firefox } puede resultar la elección correcta a largo plazo para aquellos de nosotros que valoramos la protección de nuestra privacidad personal en línea.
