# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Siete de los mejores navegadores en comparación directa
compare-index-six-of-the-best-browsers-fallback = Seis de los mejores navegadores en comparación directa

# Sub-headline
compare-index-privacy-utility-portability = Intimidad. Utilidad. Portabilidad.

# HTML page description
compare-index-a-great-internet-browser-should = Un gran navegador de Internet debe tener la funcionalidad que necesita, la portabilidad entre dispositivos y la privacidad que se merece.
compare-index-which-browser-is-best-at-keeping = ¿Qué navegador es mejor para mantener la confidencialidad?
compare-index-its-not-unreasonable-to-expect = No es descabellado esperar un alto nivel de protección de datos y privacidad de los productos que usamos habitualmente para conectarnos. Como mínimo, un navegador debe ofrecer alguna versión de "modo de navegación privada" que borre automáticamente su historial y el historial de búsqueda para que otros usuarios en la misma computadora no puedan acceder a él. En esta área, los siete navegadores comparados aquí obtienen puntos.
compare-index-its-not-unreasonable-to-expect-fallback = No es descabellado esperar un alto nivel de protección de datos y privacidad de los productos que usamos habitualmente para conectarnos. Como mínimo, un navegador debe ofrecer alguna versión de "modo de navegación privada" que borre automáticamente su historial y el historial de búsqueda para que otros usuarios en la misma computadora no puedan acceder a él. En esta área, los seis navegadores comparados aquí obtienen puntos.
compare-index-what-you-do-online-literally = Lo que haces en línea, literalmente, no debería ser asunto de nadie más.
compare-index-another-browser-feature-that = Otra característica del navegador que debería darse es la capacidad de evitar que los sitios web y las empresas rastreen sus datos de navegación y compras, incluso en el modo de navegación normal.
compare-index-another-browser-feature-fallback = Otra característica del navegador que debería darse es la capacidad de evitar que los sitios web y las empresas rastreen sus datos de navegación y compras, incluso en el modo de navegación normal. Pero ese no es el caso: de hecho, los únicos navegadores que bloquean las cookies de seguimiento de terceros de forma predeterminada son { -brand-name-firefox } y { -brand-name-safari } .
compare-index-using-a-browser-that-blocks = El uso de un navegador que bloquea rastreadores de terceros no solo es importante para la privacidad, también significa que se ejecuta mucho más rápido. La mayoría de los rastreadores son scripts que se ejecutan en segundo plano en varios sitios web. No puede verlos, pero puede sentir que ralentizan su navegador. A partir de la versión 67 de { -brand-name-firefox } , las huellas digitales y los criptomineros también están bloqueados. Si no está familiarizado con los criptomineros, aquí hay un ejemplo de cómo pueden afectarlo: tal vez haya experimentado que su computadora se calienta repentinamente o que la batería se agota más rápido de lo normal. A menudo, ese es el subproducto de los criptomineros que se arrastran por su dispositivo.
compare-index-what-has-your-browser-done = ¿Qué ha hecho tu navegador por ti últimamente?
compare-index-in-addition-to-privacy-protection = Además de la protección de la privacidad, que se realiza en gran medida en segundo plano del navegador, otro ingrediente clave para un navegador bien hecho es la interfaz de usuario y la funcionalidad reales. Casi los siete navegadores son iguales cuando se trata de navegación por pestañas, administración de marcadores, autocompletado, corrección de pruebas y extensiones. { -brand-name-firefox } , { -brand-name-edge } y { -brand-name-opera } también ofrecen una función de captura de pantalla rápida que resulta ser bastante útil y, definitivamente, es algo que nota que falta cuando cambia a un navegador sin ella.
compare-index-in-addition-to-privacy-protection-fallback = Además de la protección de la privacidad, que se realiza en gran medida en segundo plano del navegador, otro ingrediente clave para un navegador bien hecho es la interfaz de usuario y la funcionalidad reales. Casi los seis navegadores son iguales cuando se trata de navegación por pestañas, administración de marcadores, autocompletado, corrección de pruebas y extensiones. { -brand-name-firefox } , { -brand-name-edge } y { -brand-name-opera } también ofrecen una función de captura de pantalla rápida que resulta ser bastante útil y, definitivamente, es algo que nota que falta cuando cambia a un navegador sin ella.
compare-index-how-well-does-your-browser = ¿Qué tan bien funciona su navegador en todos sus dispositivos?
compare-index-almost-all-of-the-browsers = Casi todos los navegadores comparados aquí permiten la sincronización entre dispositivos móviles y de escritorio. Necesitará una cuenta para hacerlo, que puede usar para iniciar sesión en el navegador en todos los dispositivos y sincronizar cosas como contraseñas, historial de navegación, marcadores y configuraciones.
compare-index-conclusion = Conclusión:
compare-index-and-the-winner-is = Y el ganador es…
compare-index-find-out-how-firefox-chrome = Descubra cómo { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } y { -brand-name-ie } diferencian en términos de privacidad, utilidad y portabilidad.
compare-index-find-out-how-firefox-fallback = Descubra cómo { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } y { -brand-name-ie } diferencian en términos de privacidad, utilidad y portabilidad.
compare-index-looking-for-a-better-browser = Buscando un mejor navegador? Compararemos { -brand-name-firefox } con { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } y { -brand-name-ie } para ayudarlo a tomar una decisión.
compare-index-looking-for-a-better-fallback = Buscando un mejor navegador? Compararemos { -brand-name-firefox } con { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } y { -brand-name-ie } para ayudarlo a tomar una decisión.
compare-index-so-is-your-browser-the-best = Entonces, ¿es su navegador el mejor para lo que hace en línea? El navegador adecuado puede marcar una gran diferencia en su experiencia en la Web. Entonces, sin más preámbulos, comparemos { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } , { -brand-name-microsoft } { -brand-name-ie } y { -brand-name-edge } , y veamos cuál se adapta mejor a sus necesidades.
compare-index-so-is-your-browser-the-fallback = Entonces, ¿es su navegador el mejor para lo que hace en línea? El navegador adecuado puede marcar una gran diferencia en su experiencia en la Web. Entonces, sin más preámbulos, comparemos { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-microsoft } { -brand-name-ie } y { -brand-name-edge } , y veamos cuál se adapta mejor a sus necesidades.
compare-index-since-your-browser-is-your = Dado que su navegador es su puerta de entrada a Internet, la velocidad, la seguridad, la privacidad y la utilidad son primordiales. En los últimos años, { -brand-name-google } { -brand-name-chrome } ha sido el navegador elegido por muchos. Pero en un momento en que los anuncios en línea parecen seguirnos a todas partes y las filtraciones de datos son un elemento fijo en los titulares de las noticias, muchas personas están comenzando a exigir más privacidad y respeto de su navegador.
compare-index-browsers-have-come-a-long = Los navegadores han recorrido un largo camino desde que se introdujo { -brand-name-chrome } y se hizo cargo de la cuota de mercado. La mayoría de los navegadores modernos han cerrado la brecha en la portabilidad y la funcionalidad, y en algunas áreas, como la velocidad y la privacidad, han superado { -brand-name-chrome } . Aún así, determinar qué navegador es el adecuado para usted siempre dependerá de sus necesidades individuales y de lo que más valora mientras navega en línea.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } está respaldado por la organización sin fines de lucro { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } prioriza su privacidad, en todo lo que hacemos y hacemos. Creemos que tiene derecho a decidir cómo y con quién comparte su información personal. { -brand-name-firefox } recopila la menor cantidad de datos posible y nunca los vende. Los pocos datos que recopilamos solo se utilizan para mejorar los productos y las funciones. Sin secretos. Pero mucha transparencia y privacidad real.
compare-index-based-on-the-criteria-we-outlined = Según los criterios que describimos (privacidad, utilidad y portabilidad), en realidad solo hay un navegador que cumple con la marca, y ese es { -brand-name-firefox } . El área real de diferencia no es la funcionalidad, es la privacidad. { -brand-name-firefox } es el navegador más privado que no te encierra en un ecosistema. Úselo en cualquier sistema operativo, en todos sus dispositivos, y siéntase seguro cuando lo haga.
