# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome } : qual è il migliore?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Confrontiamo { -brand-name-mozilla } { -brand-name-firefox } con { -brand-name-google } { -brand-name-chrome } in termini di privacy, utilità e portabilità

# Main title.
compare-chrome-comparing-firefox-browser = Confronto tra { -brand-name-firefox-browser } e { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = In { -brand-name-firefox } abbiamo un numero enorme di utenti dedicati che apprezzano la nostra costante dedizione alla privacy online. Ad esempio, l'ultima versione di { -brand-name-firefox } include una funzione chiamata Enhanced Tracking Protection (ETP) che è attivata per impostazione predefinita per tutti gli utenti nel mondo. ETP blocca oltre 2.000 tracker, inclusi social tracker di aziende come { -brand-name-facebook } , { -brand-name-twitter } e LinkedIn. Ha anche una funzione integrata chiamata <a { $attrs }>{ -brand-name-firefox-monitor }</a> che ti avvisa automaticamente se la tua password è stata violata o deve essere aggiornata. Oltre a queste protezioni, la modalità di navigazione privata in { -brand-name-firefox } elimina automaticamente le informazioni di navigazione come cronologia e cookie, senza lasciare traccia al termine della sessione.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = In { -brand-name-firefox } abbiamo un numero enorme di utenti dedicati che apprezzano la nostra costante dedizione alla privacy online. Ad esempio, l'ultima versione di { -brand-name-firefox } include una funzione chiamata Enhanced Tracking Protection (ETP) che è attivata per impostazione predefinita per tutti gli utenti nel mondo. ETP blocca oltre 2.000 tracker, inclusi social tracker di aziende come { -brand-name-facebook } , { -brand-name-twitter } e LinkedIn. Ha anche una funzione integrata chiamata <a { $attrs }>{ -brand-name-firefox-monitor }</a> che ti avvisa automaticamente se la tua password è stata violata o deve essere aggiornata. Oltre a queste protezioni, la modalità di navigazione privata di { -brand-name-firefox } elimina automaticamente le informazioni di navigazione come cronologia e cookie, senza lasciare traccia al termine della sessione.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Abbiamo anche recentemente ribadito il nostro impegno per la privacy e la trasparenza riguardo ai dati degli utenti nella nostra più recente <a { $attrs }>Informativa sulla privacy</a> che afferma: &quot;In Mozilla, crediamo che la privacy sia fondamentale per un Internet sano&quot;.
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } è da tutti gli account un browser sicuro, con funzioni come { -brand-name-google } Navigazione sicura, che aiuta a proteggere gli utenti visualizzando un avviso impossibile da perdere quando tentano di navigare verso siti pericolosi o di scaricare file pericolosi.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = In definitiva, sta a te decidere se o dove tracciare il confine con la condivisione di cose come la cronologia delle ricerche e la cronologia degli acquisti. Ma se sei come la maggior parte delle persone, probabilmente hai cercato alcune cose su Internet che preferiresti mantenere private.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Passando rapidamente ad oggi, il panorama competitivo per i browser è cambiato con molte persone che iniziano a chiedersi cosa sta succedendo ai loro dati online come la cronologia di navigazione, le password e altre informazioni sensibili. Molto è cambiato dal 2008, quando { -brand-name-chrome } entrato in scena. In { -brand-name-firefox } , ci siamo impegnati a riprogettare la nostra interfaccia e fornire agli utenti un numero sempre crescente di miglioramenti in termini di privacy e prestazioni, oltre a numerosi strumenti utili per il browser.
compare-chrome-and-so-here-we-are-the-browser = E così eccoci qui, le guerre tra browser si stanno intensificando ancora una volta ed è tempo di rivalutare e confrontare { -brand-name-firefox-browser } vs { -brand-name-google } { -brand-name-chrome } .
compare-chrome-in-2008-google-introduced = Nel 2008, { -brand-name-google } introdotto { -brand-name-chrome } , il suo impatto come innovazione nella tecnologia dei browser è stato immediato. Era più veloce per il caricamento dei siti, occupava uno spazio minimo sullo schermo e offriva un'interfaccia utente innegabilmente semplice.
compare-chrome-in-fact-both-chrome-and-firefox = In effetti, sia { -brand-name-chrome } che { -brand-name-firefox } dispongono di una protezione rigorosa. Entrambi includono una cosa chiamata "sandboxing" che separa i processi del browser in modo che qualcosa come un sito Web dannoso non infetti altre parti del tuo laptop o altro dispositivo.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Sebbene { -brand-name-chrome } dimostri di essere un browser web sicuro, il suo record di privacy è discutibile. { -brand-name-google } raccoglie effettivamente una quantità inquietante di dati dai suoi utenti, tra cui posizione, cronologia delle ricerche e visite al sito. { -brand-name-google } sostiene la raccolta dei dati affermando che lo fa per migliorare i suoi servizi, ad esempio per aiutarti a trovare un maglione o un bar come quello che hai acquistato o visitato in precedenza. Tuttavia, altri potrebbero non essere d'accordo, sottolineando che { -brand-name-google } sta effettivamente raccogliendo una quantità di dati senza precedenti per i propri scopi di marketing. Affermano che stanno mantenendo le tue informazioni private dagli hacker, ma non è questo il punto. { -brand-name-google } gestisce la più grande rete pubblicitaria del mondo, grazie in gran parte ai dati che raccolgono dai propri utenti.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = In termini di funzionalità, sia { -brand-name-firefox } che { -brand-name-chrome } offrono un'ampia libreria di estensioni e plug-in, con il catalogo di { -brand-name-chrome } supera di gran lunga qualsiasi altro browser mentre si integra perfettamente con altri { -brand-name-google } servizi, come Gmail e { -brand-name-google } Documenti.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } ha anche una funzione di sincronizzazione per vedere le tue schede aperte e recenti, la cronologia di navigazione e i segnalibri su tutti i tuoi dispositivi.
compare-chrome-while-chrome-gets-the-nod = Mentre { -brand-name-chrome } ottiene il cenno del capo con componenti aggiuntivi ed estensioni, { -brand-name-firefox } ha un insieme ben curato di funzionalità integrate, come lo strumento di cattura dello schermo incredibilmente utile e la funzione della modalità di lettura che rimuove tutto dalla pagina tranne il testo dell'articolo che stai leggendo.
compare-chrome-although-not-as-extensive = Sebbene non sia così ampia come la libreria di componenti aggiuntivi di { -brand-name-chrome } , { -brand-name-firefox } , in quanto software open source con un numero enorme di collaboratori attivi, presenta anche un numero incredibile di estensioni utili.
compare-chrome-if-having-tons-of-open-tabs = Se ti piace avere tonnellate di schede aperte, dipende davvero dalle tue preferenze dell'interfaccia utente. { -brand-name-firefox } presenta uno scorrimento orizzontale su tutte le schede aperte anziché rimpicciolirle sempre di più con ogni nuova scheda. { -brand-name-google } { -brand-name-chrome } preferisce ridurli in modo che sia visibile solo la favicon. L'unico problema è quando hai più schede aperte dallo stesso sito Web, quindi vedi la stessa favicon su tutte le schede.
compare-chrome-almost-needless-to-say-versions = Quasi inutile dire che le versioni di { -brand-name-firefox } e { -brand-name-chrome } sono disponibili per i sistemi operativi desktop e mobili più diffusi ( { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ).
compare-chrome-both-chrome-and-firefox-also = Sia { -brand-name-chrome } che { -brand-name-firefox } ti consentono anche di sincronizzare elementi come password, segnalibri e schede aperte su tutti i tuoi dispositivi. Se hai un account { -brand-name-firefox } , puoi inviare manualmente una scheda aperta sul desktop al tuo dispositivo mobile o viceversa. Con { -brand-name-chrome } , viene eseguito automaticamente se hai scelto tale impostazione nelle tue preferenze. Non dover inviare manualmente la scheda da un dispositivo all'altro è comodo quando vuoi fare qualcosa come continuare a leggere un articolo che non hai finito prima. Ma a volte la sincronizzazione automatica potrebbe non essere l'ideale se esiste la possibilità che più utenti stiano navigando mentre sono connessi al tuo account { -brand-name-google } .

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Riteniamo giusto dire che { -brand-name-firefox } e { -brand-name-chrome } sono davvero testa a testa in termini di portabilità e utilità, con { -brand-name-chrome } un leggero vantaggio in termini di utilità a causa della sua vasta libreria di estensioni e funzionalità aggiuntive. Ma in termini di privacy, { -brand-name-firefox } vince con il nostro impegno a preservare i dati online dei nostri utenti e a fornire servizi integrati gratuiti come i gestori di password che ti avvisano anche in caso di violazione dei dati che coinvolge le tue credenziali.
compare-chrome-as-for-customization-our = Per quanto riguarda la personalizzazione, i nostri fan ti diranno che una delle cose che amano di più del nostro browser è la sua capacità di consentirti di spostare e organizzare la maggior parte degli elementi dell'interfaccia utente per soddisfare al meglio le tue esigenze. { -brand-name-chrome } ti consente di nascondere alcuni elementi dell'interfaccia utente ma non c'è molto spazio per spostare le cose in base alle tue preferenze. Tuttavia, va notato che sia { -brand-name-chrome } che { -brand-name-firefox } semplificano la modifica dell'aspetto e del tema del browser.
compare-chrome-for-practical-purposes-theres = Per motivi pratici, ovviamente non c'è davvero nulla che ti impedisca di utilizzare entrambi i browser, { -brand-name-firefox } per quei momenti della vita in cui la privacy è davvero importante e { -brand-name-chrome } se sei ancora investito nell'ecosistema { -brand-name-google } . Tuttavia, con il numero crescente di incursioni nei nostri dati personali, { -brand-name-firefox } potrebbe rivelarsi la scelta giusta a lungo termine per quelli di noi che apprezzano la protezione della nostra privacy personale online.
