# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } vs. { -brand-name-microsoft } { -brand-name-edge } : qual è il browser migliore per te?

# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Confronta { -brand-name-microsoft } { -brand-name-edge } con { -brand-name-firefox-browser } per scoprire qual è il browser migliore per te.

# Main title.
compare-edge-comparing-firefox-browser-with = Confronto tra { -brand-name-firefox-browser } e { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = Con { -brand-name-windows } 10, { -brand-name-microsoft } introdotto il suo { -brand-name-edge } browser per competere con { -brand-name-firefox } e { -brand-name-chrome } rendendolo il browser predefinito preinstallato su milioni di PC venduti. Anche così, gli utenti sono stati lenti ad adottarlo e { -brand-name-microsoft } alla fine hanno annunciato l'intenzione di rilanciare { -brand-name-edge } come browser basato su { -brand-name-chromium } ( { -brand-name-chromium } ovviamente essendo il progetto di browser Open Source di { -brand-name-google } ).
compare-edge-here-well-compare-our-firefox = Qui confronteremo il nostro { -brand-name-firefox-browser } con il { -brand-name-chromium } { -brand-name-microsoft } { -brand-name-edge } in termini di privacy, utilità e portabilità, per aiutarti a comprendere meglio quale browser si adatta meglio alle tue esigenze e preferenze.

# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } è integrato nella piattaforma { -brand-name-windows } 10 e viene eseguito in un ambiente sandbox, il che significa che isola i programmi e impedisce ai programmi dannosi di spiare il tuo computer. Ha uno SmartScreen integrato che analizza la reputazione dei siti visitati e blocca i siti sospetti. Per migliorare la privacy, { -brand-name-edge } consente di utilizzare dati biometrici o un PIN con { -brand-name-edge } Hello invece delle password per l'autenticazione online.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = In { -brand-name-firefox } , siamo orgogliosi di proteggere la sicurezza e la privacy dei nostri utenti. La nostra <a { $attrs }>politica sulla privacy</a> è trasparente e in un linguaggio semplice. In realtà ci siamo impegnati molto per assicurarci che fosse semplice e di facile lettura. Con la protezione antitracciamento avanzata ora attiva per impostazione predefinita, blocchiamo più di 2000 tracker automaticamente. I tracker sono quei piccoli pezzi di codice che cercano di mettere insieme ciò che stai facendo su più siti Internet per costruire un'immagine composita e dettagliata di chi sei, compromettendo la tua privacy solo per indirizzare annunci migliori.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = In { -brand-name-firefox } , le nostre <a { $attrs }>norme sulla privacy</a> sono trasparenti e in un linguaggio semplice. In realtà ci siamo impegnati molto per assicurarci che fosse semplice e di facile lettura. Siamo orgogliosi di proteggere la sicurezza e la privacy dei nostri utenti. Con la protezione antitracciamento avanzata ora attiva per impostazione predefinita, blocchiamo più di 2000 tracker automaticamente. I tracker sono quei piccoli pezzi di codice che cercano di mettere insieme ciò che stai facendo su più siti Internet per costruire un'immagine composita e dettagliata di chi sei, compromettendo la tua privacy solo per indirizzare annunci migliori.

# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Le tue <a { $attrs }>protezioni sulla privacy</a> ti mostrano i tracker e i cookie che le pagine hanno tentato di lasciare e quanti { -brand-name-firefox } hanno bloccato per te.

# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = In { -brand-name-firefox } , la modalità di navigazione privata cancella automaticamente le informazioni di navigazione come password, cookie e cronologia, senza lasciare traccia dopo aver chiuso la sessione. { -brand-name-edge } d'altra parte, registra effettivamente la cronologia di navigazione nella sua modalità privata (chiamata "InPrivate") ed è un'attività relativamente facile per qualcuno ricostruire la tua cronologia di navigazione completa, indipendentemente dal fatto che la tua navigazione sia stata eseguita in modalità normale o InPrivate.
compare-edge-both-browsers-are-relatively = Entrambi i browser sono relativamente uguali in termini di crittografia dei dati. Tuttavia, se la privacy e la trasparenza online sono importanti per te, { -brand-name-firefox } è chiaramente una scelta migliore qui.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } è un browser veloce e open source, il che significa che gli utenti possono personalizzare la loro esperienza di navigazione in ogni modo possibile. { -brand-name-firefox } consente inoltre all'utente occasionale diversi modi per personalizzare l'interfaccia utente con l'applicazione di diversi temi e configurazioni della barra degli strumenti. Poiché il nostro browser è sempre stato open source, abbiamo un ampio seguito di sviluppatori devoti che hanno creato una vasta libreria di componenti aggiuntivi ed estensioni del browser.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } è un browser veloce e open source, il che significa che gli utenti possono personalizzare la loro esperienza di navigazione in ogni modo possibile. { -brand-name-firefox } consente inoltre all'utente occasionale diversi modi per personalizzare l'interfaccia utente con l'applicazione di diversi temi e configurazioni della barra degli strumenti. Poiché il nostro browser è sempre stato open source, abbiamo un ampio seguito di sviluppatori devoti che hanno creato una vasta libreria di componenti aggiuntivi ed estensioni del browser.
compare-edge-since-edge-has-moved-to-the = Poiché { -brand-name-edge } è passato alla piattaforma a uso intensivo del processore { -brand-name-chromium } , puoi aspettarti che venga eseguita un po 'più lentamente, soprattutto se hai più programmi in esecuzione contemporaneamente. Tuttavia, con la piattaforma { -brand-name-chromium } arriva un'enorme libreria di estensioni nonché un discreto livello di personalizzazione dell'interfaccia utente che { -brand-name-edge } non aveva prima del suo passaggio a { -brand-name-chromium } .
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } ha alcune interessanti funzionalità dell'interfaccia utente, come le anteprime delle schede che possono semplificare la ricerca delle schede aperte corrette se ne hai molte aperte. Un'altra utile funzionalità relativa alle schede ti consente di mettere da parte tutte le schede attive che non stai utilizzando ma che non vuoi chiudere.

# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } presenta un'interfaccia a schede a scorrimento, che mantiene visibili le informazioni delle schede e le scorre orizzontalmente invece di ridurle alle dimensioni della favicon. Inoltre, ogni volta che apri una nuova scheda, la nostra funzione <a { $attrs }>{ -brand-name-pocket }</a> suggerisce articoli e contenuti pertinenti per te. Inoltre, con { -brand-name-pocket } , puoi anche salvare articoli, video e altri contenuti con un clic, per leggerli in un secondo momento.
compare-edge-firefox-and-edge-both-offer = { -brand-name-firefox } e { -brand-name-edge } offrono entrambi eccellenti modalità di lettura. Con { -brand-name-firefox } , tocca semplicemente la piccola icona nella barra di ricerca e il browser rimuove tutti gli elementi non necessari e ti presenta un articolo dall'aspetto pulito. In { -brand-name-edge } è sufficiente toccare l'icona del piccolo libro e il browser per ottenere un'interfaccia utente pulita e di facile lettura.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } e { -brand-name-edge } offrono entrambi eccellenti modalità di lettura. Con { -brand-name-firefox } è sufficiente toccare la piccola icona nella barra di ricerca e il browser rimuove tutti gli elementi non necessari e ti presenta un articolo dall'aspetto pulito. In { -brand-name-edge } è sufficiente toccare l'icona del piccolo libro e il browser per ottenere un'interfaccia utente pulita e di facile lettura.

# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } include anche molte utili funzioni integrate per impostazione predefinita come la <a { $attrs }>protezione dal monitoraggio avanzata</a> , uno strumento di screenshot integrato, l'invio di file di grandi dimensioni e altro ancora.

# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Fuori dal cancello, { -brand-name-firefox } ha più funzioni e integrazioni integrate nel browser e prontamente disponibili per il download. E mentre entrambi i browser hanno un altissimo numero di add-on ed estensioni disponibili, { -brand-name-edge } 's compatibilità con { -brand-name-google } ' s { -brand-name-chromium } piattaforma gli dà il vantaggio in termini puramente numerici.

compare-edge-with-internet-explorer-microsoft = Con { -brand-name-ie } , { -brand-name-microsoft } imparato dalla sua mancanza di disponibilità su tutte le piattaforme e reso { -brand-name-edge } prontamente disponibile su { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } , { -brand-name-mac } e presto { -brand-name-linux } .
compare-edge-with-internet-explorer-fallback = Con { -brand-name-ie } , { -brand-name-microsoft } imparato dalla sua mancanza di disponibilità tra le piattaforme e ha reso { -brand-name-edge } disponibile per { -brand-name-mac } e { -brand-name-android } . Il software è ora immediatamente disponibile su { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } e { -brand-name-mac } .

# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } è disponibile su { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } , { -brand-name-mac } e { -brand-name-linux } da anni. E come ti aspetteresti con qualsiasi browser moderno, { -brand-name-firefox } ti consente di accedere con un <a { $attrs }>account gratuito</a> e di sincronizzare dati come password, cronologia di navigazione, segnalibri e schede aperte tra computer, tablet e telefono. Ti consente anche di sincronizzare tra le piattaforme.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } ti consente inoltre di collegare il tuo account { -brand-name-microsoft } associato e di accedere per sincronizzare i preferiti, la cronologia, le password e altro tra il computer e i dispositivi { -brand-name-ios } o { -brand-name-android } .
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } ti consente anche di collegare il tuo account { -brand-name-microsoft } associato e di accedere per sincronizzare preferiti, cronologia, password e altro tra il computer e i dispositivi { -brand-name-ios } o { -brand-name-android } , sebbene alcuni { -brand-name-android } tablet non lo siano attualmente supportato.

# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Oltre a assorbire molta potenza di calcolo, { -brand-name-edge } esecuzione su { -brand-name-chromium } ha risposto alle esigenze di funzionalità e caratteristiche di molti utenti. Ma c'è ancora molto da tenere in considerazione in termini di protezione della privacy del browser. La nostra valutazione è che { -brand-name-firefox } sia ancora una scelta migliore da utilizzare per la maggior parte delle persone nella vita quotidiana, basata non solo sulla funzionalità ma, soprattutto, sulla nostra trasparenza nel modo in cui raccogliamo i dati degli utenti, cosa raccogliamo esattamente e cosa ne facciamo esso. Poiché la nostra società madre è <a { $attrs }>{ -brand-name-mozilla }</a> , un'organizzazione senza scopo di lucro dedicata alla privacy e alla libertà di Internet, abbiamo semplicemente un diverso insieme di priorità quando si tratta dei dati degli utenti.
compare-edge-the-bottom-line-is-that-while = La conclusione è che, sebbene suggeriamo di utilizzare { -brand-name-firefox } , il browser migliore per te alla fine sarà quello che si adatta alle tue esigenze individuali con supporto di estensioni, personalizzazione degli strumenti di navigazione, velocità, privacy e sicurezza.
