# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Sette dei migliori browser a confronto diretto
compare-index-six-of-the-best-browsers-fallback = Sei dei migliori browser a confronto diretto

# Sub-headline
compare-index-privacy-utility-portability = Privacy. Utilità. Portabilità.

# HTML page description
compare-index-a-great-internet-browser-should = Un ottimo browser Internet dovrebbe avere le funzionalità di cui hai bisogno, la portabilità su tutti i dispositivi e la privacy che meriti.
compare-index-which-browser-is-best-at-keeping = Quale browser è il migliore per mantenere le cose riservate?
compare-index-its-not-unreasonable-to-expect = Non è irragionevole aspettarsi un livello elevato di protezione dei dati e privacy dai prodotti che utilizziamo regolarmente per essere online. Come minimo, un browser dovrebbe offrire una versione della "modalità di navigazione privata" che cancella automaticamente la cronologia e la cronologia delle ricerche in modo che altri utenti sullo stesso computer non possano accedervi. In quest'area, tutti e sette i browser qui confrontati ottengono punti.
compare-index-its-not-unreasonable-to-expect-fallback = Non è irragionevole aspettarsi un livello elevato di protezione dei dati e privacy dai prodotti che utilizziamo regolarmente per essere online. Come minimo, un browser dovrebbe offrire una versione della "modalità di navigazione privata" che cancella automaticamente la cronologia e la cronologia delle ricerche in modo che altri utenti sullo stesso computer non possano accedervi. In quest'area, tutti e sei i browser qui confrontati ottengono punti.
compare-index-what-you-do-online-literally = Quello che fai letteralmente online non dovrebbe essere affare di nessun altro.
compare-index-another-browser-feature-that = Un'altra caratteristica del browser che dovrebbe essere data è la capacità di impedire a siti Web e aziende di tracciare i dati di navigazione e di acquisto, anche in modalità di navigazione normale.
compare-index-another-browser-feature-fallback = Un'altra caratteristica del browser che dovrebbe essere data è la capacità di impedire a siti Web e aziende di tracciare i dati di navigazione e di acquisto, anche in modalità di navigazione normale. Ma in realtà non è così: infatti, gli unici browser che bloccano i cookie di tracciamento di terze parti per impostazione predefinita sono { -brand-name-firefox } e { -brand-name-safari } .
compare-index-using-a-browser-that-blocks = L'uso di un browser che blocca i tracker di terze parti non è importante solo per la privacy, ma di solito significa anche che funziona molto più velocemente. La maggior parte dei tracker sono solo script che vengono eseguiti in background su numerosi siti Web. Non puoi vederli, ma puoi sentirli rallentare il tuo browser. A partire dalla versione 67 di { -brand-name-firefox } , anche il fingerprinting e i cryptominer sono bloccati. Se non hai familiarità con i cryptominer, ecco un esempio di come possono influenzarti: forse hai notato che il tuo computer si surriscalda improvvisamente o la batteria si scarica più velocemente del normale. Questo è spesso il sottoprodotto dei cryptominer che si insinuano sul tuo dispositivo.
compare-index-what-has-your-browser-done = Cosa ha fatto il tuo browser per te ultimamente?
compare-index-in-addition-to-privacy-protection = Oltre alla protezione della privacy, che avviene in gran parte in background del browser, un altro ingrediente chiave per un browser ben fatto è l'interfaccia utente e le funzionalità effettive. Quasi tutti e sette i browser sono uguali quando si tratta di navigazione a schede, gestione dei segnalibri, completamento automatico, correzione di bozze ed estensioni. { -brand-name-firefox } , { -brand-name-edge } e { -brand-name-opera } offrono anche una funzione di screenshot veloce che si rivela molto utile ed è sicuramente qualcosa che noti che manca quando passi a un browser senza di essa.
compare-index-in-addition-to-privacy-protection-fallback = Oltre alla protezione della privacy, che avviene in gran parte in background del browser, un altro ingrediente chiave per un browser ben fatto è l'interfaccia utente e le funzionalità effettive. Quasi tutti e sei i browser sono uguali quando si tratta di navigazione a schede, gestione dei segnalibri, completamento automatico, correzione di bozze ed estensioni. { -brand-name-firefox } , { -brand-name-edge } e { -brand-name-opera } offrono anche una funzione di screenshot veloce che si rivela molto utile ed è sicuramente qualcosa che noti che manca quando passi a un browser senza di essa.
compare-index-how-well-does-your-browser = Quanto bene funziona il tuo browser sui tuoi dispositivi?
compare-index-almost-all-of-the-browsers = Quasi tutti i browser qui confrontati consentono la sincronizzazione tra desktop e dispositivi mobili. Avrai bisogno di un account per farlo, che puoi usare per accedere al browser su tutti i dispositivi e sincronizzare cose come password, cronologia di navigazione, segnalibri e impostazioni.
compare-index-conclusion = Conclusione:
compare-index-and-the-winner-is = E il vincitore è…
compare-index-find-out-how-firefox-chrome = Scopri come { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } e { -brand-name-ie } differiscono in termini di privacy, utilità e portabilità.
compare-index-find-out-how-firefox-fallback = Scopri come { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } e { -brand-name-ie } differiscono in termini di privacy, utilità e portabilità.
compare-index-looking-for-a-better-browser = Cerchi un browser migliore? Metteremo a confronto { -brand-name-firefox } con { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } e { -brand-name-ie } per aiutarti a prendere la tua decisione.
compare-index-looking-for-a-better-fallback = Cerchi un browser migliore? Metteremo a confronto { -brand-name-firefox } con { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } e { -brand-name-ie } per aiutarti a prendere la tua decisione.
compare-index-so-is-your-browser-the-best = Quindi il tuo browser è il migliore per quello che fai online? Il browser giusto può fare una grande differenza nella tua esperienza sul web. Quindi, senza ulteriori indugi, confrontiamo { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } , { -brand-name-microsoft } { -brand-name-ie } e { -brand-name-edge } e vediamo quale si adatta meglio alle tue esigenze.
compare-index-so-is-your-browser-the-fallback = Quindi il tuo browser è il migliore per quello che fai online? Il browser giusto può fare una grande differenza nella tua esperienza sul web. Quindi, senza ulteriori indugi, confrontiamo { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-microsoft } { -brand-name-ie } e { -brand-name-edge } e vediamo quale si adatta meglio alle tue esigenze.
compare-index-since-your-browser-is-your = Poiché il tuo browser è la tua porta d'accesso a Internet, velocità, sicurezza, privacy e utilità sono di primaria importanza. Negli ultimi anni, { -brand-name-google } { -brand-name-chrome } è stato il browser preferito da molti. Ma in un momento in cui gli annunci online sembrano seguirci ovunque e le violazioni dei dati sono un appuntamento fisso nei titoli delle notizie, molte persone stanno iniziando a richiedere maggiore privacy e rispetto dal proprio browser.
compare-index-the-first-thing-to-point-out = La prima cosa da sottolineare sulla portabilità è che non tutti i browser funzionano su tutti i sistemi operativi. Mentre { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-brave } e { -brand-name-opera } funzionano su tutti i principali sistemi e sono facili da installare, { -brand-name-ie } e { -brand-name-safari } funzionano solo su { -brand-name-microsoft } e sui sistemi Apple. La versione mobile di { -brand-name-safari } è preinstallata sui dispositivi mobili Apple e la maggior parte dei dispositivi { -brand-name-android } dotata di un browser preinstallato modificato dal produttore per il dispositivo. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-brave } , { -brand-name-edge } e { -brand-name-opera } possono essere facilmente installati e persino utilizzati fianco a fianco.
compare-index-the-first-thing-to-point-fallback = La prima cosa da sottolineare sulla portabilità è che non tutti i browser funzionano su tutti i sistemi operativi. Mentre { -brand-name-firefox } , { -brand-name-chrome } e { -brand-name-opera } funzionano su tutti i principali sistemi e sono facili da installare, { -brand-name-ie } , { -brand-name-edge } e { -brand-name-safari } funzionano solo su { -brand-name-microsoft } e sui sistemi Apple. La versione mobile di { -brand-name-safari } è preinstallata sui dispositivi mobili Apple e la maggior parte dei dispositivi { -brand-name-android } dotata di un browser preinstallato modificato dal produttore per il dispositivo. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } e { -brand-name-opera } possono essere facilmente installati e persino utilizzati fianco a fianco.
compare-index-browsers-have-come-a-long = I browser hanno fatto molta strada da quando { -brand-name-chrome } stato introdotto e ha assunto la quota di mercato. La maggior parte dei browser moderni ha colmato il divario in termini di portabilità e funzionalità e in alcune aree, come la velocità e la privacy, ha effettivamente superato { -brand-name-chrome } . Tuttavia, determinare quale browser è giusto per te dipenderà sempre dalle tue esigenze individuali e da ciò che apprezzi di più mentre navighi online.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } è sostenuto dall'organizzazione no profit { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } mette la tua privacy al primo posto, in tutto ciò che facciamo e facciamo. Crediamo che tu abbia il diritto di decidere come e con chi condividere le tue informazioni personali. { -brand-name-firefox } raccoglie il minor numero di dati possibile e non li vende mai. I pochi dati che raccogliamo vengono utilizzati solo per migliorare i prodotti e le funzionalità. Nessun segreto. Ma molta trasparenza e vera privacy.
compare-index-based-on-the-criteria-we-outlined = In base ai criteri che abbiamo delineato - privacy, utilità e portabilità - c'è davvero un solo browser che soddisfa il marchio, ed è { -brand-name-firefox } . La vera area di differenza non è nella funzionalità, è la privacy. { -brand-name-firefox } è il browser più privato che non ti blocca in un ecosistema. Usalo su qualsiasi sistema operativo, su tutti i tuoi dispositivi e sentiti al sicuro quando lo fai.
