# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } बनाम { -brand-name-chrome } : कौन सा बेहतर है?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = हम गोपनीयता, उपयोगिता और पोर्टेबिलिटी के मामले में { -brand-name-mozilla } { -brand-name-firefox } { -brand-name-google } { -brand-name-chrome } से तुलना करते हैं


# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = { -brand-name-firefox } , हमारे पास समर्पित उपयोगकर्ताओं की एक बड़ी संख्या है जो ऑनलाइन गोपनीयता के लिए हमारे दृढ़ समर्पण की सराहना करते हैं। उदाहरण के लिए, { -brand-name-firefox } के नवीनतम संस्करण में एन्हांस्ड ट्रैकिंग प्रोटेक्शन (ईटीपी) नामक एक सुविधा शामिल है, जो दुनिया भर में सभी उपयोगकर्ताओं के लिए डिफ़ॉल्ट रूप से चालू है। 2,000 ट्रैकरों पर ईटीपी ब्लॉक करता है, जिसमें { -brand-name-facebook } , { -brand-name-twitter } , और लिंक्डइन जैसी कंपनियों से सामाजिक ट्रैकर शामिल हैं। इसमें एक एकीकृत सुविधा भी है जिसका नाम <a { $attrs }>{ -brand-name-firefox-monitor }</a> जो स्वचालित रूप से आपको सूचित करता है कि आपका पासवर्ड भंग हो गया है या उसे अपडेट करने की आवश्यकता है। इन सुरक्षाओं के अलावा, { -brand-name-firefox } में निजी ब्राउज़िंग मोड स्वचालित रूप से आपकी ब्राउज़िंग जानकारी को हटा देता है जैसे कि इतिहास और कुकीज़, अपना सत्र समाप्त करने के बाद कोई निशान नहीं छोड़ते।

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = { -brand-name-firefox } , हमारे पास समर्पित उपयोगकर्ताओं की एक बड़ी संख्या है जो ऑनलाइन गोपनीयता के लिए हमारे दृढ़ समर्पण की सराहना करते हैं। उदाहरण के लिए, { -brand-name-firefox } के नवीनतम संस्करण में एन्हांस्ड ट्रैकिंग प्रोटेक्शन (ईटीपी) नामक एक सुविधा शामिल है, जो दुनिया भर में सभी उपयोगकर्ताओं के लिए डिफ़ॉल्ट रूप से चालू है। 2,000 ट्रैकरों पर ईटीपी ब्लॉक करता है, जिसमें { -brand-name-facebook } , { -brand-name-twitter } , और लिंक्डइन जैसी कंपनियों से सामाजिक ट्रैकर शामिल हैं। इसमें एक एकीकृत सुविधा भी है जिसका नाम <a { $attrs }>{ -brand-name-firefox-monitor }</a> जो स्वचालित रूप से आपको सूचित करता है कि आपका पासवर्ड भंग हो गया है या उसे अपडेट करने की आवश्यकता है। इन सुरक्षा के अलावा, { -brand-name-firefox } का निजी ब्राउजिंग मोड आपके ब्राउज़िंग जानकारी जैसे इतिहास और कुकीज़ को स्वचालित रूप से हटा देता है, जिससे आपका सत्र समाप्त होने के बाद कोई निशान नहीं रह जाता है।

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = हमने हाल ही की <a { $attrs }>गोपनीयता सूचना</a> में उपयोगकर्ता डेटा के बारे में हमारी गोपनीयता और पारदर्शिता के प्रति हमारी प्रतिबद्धता को भी बहाल किया है, जिसमें कहा गया है, &quot;मोज़िला में, हम मानते हैं कि गोपनीयता एक स्वस्थ इंटरनेट के लिए मौलिक है।&quot;
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } सभी खातों द्वारा एक सुरक्षित ब्राउज़र है, जिसमें { -brand-name-google } सेफ ब्राउजिंग जैसी विशेषताएं हैं, जो खतरनाक साइटों को नेविगेट करने या खतरनाक फ़ाइलों को डाउनलोड करने का प्रयास करने पर उपयोगकर्ताओं को एक असंभव-टू-मिस चेतावनी प्रदर्शित करने में मदद करती हैं।

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = अंतत: यह तय करना है कि आपके खोज इतिहास और खरीदारी इतिहास जैसी चीजों को साझा करने के साथ रेखा खींचना है या नहीं। लेकिन अगर आप ज्यादातर लोगों की तरह कुछ भी कर रहे हैं, तो आप शायद इंटरनेट पर कुछ ऐसी चीजों की तलाश कर रहे हैं जिन्हें आप निजी तौर पर रखना चाहते हैं।

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = आज के लिए फास्ट-फॉरवर्ड, ब्राउज़रों के लिए प्रतिस्पर्धी परिदृश्य कई लोगों के साथ बदल गया है, जो सवाल करने लगे हैं कि उनके ऑनलाइन डेटा का क्या हो रहा है जैसे ब्राउज़िंग इतिहास, पासवर्ड और अन्य संवेदनशील जानकारी। 2008 के बाद से बहुत कुछ बदल गया जब { -brand-name-chrome } दृश्य पर आया। { -brand-name-firefox } , हम सिर नीचे कर रहे हैं, हमारे इंटरफ़ेस को फिर से डिज़ाइन करने और उपयोगकर्ताओं को गोपनीयता और प्रदर्शन बढ़ाने के साथ-साथ बहुत सारे आसान ब्राउज़र टूल प्रदान करने के लिए काम कर रहे हैं।
compare-chrome-and-so-here-we-are-the-browser = और इसलिए यहां हम हैं, ब्राउज़र-वार एक बार फिर से बढ़ रहे हैं और यह { -brand-name-firefox-browser } बनाम { -brand-name-google } { -brand-name-chrome } का पुनर्मूल्यांकन और तुलना करने का समय है।
compare-chrome-in-fact-both-chrome-and-firefox = वास्तव में, दोनों { -brand-name-chrome } और { -brand-name-firefox } में कठोर सुरक्षा है। दोनों में "सैंडबॉक्सिंग" नामक एक चीज शामिल है, जो ब्राउज़र की प्रक्रियाओं को अलग करती है, इसलिए हानिकारक वेबसाइट जैसी कोई चीज आपके लैपटॉप या अन्य डिवाइस के अन्य हिस्सों को संक्रमित नहीं करती है।

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = जबकि { -brand-name-chrome } एक सुरक्षित वेब ब्राउज़र साबित होता है, लेकिन इसका गोपनीयता रिकॉर्ड संदिग्ध है। { -brand-name-google } वास्तव में अपने उपयोगकर्ताओं से स्थान, खोज इतिहास और साइट विज़िट सहित बड़ी मात्रा में डेटा एकत्र करता है। { -brand-name-google } डेटा कलेक्शन के लिए अपना मामला यह कहते हुए बनाता है कि वह अपनी सेवाओं को बेहतर बनाने के लिए ऐसा कर रहा है - जैसे कि आप पहले से खरीदे गए या गए किसी स्वेटर या कॉफी शॉप को खोजने में मदद करते हैं। हालांकि, अन्य लोग असहमत हो सकते हैं, जिससे यह संकेत मिलता है कि { -brand-name-google } वास्तव में अपने स्वयं के विपणन उद्देश्यों के लिए अभूतपूर्व मात्रा में डेटा एकत्र कर रहा है। वे कहते हैं कि वे आपकी जानकारी को हैकर्स से निजी रख रहे हैं, लेकिन वह इस बिंदु के बगल में है। { -brand-name-google } स्वयं दुनिया का सबसे बड़ा विज्ञापन नेटवर्क चलाता है, बड़े हिस्से में धन्यवाद कि वे अपने उपयोगकर्ताओं से फसल लेते हैं।

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = सुविधाओं के संदर्भ में, दोनों { -brand-name-firefox } और { -brand-name-chrome } एक्सटेंशन और प्लग-इन की एक बड़ी लाइब्रेरी की पेशकश करते हैं, { -brand-name-chrome } के कैटलॉग के साथ किसी भी अन्य ब्राउज़र को काफी हद तक अलग कर देते हैं जबकि अच्छी तरह से अन्य { -brand-name-google } सेवाओं के साथ एकीकरण करते हैं, जैसे जीमेल और { -brand-name-google } डॉक्स।
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } आपके खुले और हाल के टैब, ब्राउज़िंग इतिहास और आपके सभी उपकरणों के बुकमार्क देखने के लिए एक सिंक सुविधा है।
compare-chrome-while-chrome-gets-the-nod = जबकि { -brand-name-chrome } को ऐड-ऑन और एक्सटेंशन के साथ नोड मिलता है, { -brand-name-firefox } में बिल्ट-इन फीचर्स का एक अच्छा क्यूरेट सेट है, जैसे कि अविश्वसनीय रूप से आसान स्क्रीन कैप्चर टूल, और रीडिंग मोड फीचर जो पेज को छोड़कर सभी चीजों को स्ट्रिप्स से दूर रखता है। लेख आप पढ़ रहे हैं से पाठ।
compare-chrome-although-not-as-extensive = हालाँकि यह { -brand-name-chrome } के ऐड-ऑन लाइब्रेरी, { -brand-name-firefox } रूप में व्यापक नहीं है, क्योंकि एक बड़ी संख्या में सक्रिय योगदानकर्ताओं के साथ ओपन-सोर्स सॉफ़्टवेयर भी एक अविश्वसनीय संख्या में उपयोगी एक्सटेंशन हैं।
compare-chrome-if-having-tons-of-open-tabs = यदि आपके पास खुले टैब के टन आपकी चीज है, तो यह वास्तव में आपके यूआई वरीयता के लिए नीचे आता है। { -brand-name-firefox } प्रत्येक नए के साथ छोटे और छोटे को सिकोड़ने के बजाय अपने सभी खुले टैब पर एक क्षैतिज स्क्रॉल करें। { -brand-name-google } { -brand-name-chrome } उन्हें नीचे हटना पसंद करता है, इसलिए सिर्फ फेविकॉन दिखाई देता है। इसके साथ एकमात्र समस्या यह है कि जब आपके पास एक ही वेबसाइट से कई टैब खुले होते हैं, तो आप अपने टैब में एक ही फ़ेविकॉन देखते हैं।
compare-chrome-almost-needless-to-say-versions = कहने की जरूरत नहीं है, दोनों { -brand-name-firefox } और { -brand-name-chrome } संस्करण सबसे लोकप्रिय डेस्कटॉप और मोबाइल ऑपरेटिंग सिस्टम ( { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ) के लिए उपलब्ध हैं।
compare-chrome-both-chrome-and-firefox-also = दोनों { -brand-name-chrome } और { -brand-name-firefox } भी आपको पासवर्ड, बुकमार्क और खुले टैब जैसी चीजों को सिंक करने की अनुमति देते हैं। यदि आपके पास { -brand-name-firefox } खाता है, तो आप अपने डेस्कटॉप पर अपने मोबाइल डिवाइस पर एक खुला टैब मैन्युअल रूप से भेज सकते हैं या इसके विपरीत। { -brand-name-chrome } , यह स्वचालित रूप से किया जाता है यदि आपने अपनी प्राथमिकताओं में उस सेटिंग को चुना है। जब आप कुछ करना चाहते हैं तो एक डिवाइस से दूसरे में टैब को मैन्युअल रूप से भेजने के लिए सुविधाजनक नहीं है जब आप एक लेख पढ़ना जारी रखते हैं, जिसे आपने पहले खत्म नहीं किया था। लेकिन कई बार ऐसा हो सकता है जहां स्वत: सिंक्रनाइज़ेशन आदर्श नहीं हो सकता है यदि एक मौका है जब कई उपयोगकर्ता आपके { -brand-name-google } खाते में हस्ताक्षर करते समय ब्राउज़ कर रहे हैं।

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = हमें लगता है कि यह कहना उचित है कि { -brand-name-firefox } और { -brand-name-chrome } पोर्टेबिलिटी और यूटिलिटी के मामले में वास्तव में गर्दन और गर्दन हैं, { -brand-name-chrome } उपयोगिता में थोड़ी बढ़त होने के कारण इसकी विशाल लाइब्रेरी और एक्सटेंशन की सुविधाओं के कारण। लेकिन गोपनीयता के संदर्भ में, { -brand-name-firefox } दिन हमारे उपयोगकर्ताओं के ऑनलाइन डेटा को संरक्षित करने और पासवर्ड प्रबंधकों जैसी मुफ्त बेक्ड-इन सेवाएं प्रदान करने की हमारी प्रतिबद्धता के साथ जीतता है, अगर आपके क्रेडेंशियल्स को शामिल करने वाले डेटा उल्लंघन होने पर भी आपको सचेत करता है।
compare-chrome-as-for-customization-our = अनुकूलन के लिए, हमारे प्रशंसक आपको उन चीजों में से एक बताएंगे जो वे हमारे ब्राउज़र के बारे में सबसे अधिक पसंद करते हैं, इसकी क्षमता है कि आप अपनी आवश्यकताओं के अनुसार अधिकांश यूआई तत्वों को स्थानांतरित करने और व्यवस्थित करने की अनुमति दे सकते हैं। { -brand-name-chrome } आपको कुछ यूआई तत्वों को छिपाने की अनुमति देता है, लेकिन आपकी प्राथमिकताओं के आधार पर चीजों को स्थानांतरित करने के लिए बहुत अधिक भत्ता नहीं है। हालांकि, यह ध्यान दिया जाना चाहिए कि दोनों { -brand-name-chrome } और { -brand-name-firefox } यह आपके ब्राउज़र की उपस्थिति और विषय को बदलने में बहुत आसान बनाते हैं।
compare-chrome-for-practical-purposes-theres = व्यावहारिक उद्देश्यों के लिए, स्पष्ट रूप से वास्तव में कुछ भी नहीं है जो आपको दोनों ब्राउज़र का उपयोग करने से रोक रहा है- { -brand-name-firefox } जीवन में उन क्षणों के लिए जब गोपनीयता वास्तव में मायने रखती है, और { -brand-name-chrome } यदि आप अभी भी { -brand-name-google } पारिस्थितिक तंत्र में निवेशित हैं। फिर भी हमारे व्यक्तिगत डेटा में बढ़ती संख्या के साथ, { -brand-name-firefox } हममें से उन लोगों के लिए लंबे समय में सही विकल्प साबित हो सकता है, जो ऑनलाइन हमारी व्यक्तिगत गोपनीयता की रक्षा करते हैं।
