# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } बनाम { -brand-name-safari } : आपके लिए बेहतर ब्राउज़र कौन सा है?

# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } { -brand-name-mac } और { -brand-name-iphone } पर पूर्व-स्थापित ब्राउज़र है। यह पता लगाने के लिए { -brand-name-safari } से { -brand-name-firefox-browser } तुलना करें कि आपके लिए कौन सा बेहतर ब्राउज़र है।


# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = यदि आप एक मैक का उपयोग करते हैं या एक { -brand-name-iphone } , तो संभावना है कि आप { -brand-name-safari } वेब ब्राउज़र से परिचित हैं। यह तथ्य कि यह { -brand-name-apple } उत्पाद उपयोगकर्ताओं के लिए डिफ़ॉल्ट ब्राउज़र के रूप में पूर्व-स्थापित है, निश्चित रूप से यह एक प्रारंभिक लाभ देता है, लेकिन { -brand-name-firefox } पास इसकी उपयोगी विशेषताओं का अपना सेट है जो इसे एक आकर्षक विकल्प बनाता है। यहां हम अपने ब्राउज़र और { -brand-name-safari } बीच गोपनीयता, उपयोगिता और उपकरणों के बीच पोर्टेबिलिटी के बीच मुख्य अंतर का पता लगाएंगे।

# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = तकनीकी कंपनियों के लिए गोपनीयता एक श्वेत गर्म विषय बन गया है क्योंकि वे महसूस करते हैं कि अधिक से अधिक लोग डेटा उल्लंघनों, विज्ञापन ट्रैकर्स और हैकर्स जैसी चीजों के प्रति संवेदनशील महसूस कर रहे हैं। लेकिन जब वास्तविक उपकरण पर लोग वास्तविक इंटरव्यू को नेविगेट करने के लिए उपयोग करते हैं, तो क्या यह सब बात है या वे वास्तव में आपके डेटा को सुरक्षित रखने के लिए कार्रवाई कर रहे हैं?
compare-safari-as-alluded-to-before-apple-fallback = जैसा कि पहले कहा गया था, { -brand-name-apple } उन कंपनियों में से एक है जिन्होंने हाल ही में अपने गोपनीयता खेल को आगे बढ़ाने का फैसला किया है। बहुत पहले नहीं, { -brand-name-apple } ने { -brand-name-safari } में क्रॉस-साइट ट्रैकिंग रोकथाम को लागू किया, जो विज्ञापनों को इंटरनेट पर आपके आसपास आने से रोकता है। { -brand-name-safari } किसी भी वेबसाइट पर नए खाते के लिए साइन अप करते समय एक मजबूत पासवर्ड सुझाव भी देता है। और यदि आप iCloud इकोसिस्टम में निवेशित हैं, तो यह उस पासवर्ड को आपके अन्य उपकरणों के साथ सुरक्षित रूप से सिंक करता है, इसलिए आपको वास्तव में इसे याद नहीं रखना है।

# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = { -brand-name-safari } , हमने { -brand-name-firefox } पर गोपनीयता और सुरक्षा पर ध्यान केंद्रित किया है। लेकिन { -brand-name-safari } विपरीत, हम लंबे समय से गोपनीयता साबुन बॉक्स पर खड़े हैं। वास्तव में, { -brand-name-mozilla } (हमारी मूल कंपनी) तकनीक समुदाय में ऑनलाइन गोपनीयता के लिए अलार्म बजाने वाली पहली आवाजों में से एक थी।

# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = हर बार जब आप इसे बंद करते हैं तो हमारा प्राइवेट ब्राउजिंग मोड ट्रैकर्स को ब्लॉक कर देता है और आपके पासवर्ड, कुकीज और हिस्ट्री को मिटा देता है। लेकिन आप नियमित ब्राउज़िंग मोड में भी हमारी उन्नत गोपनीयता सुविधाओं का अनुभव कर सकते हैं। { -brand-name-firefox } के नवीनतम संस्करण के साथ, डिफ़ॉल्ट रूप से बढ़ाया ट्रैकिंग रोकथाम चालू है। यह क्रॉस-साइट ट्रैकर्स जैसी चीजों को आपके द्वारा वेब पर कूदने से रोकता है। इसके अलावा, { -brand-name-facebook } गोपनीयता की समस्या के लिए लगभग रोज़ पकड़ा जाता है, हमारा <a { $attrs }>{ -brand-name-facebook-container }</a> एक्सटेंशन बहुत मायने रखता है। यह आपको वेब के चारों ओर ट्रैक करने के लिए { -brand-name-facebook } लिए कठिन बनाता है - क्रॉस-साइट ट्रैकिंग को रोकने के लिए { -brand-name-safari } समान जो करता है - लेकिन { -brand-name-firefox } वास्तव में आपके { -brand-name-facebook } सत्र को ट्रैकिंग से { -brand-name-facebook } अवरुद्ध एक अलग कंटेनर में अलग करता है। आप अन्य वेबसाइटों पर क्या करते हैं। उन्हें यह जानने की आवश्यकता क्यों है कि आप वैसे भी WebMD में क्या देखते हैं?

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = जहां तक सुरक्षा जाती है, { -brand-name-firefox } वहां भी ठोस है। किसी भी समय आप { -brand-name-firefox } , आप पासवर्ड पासवर्ड फ़ील्ड में राइट-क्लिक करके भरण पासवर्ड विकल्प का उपयोग करके एक मजबूत पासवर्ड सुरक्षित रूप से उत्पन्न कर सकते हैं। जब आप अपना नया पासवर्ड सेव करते हैं, तो हम आपको इसके बिल्ट-इन पासवर्ड मैनेजर, <a { $lockwise }>{ -brand-name-lockwise }</a> को सेव करने का संकेत देंगे। हम <a { $monitor }>{ -brand-name-monitor }</a> नामक एक और निःशुल्क और उपयोगी उत्पाद के साथ उपयोगकर्ताओं और खाताधारकों की सेवा भी करते हैं जो कि आपके डेटा को एक ज्ञात ब्रीच ब्रीच में शामिल करने पर स्वचालित रूप से आपको सचेत करता है।
compare-safari-if-you-choose-to-use-safari = यदि आप { -brand-name-safari } का उपयोग करना चुनते हैं, तो जब तक आप { -brand-name-apple } डिवाइस का उपयोग कर रहे हैं, तब तक आप सुरक्षित हाथों में हैं। लेकिन { -brand-name-safari } केवल { -brand-name-apple } उपकरणों पर काम करता है, जबकि { -brand-name-firefox } { -brand-name-windows } , { -brand-name-mac } , { -brand-name-ios } , { -brand-name-android } और { -brand-name-linux } । इसलिए कोई फर्क नहीं पड़ता कि आप किस ऑपरेटिंग सिस्टम को चुनते हैं, { -brand-name-firefox } आपने हमारी सुरक्षा और गोपनीयता सुरक्षा को कवर किया है।
compare-safari-apple-is-widely-known-for = { -brand-name-apple } व्यापक रूप से अपने बंद पारिस्थितिकी तंत्र के लिए जाना जाता है क्योंकि यह अपने उत्पादों के लिए सॉफ्टवेयर बनाने से संबंधित है। लेकिन { -brand-name-app-store } अंदर, यह ब्राउज़र को अधिक मजबूत बनाने के लिए प्लगइन्स और ऐड-ऑन बनाने के लिए डेवलपर्स को एक अनुभाग प्रदान करता है। ये एक्सटेंशन { -brand-name-app-store } माध्यम से भी ब्राउज़ करने योग्य हैं और आसानी से { -brand-name-safari } जुड़ जाते हैं।
compare-safari-in-addition-to-the-regular = किसी ब्राउज़र में आपके द्वारा अपेक्षित सुविधाओं के नियमित सेट के अलावा, जैसे टैब्ड ब्राउज़िंग और निजी ब्राउज़िंग, { -brand-name-safari } में कुछ अनपेक्षित सुविधाएँ भी हैं। उदाहरण के लिए, यदि कोई उपयोगकर्ता { -brand-name-safari } अंदर एक पृष्ठ पर कहीं भी किसी शब्द को राइट-क्लिक करता है, तो लुक अप पर क्लिक करें, उन्हें थिसॉरस, { -brand-name-app-store } , फिल्मों और अधिक से एक शब्दकोष प्लस प्रविष्टियां मिलेंगी। { -brand-name-safari } माता-पिता के नियंत्रण को कस्टमाइज़ करना आसान है, जब बच्चे इंटरनेट के बारे में उत्सुक होना शुरू करते हैं, तो वयस्कों को थोड़ा आसान साँस लेने की अनुमति मिलती है।

# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = { -brand-name-safari } , { -brand-name-firefox } अपने उत्साही डेवलपर समुदाय को ब्राउज़र में  <a { $attrs }> ऐड-ऑन और एक्सटेंशन </a>  बनाने के लिए प्रोत्साहित करता है। और चूंकि हमारा मंच खुला-स्रोत है, इसलिए कार्यक्षमता का खजाना जोड़ते हुए एक विशाल चयन है।

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = इसके अलावा, जब आप { -brand-name-firefox } खाते के लिए साइन अप करते हैं तो आपको <a { $pocket }>{ -brand-name-pocket }</a> और <a { $send }>{ -brand-name-send }</a> जैसी अनूठी सेवाओं तक पहुँच मिलती है जो सीधे ब्राउज़र में एकीकृत हो जाती हैं। { -brand-name-pocket } के लिए { -brand-name-firefox } बटन आप वेब पृष्ठों और के लिए वीडियो सहेजें की सुविधा देता है { -brand-name-pocket } ऑफ़लाइन भी - बस एक क्लिक में है, तो आप जब भी और जहां आप चाहते हैं एक साफ, व्याकुलता से मुक्त संस्करण पढ़ सकते हैं। { -brand-name-send } आप विभिन्न सुरक्षा नियंत्रणों के साथ बड़ी फ़ाइलों को एंड-टू-एंड एन्क्रिप्शन के साथ साझा कर सकते हैं, जैसे कि फ़ाइल लिंक के लिए समाप्ति समय सेट करने की क्षमता, समाप्ति की संख्या, डाउनलोड की संख्या और वैकल्पिक जोड़ना सुरक्षा की एक अतिरिक्त परत के लिए पासवर्ड।

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = इसके अलावा, जब आप { -brand-name-firefox } खाते के लिए साइन अप करते हैं, तो आपको स्क्रीनशॉट, <a { $pocket }>{ -brand-name-pocket }</a> और <a { $send }>{ -brand-name-send }</a> जैसी कुछ अनूठी सेवाओं तक पहुंच मिलती है, जो सीधे ब्राउज़र में एकीकृत होती हैं। स्क्रीनशॉट एक सुविधा है जिसे { -brand-name-firefox } ब्राउज़र में बनाया गया है, जिससे आप किसी वेब पेज के किसी भी हिस्से को कॉपी या डाउनलोड कर सकते हैं। जब आप स्क्रीनशॉट को सहेजते हैं, तो आप यह भी चुन सकते हैं कि आप अपने डेस्कटॉप को बंद करने के बजाय किस फ़ोल्डर में इसे ढूंढना चाहते हैं। { -brand-name-pocket } के लिए { -brand-name-firefox } बटन आप वेब पृष्ठों और के लिए वीडियो सहेजें की सुविधा देता है { -brand-name-pocket } ऑफ़लाइन भी - बस एक क्लिक में है, तो आप जब भी और जहां आप चाहते हैं एक साफ, व्याकुलता से मुक्त संस्करण पढ़ सकते हैं। { -brand-name-send } , आप बड़ी फ़ाइलों को एंड-टू-एंड एन्क्रिप्शन और विभिन्न प्रकार के सुरक्षा नियंत्रणों के साथ साझा कर सकते हैं, जैसे फ़ाइल लिंक के लिए समाप्ति समय निर्धारित करने की क्षमता, डाउनलोड की संख्या, और क्या जोड़ना है सुरक्षा की एक अतिरिक्त परत के लिए वैकल्पिक पासवर्ड।

# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>स्क्रीनशॉट</a> { -brand-name-firefox } ब्राउज़र में बनाया गया एक अन्य लोकप्रिय फीचर है, जिससे आप आसानी से अपनी स्क्रीन की तस्वीर खींच सकते हैं। जब आप एक स्क्रीनशॉट लेते हैं, तो आप फ़ाइल को कॉपी करने के लिए चुन सकते हैं या अपने डेस्कटॉप को अव्यवस्थित करने के बजाय आप इसे किस फ़ोल्डर में चुनना चाहते हैं।

# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } और { -brand-name-safari } दोनों डेस्कटॉप से मोबाइल ब्राउजिंग या इसके विपरीत चलते समय एक सहज अनुभव प्रदान करते हैं। { -brand-name-safari } , इसकी मुख्य विशेषताओं में से एक इसकी निरंतरता विशेषताएं हैं। यह आपके बुकमार्क, टैब, इतिहास और आईक्लाउड से अधिक को सिंक करता है ताकि वे आपके सभी उपकरणों पर उपलब्ध हों। इसका मतलब है कि आप अपने { -brand-name-iphone } पर एक टैब खोल सकते हैं और यह आपके { -brand-name-mac } लैपटॉप पर भी बस एक क्लिक के साथ दिखाई दे सकता है।
compare-safari-both-browsers-have-a-lot = दोनों ब्राउज़रों में कई क्रॉसओवर विशेषताएं हैं, साथ ही साथ कुछ अद्वितीय फ़ंक्शन भी हैं। यह ध्यान देने योग्य है, यदि आप बहुत सारे स्क्रीनशॉट लेते हैं, तो आपको आश्चर्य होगा कि आप कभी भी इस आसान सुविधा के बिना कैसे रहते थे जो कि { -brand-name-firefox } में बनाया गया है। लेकिन अगर आप सिर्फ सर्फिंग और खरीदारी के लिए एक तेज़, निजी ब्राउज़र की तलाश कर रहे हैं, तो आप { -brand-name-firefox } एक कोशिश दे सकते हैं - खासकर यदि आप विशेष रूप से { -brand-name-safari } का उपयोग कर रहे हैं क्योंकि यह डिफ़ॉल्ट ब्राउज़र के रूप में प्रीलोडेड आया है आपका कंप्यूटर। आखिरकार, आपको पता चल जाएगा कि कौन सा आपकी आवश्यकताओं के अनुकूल है।

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } भी एक समान सिंक सुविधा प्रदान करता है जब आप एक नि: शुल्क <a { $attrs }>{ -brand-name-firefox-account }</a> लिए साइन अप करते हैं जो उपयोगकर्ताओं को आसानी से अपने बुकमार्क, ब्राउज़िंग इतिहास, प्राथमिकताएं, पासवर्ड, भरे हुए फॉर्म, ऐड-ऑन और कई में अंतिम 25 खोले गए टैब को सिंक्रनाइज़ करने में सक्षम बनाता है। कंप्यूटर। क्या सेट { -brand-name-firefox } से अलग { -brand-name-safari } , कि यह किसी भी डेस्कटॉप या मोबाइल मंच पर उपलब्ध है है { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } या { -brand-name-macos } , आप खुद कर सकते हैं किसी भी डिवाइस पर अपनी पोर्टेबिलिटी बढ़ाने।

# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = <a { $ios }>{ -brand-name-ios }</a> और <a { $android }>{ -brand-name-android }</a> लिए { -brand-name-firefox } ऐप उपलब्ध सबसे तेज़ ब्राउज़रों में से एक है और इसमें ठोस सुरक्षा और एंटी-ट्रैकिंग विशेषताएं भी हैं - यदि आप लगातार लैपटॉप और मोबाइल उपकरणों के बीच उछल रहे हैं, तो एक बड़ा प्लस।
compare-safari-since-safari-is-apples-proprietary = चूंकि { -brand-name-safari } { -brand-name-apple } का मालिकाना वेब ब्राउज़र है, इसका iCloud सिंकिंग { -brand-name-apple } उत्पादों के साथ विशेष रूप से काम करता है। यह कुछ हद तक सीमित हो सकता है, उदाहरण के लिए, आप दोनों { -brand-name-android } उपयोगकर्ता और { -brand-name-iphone } उपयोगकर्ता हैं या यदि आपके पास काम के लिए { -brand-name-windows } आधारित पीसी है, लेकिन अपने व्यक्तिगत डिवाइस के रूप में { -brand-name-iphone } उपयोग करें।

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } यदि आप एक { -brand-name-apple } उपयोगकर्ता के साथ एकाधिक { -brand-name-apple } उत्पाद हैं, तो ब्राउज़िंग अनुभव को सरल, तेज़ और निर्बाध बनाने का एक बड़ा काम करता है। { -brand-name-safari } , { -brand-name-firefox } एक तेज और उपयोगितावादी ब्राउज़र है, लेकिन गोपनीयता और क्रॉस-प्लेटफॉर्म संगतता हमारी परिभाषित विशेषताएं हैं। { -brand-name-firefox } हर महीने नई सुविधाओं और कार्यक्षमता के साथ अद्यतन करता है। उदाहरण के लिए, नए उपयोगकर्ताओं के लिए डिफ़ॉल्ट रूप से हमारे <a { $attrs }>एन्हांस्ड ट्रैकिंग प्रोटेक्शन (ETP)</a> पर हाल ही में अपडेट किया गया, जो कुकीज़ और क्रॉस-साइट ट्रैकर्स को प्रभावी ढंग से ब्लॉक करता है।
compare-safari-in-the-end-it-just-boils = अंत में, यह आपके ब्राउज़र में आपके द्वारा दिए गए मूल्य को उबालता है। यदि आप { -brand-name-apple } पारिस्थितिकी तंत्र के साथ एकीकृत हैं, तो { -brand-name-safari } अभी भी एक बढ़िया विकल्प है। लेकिन यदि आप नवीनतम और सबसे बड़ी गोपनीयता सुरक्षा वाले हैं और कई ऑपरेटिंग सिस्टम में काम करने में सक्षम हैं, तो हमें लगता है कि { -brand-name-firefox } आपका सबसे अच्छा दांव है। { -brand-name-firefox } उन { -brand-name-apple } -एक्सक्लूसिव उपयोगकर्ताओं के लिए एक माध्यमिक ब्राउज़र के रूप में भी एक ठोस विकल्प है जो उन ऑनलाइन क्षणों के लिए एक अलग ब्राउज़र में स्विच करना चाहते हैं जो गोपनीयता सुरक्षा की अतिरिक्त परतों के लिए कॉल करते हैं।
