# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } so với { -brand-name-chrome } : Cái nào tốt hơn?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Chúng tôi so sánh { -brand-name-mozilla } { -brand-name-firefox } với { -brand-name-google } { -brand-name-chrome } về quyền riêng tư, tiện ích và tính di động

# Main title.
compare-chrome-comparing-firefox-browser = So sánh { -brand-name-firefox-browser } với { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Tại { -brand-name-firefox } , chúng tôi có một số lượng lớn người dùng tận tâm đánh giá cao sự cống hiến kiên định của chúng tôi đối với quyền riêng tư trực tuyến. Ví dụ: phiên bản mới nhất của { -brand-name-firefox } bao gồm một tính năng được gọi là Bảo vệ Theo dõi Nâng cao (ETP) được bật theo mặc định cho tất cả người dùng trên toàn thế giới. ETP chặn hơn 2.000 trình theo dõi, bao gồm cả trình theo dõi xã hội từ các công ty như { -brand-name-facebook } , { -brand-name-twitter } và LinkedIn. Nó cũng có một tính năng tích hợp được gọi là <a { $attrs }>{ -brand-name-firefox-monitor }</a> tự động thông báo cho bạn nếu mật khẩu của bạn đã bị vi phạm hoặc cần được cập nhật. Ngoài những biện pháp bảo vệ này, chế độ Duyệt web riêng tư trong { -brand-name-firefox } tự động xóa thông tin duyệt web của bạn như lịch sử và cookie, không để lại dấu vết sau khi bạn kết thúc phiên của mình.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Tại { -brand-name-firefox } , chúng tôi có một số lượng lớn người dùng tận tâm đánh giá cao sự cống hiến kiên định của chúng tôi đối với quyền riêng tư trực tuyến. Ví dụ: phiên bản mới nhất của { -brand-name-firefox } bao gồm một tính năng được gọi là Bảo vệ Theo dõi Nâng cao (ETP) được bật theo mặc định cho tất cả người dùng trên toàn thế giới. ETP chặn hơn 2.000 trình theo dõi, bao gồm cả trình theo dõi xã hội từ các công ty như { -brand-name-facebook } , { -brand-name-twitter } và LinkedIn. Nó cũng có một tính năng tích hợp được gọi là <a { $attrs }>{ -brand-name-firefox-monitor }</a> tự động thông báo cho bạn nếu mật khẩu của bạn đã bị vi phạm hoặc cần được cập nhật. Ngoài các biện pháp bảo vệ này, chế độ Duyệt web Riêng tư của { -brand-name-firefox } tự động xóa thông tin duyệt web của bạn như lịch sử và cookie, không để lại dấu vết sau khi bạn kết thúc phiên của mình.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Gần đây, chúng tôi cũng đã tái lập lại cam kết của mình đối với quyền riêng tư và tính minh bạch liên quan đến dữ liệu người dùng trong <a { $attrs }>Thông báo về quyền riêng tư</a> gần đây nhất của chúng tôi nêu rõ: “Tại Mozilla, chúng tôi tin rằng quyền riêng tư là nền tảng cho một mạng internet lành mạnh.”
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } đối với tất cả các tài khoản là một trình duyệt an toàn, với các tính năng như { -brand-name-google } Duyệt web An toàn, giúp bảo vệ người dùng bằng cách hiển thị cảnh báo không thể bỏ lỡ khi họ cố gắng điều hướng đến các trang web nguy hiểm hoặc tải xuống các tệp nguy hiểm.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Cuối cùng, tùy thuộc vào bạn để quyết định có hay không hoặc nơi thu hút sự chia sẻ những thứ như lịch sử tìm kiếm và lịch sử mua sắm của bạn. Nhưng nếu bạn giống như hầu hết mọi người, bạn có thể đã tìm kiếm một số thứ trên internet mà bạn muốn giữ kín.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Từ trước đến nay, bối cảnh cạnh tranh cho các trình duyệt đã thay đổi với nhiều người bắt đầu đặt câu hỏi về điều gì đang xảy ra với dữ liệu trực tuyến của họ như lịch sử duyệt web, mật khẩu và các thông tin nhạy cảm khác. Đã có nhiều thay đổi kể từ năm 2008 khi { -brand-name-chrome } xuất hiện. Tại { -brand-name-firefox } , chúng tôi đã nỗ lực hết mình, làm việc để thiết kế lại giao diện của mình và cung cấp cho người dùng ngày càng nhiều các cải tiến về quyền riêng tư và hiệu suất cũng như nhiều công cụ trình duyệt tiện dụng.
compare-chrome-and-so-here-we-are-the-browser = Và chúng ta đây rồi, cuộc chiến giữa các trình duyệt lại một lần nữa leo thang và đã đến lúc đánh giá lại và so sánh { -brand-name-firefox-browser } so với { -brand-name-google } { -brand-name-chrome } .
compare-chrome-in-2008-google-introduced = Vào năm 2008, { -brand-name-google } giới thiệu { -brand-name-chrome } và tác động của nó như một sự đổi mới trong công nghệ trình duyệt ngay lập tức. Nó nhanh hơn để tải các trang web, chiếm không gian màn hình tối thiểu và cung cấp một giao diện người dùng đơn giản không thể phủ nhận.
compare-chrome-in-fact-both-chrome-and-firefox = Trên thực tế, cả { -brand-name-chrome } và { -brand-name-firefox } đều có bảo mật nghiêm ngặt. Cả hai đều bao gồm một thứ gọi là “hộp cát” ngăn cách các quy trình của trình duyệt để một thứ gì đó như một trang web có hại không lây nhiễm sang các bộ phận khác của máy tính xách tay hoặc thiết bị khác của bạn.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Mặc dù { -brand-name-chrome } chứng minh là một trình duyệt web an toàn, nhưng hồ sơ bảo mật của nó là đáng ngờ. { -brand-name-google } thực sự thu thập một lượng lớn dữ liệu đáng lo ngại từ người dùng bao gồm vị trí, lịch sử tìm kiếm và lượt truy cập trang web. { -brand-name-google } đưa ra trường hợp thu thập dữ liệu nói rằng họ đang làm điều đó để cải thiện các dịch vụ của mình - như giúp bạn tìm một chiếc áo len hoặc một cửa hàng cà phê giống như cửa hàng bạn đã mua hoặc ghé thăm trước đây. Tuy nhiên, những người khác có thể không đồng ý, đưa ra quan điểm rằng { -brand-name-google } thực sự đang thu thập một lượng dữ liệu chưa từng có cho các mục đích tiếp thị của riêng mình. Họ quảng cáo rằng họ đang giữ bí mật thông tin của bạn khỏi tin tặc, nhưng điều đó không quan trọng. Bản thân { -brand-name-google } điều hành mạng quảng cáo lớn nhất thế giới, phần lớn nhờ vào dữ liệu họ thu thập được từ người dùng của mình.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Về tính năng, cả { -brand-name-firefox } và { -brand-name-chrome } cung cấp một thư viện lớn các tiện ích mở rộng và trình cắm, với danh mục của { -brand-name-chrome } nhiều hơn bất kỳ trình duyệt nào khác trong khi tích hợp độc đáo với các dịch vụ { -brand-name-google } khác, như Gmail và { -brand-name-google } Tài liệu.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } cũng có tính năng đồng bộ hóa để xem các tab đang mở và gần đây, lịch sử duyệt web và dấu trang trên tất cả các thiết bị của bạn.
compare-chrome-while-chrome-gets-the-nod = Mặc dù { -brand-name-chrome } nhận được sự chú ý với các tiện ích bổ sung và tiện ích mở rộng, { -brand-name-firefox } có một tập hợp các tính năng tích hợp được sắp xếp độc đáo, chẳng hạn như công cụ chụp màn hình cực kỳ tiện dụng và tính năng chế độ đọc giúp loại bỏ mọi thứ khỏi trang ngoại trừ văn bản từ bài báo bạn đang đọc.
compare-chrome-although-not-as-extensive = Mặc dù không mở rộng như thư viện tiện ích bổ sung của { -brand-name-chrome } , { -brand-name-firefox } , với tư cách là phần mềm nguồn mở với một số lượng lớn những người đóng góp tích cực, cũng có số lượng tiện ích mở rộng hữu ích đáng kinh ngạc.
compare-chrome-if-having-tons-of-open-tabs = Nếu bạn có rất nhiều tab đang mở, thì điều đó thực sự phụ thuộc vào tùy chọn giao diện người dùng của bạn. { -brand-name-firefox } có tính năng cuộn ngang trên tất cả các tab đang mở của bạn thay vì thu nhỏ chúng nhỏ hơn và nhỏ hơn với mỗi tab mới. { -brand-name-google } { -brand-name-chrome } muốn thu nhỏ chúng lại để chỉ hiển thị biểu tượng yêu thích. Vấn đề duy nhất với điều này là khi bạn mở nhiều tab từ cùng một trang web, vì vậy bạn sẽ thấy cùng một biểu tượng yêu thích trên các tab của mình.
compare-chrome-almost-needless-to-say-versions = Hầu như không cần phải nói, các phiên bản của cả { -brand-name-firefox } và { -brand-name-chrome } đều có sẵn cho các hệ điều hành máy tính để bàn và điện thoại di động phổ biến nhất ( { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ).
compare-chrome-both-chrome-and-firefox-also = Cả { -brand-name-chrome } và { -brand-name-firefox } cũng cho phép bạn đồng bộ hóa những thứ như mật khẩu, dấu trang và các tab đang mở trên tất cả các thiết bị của bạn. Nếu bạn có tài khoản { -brand-name-firefox } , bạn có thể gửi theo cách thủ công một tab đang mở trên máy tính để bàn đến thiết bị di động của bạn hoặc ngược lại. Với { -brand-name-chrome } , việc này được thực hiện tự động nếu bạn đã chọn cài đặt đó trong tùy chọn của mình. Không phải gửi tab theo cách thủ công từ thiết bị này sang thiết bị khác rất tiện lợi khi bạn muốn làm một việc gì đó như tiếp tục đọc một bài báo mà bạn chưa hoàn thành trước đó. Nhưng đôi khi đồng bộ hóa tự động có thể không lý tưởng nếu có khả năng nhiều người dùng đang duyệt trong khi đăng nhập vào tài khoản { -brand-name-google } của bạn.

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Chúng tôi nghĩ rằng thật công bằng khi nói { -brand-name-firefox } và { -brand-name-chrome } thực sự là cổ điển về tính di động và tiện ích, với { -brand-name-chrome } có một chút lợi thế về tiện ích vì thư viện tiện ích mở rộng và tính năng bổ sung khổng lồ của nó. Nhưng về Quyền riêng tư, { -brand-name-firefox } giành được chiến thắng trong ngày với cam kết của chúng tôi trong việc bảo toàn dữ liệu trực tuyến của người dùng và cung cấp các dịch vụ tiện ích miễn phí như trình quản lý mật khẩu cũng cảnh báo cho bạn nếu xảy ra vi phạm dữ liệu liên quan đến thông tin đăng nhập của bạn.
compare-chrome-as-for-customization-our = Đối với tùy chỉnh, người hâm mộ của chúng tôi sẽ cho bạn biết một trong những điều họ yêu thích nhất về trình duyệt của chúng tôi là khả năng cho phép bạn di chuyển và sắp xếp phần lớn các yếu tố giao diện người dùng để phù hợp nhất với nhu cầu của bạn. { -brand-name-chrome } cho phép bạn ẩn các phần tử giao diện người dùng nhất định nhưng không có nhiều sự cho phép, nếu có, để di chuyển mọi thứ xung quanh dựa trên tùy chọn của bạn. Tuy nhiên, cần lưu ý rằng cả { -brand-name-chrome } và { -brand-name-firefox } giúp bạn dễ dàng thay đổi giao diện và chủ đề của trình duyệt.
compare-chrome-for-practical-purposes-theres = Đối với các mục đích thực tế, rõ ràng không có gì ngăn cản bạn sử dụng cả hai trình duyệt— { -brand-name-firefox } trong những khoảnh khắc trong cuộc sống khi quyền riêng tư thực sự quan trọng và { -brand-name-chrome } nếu bạn vẫn đầu tư vào hệ sinh thái { -brand-name-google } . Tuy nhiên, với số lượng ngày càng tăng các cuộc xâm nhập vào dữ liệu cá nhân của chúng tôi, { -brand-name-firefox } có thể chứng minh là lựa chọn đúng đắn về lâu dài cho những người trong chúng tôi, những người coi trọng việc bảo vệ quyền riêng tư cá nhân của mình trực tuyến.
