# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Bảy trình duyệt tốt nhất khi so sánh trực tiếp
compare-index-six-of-the-best-browsers-fallback = Sáu trong số các trình duyệt tốt nhất khi so sánh trực tiếp

# Sub-headline
compare-index-privacy-utility-portability = Riêng tư. Tiện ích. Tính di động.

# HTML page description
compare-index-a-great-internet-browser-should = Một trình duyệt internet tuyệt vời phải có chức năng bạn cần, khả năng di động trên các thiết bị và quyền riêng tư mà bạn xứng đáng được hưởng.
compare-index-which-browser-is-best-at-keeping = Trình duyệt nào tốt nhất trong việc giữ bí mật mọi thứ?
compare-index-its-not-unreasonable-to-expect = Không có gì vô lý khi mong đợi mức độ bảo vệ dữ liệu và quyền riêng tư cao từ các sản phẩm mà chúng tôi thường xuyên sử dụng để truy cập trực tuyến. Ở mức tối thiểu, trình duyệt phải cung cấp một số phiên bản của “chế độ duyệt web riêng tư” tự động xóa lịch sử và lịch sử tìm kiếm của bạn để những người dùng khác trên cùng một máy tính không thể truy cập. Trong lĩnh vực này, tất cả bảy trình duyệt được so sánh ở đây đều đạt điểm.
compare-index-its-not-unreasonable-to-expect-fallback = Không có gì vô lý khi mong đợi mức độ bảo vệ dữ liệu và quyền riêng tư cao từ các sản phẩm mà chúng tôi thường xuyên sử dụng để truy cập trực tuyến. Ở mức tối thiểu, trình duyệt phải cung cấp một số phiên bản của “chế độ duyệt web riêng tư” tự động xóa lịch sử và lịch sử tìm kiếm của bạn để những người dùng khác trên cùng một máy tính không thể truy cập. Trong lĩnh vực này, tất cả sáu trình duyệt được so sánh ở đây đều đạt điểm.
compare-index-what-you-do-online-literally = Những gì bạn làm trực tuyến theo nghĩa đen không phải là việc của bất kỳ ai khác.
compare-index-another-browser-feature-that = Một tính năng trình duyệt khác nên được cung cấp là khả năng ngăn các trang web và công ty theo dõi dữ liệu duyệt web và mua sắm của bạn - ngay cả trong chế độ duyệt bình thường.
compare-index-another-browser-feature-fallback = Một tính năng trình duyệt khác nên được cung cấp là khả năng ngăn các trang web và công ty theo dõi dữ liệu duyệt web và mua sắm của bạn - ngay cả trong chế độ duyệt bình thường. Nhưng thực tế không phải vậy: trên thực tế, các trình duyệt duy nhất chặn cookie theo dõi của bên thứ ba theo mặc định là { -brand-name-firefox } và { -brand-name-safari } .
compare-index-using-a-browser-that-blocks = Sử dụng trình duyệt chặn trình theo dõi của bên thứ ba không chỉ quan trọng đối với quyền riêng tư - điều đó thường có nghĩa là nó cũng chạy nhanh hơn nhiều. Hầu hết các trình theo dõi chỉ là các tập lệnh chạy nền trên một số trang web. Bạn không thể nhìn thấy chúng, nhưng bạn có thể cảm thấy chúng làm chậm trình duyệt của bạn. Kể từ phiên bản 67 của { -brand-name-firefox } , tính năng lấy dấu vân tay và máy tính mật mã cũng bị chặn. Nếu bạn không quen thuộc với các máy dò mật mã, đây là một ví dụ về cách chúng có thể ảnh hưởng đến bạn: có thể bạn đã gặp phải trường hợp máy tính của mình đột ngột nóng hơn hoặc pin cạn kiệt nhanh hơn bình thường. Đó thường là sản phẩm phụ của các máy đào tiền mã hóa len lỏi trên thiết bị của bạn.
compare-index-what-has-your-browser-done = Trình duyệt của bạn đã làm gì cho bạn gần đây?
compare-index-in-addition-to-privacy-protection = Ngoài bảo vệ quyền riêng tư, phần lớn diễn ra trong nền của trình duyệt, một thành phần quan trọng khác đối với một trình duyệt tốt là giao diện và chức năng người dùng thực tế. Hầu như tất cả bảy trình duyệt đều bình đẳng khi nói đến duyệt tab, quản lý dấu trang, tự động hoàn thành, hiệu đính và tiện ích mở rộng. { -brand-name-firefox } , { -brand-name-edge } và { -brand-name-opera } cũng cung cấp chức năng chụp ảnh màn hình nhanh được chứng minh là khá tiện dụng và chắc chắn là thứ bạn thấy thiếu khi chuyển sang trình duyệt mà không có nó.
compare-index-in-addition-to-privacy-protection-fallback = Ngoài bảo vệ quyền riêng tư, phần lớn diễn ra trong nền của trình duyệt, một thành phần quan trọng khác đối với một trình duyệt tốt là giao diện và chức năng người dùng thực tế. Hầu như tất cả sáu trình duyệt đều ngang nhau khi nói đến duyệt tab, quản lý dấu trang, tự động hoàn thành, hiệu đính và tiện ích mở rộng. { -brand-name-firefox } , { -brand-name-edge } và { -brand-name-opera } cũng cung cấp chức năng chụp ảnh màn hình nhanh được chứng minh là khá tiện dụng và chắc chắn là thứ bạn thấy thiếu khi chuyển sang trình duyệt mà không có nó.
compare-index-how-well-does-your-browser = Trình duyệt của bạn hoạt động tốt như thế nào trên các thiết bị của bạn?
compare-index-almost-all-of-the-browsers = Hầu hết tất cả các trình duyệt được so sánh ở đây đều cho phép đồng bộ hóa giữa máy tính để bàn và thiết bị di động. Bạn sẽ cần một tài khoản để làm điều đó, bạn có thể sử dụng tài khoản này để đăng nhập vào trình duyệt trên tất cả các thiết bị và đồng bộ hóa những thứ như mật khẩu, lịch sử duyệt web, dấu trang và cài đặt.
compare-index-conclusion = Phần kết luận:
compare-index-and-the-winner-is = Và người chiến thắng là…
compare-index-find-out-how-firefox-chrome = Tìm hiểu { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } và { -brand-name-ie } khác nhau như thế nào về quyền riêng tư, tiện ích và tính di động.
compare-index-find-out-how-firefox-fallback = Tìm hiểu xem { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } và { -brand-name-ie } khác nhau như thế nào về quyền riêng tư, tiện ích và tính di động.
compare-index-looking-for-a-better-browser = Tìm kiếm một trình duyệt tốt hơn? Chúng tôi sẽ so sánh { -brand-name-firefox } với { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } và { -brand-name-ie } để giúp bạn đưa ra quyết định của mình.
compare-index-looking-for-a-better-fallback = Tìm kiếm một trình duyệt tốt hơn? Chúng tôi sẽ so sánh { -brand-name-firefox } với { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } và { -brand-name-ie } để giúp bạn đưa ra quyết định của mình.
compare-index-so-is-your-browser-the-best = Vậy trình duyệt của bạn có phải là trình duyệt tốt nhất cho những gì bạn làm trực tuyến không? Trình duyệt phù hợp có thể tạo ra sự khác biệt lớn trong cách bạn trải nghiệm web. Vì vậy, không cần phải lo lắng gì thêm, hãy so sánh { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } , { -brand-name-microsoft } { -brand-name-ie } và { -brand-name-edge } - và xem cái nào phù hợp nhất với nhu cầu của bạn.
compare-index-so-is-your-browser-the-fallback = Vậy trình duyệt của bạn có phải là trình duyệt tốt nhất cho những gì bạn làm trực tuyến không? Trình duyệt phù hợp có thể tạo ra sự khác biệt lớn trong cách bạn trải nghiệm web. Vì vậy, không cần phải lo lắng gì thêm, hãy so sánh { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-microsoft } { -brand-name-ie } và { -brand-name-edge } - và xem cái nào phù hợp nhất với nhu cầu của bạn.
compare-index-since-your-browser-is-your = Vì trình duyệt của bạn là cổng vào internet nên tốc độ, bảo mật, quyền riêng tư và tiện ích là điều tối quan trọng. Trong những năm gần đây, { -brand-name-google } { -brand-name-chrome } đã là trình duyệt được nhiều người lựa chọn. Nhưng vào thời điểm mà các quảng cáo trực tuyến dường như theo chúng ta ở khắp mọi nơi và vi phạm dữ liệu là nguyên nhân của các tiêu đề tin tức, rất nhiều người bắt đầu yêu cầu trình duyệt của họ được tôn trọng và riêng tư hơn.
compare-index-the-first-thing-to-point-out = Điều đầu tiên cần chỉ ra về tính di động là không phải tất cả các trình duyệt đều chạy trên tất cả các hệ điều hành. Mặc dù { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-brave } và { -brand-name-opera } hoạt động trên tất cả các hệ thống chính và dễ cài đặt, { -brand-name-ie } và { -brand-name-safari } chỉ hoạt động trên { -brand-name-microsoft } và các hệ thống của riêng Apple. Phiên bản di động của { -brand-name-safari } được cài đặt sẵn trên các thiết bị di động của Apple và hầu hết các thiết bị { -brand-name-android } đều có trình duyệt cài đặt sẵn do nhà sản xuất sửa đổi cho thiết bị. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-brave } , { -brand-name-edge } và { -brand-name-opera } có thể dễ dàng được cài đặt và thậm chí sử dụng song song với nhau.
compare-index-the-first-thing-to-point-fallback = Điều đầu tiên cần chỉ ra về tính di động là không phải tất cả các trình duyệt đều chạy trên tất cả các hệ điều hành. Mặc dù { -brand-name-firefox } , { -brand-name-chrome } và { -brand-name-opera } hoạt động trên tất cả các hệ thống chính và dễ cài đặt, { -brand-name-ie } , { -brand-name-edge } và { -brand-name-safari } chỉ hoạt động trên { -brand-name-microsoft } và các hệ thống của Apple. Phiên bản di động của { -brand-name-safari } được cài đặt sẵn trên các thiết bị di động của Apple và hầu hết các thiết bị { -brand-name-android } đều có trình duyệt được cài đặt sẵn do nhà sản xuất sửa đổi cho thiết bị. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } và { -brand-name-opera } có thể dễ dàng được cài đặt và thậm chí được sử dụng song song với nhau.
compare-index-browsers-have-come-a-long = Các trình duyệt đã trải qua một chặng đường dài kể từ khi { -brand-name-chrome } được giới thiệu và chiếm thị phần. Hầu hết các trình duyệt hiện đại đã thu hẹp khoảng cách về tính di động và chức năng, và trong một số lĩnh vực, như tốc độ và quyền riêng tư, đã thực sự vượt qua { -brand-name-chrome } . Tuy nhiên, việc xác định trình duyệt nào phù hợp với bạn sẽ luôn phụ thuộc vào nhu cầu cá nhân của bạn và những gì bạn đánh giá cao nhất khi điều hướng trực tuyến.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } được hỗ trợ bởi tổ chức phi lợi nhuận { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } đặt quyền riêng tư của bạn lên hàng đầu - trong mọi việc chúng tôi thực hiện và làm. Chúng tôi tin rằng bạn có quyền quyết định cách thức và người mà bạn chia sẻ thông tin cá nhân của mình. { -brand-name-firefox } thu thập càng ít dữ liệu càng tốt và không bao giờ bán nó. Dữ liệu nhỏ mà chúng tôi thu thập chỉ được sử dụng để làm cho các sản phẩm và tính năng tốt hơn. Không có bí mật. Nhưng rất nhiều sự minh bạch và sự riêng tư thực sự.
compare-index-based-on-the-criteria-we-outlined = Dựa trên các tiêu chí chúng tôi đã vạch ra - quyền riêng tư, tiện ích và tính di động - thực sự chỉ có một trình duyệt đáp ứng được tiêu chí đó và đó là { -brand-name-firefox } . Điểm khác biệt thực sự không nằm ở chức năng, mà là quyền riêng tư. { -brand-name-firefox } là trình duyệt riêng tư nhất không khóa bạn vào một hệ sinh thái. Sử dụng nó trên mọi hệ điều hành, trên tất cả các thiết bị của bạn và hoàn toàn yên tâm khi sử dụng.
