# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } so với { -brand-name-safari } : Trình duyệt nào tốt hơn cho bạn?

# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } là trình duyệt được cài đặt sẵn trên { -brand-name-mac } và { -brand-name-iphone } . So sánh { -brand-name-safari } với { -brand-name-firefox-browser } để tìm ra trình duyệt nào tốt hơn cho bạn.

# Main title.
compare-safari-comparing-firefox-browser = So sánh { -brand-name-firefox-browser } với { -brand-name-apple } { -brand-name-safari }

# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Nếu bạn sử dụng máy Mac hoặc có { -brand-name-iphone } , rất có thể bạn đã quen với trình duyệt web { -brand-name-safari } . Thực tế là nó được cài đặt sẵn làm trình duyệt mặc định cho người dùng sản phẩm { -brand-name-apple } chắc chắn mang lại lợi thế sớm cho nó, nhưng { -brand-name-firefox } có bộ tính năng hữu ích riêng khiến nó trở thành một sự thay thế hấp dẫn. Ở đây, chúng tôi sẽ khám phá những điểm khác biệt chính giữa trình duyệt của chúng tôi và { -brand-name-safari } về quyền riêng tư, tiện ích và tính di động giữa các thiết bị.

# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Quyền riêng tư đã trở thành một chủ đề nóng đối với các công ty công nghệ khi họ nhận ra ngày càng nhiều người cảm thấy dễ bị tổn thương bởi những thứ như vi phạm dữ liệu, trình theo dõi quảng cáo và tin tặc. Nhưng khi nói đến các công cụ thực sự mà mọi người sử dụng để điều hướng các mạng xen kẽ thực tế, tất cả chỉ là chuyện hay họ đang thực sự hành động để giữ an toàn cho dữ liệu của bạn?
compare-safari-as-alluded-to-before-apple-fallback = Như đã đề cập trước đây, { -brand-name-apple } là một trong những công ty gần đây đã quyết định đẩy mạnh trò chơi bảo mật của họ. Cách đây không lâu, { -brand-name-apple } triển khai tính năng ngăn chặn theo dõi trên nhiều trang web trong { -brand-name-safari } , ngăn không cho quảng cáo theo dõi bạn trên internet. { -brand-name-safari } cũng đưa ra đề xuất mật khẩu mạnh khi bạn đăng ký tài khoản mới trên bất kỳ trang web nào. Và nếu bạn đầu tư vào hệ sinh thái iCloud, nó sẽ đồng bộ hóa mật khẩu đó một cách an toàn với các thiết bị khác của bạn, vì vậy bạn thực sự không bao giờ phải nhớ nó.

# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Giống như { -brand-name-safari } , chúng tôi tại { -brand-name-firefox } đã đưa ra quan điểm tập trung vào quyền riêng tư và bảo mật. Nhưng không giống như { -brand-name-safari } , chúng tôi đã đứng trên hộp xà phòng về quyền riêng tư trong một thời gian dài. Trên thực tế, { -brand-name-mozilla } (công ty mẹ của chúng tôi) là một trong những tiếng nói đầu tiên trong cộng đồng công nghệ gióng lên hồi chuông cảnh báo về quyền riêng tư trực tuyến.

# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Chế độ Duyệt web riêng tư của chúng tôi chặn các trình theo dõi và xóa mật khẩu, cookie và lịch sử của bạn mỗi khi bạn đóng nó. Nhưng bạn cũng có thể trải nghiệm các tính năng bảo mật nâng cao của chúng tôi ngay cả trong chế độ duyệt thông thường. Với phiên bản mới nhất của { -brand-name-firefox } , tính năng ngăn chặn theo dõi nâng cao được bật theo mặc định. Điều này ngăn những thứ như trình theo dõi trên nhiều trang web theo dõi bạn khi bạn di chuyển khắp nơi trên web. Ngoài ra, với việc { -brand-name-facebook } bị phát hiện gần như hàng ngày vì các vấn đề về quyền riêng tư, tiện ích mở rộng <a { $attrs }>{ -brand-name-facebook-container }</a> của chúng tôi rất có ý nghĩa. Điều này làm cho việc { -brand-name-facebook } theo dõi bạn trên web khó hơn - tương tự như những gì { -brand-name-safari } làm để ngăn theo dõi trang web chéo - nhưng { -brand-name-firefox } thực sự cô lập phiên { -brand-name-facebook } của bạn thành một vùng chứa riêng biệt, chặn { -brand-name-facebook } khỏi theo dõi những gì bạn làm trên các trang web khác. Tại sao họ vẫn cần biết những gì bạn tra cứu trên WebMD?

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Về mặt bảo mật, { -brand-name-firefox } cũng rất vững chắc ở đó. Bất kỳ lúc nào bạn đang ở { -brand-name-firefox } , bạn có thể nhấp chuột phải vào trường mật khẩu để tạo mật khẩu mạnh một cách an toàn bằng cách sử dụng tuỳ chọn Điền Mật khẩu. Khi bạn lưu mật khẩu mới của mình, chúng tôi sẽ nhắc bạn lưu vào trình quản lý mật khẩu tích hợp sẵn của nó, <a { $lockwise }>{ -brand-name-lockwise }</a> . Chúng tôi cũng cung cấp cho người dùng và chủ tài khoản một sản phẩm hữu ích và miễn phí khác có tên là <a { $monitor }>{ -brand-name-monitor }</a> tự động cảnh báo cho bạn nếu dữ liệu của bạn bị bao gồm trong một vi phạm dữ liệu đã biết.
compare-safari-if-you-choose-to-use-safari = Nếu bạn chọn sử dụng { -brand-name-safari } , bạn sẽ được an toàn miễn là bạn đang sử dụng thiết bị { -brand-name-apple } . Nhưng { -brand-name-safari } chỉ hoạt động trên { -brand-name-apple } thiết bị, trong khi { -brand-name-firefox } hoạt động trên { -brand-name-windows } , { -brand-name-mac } , { -brand-name-ios } , { -brand-name-android } và { -brand-name-linux } . Vì vậy, bất kể bạn chọn hệ điều hành nào, { -brand-name-firefox } bạn đã được bảo vệ bằng các biện pháp bảo mật và quyền riêng tư của chúng tôi.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } được biết đến rộng rãi với hệ sinh thái khép kín vì nó liên quan đến việc tạo phần mềm cho các sản phẩm của mình. Nhưng bên trong { -brand-name-app-store } , nó cung cấp một phần cho các nhà phát triển để tạo các plugin và tiện ích bổ sung để làm cho trình duyệt mạnh mẽ hơn. Các tiện ích mở rộng này cũng có thể duyệt qua { -brand-name-app-store } và dễ dàng thêm vào { -brand-name-safari } .
compare-safari-in-addition-to-the-regular = Ngoài bộ tính năng thông thường mà bạn mong đợi trong một trình duyệt, chẳng hạn như duyệt theo tab và duyệt web riêng tư, { -brand-name-safari } cũng có một số tính năng không mong đợi. Ví dụ: nếu người dùng nhấp chuột phải vào một từ ở bất kỳ đâu trên trang bên trong { -brand-name-safari } , sau đó nhấp vào Tra cứu, họ sẽ nhận được định nghĩa từ điển cộng với các mục từ từ đồng nghĩa, { -brand-name-app-store } , phim và hơn thế nữa. Kiểm soát của phụ huynh của { -brand-name-safari } dễ dàng tùy chỉnh, cho phép người lớn dễ thở hơn một chút khi trẻ em bắt đầu tò mò về internet.

# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Giống như { -brand-name-safari } , { -brand-name-firefox } khuyến khích cộng đồng nhà phát triển nhiệt tình của mình tạo <a { $attrs }>các tiện ích bổ sung và tiện ích mở rộng</a> cho trình duyệt. Và vì nền tảng của chúng tôi là mã nguồn mở nên có rất nhiều lựa chọn bổ sung nhiều chức năng.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Ngoài ra, khi bạn đăng ký tài khoản { -brand-name-firefox } bạn có quyền truy cập vào các dịch vụ duy nhất như <a { $pocket }>{ -brand-name-pocket }</a> và <a { $send }>{ -brand-name-send }</a> tích hợp trực tiếp vào trình duyệt. Nút { -brand-name-pocket } cho { -brand-name-firefox } cho phép bạn lưu các trang web và video vào { -brand-name-pocket } chỉ bằng một cú nhấp chuột, vì vậy bạn có thể đọc một phiên bản rõ ràng, không bị phân tâm bất cứ khi nào và bất cứ nơi nào bạn muốn - ngay cả khi ngoại tuyến. Với { -brand-name-send } bạn có thể chia sẻ các tệp lớn bằng mã hóa end-to-end với nhiều biện pháp kiểm soát bảo mật, chẳng hạn như khả năng đặt thời gian hết hạn cho một liên kết tệp hết hạn, số lượng tải xuống và có thêm tùy chọn không mật khẩu cho một lớp bảo mật bổ sung.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Ngoài ra, khi bạn đăng ký tài khoản { -brand-name-firefox } bạn có quyền truy cập vào một số dịch vụ duy nhất như Ảnh chụp màn hình <a { $pocket }>{ -brand-name-pocket }</a> và <a { $send }>{ -brand-name-send }</a> tích hợp trực tiếp vào trình duyệt. Ảnh chụp màn hình là một tính năng được tích hợp ngay trong trình duyệt { -brand-name-firefox } , cho phép bạn sao chép hoặc tải xuống bất kỳ hoặc tất cả các phần của trang web. Khi lưu ảnh chụp màn hình, bạn cũng có thể chọn thư mục bạn muốn tìm ảnh trong đó thay vì làm lộn xộn màn hình. Nút { -brand-name-pocket } cho { -brand-name-firefox } cho phép bạn lưu các trang web và video vào { -brand-name-pocket } chỉ bằng một cú nhấp chuột, vì vậy bạn có thể đọc một phiên bản rõ ràng, không bị phân tâm bất cứ khi nào và bất cứ nơi nào bạn muốn - ngay cả khi ngoại tuyến. Với { -brand-name-send } , bạn có thể chia sẻ các tệp lớn với mã hóa end-to-end và nhiều biện pháp kiểm soát bảo mật, chẳng hạn như khả năng đặt thời gian hết hạn cho một liên kết tệp sẽ hết hạn, số lượng tải xuống và có thêm một mật khẩu tùy chọn cho một lớp bảo mật bổ sung.

# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Ảnh chụp màn hình</a> là một tính năng phổ biến khác được tích hợp ngay trong trình duyệt { -brand-name-firefox } , cho phép bạn dễ dàng chụp ảnh màn hình của mình. Khi bạn chụp ảnh màn hình, bạn có thể chọn sao chép tệp hoặc chọn thư mục bạn muốn tìm tệp đó trong đó, thay vì làm lộn xộn màn hình của bạn.

# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } và { -brand-name-safari } đều cung cấp trải nghiệm liền mạch khi chuyển từ duyệt trên máy tính để bàn sang thiết bị di động hoặc ngược lại. Đối với { -brand-name-safari } , một trong những điểm mạnh chính của nó là các tính năng liên tục. Nó đồng bộ hóa dấu trang, tab, lịch sử của bạn và hơn thế nữa với iCloud để chúng có sẵn trên tất cả các thiết bị của bạn. Điều đó có nghĩa là bạn có thể mở một tab trên { -brand-name-iphone } và nó cũng xuất hiện trên máy tính xách tay { -brand-name-mac } của bạn chỉ bằng một cú nhấp chuột.
compare-safari-both-browsers-have-a-lot = Cả hai trình duyệt đều có rất nhiều tính năng chéo, cũng như một số chức năng độc đáo. Điều đáng nói là, nếu bạn chụp nhiều ảnh màn hình, bạn sẽ tự hỏi mình đã sống như thế nào nếu không có tính năng tiện dụng này được tích hợp ngay trong { -brand-name-firefox } . Nhưng nếu bạn chỉ đang tìm kiếm một trình duyệt nhanh, riêng tư để lướt web và mua sắm, thì bạn có thể muốn { -brand-name-firefox } dùng thử - đặc biệt nếu bạn chỉ sử dụng { -brand-name-safari } vì nó được tải sẵn làm trình duyệt mặc định trên máy tính của bạn. Cuối cùng, bạn sẽ khám phá ra cái nào phù hợp hơn với nhu cầu của bạn.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } cũng cung cấp tính năng đồng bộ hóa tương tự khi bạn đăng ký miễn phí <a { $attrs }>{ -brand-name-firefox-account }</a> cho phép người dùng dễ dàng đồng bộ hóa dấu trang, lịch sử duyệt web, tùy chọn, mật khẩu, biểu mẫu đã điền, tiện ích bổ sung và 25 tab đã mở cuối cùng trên nhiều máy vi tính. Điều làm { -brand-name-firefox } khác biệt với { -brand-name-safari } là nó có sẵn trên bất kỳ nền tảng máy tính để bàn hoặc di động nào, { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } hoặc { -brand-name-macos } , thúc đẩy tính di động của nó trên bất kỳ thiết bị nào bạn có thể sở hữu.

# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Ứng dụng { -brand-name-firefox } cho <a { $ios }>{ -brand-name-ios }</a> và <a { $android }>{ -brand-name-android }</a> là một trong những trình duyệt nhanh nhất hiện có và cũng có các tính năng chống theo dõi và bảo mật vững chắc - một điểm cộng rất lớn nếu bạn thường xuyên di chuyển giữa máy tính xách tay và thiết bị di động.
compare-safari-since-safari-is-apples-proprietary = Vì { -brand-name-safari } là trình duyệt web độc quyền của { -brand-name-apple } , đồng bộ hóa iCloud của nó chỉ hoạt động với các sản phẩm { -brand-name-apple } . Điều này có thể hạn chế phần nào nếu ví dụ: bạn vừa là người dùng { -brand-name-android } người dùng { -brand-name-iphone } hoặc nếu bạn có một máy tính dùng để làm việc { -brand-name-windows } nhưng sử dụng { -brand-name-iphone } làm thiết bị cá nhân của mình.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } làm rất tốt việc làm cho trải nghiệm duyệt web trở nên đơn giản, nhanh chóng và liền mạch nếu bạn là { -brand-name-apple } người dùng có nhiều { -brand-name-apple } sản phẩm. Giống như { -brand-name-safari } , { -brand-name-firefox } là một trình duyệt nhanh và tiện dụng, nhưng quyền riêng tư và khả năng tương thích đa nền tảng là những tính năng xác định của chúng tôi. { -brand-name-firefox } cập nhật mỗi tháng với các tính năng và chức năng mới. Ví dụ: một bản cập nhật gần đây đã bật  <a { $attrs }> Bảo vệ theo dõi nâng cao (ETP) </a>  của chúng tôi theo mặc định cho người dùng mới, tính năng này chặn cookie và trình theo dõi trên nhiều trang web một cách hiệu quả.
compare-safari-in-the-end-it-just-boils = Cuối cùng, nó chỉ tóm gọn những gì bạn đánh giá trong trình duyệt của mình. Nếu bạn được tích hợp với { -brand-name-apple } hệ sinh thái, { -brand-name-safari } vẫn là một lựa chọn tuyệt vời. Nhưng nếu bạn đánh giá cao việc có các biện pháp bảo vệ quyền riêng tư mới nhất và tốt nhất và có thể hoạt động trên nhiều hệ điều hành, chúng tôi nghĩ { -brand-name-firefox } là lựa chọn tốt nhất của bạn. { -brand-name-firefox } cũng là một tùy chọn chắc chắn làm trình duyệt phụ cho những người dùng { -brand-name-apple } độc quyền có thể muốn chuyển sang một trình duyệt khác cho những khoảnh khắc trực tuyến cần thêm các lớp bảo vệ quyền riêng tư.
