# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } a { -brand-name-chrome } : co jest lepsze?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Porównujemy { -brand-name-mozilla } { -brand-name-firefox } z { -brand-name-google } { -brand-name-chrome } pod względem prywatności, użyteczności i przenośności

# Main title.
compare-chrome-comparing-firefox-browser = Porównanie { -brand-name-firefox-browser } z { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = W { -brand-name-firefox } mamy ogromną liczbę oddanych użytkowników, którzy doceniają nasze niezachwiane zaangażowanie w ochronę prywatności online. Na przykład najnowsza wersja { -brand-name-firefox } zawiera funkcję o nazwie Enhanced Tracking Protection (ETP), która jest domyślnie włączona dla wszystkich użytkowników na całym świecie. ETP blokuje ponad 2000 trackerów, w tym społecznościowe trackery od firm takich jak { -brand-name-facebook } , { -brand-name-twitter } i LinkedIn. Posiada również zintegrowaną funkcję <a { $attrs }>{ -brand-name-firefox-monitor }</a> która automatycznie powiadamia Cię, jeśli Twoje hasło zostało złamane lub wymaga aktualizacji. Oprócz tych zabezpieczeń tryb przeglądania prywatnego w { -brand-name-firefox } automatycznie usuwa informacje dotyczące przeglądania, takie jak historia i pliki cookie, nie pozostawiając żadnych śladów po zakończeniu sesji.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = W { -brand-name-firefox } mamy ogromną liczbę oddanych użytkowników, którzy doceniają nasze niezachwiane zaangażowanie w ochronę prywatności online. Na przykład najnowsza wersja { -brand-name-firefox } zawiera funkcję o nazwie Enhanced Tracking Protection (ETP), która jest domyślnie włączona dla wszystkich użytkowników na całym świecie. ETP blokuje ponad 2000 trackerów, w tym społecznościowe trackery od firm takich jak { -brand-name-facebook } , { -brand-name-twitter } i LinkedIn. Posiada również zintegrowaną funkcję <a { $attrs }>{ -brand-name-firefox-monitor }</a> która automatycznie powiadamia Cię, jeśli Twoje hasło zostało złamane lub wymaga aktualizacji. Oprócz tych zabezpieczeń tryb przeglądania prywatnego w { -brand-name-firefox } automatycznie usuwa informacje przeglądania, takie jak historia i pliki cookie, nie pozostawiając żadnych śladów po zakończeniu sesji.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Niedawno potwierdziliśmy również nasze zaangażowanie w ochronę prywatności i przejrzystości danych użytkowników w naszej najnowszej Polityce <a { $attrs }>prywatności, w</a> której stwierdza się: „W Mozilli uważamy, że prywatność jest podstawą zdrowego internetu”.
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } to na wszystkich kontach bezpieczna przeglądarka z takimi funkcjami, jak { -brand-name-google } Bezpieczne przeglądanie, które pomaga chronić użytkowników, wyświetlając niemożliwe do przeoczenia ostrzeżenie, gdy próbują przejść do niebezpiecznych witryn lub pobrać niebezpieczne pliki.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Ostatecznie to Ty decydujesz, czy lub nie wyznaczyć granicę, udostępniając takie rzeczy, jak historia wyszukiwania i historia zakupów. Ale jeśli jesteś podobny do większości ludzi, prawdopodobnie szukałeś w Internecie pewnych rzeczy, które wolałbyś zachować dla siebie.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = W dzisiejszych czasach konkurencja w przeglądarkach zmieniła się i wiele osób zaczyna zastanawiać się, co dzieje się z ich danymi online, takimi jak historia przeglądania, hasła i inne poufne informacje. Wiele się zmieniło od 2008 roku, kiedy na scenie pojawił się { -brand-name-chrome } . W firmie { -brand-name-firefox } pracowaliśmy nad przeprojektowaniem naszego interfejsu i zapewnieniem użytkownikom coraz większej liczby ulepszeń w zakresie prywatności i wydajności, a także wielu przydatnych narzędzi przeglądarki.
compare-chrome-and-so-here-we-are-the-browser = I oto jesteśmy, wojny przeglądarek ponownie nasilają się i nadszedł czas, aby ponownie ocenić i porównać { -brand-name-firefox-browser } z { -brand-name-google } { -brand-name-chrome } .
compare-chrome-in-2008-google-introduced = W 2008 roku firma { -brand-name-google } wprowadziła { -brand-name-chrome } , a jej wpływ jako innowacji w technologii przeglądarek był natychmiastowy. Był szybszy do ładowania witryn, zajmował minimalną przestrzeń na ekranie i oferował niezaprzeczalnie prosty interfejs użytkownika.
compare-chrome-in-fact-both-chrome-and-firefox = W rzeczywistości zarówno { -brand-name-chrome } i { -brand-name-firefox } mają rygorystyczne zabezpieczenia. Obie zawierają coś, co nazywa się „piaskownicą”, która oddziela procesy przeglądarki, aby coś w rodzaju szkodliwej witryny nie infekowało innych części laptopa ani innego urządzenia.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Chociaż { -brand-name-chrome } okazuje się bezpieczną przeglądarką internetową, jej dane dotyczące prywatności są wątpliwe. { -brand-name-google } rzeczywistości gromadzi niepokojąco duże ilości danych od swoich użytkowników, w tym lokalizację, historię wyszukiwania i odwiedziny w witrynie. { -brand-name-google } opowiada się za gromadzeniem danych, twierdząc, że robi to w celu ulepszenia swoich usług - na przykład pomaga znaleźć sweter lub kawiarnię, taką jak ta, którą wcześniej kupiłeś lub odwiedziłeś. Jednak inni mogą się nie zgodzić, zwracając uwagę, że { -brand-name-google } rzeczywistości gromadzi bezprecedensową ilość danych do własnych celów marketingowych. Reklamują, że chronią Twoje informacje przed hakerami, ale to nie ma znaczenia. Sam { -brand-name-google } zarządza największą na świecie siecią reklamową, w dużej mierze dzięki danym, które zbierają od swoich użytkowników.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = Jeśli chodzi o funkcje, zarówno { -brand-name-firefox } i { -brand-name-chrome } oferują dużą bibliotekę rozszerzeń i wtyczek, przy czym katalog { -brand-name-chrome } znacznie przewyższa liczbę innych przeglądarek, a jednocześnie dobrze integruje się z innymi { -brand-name-google } usługami, takimi jak Gmail i { -brand-name-google } Dokumenty.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } ma również funkcję synchronizacji, która pozwala zobaczyć otwarte i ostatnio używane karty, historię przeglądania i zakładki na wszystkich Twoich urządzeniach.
compare-chrome-while-chrome-gets-the-nod = Podczas gdy { -brand-name-chrome } zyskuje uznanie dzięki dodatkom i rozszerzeniom, { -brand-name-firefox } ma ładnie dobrany zestaw wbudowanych funkcji, takich jak niezwykle przydatne narzędzie do przechwytywania ekranu i funkcja trybu czytania, która usuwa wszystko ze strony oprócz tekst z artykułu, który czytasz.
compare-chrome-although-not-as-extensive = Chociaż nie jest tak obszerna jak biblioteka dodatków { -brand-name-chrome } , { -brand-name-firefox } , jako oprogramowanie typu open source z ogromną liczbą aktywnych współpracowników, zawiera również niesamowitą liczbę przydatnych rozszerzeń.
compare-chrome-if-having-tons-of-open-tabs = Jeśli masz mnóstwo otwartych kart, to naprawdę sprowadza się to do preferencji interfejsu użytkownika. { -brand-name-firefox } umożliwia przewijanie w poziomie na wszystkich otwartych kartach, zamiast zmniejszać je coraz mniejsze przy każdej nowej. { -brand-name-google } { -brand-name-chrome } woli je zmniejszyć, więc widoczna jest tylko ikona ulubionych. Jedynym problemem jest to, że masz otwartych wiele kart z tej samej witryny, więc widzisz tę samą ikonę ulubionych na wszystkich kartach.
compare-chrome-almost-needless-to-say-versions = Nie trzeba dodawać, że wersje { -brand-name-firefox } i { -brand-name-chrome } są dostępne dla najpopularniejszych systemów operacyjnych na komputery stacjonarne i urządzenia przenośne ( { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ).
compare-chrome-both-chrome-and-firefox-also = Zarówno { -brand-name-chrome } i { -brand-name-firefox } umożliwiają także synchronizację haseł, zakładek i otwartych kart na wszystkich urządzeniach. Jeśli masz konto { -brand-name-firefox } , możesz ręcznie wysłać otwartą kartę z komputera stacjonarnego na urządzenie przenośne lub odwrotnie. W przypadku { -brand-name-chrome } dzieje się to automatycznie, jeśli wybrałeś to ustawienie w swoich preferencjach. Brak konieczności ręcznego wysyłania karty z jednego urządzenia na drugie jest wygodny, gdy chcesz zrobić coś takiego, jak kontynuowanie czytania artykułu, którego wcześniej nie skończyłeś. Jednak mogą wystąpić sytuacje, w których automatyczna synchronizacja może nie być idealna, jeśli istnieje prawdopodobieństwo, że wielu użytkowników przegląda witrynę po zalogowaniu się na konto { -brand-name-google } .

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Uważamy, że można śmiało powiedzieć, że { -brand-name-firefox } i { -brand-name-chrome } są naprawdę łeb w łeb pod względem przenośności i użyteczności, przy czym { -brand-name-chrome } ma niewielką przewagę użytkową ze względu na ogromną bibliotekę rozszerzeń i funkcji dodatkowych. Jednak jeśli chodzi o prywatność, { -brand-name-firefox } wygrywa dzień dzięki naszemu zaangażowaniu w ochronę danych online naszych użytkowników i świadczenie bezpłatnych, gotowych usług, takich jak menedżery haseł, które również powiadamiają Cię, jeśli zdarzy się, że dojdzie do naruszenia danych uwierzytelniających.
compare-chrome-as-for-customization-our = Jeśli chodzi o dostosowywanie, nasi fani powiedzą Ci, że jedną z rzeczy, które najbardziej lubią w naszej przeglądarce, jest możliwość przenoszenia i aranżacji większości elementów interfejsu użytkownika, tak aby najlepiej odpowiadały Twoim potrzebom. { -brand-name-chrome } umożliwia ukrycie niektórych elementów interfejsu użytkownika, ale nie ma zbyt wiele możliwości przenoszenia elementów zgodnie z własnymi preferencjami (jeśli w ogóle). Należy jednak zauważyć, że zarówno { -brand-name-chrome } i { -brand-name-firefox } ułatwiają zmianę wyglądu i motywu przeglądarki.
compare-chrome-for-practical-purposes-theres = Ze względów praktycznych oczywiście nic nie stoi na przeszkodzie, aby korzystać z obu przeglądarek - { -brand-name-firefox } w tych momentach życia, w których prywatność jest naprawdę ważna, i { -brand-name-chrome } jeśli nadal inwestujesz w ekosystem { -brand-name-google } . Jednak wraz z rosnącą liczbą wtargnięć na nasze dane osobowe { -brand-name-firefox } może okazać się na dłuższą metę właściwym wyborem dla tych z nas, którzy cenią sobie ochronę naszej prywatności w Internecie.
