# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Siedem najlepszych przeglądarek w bezpośrednim porównaniu
compare-index-six-of-the-best-browsers-fallback = Sześć najlepszych przeglądarek w bezpośrednim porównaniu

# Sub-headline
compare-index-privacy-utility-portability = Prywatność. Użyteczność. Ruchliwość.

# HTML page description
compare-index-a-great-internet-browser-should = Dobra przeglądarka internetowa powinna mieć potrzebną funkcjonalność, możliwość przenoszenia między urządzeniami i prywatność, na którą zasługujesz.
compare-index-which-browser-is-best-at-keeping = Która przeglądarka najlepiej zachowuje poufność?
compare-index-its-not-unreasonable-to-expect = Oczekiwanie wysokiego poziomu ochrony danych i prywatności od produktów, z których regularnie korzystamy, nie jest nierozsądne. Przeglądarka powinna przynajmniej oferować jakąś wersję „trybu przeglądania prywatnego”, który automatycznie usuwa historię i historię wyszukiwania, aby inni użytkownicy tego samego komputera nie mogli uzyskać do nich dostępu. W tym obszarze wszystkie siedem porównywanych przeglądarek zdobywa punkty.
compare-index-its-not-unreasonable-to-expect-fallback = Oczekiwanie wysokiego poziomu ochrony danych i prywatności od produktów, z których regularnie korzystamy, nie jest nierozsądne. Przeglądarka powinna przynajmniej oferować jakąś wersję „trybu przeglądania prywatnego”, który automatycznie usuwa historię i historię wyszukiwania, aby inni użytkownicy tego samego komputera nie mogli uzyskać do nich dostępu. W tym obszarze wszystkie sześć porównywanych przeglądarek zdobywa punkty.
compare-index-what-you-do-online-literally = To, co robisz online, nie powinno być sprawą nikogo innego.
compare-index-another-browser-feature-that = Kolejną funkcją przeglądarki, którą należy podać, jest możliwość zapobiegania śledzeniu przez strony internetowe i firmy danych dotyczących przeglądania i zakupów - nawet w normalnym trybie przeglądania.
compare-index-another-browser-feature-fallback = Kolejną funkcją przeglądarki, którą należy podać, jest możliwość zapobiegania śledzeniu przez strony internetowe i firmy danych dotyczących przeglądania i zakupów - nawet w normalnym trybie przeglądania. W rzeczywistości tak nie jest. W rzeczywistości jedynymi przeglądarkami, które domyślnie blokują śledzące pliki cookie innych firm, są { -brand-name-firefox } i { -brand-name-safari } .
compare-index-using-a-browser-that-blocks = Korzystanie z przeglądarki, która blokuje narzędzia śledzące innych firm, jest nie tylko ważne dla prywatności - zwykle oznacza również, że działa znacznie szybciej. Większość trackerów to po prostu skrypty działające w tle na wielu stronach internetowych. Nie możesz ich zobaczyć, ale możesz poczuć, że spowalniają Twoją przeglądarkę. Począwszy od wersji 67 { -brand-name-firefox } , odciski palców i kryptominy są również blokowane. Jeśli nie znasz kryptominerów, oto przykład tego, jak mogą na Ciebie wpłynąć: być może zdarzyło Ci się, że Twój komputer nagle stał się cieplejszy lub bateria wyczerpała się szybciej niż zwykle. To często produkt uboczny kryptominerów pełzających po twoim urządzeniu.
compare-index-what-has-your-browser-done = Co ostatnio zrobiła dla Ciebie Twoja przeglądarka?
compare-index-in-addition-to-privacy-protection = Oprócz ochrony prywatności, która w dużej mierze odbywa się w tle przeglądarki, kolejnym kluczowym składnikiem dobrze wykonanej przeglądarki jest rzeczywisty interfejs użytkownika i funkcjonalność. Prawie wszystkie siedem przeglądarek jest równych pod względem przeglądania kart, zarządzania zakładkami, automatycznego uzupełniania, korekty i rozszerzeń. { -brand-name-firefox } , { -brand-name-edge } i { -brand-name-opera } oferują również szybką funkcję zrzutu ekranu, która okazuje się bardzo przydatna i zdecydowanie brakuje jej, gdy przełączasz się na przeglądarkę bez niej.
compare-index-in-addition-to-privacy-protection-fallback = Oprócz ochrony prywatności, która w dużej mierze odbywa się w tle przeglądarki, kolejnym kluczowym składnikiem dobrze wykonanej przeglądarki jest rzeczywisty interfejs użytkownika i funkcjonalność. Prawie wszystkie sześć przeglądarek jest równych pod względem przeglądania kart, zarządzania zakładkami, automatycznego uzupełniania, korekty i rozszerzeń. { -brand-name-firefox } , { -brand-name-edge } i { -brand-name-opera } oferują również szybką funkcję zrzutu ekranu, która okazuje się bardzo przydatna i zdecydowanie brakuje jej, gdy przełączasz się na przeglądarkę bez niej.
compare-index-how-well-does-your-browser = Jak dobrze Twoja przeglądarka działa na Twoich urządzeniach?
compare-index-almost-all-of-the-browsers = Prawie wszystkie porównywane tutaj przeglądarki umożliwiają synchronizację między komputerem a urządzeniami mobilnymi. Aby to zrobić, będziesz potrzebować konta, którego możesz używać do logowania się do przeglądarki na wszystkich urządzeniach i synchronizowania takich elementów, jak hasła, historia przeglądania, zakładki i ustawienia.
compare-index-conclusion = Wniosek:
compare-index-and-the-winner-is = A zwycięzcą jest…
compare-index-find-out-how-firefox-chrome = Dowiedz się, czym { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } i { -brand-name-ie } różnią się pod względem prywatności, użyteczności i przenośności.
compare-index-find-out-how-firefox-fallback = Dowiedz się, czym różnią się { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } i { -brand-name-ie } pod względem prywatności, użyteczności i przenośności.
compare-index-looking-for-a-better-browser = Szukasz lepszej przeglądarki? Porównamy { -brand-name-firefox } z { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } i { -brand-name-ie } aby pomóc Ci podjąć decyzję.
compare-index-looking-for-a-better-fallback = Szukasz lepszej przeglądarki? Porównamy { -brand-name-firefox } z { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } i { -brand-name-ie } aby pomóc Ci podjąć decyzję.
compare-index-so-is-your-browser-the-best = Czy Twoja przeglądarka jest najlepsza do tego, co robisz online? Właściwa przeglądarka może mieć duży wpływ na sposób korzystania z sieci. Zatem bez zbędnych ceregieli porównajmy { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } , { -brand-name-microsoft } { -brand-name-ie } i { -brand-name-edge } - i zobaczmy, który najlepiej odpowiada Twoim potrzebom.
compare-index-so-is-your-browser-the-fallback = Czy Twoja przeglądarka jest najlepsza do tego, co robisz online? Właściwa przeglądarka może mieć duży wpływ na sposób korzystania z sieci. Zatem bez zbędnych ceregieli porównajmy { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-microsoft } { -brand-name-ie } i { -brand-name-edge } - i zobaczmy, który najlepiej odpowiada Twoim potrzebom.
compare-index-since-your-browser-is-your = Ponieważ Twoja przeglądarka jest Twoją bramą do Internetu, szybkość, bezpieczeństwo, prywatność i użyteczność są najważniejsze. W ostatnich latach { -brand-name-google } { -brand-name-chrome } była przeglądarką wybieraną przez wielu użytkowników. Ale w czasach, gdy reklamy internetowe pojawiają się wszędzie, a wycieki danych są stałym elementem nagłówków wiadomości, wiele osób zaczyna wymagać od przeglądarki większej prywatności i szacunku.
compare-index-the-first-thing-to-point-out = Pierwszą rzeczą, na którą należy zwrócić uwagę w kwestii przenośności, jest to, że nie wszystkie przeglądarki działają we wszystkich systemach operacyjnych. Chociaż { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-brave } i { -brand-name-opera } działają na wszystkich głównych systemach i są łatwe w instalacji, { -brand-name-ie } i { -brand-name-safari } działają tylko w { -brand-name-microsoft } i własnych systemach Apple. Mobilna wersja { -brand-name-safari } jest fabrycznie zainstalowana na urządzeniach mobilnych Apple, a większość urządzeń { -brand-name-android } ma fabrycznie zainstalowaną przeglądarkę zmodyfikowaną przez producenta dla danego urządzenia. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-brave } , { -brand-name-edge } i { -brand-name-opera } można łatwo zainstalować, a nawet używać obok siebie.
compare-index-the-first-thing-to-point-fallback = Pierwszą rzeczą, na którą należy zwrócić uwagę w kwestii przenośności, jest to, że nie wszystkie przeglądarki działają we wszystkich systemach operacyjnych. Chociaż { -brand-name-firefox } , { -brand-name-chrome } i { -brand-name-opera } działają we wszystkich głównych systemach i są łatwe w instalacji, { -brand-name-ie } , { -brand-name-edge } i { -brand-name-safari } działają tylko w { -brand-name-microsoft } i własnych systemach Apple. Mobilna wersja { -brand-name-safari } jest fabrycznie instalowana na urządzeniach mobilnych Apple, a większość urządzeń { -brand-name-android } ma fabrycznie zainstalowaną przeglądarkę zmodyfikowaną przez producenta dla danego urządzenia. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } i { -brand-name-opera } można łatwo zainstalować, a nawet używać obok siebie.
compare-index-browsers-have-come-a-long = Przeglądarki przeszły długą drogę, odkąd { -brand-name-chrome } został wprowadzony i przejął udział w rynku. Większość nowoczesnych przeglądarek wypełniła lukę pod względem przenośności i funkcjonalności, aw niektórych obszarach, takich jak szybkość i prywatność, faktycznie przekroczyła poziom { -brand-name-chrome } . Jednak określenie, która przeglądarka jest dla Ciebie odpowiednia, zawsze będzie zależeć od Twoich indywidualnych potrzeb i tego, co cenisz najbardziej podczas nawigacji online.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } jest wspierany przez organizację non-profit { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } stawia Twoją prywatność na pierwszym miejscu - we wszystkim, co robimy i robimy. Uważamy, że masz prawo decydować, w jaki sposób i komu udostępniasz swoje dane osobowe. { -brand-name-firefox } zbiera jak najmniej danych i nigdy ich nie sprzedaje. Małe dane, które zbieramy, służą tylko do ulepszania produktów i funkcji. Żadnych tajemnic. Ale dużo przejrzystości i prawdziwej prywatności.
compare-index-based-on-the-criteria-we-outlined = W oparciu o przedstawione przez nas kryteria - prywatność, użyteczność i przenośność - tak naprawdę tylko jedna przeglądarka spełnia ten warunek - { -brand-name-firefox } . Prawdziwym obszarem różnicy nie jest funkcjonalność, ale prywatność. { -brand-name-firefox } to najbardziej prywatna przeglądarka, która nie blokuje Cię w ekosystemie. Używaj go w dowolnym systemie operacyjnym, na wszystkich urządzeniach i poczuj się bezpiecznie.
