# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } a { -brand-name-safari } : Która przeglądarka jest dla Ciebie lepsza?

# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } to wstępnie zainstalowana przeglądarka w { -brand-name-mac } i { -brand-name-iphone } . Porównaj { -brand-name-safari } z { -brand-name-firefox-browser } aby dowiedzieć się, która przeglądarka jest dla Ciebie lepsza.

# Main title.
compare-safari-comparing-firefox-browser = Porównanie { -brand-name-firefox-browser } z { -brand-name-apple } { -brand-name-safari }

# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Jeśli używasz komputera Mac lub masz { -brand-name-iphone } , prawdopodobnie znasz przeglądarkę internetową { -brand-name-safari } . Fakt, że jest on wstępnie zainstalowany jako domyślna przeglądarka dla użytkowników produktu { -brand-name-apple } zdecydowanie daje mu wczesną przewagę, ale { -brand-name-firefox } ma własny zestaw przydatnych funkcji, które czynią go atrakcyjną alternatywą. W tym miejscu omówimy główne różnice między naszą przeglądarką a { -brand-name-safari } pod względem prywatności, użyteczności i przenośności między urządzeniami.

# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Prywatność stała się gorącym tematem dla firm technologicznych, ponieważ zdają sobie sprawę, że coraz więcej osób czuje się podatnych na takie rzeczy, jak naruszenia danych, narzędzia do śledzenia reklam i hakerzy. Ale jeśli chodzi o rzeczywiste narzędzia, których ludzie używają do poruszania się po rzeczywistych interwebach, czy to wszystko mówi, czy faktycznie podejmują działania, aby chronić twoje dane?
compare-safari-as-alluded-to-before-apple-fallback = Jak wspomniano wcześniej, { -brand-name-apple } jest jedną z tych firm, które niedawno zdecydowały się zintensyfikować swoją grę w prywatność. Niedawno { -brand-name-apple } wdrożyliśmy zapobieganie śledzeniu w wielu witrynach w { -brand-name-safari } , które zapobiega śledzeniu Cię przez reklamy w internecie. { -brand-name-safari } oferuje również sugestię silnego hasła podczas rejestracji nowego konta w dowolnej witrynie internetowej. A jeśli zainwestowałeś w ekosystem iCloud, bezpiecznie synchronizuje to hasło z innymi urządzeniami, więc nigdy nie musisz go pamiętać.

# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Podobnie jak { -brand-name-safari } , w { -brand-name-firefox } skupiliśmy się na prywatności i bezpieczeństwie. Ale w przeciwieństwie do { -brand-name-safari } , od dawna stoimy na pudełku z mydłem zapewniającym prywatność. W rzeczywistości { -brand-name-mozilla } (nasza firma macierzysta) była jednym z pierwszych głosów w społeczności techników, którzy wszczęli alarm dotyczący prywatności w Internecie.

# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Nasz tryb przeglądania prywatnego blokuje elementy śledzące i usuwa Twoje hasła, pliki cookie i historię za każdym razem, gdy go zamykasz. Ale możesz także korzystać z naszych zaawansowanych funkcji prywatności nawet w zwykłym trybie przeglądania. W najnowszym wydaniu { -brand-name-firefox } ulepszona ochrona przed śledzeniem jest domyślnie włączona. Zapobiega to śledzeniu Cię przez elementy takie jak cross-site tracker, gdy skaczesz po sieci. Ponadto, ponieważ { -brand-name-facebook } jest niemal codziennie łapany na problemy z prywatnością, nasze rozszerzenie <a { $attrs }>{ -brand-name-facebook-container }</a> ma wiele sensu. Utrudnia { -brand-name-facebook } śledzenie Cię w sieci - podobnie jak { -brand-name-safari } zapobiega śledzeniu w wielu witrynach - ale { -brand-name-firefox } rzeczywistości izoluje sesję { -brand-name-facebook } w oddzielnym kontenerze blokującym { -brand-name-facebook } śledzenie co robisz na innych stronach internetowych. Dlaczego i tak muszą wiedzieć, co wyszukujesz w WebMD?

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = Jeśli chodzi o bezpieczeństwo, { -brand-name-firefox } jest tam solidny. Za każdym razem, gdy jesteś w { -brand-name-firefox } , możesz kliknąć prawym przyciskiem myszy pole hasła, aby bezpiecznie wygenerować silne hasło za pomocą opcji Wypełnij hasło. Gdy zapiszesz nowe hasło, poprosimy Cię o zapisanie we wbudowanym menedżerze haseł, <a { $lockwise }>{ -brand-name-lockwise }</a> . Udostępniamy również użytkownikom i posiadaczom kont inny darmowy i przydatny produkt o nazwie <a { $monitor }>{ -brand-name-monitor }</a> który automatycznie ostrzega, jeśli Twoje dane zostaną uwzględnione w znanym wycieku danych.
compare-safari-if-you-choose-to-use-safari = Decydując się na używanie { -brand-name-safari } , jesteś w dobrych rękach, o ile używasz urządzenia { -brand-name-apple } . Ale { -brand-name-safari } działa tylko na urządzeniach { -brand-name-apple } , podczas gdy { -brand-name-firefox } działa na { -brand-name-windows } , { -brand-name-mac } , { -brand-name-ios } , { -brand-name-android } i { -brand-name-linux } . Dlatego niezależnie od wybranego systemu operacyjnego { -brand-name-firefox } zapewni Ci nasze zabezpieczenia i ochronę prywatności.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } jest powszechnie znana ze swojego zamkniętego ekosystemu, ponieważ odnosi się do tworzenia oprogramowania dla swoich produktów. Ale w { -brand-name-app-store } oferuje programistom sekcję do tworzenia wtyczek i dodatków, aby uczynić przeglądarkę bardziej niezawodną. Te rozszerzenia można również przeglądać za pośrednictwem { -brand-name-app-store } i łatwo dodawać do { -brand-name-safari } .
compare-safari-in-addition-to-the-regular = Oprócz zwykłego zestawu funkcji, których można oczekiwać w przeglądarce, takich jak przeglądanie na kartach i przeglądanie prywatne, { -brand-name-safari } ma również kilka nieoczekiwanych funkcji. Na przykład, jeśli użytkownik kliknie prawym przyciskiem myszy słowo w dowolnym miejscu na stronie wewnątrz { -brand-name-safari } , a następnie kliknie polecenie Wyszukaj, otrzyma definicję słownikową oraz wpisy z tezaurusa, { -brand-name-app-store } , filmów i nie tylko. Funkcję kontroli rodzicielskiej { -brand-name-safari } można łatwo dostosować, umożliwiając dorosłym nieco łatwiejsze oddychanie, gdy dzieci zaczynają interesować się Internetem.

# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Podobnie jak { -brand-name-safari } , { -brand-name-firefox } zachęca swoją entuzjastyczną społeczność programistów do tworzenia <a { $attrs }>dodatków i rozszerzeń</a> do przeglądarki. A ponieważ nasza platforma jest open-source, istnieje szeroki wybór oferujący bogactwo funkcji.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Ponadto po założeniu konta { -brand-name-firefox } uzyskujesz dostęp do unikalnych usług, takich jak <a { $pocket }>{ -brand-name-pocket }</a> i <a { $send }>{ -brand-name-send }</a> które integrują się bezpośrednio z przeglądarką. Przycisk { -brand-name-pocket } dla { -brand-name-firefox } umożliwia zapisywanie stron internetowych i filmów w { -brand-name-pocket } jednym kliknięciem, dzięki czemu możesz czytać przejrzystą, wolną od rozpraszania wersję wersję, kiedy i gdzie chcesz - nawet offline. Dzięki { -brand-name-send } możesz udostępniać duże pliki za pomocą pełnego szyfrowania z różnymi kontrolami bezpieczeństwa, takimi jak możliwość ustawienia czasu wygaśnięcia łącza do pliku, liczby pobrań i tego, czy dodać opcjonalny hasło dla dodatkowej warstwy bezpieczeństwa.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Ponadto po założeniu konta { -brand-name-firefox } uzyskujesz dostęp do niektórych unikalnych usług, takich jak zrzuty ekranu <a { $pocket }>{ -brand-name-pocket }</a> i <a { $send }>{ -brand-name-send }</a> które integrują się bezpośrednio z przeglądarką. Zrzuty ekranu to funkcja wbudowana bezpośrednio w przeglądarkę { -brand-name-firefox } , która umożliwia kopiowanie lub pobieranie dowolnej lub części strony internetowej. Zapisując zrzut ekranu, możesz także wybrać folder, w którym chcesz go znaleźć, zamiast zaśmiecać pulpit. Przycisk { -brand-name-pocket } dla { -brand-name-firefox } umożliwia zapisywanie stron internetowych i filmów w { -brand-name-pocket } jednym kliknięciem, dzięki czemu możesz czytać przejrzystą, wolną od rozpraszania wersję wersję, kiedykolwiek i gdziekolwiek chcesz - nawet offline. Dzięki { -brand-name-send } możesz udostępniać duże pliki przy użyciu pełnego szyfrowania i różnych kontroli bezpieczeństwa, takich jak możliwość ustawienia czasu wygaśnięcia łącza do pliku, liczby pobrań i tego, czy dodać opcjonalne hasło dla dodatkowej warstwy bezpieczeństwa.

# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Zrzuty ekranu</a> to kolejna popularna funkcja wbudowana bezpośrednio w przeglądarkę { -brand-name-firefox } , która umożliwia łatwe przechwytywanie obrazu ekranu. Robiąc zrzut ekranu, możesz skopiować plik lub wybrać folder, w którym chcesz go znaleźć, zamiast zaśmiecać pulpit.

# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } i { -brand-name-safari } zapewniają bezproblemową obsługę podczas przechodzenia z przeglądania na komputerze do przeglądania mobilnego i odwrotnie. W przypadku { -brand-name-safari } jedną z jego głównych zalet są cechy ciągłości. Synchronizuje Twoje zakładki, karty, historię i inne dane z iCloud, dzięki czemu są one dostępne na wszystkich Twoich urządzeniach. Oznacza to, że jednym kliknięciem możesz otworzyć kartę na swoim { -brand-name-iphone } i wyświetlić ją również na swoim laptopie { -brand-name-mac } .
compare-safari-both-browsers-have-a-lot = Obie przeglądarki mają wiele funkcji crossover, a także kilka unikalnych funkcji. Warto wspomnieć, że jeśli zrobisz dużo zrzutów ekranu, będziesz się zastanawiać, jak żyłeś bez tej przydatnej funkcji wbudowanej bezpośrednio w { -brand-name-firefox } . Ale jeśli szukasz tylko szybkiej, prywatnej przeglądarki do surfowania i robienia zakupów, możesz { -brand-name-firefox } spróbować - zwłaszcza jeśli korzystałeś wyłącznie z { -brand-name-safari } ponieważ jest ona wstępnie załadowana jako domyślna przeglądarka w Twój komputer. W końcu odkryjesz, który z nich bardziej odpowiada Twoim potrzebom.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } oferuje również podobną funkcję synchronizacji po zarejestrowaniu się w bezpłatnej <a { $attrs }>{ -brand-name-firefox-account }</a> która umożliwia użytkownikom łatwą synchronizację zakładek, historii przeglądania, preferencji, haseł, wypełnionych formularzy, dodatków i ostatnich 25 otwartych kart w wielu komputery. To, co odróżnia { -brand-name-firefox } od { -brand-name-safari } polega na tym, że jest dostępny na dowolnej platformie stacjonarnej lub mobilnej { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } lub { -brand-name-macos } , co zwiększa jego przenośność na każdym posiadanym urządzeniu.

# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Aplikacja { -brand-name-firefox } dla <a { $ios }>{ -brand-name-ios }</a> i <a { $android }>{ -brand-name-android }</a> jest jedną z najszybszych dostępnych przeglądarek, a także ma solidne zabezpieczenia i funkcje zapobiegające śledzeniu - to ogromny plus, jeśli ciągle skaczesz między laptopem a urządzeniami mobilnymi.
compare-safari-since-safari-is-apples-proprietary = Ponieważ { -brand-name-safari } to zastrzeżona przeglądarka internetowa firmy { -brand-name-apple } , jej synchronizacja iCloud działa wyłącznie z produktami { -brand-name-apple } . Może to być nieco ograniczone, jeśli na przykład jesteś zarówno użytkownikiem { -brand-name-android } i { -brand-name-iphone } lub jeśli masz komputer PC z systemem { -brand-name-windows } do pracy, ale używasz { -brand-name-iphone } jako urządzenia osobistego.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } świetnie radzi sobie z prostym, szybkim i bezproblemowym przeglądaniem, jeśli jesteś { -brand-name-apple } użytkownikiem korzystającym z wielu { -brand-name-apple } produktów. Podobnie jak { -brand-name-safari } , { -brand-name-firefox } jest szybką i praktyczną przeglądarką, ale prywatność i kompatybilność z różnymi platformami to nasze cechy, które definiujemy. { -brand-name-firefox } aktualizuje się co miesiąc o nowe funkcje i możliwości. Na przykład jedna ostatnia aktualizacja domyślnie włączyła naszą  <a { $attrs }> Enhanced Tracking Protection (ETP) </a>  dla nowych użytkowników, która skutecznie blokuje pliki cookie i elementy śledzące między witrynami.
compare-safari-in-the-end-it-just-boils = Ostatecznie sprowadza się to po prostu do tego, co cenisz w przeglądarce. Jeśli jesteś zintegrowany z { -brand-name-apple } ekosystemem, { -brand-name-safari } to nadal doskonały wybór. Jeśli jednak cenisz sobie najnowsze i najlepsze zabezpieczenia prywatności oraz możliwość pracy w wielu systemach operacyjnych, uważamy, że najlepszym rozwiązaniem jest { -brand-name-firefox } . { -brand-name-firefox } to również solidna opcja jako dodatkowa przeglądarka dla tych { -brand-name-apple } -wyłącznych użytkowników, którzy mogą chcieć przełączyć się na inną przeglądarkę w chwilach online, które wymagają dodatkowych warstw ochrony prywatności.
