# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/edge/

# HTML page title.
compare-edge-firefox-vs-microsoft-edge-which = { -brand-name-firefox } frente a { -brand-name-microsoft } { -brand-name-edge } : ¿Cuál es el mejor navegador para usted?

# HTML page description.
compare-edge-compare-microsoft-edge-to-the = Compare { -brand-name-microsoft } { -brand-name-edge } con { -brand-name-firefox-browser } para averiguar cuál es el mejor navegador para usted.

# Main title.
compare-edge-comparing-firefox-browser-with = Comparando { -brand-name-firefox-browser } con { -brand-name-microsoft } { -brand-name-edge }
compare-edge-with-windows-10-microsoft-introduced = Con { -brand-name-windows } 10, { -brand-name-microsoft } presentó su { -brand-name-edge } navegador para competir con { -brand-name-firefox } y { -brand-name-chrome } convirtió en el navegador predeterminado preinstalado en millones de PC vendidos. Aun así, los usuarios tardaron en adoptarlo y { -brand-name-microsoft } finalmente anunciaron planes para relanzar { -brand-name-edge } como un navegador basado en { -brand-name-chromium } ( { -brand-name-chromium } por supuesto es el proyecto de navegador de código abierto de { -brand-name-google } ).
compare-edge-here-well-compare-our-firefox = Aquí compararemos nuestro { -brand-name-firefox-browser } con el { -brand-name-chromium } basado { -brand-name-microsoft } { -brand-name-edge } en términos de privacidad, utilidad y portabilidad, para ayudarlo a comprender mejor qué navegador se adapta mejor a sus necesidades y preferencias.

# "SmartScreen" and "Windows Hello" are brand names.
compare-edge-edge-is-integrated-into-the = { -brand-name-edge } está integrado en la plataforma { -brand-name-windows } 10 y se ejecuta en un entorno de zona de pruebas, lo que significa que aísla los programas y evita que los programas malintencionados espíen su computadora. Tiene una SmartScreen incorporada que analiza la reputación de los sitios que visita y bloquea los sitios sospechosos. Para mejorar la privacidad, { -brand-name-edge } permite usar datos biométricos o un PIN con { -brand-name-edge } Hola en lugar de contraseñas para la autenticación en línea.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-we-pride-ourselves = En { -brand-name-firefox } , nos enorgullecemos de proteger la seguridad y la privacidad de nuestros usuarios. Nuestra <a { $attrs }>política de privacidad</a> es transparente y en un lenguaje sencillo. De hecho, trabajamos mucho para asegurarnos de que fuera sencillo y fácil de leer. Con la Protección de seguimiento mejorada ahora activada de forma predeterminada, bloqueamos más de 2000 rastreadores automáticamente. Los rastreadores son esos pequeños fragmentos de código que intentan reconstruir lo que está haciendo en varios sitios de Internet para crear una imagen compuesta y detallada de quién es usted, comprometiendo su privacidad solo para orientar mejores anuncios.

# Variables:
#   $attrs (string) - link to /privacy/firefox/ with additional attributes for analytics
compare-edge-at-firefox-our-privacy-fallback = En { -brand-name-firefox } , nuestra <a { $attrs }>política de privacidad</a> es transparente y está en un lenguaje sencillo. De hecho, trabajamos mucho para asegurarnos de que fuera sencillo y fácil de leer. Estamos orgullosos de proteger la seguridad y privacidad de nuestros usuarios. Con la Protección de seguimiento mejorada ahora activada de forma predeterminada, bloqueamos más de 2000 rastreadores automáticamente. Los rastreadores son esos pequeños fragmentos de código que intentan reconstruir lo que está haciendo en varios sitios de Internet para crear una imagen compuesta y detallada de quién es usted, comprometiendo su privacidad solo para orientar mejores anuncios.

# Variables:
#   $attrs (string) - link to /firefox/privacy/products/ with additional attributes for analytics
compare-edge-your-privacy-protections-shows = Your <a { $attrs }>Privacy Protections le</a> muestra los rastreadores y las cookies que las páginas han intentado dejar y cuántos { -brand-name-firefox } ha bloqueado para usted.

# "InPrivate" is a brand name.
compare-edge-in-firefox-private-browsing = En { -brand-name-firefox } , el modo de navegación privada borra automáticamente su información de navegación, como contraseñas, cookies e historial, sin dejar rastro después de cerrar la sesión. { -brand-name-edge } por otro lado, en realidad registra el historial de navegación en su modo privado (llamado "InPrivate") y es una tarea relativamente fácil para alguien reconstruir su historial de navegación completo, independientemente de si su navegación se realizó en modo normal o InPrivate.
compare-edge-both-browsers-are-relatively = Ambos navegadores son relativamente iguales en términos de cifrado de datos. Sin embargo, si la privacidad y la transparencia en línea son importantes para usted, entonces { -brand-name-firefox } es claramente una mejor opción aquí.
compare-edge-firefox-is-a-fast-and-open = { -brand-name-firefox } es un navegador rápido y de código abierto, lo que significa que los usuarios pueden personalizar su experiencia de navegación de todas las formas posibles. { -brand-name-firefox } también permite al usuario ocasional varias formas diferentes de personalizar la interfaz de usuario aplicando diferentes temas y configuraciones de barra de herramientas. Dado que nuestro navegador siempre ha sido de código abierto, tenemos un gran número de seguidores de desarrolladores dedicados que han creado una extensa biblioteca de complementos y extensiones de navegador.
compare-edge-firefox-is-a-fast-and-open-fallback = { -brand-name-firefox } es un navegador rápido y de código abierto, lo que significa que los usuarios pueden personalizar su experiencia de navegación de todas las formas posibles. { -brand-name-firefox } también permite al usuario ocasional varias formas diferentes de personalizar la interfaz de usuario aplicando diferentes temas y configuraciones de barra de herramientas. Dado que nuestro navegador siempre ha sido de código abierto, tenemos un gran número de seguidores de desarrolladores dedicados que han creado una extensa biblioteca de complementos y extensiones de navegador.
compare-edge-since-edge-has-moved-to-the = Dado que { -brand-name-edge } ha trasladado a la plataforma de procesador intensivo { -brand-name-chromium } , puede esperar que se ejecute un poco más lento, especialmente si tiene varios programas ejecutándose a la vez. Sin embargo, con la plataforma { -brand-name-chromium } viene una biblioteca masiva de extensiones, así como un nivel decente de personalización de la interfaz de usuario que { -brand-name-edge } no tenía antes de su traslado a { -brand-name-chromium } .
compare-edge-edge-has-some-nice-ui-features = { -brand-name-edge } tiene algunas funciones de interfaz de usuario interesantes, como las vistas previas de sus pestañas, que pueden facilitar la búsqueda de las pestañas abiertas adecuadas si tiene muchas abiertas. Otra función útil relacionada con las pestañas le permite dejar de lado las pestañas activas que no está usando pero que no desea cerrar.

# Variables:
#   $attrs (string) - link to /firefox/pocket/ with additional attributes for analytics
compare-edge-firefox-features-a-scrolling = { -brand-name-firefox } cuenta con una interfaz de pestaña de desplazamiento, que mantiene visible la información de la pestaña y la desplaza horizontalmente en lugar de reducirla al tamaño de favicon. Además, cada vez que abre una pestaña nueva, nuestra función <a { $attrs }>{ -brand-name-pocket }</a> sugiere artículos y contenido relevantes para usted. Además, con { -brand-name-pocket } , también puede guardar artículos, videos y otro contenido con un solo clic, para leer en otro momento.
compare-edge-firefox-and-edge-both-offer = { -brand-name-firefox } y { -brand-name-edge } ambos ofrecen excelentes modos de lectura. Con { -brand-name-firefox } , simplemente toca el ícono pequeño en la barra de búsqueda y el navegador elimina todos los elementos innecesarios y te presenta un artículo de apariencia limpia. En { -brand-name-edge } , simplemente toque el ícono del libro pequeño y el navegador para obtener una interfaz de usuario limpia y fácil de leer.
compare-edge-firefox-and-edge-both-offer-fallback = { -brand-name-firefox } y { -brand-name-edge } ambos ofrecen excelentes modos de lectura. Con { -brand-name-firefox } , simplemente toca el pequeño icono en la barra de búsqueda y el navegador elimina todos los elementos innecesarios y te presenta un artículo de aspecto limpio. En { -brand-name-edge } , simplemente toque el ícono del libro pequeño y el navegador para obtener una interfaz de usuario limpia y fácil de leer.

# Variables:
#   $attrs (string) - link to https://support.mozilla.org/kb/enhanced-tracking-protection-firefox-desktop with additional attributes for analytics
compare-edge-firefox-also-includes-lots = { -brand-name-firefox } también incluye muchas funciones prácticas integradas de forma predeterminada, como <a { $attrs }>Protección de seguimiento mejorada</a> , una herramienta de captura de pantalla integrada, envío de archivos grandes y más.

# "Out of the gate" means from the very start. Alternative: "From the start,". Race horses are held behind a gate that is opened to release all the horses at the same time at the start of the race, so a horse that leads the race from the very start is said to lead "right out of the gate."
compare-edge-out-of-the-gate-firefox-has = Fuera de la puerta, { -brand-name-firefox } tiene más funciones e integraciones integradas en el navegador y están disponibles para descargar. Y mientras tanto los navegadores tienen un enorme número de add-ons y extensiones disponibles, { -brand-name-edge } 's compatibilidad con { -brand-name-google } ' s { -brand-name-chromium } plataforma le da la ventaja en términos de números absolutos.

compare-edge-with-internet-explorer-microsoft = Con { -brand-name-ie } , { -brand-name-microsoft } aprendió de su falta de disponibilidad en todas las plataformas y logró que { -brand-name-edge } estuviera disponible en { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } , { -brand-name-mac } y pronto { -brand-name-linux } .
compare-edge-with-internet-explorer-fallback = Con { -brand-name-ie } , { -brand-name-microsoft } aprendió de su falta de disponibilidad en todas las plataformas y puso { -brand-name-edge } disposición de { -brand-name-mac } y { -brand-name-android } . El software ahora está disponible en { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } y { -brand-name-mac } .

# Variables:
#   $attrs (string) - link to /firefox/accounts/ with additional attributes for analytics
compare-edge-firefox-has-been-available = { -brand-name-firefox } ha estado disponible en { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } , { -brand-name-mac } y { -brand-name-linux } durante años. Y como es de esperar con cualquier navegador moderno, { -brand-name-firefox } permite iniciar sesión con una <a { $attrs }>cuenta gratuita</a> y sincronizar datos como contraseñas, historial de navegación, marcadores y pestañas abiertas entre su computadora, tableta y teléfono. También le permite sincronizar entre plataformas.
compare-edge-edge-also-allows-you-to-connect = { -brand-name-edge } también te permite conectar tu cuenta asociada { -brand-name-microsoft } e iniciar sesión para sincronizar tus favoritos, historial, contraseñas y más entre tu computadora y dispositivos { -brand-name-ios } o { -brand-name-android } .
compare-edge-edge-also-allows-you-to-fallback = { -brand-name-edge } también te permite conectar tu cuenta { -brand-name-microsoft } asociada e iniciar sesión para sincronizar tus favoritos, historial, contraseñas y más entre tu computadora y dispositivos { -brand-name-ios } o { -brand-name-android } , aunque algunas { -brand-name-android } tabletas no lo son actualmente. soportado.

# Variables:
#   $attrs (string) - link to home page with additional attributes for analytics
compare-edge-aside-from-sucking-up-a-lot = Además de absorber una gran cantidad de potencia informática, { -brand-name-edge } ejecutarse en { -brand-name-chromium } ha respondido a muchas necesidades de funcionalidad y características de los usuarios. Pero todavía hay mucho que tener en cuenta en términos de las protecciones de privacidad del navegador. Nuestra evaluación es que { -brand-name-firefox } sigue siendo una mejor opción para que la mayoría de las personas la utilicen en su vida diaria, basada no solo en la funcionalidad sino, lo que es más importante, en nuestra transparencia en la forma en que recopilamos los datos del usuario, qué recopilamos exactamente y qué hacemos con eso. Debido a que nuestra empresa matriz es <a { $attrs }>{ -brand-name-mozilla }</a> , una organización sin fines de lucro dedicada a la privacidad y la libertad en Internet, simplemente tenemos un conjunto diferente de prioridades en lo que respecta a los datos de los usuarios.
compare-edge-the-bottom-line-is-that-while = La conclusión es que, si bien sugerimos usar { -brand-name-firefox } , el mejor navegador para usted será, en última instancia, el que se adapte a sus necesidades individuales con soporte de extensión, personalización de herramientas de navegación, velocidad, privacidad y seguridad.
