# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } vs. { -brand-name-chrome } : Was ist besser?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Wir vergleichen { -brand-name-mozilla } { -brand-name-firefox } mit { -brand-name-google } { -brand-name-chrome } in Bezug auf Datenschutz, Nützlichkeit und Portabilität

# Main title.
compare-chrome-comparing-firefox-browser = Vergleich von { -brand-name-firefox-browser } mit { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = Bei { -brand-name-firefox } haben wir eine große Anzahl engagierter Benutzer, die unser unerschütterliches Engagement für den Online-Datenschutz schätzen. Beispielsweise enthält die neueste Version von { -brand-name-firefox } eine Funktion namens Enhanced Tracking Protection (ETP), die standardmäßig für alle Benutzer weltweit aktiviert ist. ETP blockiert über 2.000 Tracker, einschließlich Social Tracker von Unternehmen wie { -brand-name-facebook } , { -brand-name-twitter } und LinkedIn. Es hat auch eine integrierte Funktion namens <a { $attrs }>{ -brand-name-firefox-monitor }</a> , die Sie automatisch benachrichtigt, wenn Ihr Passwort verletzt wurde oder aktualisiert werden muss. Zusätzlich zu diesen Schutzmaßnahmen löscht der private Browsermodus in { -brand-name-firefox } automatisch Ihre Browsing-Informationen wie Verlauf und Cookies und hinterlässt nach Beendigung Ihrer Sitzung keine Spuren.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = Bei { -brand-name-firefox } haben wir eine große Anzahl engagierter Benutzer, die unser unerschütterliches Engagement für den Online-Datenschutz schätzen. Beispielsweise enthält die neueste Version von { -brand-name-firefox } eine Funktion namens Enhanced Tracking Protection (ETP), die standardmäßig für alle Benutzer weltweit aktiviert ist. ETP blockiert über 2.000 Tracker, einschließlich Social Tracker von Unternehmen wie { -brand-name-facebook } , { -brand-name-twitter } und LinkedIn. Es hat auch eine integrierte Funktion namens <a { $attrs }>{ -brand-name-firefox-monitor }</a> , die Sie automatisch benachrichtigt, wenn Ihr Passwort verletzt wurde oder aktualisiert werden muss. Zusätzlich zu diesen Schutzmaßnahmen löscht der private Browsing-Modus von { -brand-name-firefox } automatisch Ihre Browsing-Informationen wie Verlauf und Cookies und hinterlässt nach Abschluss Ihrer Sitzung keine Spuren.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Wir haben kürzlich unser Engagement für Datenschutz und Transparenz in Bezug auf Benutzerdaten in unserer jüngsten <a { $attrs }>Datenschutzerklärung bekräftigt</a> , in der es heißt: „Bei Mozilla glauben wir, dass Datenschutz für ein gesundes Internet von grundlegender Bedeutung ist.“
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } ist in jedem Fall ein sicherer Browser mit Funktionen wie { -brand-name-google } Safe Browsing, mit dem Benutzer geschützt werden, indem eine Warnung angezeigt wird, die nicht zu übersehen ist, wenn sie versuchen, zu gefährlichen Websites zu navigieren oder gefährliche Dateien herunterzuladen.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Letztendlich liegt es an Ihnen, zu entscheiden, ob oder wo Sie die Grenze ziehen möchten, um Dinge wie Ihren Suchverlauf und Ihren Einkaufsverlauf zu teilen. Aber wenn Sie den meisten Menschen ähnlich sind, haben Sie wahrscheinlich im Internet nach Dingen gesucht, die Sie lieber privat halten möchten.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Im Schnellvorlauf bis heute hat sich die Wettbewerbslandschaft für Browser geändert, und viele Menschen beginnen zu hinterfragen, was mit ihren Online-Daten wie Browserverlauf, Passwörtern und anderen vertraulichen Informationen geschieht. Seit 2008, als { -brand-name-chrome } auf die Bühne kam, hat sich viel geändert. Bei { -brand-name-firefox } haben wir uns bemüht, unsere Benutzeroberfläche neu zu gestalten und den Benutzern eine ständig wachsende Anzahl von Datenschutz- und Leistungsverbesserungen sowie zahlreiche praktische Browser-Tools zur Verfügung zu stellen.
compare-chrome-and-so-here-we-are-the-browser = Und hier eskalieren die Browserkriege erneut und es ist Zeit, { -brand-name-firefox-browser } { -brand-name-google } { -brand-name-chrome } neu zu bewerten und zu vergleichen.
compare-chrome-in-2008-google-introduced = Im Jahr 2008 führte { -brand-name-google } { -brand-name-chrome } , und seine Auswirkungen als Innovation in der Browsertechnologie waren unmittelbar spürbar. Es war schneller zum Laden von Websites, nahm nur minimalen Platz auf dem Bildschirm ein und bot eine unbestreitbar einfache Benutzeroberfläche.
compare-chrome-in-fact-both-chrome-and-firefox = Tatsächlich verfügen sowohl { -brand-name-chrome } als auch { -brand-name-firefox } über strenge Sicherheitsvorkehrungen. Beide enthalten eine Funktion namens „Sandboxing“, die die Prozesse des Browsers voneinander trennt, sodass eine schädliche Website andere Teile Ihres Laptops oder eines anderen Geräts nicht infiziert.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = Während { -brand-name-chrome } sich als sicherer Webbrowser erweist, ist seine Datenschutzerklärung fraglich. { -brand-name-google } sammelt tatsächlich eine störend große Datenmenge von seinen Benutzern, einschließlich Standort, Suchverlauf und Besuche vor Ort. { -brand-name-google } spricht sich für die Datenerfassung aus und sagt, dass dies dazu dient, die Dienstleistungen zu verbessern - beispielsweise um Ihnen zu helfen, einen Pullover oder ein Café zu finden, wie Sie es zuvor gekauft oder besucht haben. Andere sind jedoch möglicherweise anderer Meinung und weisen darauf hin, dass { -brand-name-google } tatsächlich eine beispiellose Datenmenge für eigene Marketingzwecke sammelt. Sie preisen an, dass sie Ihre Informationen vor Hackern geheim halten, aber das ist nebensächlich. { -brand-name-google } selbst betreibt das weltweit größte Werbenetzwerk, was zum großen Teil den Daten zu verdanken ist, die sie von ihren Nutzern erhalten.

# "Gmail" and "Google Docs" are brand names.
compare-chrome-in-terms-of-features-both = In Bezug auf die Funktionen bieten sowohl { -brand-name-firefox } als auch { -brand-name-chrome } eine große Bibliothek an Erweiterungen und Plug-Ins. Der Katalog von { -brand-name-chrome } übertrifft jeden anderen Browser bei weitem und lässt sich gut in andere { -brand-name-google } -Dienste wie Google Mail und { -brand-name-google } Dokumente.
compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } verfügt außerdem über eine Synchronisierungsfunktion, mit der Sie Ihre geöffneten und zuletzt verwendeten Registerkarten, den Browserverlauf und Lesezeichen auf allen Ihren Geräten anzeigen können.
compare-chrome-while-chrome-gets-the-nod = Während { -brand-name-chrome } mit Add-Ons und Erweiterungen den Zuschlag erhält, verfügt { -brand-name-firefox } über eine gut kuratierte Reihe integrierter Funktionen, wie das unglaublich praktische Bildschirmaufnahme-Tool und die Lesemodus-Funktion, mit der alles von der Seite entfernt wird, außer dem Text aus dem Artikel, den Sie lesen.
compare-chrome-although-not-as-extensive = Obwohl { -brand-name-chrome } nicht so umfangreich ist wie die Add-On-Bibliothek von { -brand-name-firefox } bietet es als Open-Source-Software mit einer großen Anzahl aktiver Mitwirkender auch eine unglaubliche Anzahl nützlicher Erweiterungen.
compare-chrome-if-having-tons-of-open-tabs = Wenn es Ihre Sache ist, Tonnen von offenen Registerkarten zu haben, dann kommt es wirklich auf Ihre Benutzeroberflächenpräferenz an. { -brand-name-firefox } bietet einen horizontalen Bildlauf auf allen geöffneten Registerkarten, anstatt sie mit jedem neuen zu verkleinern. { -brand-name-google } { -brand-name-chrome } verkleinert sie lieber, damit nur das Favicon sichtbar ist. Das einzige Problem dabei ist, wenn Sie mehrere Registerkarten auf derselben Website geöffnet haben, sodass Sie auf Ihren Registerkarten dasselbe Favicon sehen.
compare-chrome-almost-needless-to-say-versions = Es ist fast unnötig zu erwähnen, dass Versionen von { -brand-name-firefox } und { -brand-name-chrome } für die gängigsten Desktop- und mobilen Betriebssysteme verfügbar sind ( { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ).
compare-chrome-both-chrome-and-firefox-also = Mit { -brand-name-chrome } und { -brand-name-firefox } können Sie auch Kennwörter, Lesezeichen und geöffnete Registerkarten auf allen Ihren Geräten synchronisieren. Wenn Sie ein { -brand-name-firefox } Konto haben, können Sie manuell einen geöffneten Tab auf Ihrem Desktop an Ihr Mobilgerät senden oder umgekehrt. Mit { -brand-name-chrome } erfolgt dies automatisch, wenn Sie diese Einstellung in Ihren Einstellungen ausgewählt haben. Es ist praktisch, die Registerkarte nicht manuell von einem Gerät zum anderen senden zu müssen, wenn Sie beispielsweise einen Artikel weiterlesen möchten, den Sie zuvor noch nicht fertiggestellt haben. Es kann jedoch vorkommen, dass die automatische Synchronisierung nicht ideal ist, wenn mehrere Benutzer surfen, während sie in Ihrem { -brand-name-google } -Konto angemeldet sind.

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Wir denken, es ist fair zu sagen, dass { -brand-name-firefox } und { -brand-name-chrome } in Bezug auf Portabilität und Nützlichkeit wirklich gleichauf sind, wobei { -brand-name-chrome } aufgrund seiner riesigen Bibliothek an Erweiterungen und Zusatzfunktionen einen leichten Nutzenvorteil hat. In Bezug auf den Datenschutz gewinnt { -brand-name-firefox } den Tag mit unserer Verpflichtung, die Online-Daten unserer Benutzer zu bewahren und kostenlose integrierte Dienste wie Passwort-Manager bereitzustellen, die Sie auch benachrichtigen, wenn es zu einem Datenverstoß mit Ihren Anmeldeinformationen kommt.
compare-chrome-as-for-customization-our = In Bezug auf die Anpassung werden unsere Fans Ihnen sagen, dass eines der Dinge, die sie an unserem Browser am meisten lieben, die Fähigkeit ist, Ihnen zu ermöglichen, einen Großteil der UI-Elemente zu verschieben und anzuordnen, um sie Ihren Anforderungen am besten anzupassen. { -brand-name-chrome } können Sie bestimmte Elemente der Benutzeroberfläche ausblenden, aber es gibt nicht viel Spielraum, um Dinge basierend auf Ihren Einstellungen zu verschieben. Es sollte jedoch beachtet werden, dass sowohl { -brand-name-chrome } als auch { -brand-name-firefox } das Ändern des Erscheinungsbilds und des Themas Ihres Browsers ziemlich einfach machen.
compare-chrome-for-practical-purposes-theres = Aus praktischen Gründen hindert Sie offensichtlich nichts daran, beide Browser zu verwenden - { -brand-name-firefox } für jene Momente im Leben, in denen Datenschutz wirklich wichtig ist, und { -brand-name-chrome } wenn Sie noch in das { -brand-name-google } -Ökosystem investiert sind. Angesichts der wachsenden Anzahl von Eingriffen in unsere persönlichen Daten könnte sich { -brand-name-firefox } auf lange Sicht als die richtige Wahl für diejenigen von uns erweisen, die Wert darauf legen, unsere Privatsphäre online zu schützen.
