# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Sieben der besten Browser im direkten Vergleich
compare-index-six-of-the-best-browsers-fallback = Sechs der besten Browser im direkten Vergleich

# Sub-headline
compare-index-privacy-utility-portability = Privatsphäre. Nützlichkeit. Portabilität.

# HTML page description
compare-index-a-great-internet-browser-should = Ein großartiger Internetbrowser sollte über die Funktionen verfügen, die Sie benötigen, die Portabilität zwischen Geräten und die Privatsphäre, die Sie verdienen.
compare-index-which-browser-is-best-at-keeping = Welcher Browser kann die Dinge am besten vertraulich behandeln?
compare-index-its-not-unreasonable-to-expect = Es ist nicht unangemessen, von den Produkten, die wir regelmäßig verwenden, um online zu gehen, ein hohes Maß an Datenschutz und Privatsphäre zu erwarten. Ein Browser sollte mindestens eine Version des "privaten Browsermodus" anbieten, die Ihren Verlauf und Suchverlauf automatisch löscht, damit andere Benutzer auf demselben Computer nicht darauf zugreifen können. In diesem Bereich erzielen alle sieben hier verglichenen Browser Punkte.
compare-index-its-not-unreasonable-to-expect-fallback = Es ist nicht unangemessen, von den Produkten, die wir regelmäßig verwenden, um online zu gehen, ein hohes Maß an Datenschutz und Privatsphäre zu erwarten. Ein Browser sollte mindestens eine Version des "privaten Browsermodus" anbieten, die Ihren Verlauf und Suchverlauf automatisch löscht, damit andere Benutzer auf demselben Computer nicht darauf zugreifen können. In diesem Bereich erhalten alle sechs hier verglichenen Browser Punkte.
compare-index-what-you-do-online-literally = Was Sie online tun, sollte buchstäblich niemanden etwas angehen.
compare-index-another-browser-feature-that = Eine weitere Browserfunktion, die selbstverständlich sein sollte, ist die Möglichkeit, zu verhindern, dass Websites und Unternehmen Ihre Browser- und Einkaufsdaten verfolgen - auch im normalen Browsermodus.
compare-index-another-browser-feature-fallback = Eine weitere Browserfunktion, die selbstverständlich sein sollte, ist die Möglichkeit, zu verhindern, dass Websites und Unternehmen Ihre Browser- und Einkaufsdaten verfolgen - auch im normalen Browsermodus. Dies ist jedoch nicht der Fall: Tatsächlich sind { -brand-name-firefox } und { -brand-name-safari } die einzigen Browser, die Tracking-Cookies von Drittanbietern standardmäßig blockieren.
compare-index-using-a-browser-that-blocks = Die Verwendung eines Browsers, der Tracker von Drittanbietern blockiert, ist nicht nur für den Datenschutz wichtig, sondern bedeutet auch, dass er auch viel schneller ausgeführt wird. Die meisten Tracker sind nur Skripte, die auf einer Reihe von Websites im Hintergrund ausgeführt werden. Sie können sie nicht sehen, aber Sie können fühlen, wie sie Ihren Browser verlangsamen. Ab Version 67 von { -brand-name-firefox } sind auch Fingerabdrücke und Kryptominierer blockiert. Wenn Sie mit Kryptominern nicht vertraut sind, finden Sie hier ein Beispiel dafür, wie sie sich auf Sie auswirken können: Möglicherweise ist Ihr Computer plötzlich heißer geworden oder der Akku ist schneller als normal leer. Dies ist häufig das Nebenprodukt von Kryptominern, die sich auf Ihrem Gerät herumschleichen.
compare-index-what-has-your-browser-done = Was hat Ihr Browser in letzter Zeit für Sie getan?
compare-index-in-addition-to-privacy-protection = Neben dem Schutz der Privatsphäre, der größtenteils im Hintergrund des Browsers stattfindet, ist die eigentliche Benutzeroberfläche und Funktionalität ein weiterer wichtiger Bestandteil eines gut gemachten Browsers. Fast alle sieben Browser sind gleich, wenn es um das Durchsuchen von Registerkarten, die Verwaltung von Lesezeichen, die automatische Vervollständigung, das Korrekturlesen und Erweiterungen geht. { -brand-name-firefox } , { -brand-name-edge } und { -brand-name-opera } bieten auch eine schnelle Screenshot-Funktion, die sich als sehr praktisch erweist und definitiv etwas ist, das Sie bemerken, wenn Sie zu einem Browser ohne diese Funktion wechseln.
compare-index-in-addition-to-privacy-protection-fallback = Neben dem Schutz der Privatsphäre, der größtenteils im Hintergrund des Browsers stattfindet, ist die eigentliche Benutzeroberfläche und Funktionalität ein weiterer wichtiger Bestandteil eines gut gemachten Browsers. Fast alle sechs Browser sind gleich, wenn es um das Durchsuchen von Registerkarten, die Verwaltung von Lesezeichen, die automatische Vervollständigung, das Korrekturlesen und Erweiterungen geht. { -brand-name-firefox } , { -brand-name-edge } und { -brand-name-opera } bieten auch eine schnelle Screenshot-Funktion, die sich als sehr praktisch erweist und definitiv etwas ist, das Sie bemerken, wenn Sie zu einem Browser ohne diese Funktion wechseln.
compare-index-how-well-does-your-browser = Wie gut funktioniert Ihr Browser auf Ihren Geräten?
compare-index-almost-all-of-the-browsers = Fast alle hier verglichenen Browser ermöglichen die Synchronisation zwischen Desktop- und Mobilgeräten. Dazu benötigen Sie ein Konto, mit dem Sie sich auf allen Geräten beim Browser anmelden und beispielsweise Kennwörter, Browserverlauf, Lesezeichen und Einstellungen synchronisieren können.
compare-index-conclusion = Fazit:
compare-index-and-the-winner-is = Und der Gewinner ist…
compare-index-find-out-how-firefox-chrome = Finden Sie heraus, wie sich { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } und { -brand-name-ie } in Bezug auf Datenschutz, Nützlichkeit und Portabilität unterscheiden.
compare-index-find-out-how-firefox-fallback = Finden Sie heraus, wie sich { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } und { -brand-name-ie } in Bezug auf Datenschutz, Nützlichkeit und Portabilität unterscheiden.
compare-index-looking-for-a-better-browser = Suchen Sie einen besseren Browser? Wir vergleichen { -brand-name-firefox } mit { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } und { -brand-name-ie } , um Ihnen bei Ihrer Entscheidung zu helfen.
compare-index-looking-for-a-better-fallback = Suchen Sie einen besseren Browser? Wir vergleichen { -brand-name-firefox } mit { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } und { -brand-name-ie } , um Ihnen bei Ihrer Entscheidung zu helfen.
compare-index-so-is-your-browser-the-best = Ist Ihr Browser also der beste für Ihre Online-Aktivitäten? Der richtige Browser kann einen großen Unterschied darin machen, wie Sie das Web erleben. Vergleichen wir also ohne weiteres { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } , { -brand-name-microsoft } { -brand-name-ie } und { -brand-name-edge } - und finden Sie heraus, welche Ihren Anforderungen am besten entspricht.
compare-index-so-is-your-browser-the-fallback = Ist Ihr Browser also der beste für Ihre Online-Aktivitäten? Der richtige Browser kann einen großen Unterschied darin machen, wie Sie das Web erleben. Vergleichen wir also ohne weiteres { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-microsoft } { -brand-name-ie } und { -brand-name-edge } - und finden Sie heraus, welche Ihren Anforderungen am besten entspricht.
compare-index-since-your-browser-is-your = Da Ihr Browser Ihr Tor zum Internet ist, sind Geschwindigkeit, Sicherheit, Datenschutz und Nutzen von größter Bedeutung. In den letzten Jahren war { -brand-name-google } { -brand-name-chrome } für viele der Browser der Wahl. Aber in einer Zeit, in der Online-Anzeigen uns überall zu folgen scheinen und Datenverletzungen ein fester Bestandteil der Schlagzeilen sind, fordern viele Menschen von ihrem Browser mehr Privatsphäre und Respekt.
compare-index-the-first-thing-to-point-out = Das erste, was Sie über die Portabilität wissen sollten, ist, dass nicht alle Browser auf allen Betriebssystemen ausgeführt werden. Während { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-brave } und { -brand-name-opera } auf allen wichtigen Systemen funktionieren und einfach zu installieren sind, funktionieren { -brand-name-ie } und { -brand-name-safari } nur auf { -brand-name-microsoft } und Apples eigenen Systemen. Die mobile Version von { -brand-name-safari } ist auf Apples Mobilgeräten vorinstalliert, und die meisten { -brand-name-android } Geräte verfügen über einen vorinstallierten Browser, der vom Hersteller für das Gerät geändert wurde. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-brave } , { -brand-name-edge } und { -brand-name-opera } können einfach installiert und sogar nebeneinander verwendet werden.
compare-index-the-first-thing-to-point-fallback = Das erste, was Sie über die Portabilität wissen sollten, ist, dass nicht alle Browser auf allen Betriebssystemen ausgeführt werden. Während { -brand-name-firefox } , { -brand-name-chrome } und { -brand-name-opera } auf allen wichtigen Systemen funktionieren und einfach zu installieren sind, funktionieren { -brand-name-ie } , { -brand-name-edge } und { -brand-name-safari } nur auf { -brand-name-microsoft } und Apples eigenen Systemen. Die mobile Version von { -brand-name-safari } ist auf Apples Mobilgeräten vorinstalliert, und die meisten { -brand-name-android } Geräte verfügen über einen vorinstallierten Browser, der vom Hersteller für das Gerät geändert wurde. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } und { -brand-name-opera } können einfach installiert und sogar nebeneinander verwendet werden.
compare-index-browsers-have-come-a-long = Browser haben seit der Einführung von { -brand-name-chrome } einen langen Weg zurückgelegt und den Marktanteil übernommen. Die meisten modernen Browser haben die Lücke in Bezug auf Portabilität und Funktionalität geschlossen und in einigen Bereichen, wie Geschwindigkeit und Datenschutz, { -brand-name-chrome } sogar übertroffen. Die Entscheidung, welcher Browser für Sie geeignet ist, hängt jedoch immer von Ihren individuellen Bedürfnissen ab und davon, was Sie bei der Online-Navigation am meisten schätzen.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } wird durch die gemeinnützige { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } steht Ihre Privatsphäre an erster Stelle - bei allem, was wir machen und tun. Wir glauben, dass Sie das Recht haben zu entscheiden, wie und mit wem Sie Ihre persönlichen Daten teilen. { -brand-name-firefox } sammelt so wenig Daten wie möglich und verkauft sie nie. Die wenigen Daten, die wir sammeln, werden nur verwendet, um Produkte und Funktionen zu verbessern. Keine Geheimnisse. Aber viel Transparenz und echte Privatsphäre.
compare-index-based-on-the-criteria-we-outlined = Basierend auf den von uns beschriebenen Kriterien - Datenschutz, Nutzen und Portabilität - gibt es wirklich nur einen Browser, der die Marke erfüllt, und das ist { -brand-name-firefox } . Der eigentliche Unterschied liegt nicht in der Funktionalität, sondern in der Privatsphäre. { -brand-name-firefox } ist der privateste Browser, der Sie nicht an ein Ökosystem bindet. Verwenden Sie es auf jedem Betriebssystem und auf allen Ihren Geräten und fühlen Sie sich dabei sicher.
