# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/safari/

# HTML page title
compare-safari-firefox-vs-safari-which-is = { -brand-name-firefox } vs. { -brand-name-safari } : Welcher Browser ist der bessere für Sie?

# HTML page description.
compare-safari-safari-is-the-pre-installed = { -brand-name-safari } ist der vorinstallierte Browser auf { -brand-name-mac } und { -brand-name-iphone } . Vergleichen Sie { -brand-name-safari } mit { -brand-name-firefox-browser } , um herauszufinden, welcher Browser für Sie der bessere ist.

# Main title.
compare-safari-comparing-firefox-browser = Vergleich von { -brand-name-firefox-browser } mit { -brand-name-apple } { -brand-name-safari }

# "Mac" is a brand name, used here as informal shorthand for "macOS computer".
compare-safari-if-you-use-a-mac-or-have = Wenn Sie einen Mac verwenden oder eine { -brand-name-iphone } , sind Sie wahrscheinlich mit dem Webbrowser { -brand-name-safari } vertraut. Die Tatsache, dass es als Standardbrowser für { -brand-name-apple } Produktbenutzer vorinstalliert ist, bietet definitiv einen frühen Vorteil, aber { -brand-name-firefox } verfügt über eine Reihe nützlicher Funktionen, die es zu einer attraktiven Alternative machen. Hier werden die Hauptunterschiede zwischen unserem Browser und { -brand-name-safari } in Bezug auf Datenschutz, Nützlichkeit und Portabilität zwischen Geräten untersucht.

# A "white hot topic" is something a lot of people are talking about. "Interwebs" is a slang term for the web. Alternative: "web".
compare-safari-privacy-has-become-a-white = Datenschutz ist für Tech-Unternehmen zu einem heißen Thema geworden, da sie feststellen, dass sich immer mehr Menschen anfällig für Datenverletzungen, Anzeigen-Tracker und Hacker fühlen. Aber wenn es um die realen Tools geht, mit denen die Benutzer in den tatsächlichen Interwebs navigieren, ist alles in Ordnung oder ergreifen sie tatsächlich Maßnahmen, um Ihre Daten sicher zu halten?
compare-safari-as-alluded-to-before-apple-fallback = Wie bereits erwähnt, ist { -brand-name-apple } eines der Unternehmen, die kürzlich beschlossen haben, ihr Datenschutzspiel zu verbessern. Vor nicht allzu langer Zeit hat { -brand-name-apple } in { -brand-name-safari } die Cross-Site-Tracking-Verhinderung implementiert, die verhindert, dass Anzeigen Ihnen im Internet folgen. { -brand-name-safari } bietet auch einen starken Passwortvorschlag, wenn Sie sich auf einer Website für ein neues Konto anmelden. Wenn Sie in das iCloud-Ökosystem investiert sind, wird dieses Kennwort sicher mit Ihren anderen Geräten synchronisiert, sodass Sie sich nie daran erinnern müssen.

# "Standing on the soap box" means trying to spread a persuasive message to the masses. Alternative: "We've been spreading the message about privacy for a long time." Soap used to come in wooden crates, and this idiom refers to activists or preachers who would stand on an empty soap box on a street corner to speak to a crowd.
compare-safari-like-safari-we-at-firefox = Wie bei { -brand-name-safari } haben wir bei { -brand-name-firefox } Wert auf Datenschutz und Sicherheit gelegt. Aber im Gegensatz zu { -brand-name-safari } stehen wir schon lange auf der Seifenkiste. Tatsächlich war { -brand-name-mozilla } (unsere Muttergesellschaft) eine der ersten Stimmen in der Tech-Community, die Alarm für den Online-Datenschutz schlug.

# Variables:
#   $attrs (string) - link to https://addons.mozilla.org/firefox/addon/facebook-container/ with additional attributes for analytics
# "WebMD" is a brand name.
compare-safari-our-private-browsing-mode = Unser privater Browsermodus blockiert Tracker und löscht Ihre Passwörter, Cookies und den Verlauf jedes Mal, wenn Sie ihn schließen. Sie können unsere erweiterten Datenschutzfunktionen aber auch im normalen Browsermodus nutzen. Mit der neuesten Ausgabe von { -brand-name-firefox } ist die erweiterte Tracking-Verhinderung standardmäßig aktiviert. Dies verhindert, dass Dinge wie Cross-Site-Tracker Ihnen folgen, wenn Sie durch das Web springen. Da { -brand-name-facebook } fast täglich wegen Datenschutzproblemen entdeckt wird, ist unsere <a { $attrs }>{ -brand-name-facebook-container }</a> -Erweiterung sehr sinnvoll. Es macht es für { -brand-name-facebook } schwieriger, Sie im Web zu verfolgen - ähnlich wie { -brand-name-safari } , um die standortübergreifende Verfolgung zu verhindern -, aber { -brand-name-firefox } isoliert Ihre { -brand-name-facebook } -Sitzung tatsächlich in einen separaten Container, der die Verfolgung von { -brand-name-facebook } blockiert was Sie auf anderen Websites tun. Warum müssen sie überhaupt wissen, was Sie in WebMD nachschlagen?

# Variables:
#   $lockwise (string) - link to /firefox/lockwise/ with additional attributes for analytics
#   $monitor (string) - link to monitor.firefox.com with additional attributes for analytics
compare-safari-as-far-as-security-goes-firefox = In Bezug auf die Sicherheit ist { -brand-name-firefox } dort solide. Jedes Mal, wenn Sie sich in { -brand-name-firefox } , können Sie mit der rechten Maustaste in das Kennwortfeld klicken, um mithilfe der Option Kennwort füllen sicher ein sicheres Kennwort zu generieren. Wenn Sie Ihr neues Passwort speichern, werden Sie aufgefordert, es in seinem integrierten Passwort-Manager <a { $lockwise }>{ -brand-name-lockwise }</a> zu speichern. Wir bieten Benutzern und Kontoinhabern auch ein weiteres kostenloses und nützliches Produkt namens <a { $monitor }>{ -brand-name-monitor }</a> , das Sie automatisch benachrichtigt, wenn Ihre Daten in einem bekannten Datenverstoß enthalten sind.
compare-safari-if-you-choose-to-use-safari = Wenn Sie { -brand-name-safari } , sind Sie in sicheren Händen, solange Sie ein { -brand-name-apple } -Gerät verwenden. { -brand-name-safari } funktioniert jedoch nur auf { -brand-name-apple } Geräten, während { -brand-name-firefox } auf { -brand-name-windows } , { -brand-name-mac } , { -brand-name-ios } , { -brand-name-android } und { -brand-name-linux } funktioniert. Unabhängig davon, für welches Betriebssystem Sie sich entscheiden, { -brand-name-firefox } haben Sie unseren Sicherheits- und Datenschutz geschützt.
compare-safari-apple-is-widely-known-for = { -brand-name-apple } ist weithin bekannt für sein geschlossenes Ökosystem, da es sich um die Erstellung von Software für seine Produkte handelt. In { -brand-name-app-store } wird Entwicklern jedoch ein Abschnitt zum Erstellen von Plugins und Add-Ons angeboten, um den Browser robuster zu machen. Diese Erweiterungen können auch über { -brand-name-app-store } durchsucht und problemlos zu { -brand-name-safari } hinzugefügt werden.

# Variables:
#   $attrs (string) - link to addons.mozilla.org with additional attributes for analytics
compare-safari-like-safari-firefox-encourages = Wie { -brand-name-safari } ermutigt { -brand-name-firefox } seine begeisterte Entwicklergemeinde, <a { $attrs }>Add-Ons und Erweiterungen</a> für den Browser zu erstellen. Und da unsere Plattform Open Source ist, gibt es eine große Auswahl, die eine Fülle von Funktionen hinzufügt.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
compare-safari-also-when-you-sign-up-for = Wenn Sie sich für ein { -brand-name-firefox } Konto anmelden, erhalten Sie Zugriff auf eindeutige Dienste wie <a { $pocket }>{ -brand-name-pocket }</a> und <a { $send }>{ -brand-name-send }</a> , die direkt in den Browser integriert werden. Mit der Schaltfläche { -brand-name-pocket } für { -brand-name-firefox } können Sie Webseiten und Videos mit nur einem Klick auf { -brand-name-pocket } speichern, sodass Sie jederzeit und überall eine saubere, ablenkungsfreie Version lesen können - auch offline. Mit { -brand-name-send } Sie große Dateien mit End-to-End-Verschlüsselung mit einer Vielzahl von Sicherheitskontrollen freigeben, z. B. die Möglichkeit, eine Ablaufzeit für das Ablaufen eines Dateilinks festzulegen, die Anzahl der Downloads und das Hinzufügen einer Option Passwort für eine zusätzliche Sicherheitsebene.

# Variables:
#   $pocket (string) - link to getpocket.com with additional attributes for analytics
#   $send (string) - link to send.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-also-when-you-sign-up-for-fallback = Wenn Sie sich für ein { -brand-name-firefox } -Konto anmelden, erhalten Sie Zugriff auf einige einzigartige Dienste wie Screenshots, <a { $pocket }>{ -brand-name-pocket }</a> und <a { $send }>{ -brand-name-send }</a> , die direkt in den Browser integriert werden. Screenshots sind eine Funktion, die direkt in den { -brand-name-firefox } -Browser integriert ist und es Ihnen ermöglicht, einen oder alle Teile einer Webseite zu kopieren oder herunterzuladen. Wenn Sie den Screenshot speichern, können Sie auch auswählen, in welchem Ordner Sie ihn finden möchten, anstatt Ihren Desktop zu überladen. Mit der Schaltfläche { -brand-name-pocket } für { -brand-name-firefox } können Sie Webseiten und Videos mit nur einem Klick auf { -brand-name-pocket } speichern, sodass Sie jederzeit und überall eine saubere, ablenkungsfreie Version lesen können - auch offline. Mit { -brand-name-send } können Sie große Dateien mit End-to-End-Verschlüsselung und einer Vielzahl von Sicherheitskontrollen freigeben, z. B. die Möglichkeit, eine Ablaufzeit für das Ablaufen eines Dateilinks festzulegen, die Anzahl der Downloads und das Hinzufügen einer optionales Passwort für eine zusätzliche Sicherheitsebene.

# Variables:
#   $attrs (string) - link to screenshots.firefox.com with additional attributes for analytics
# "Screenshots" is a brand name when capitalized and plural, but also appears here as a regular, non-brand term (lowercase and singular).
compare-safari-screenshots-is-another-popular = <a { $attrs }>Screenshots</a> sind eine weitere beliebte Funktion, die direkt in den { -brand-name-firefox } -Browser integriert ist und es Ihnen ermöglicht, auf einfache Weise ein Bild Ihres Bildschirms aufzunehmen. Wenn Sie einen Screenshot machen, können Sie die Datei kopieren oder auswählen, in welchem Ordner Sie sie finden möchten, anstatt Ihren Desktop zu überladen.

# "iCloud" is a brand name.
compare-safari-firefox-and-safari-both-provide = { -brand-name-firefox } und { -brand-name-safari } bieten beide eine nahtlose Erfahrung beim Wechsel vom Desktop zum mobilen Surfen oder umgekehrt. Für { -brand-name-safari } ist eine seiner Hauptstärken die Kontinuitätsmerkmale. Es synchronisiert Ihre Lesezeichen, Registerkarten, den Verlauf und mehr mit iCloud, sodass sie auf allen Ihren Geräten verfügbar sind. Das heißt, Sie können einen Tab auf Ihrem { -brand-name-iphone } öffnen und ihn mit nur einem Klick auch auf Ihrem { -brand-name-mac } -Laptop anzeigen lassen.
compare-safari-both-browsers-have-a-lot = Beide Browser verfügen über zahlreiche Crossover-Funktionen sowie einige einzigartige Funktionen. Wenn Sie viele Screenshots machen, werden Sie sich fragen, wie Sie jemals ohne diese praktische Funktion gelebt haben, die direkt in { -brand-name-firefox } . Wenn Sie jedoch nur nach einem schnellen, privaten Browser zum Surfen und Einkaufen suchen, sollten Sie { -brand-name-firefox } ausprobieren - insbesondere, wenn Sie ausschließlich { -brand-name-safari } da dieser als Standardbrowser vorinstalliert war dein Computer. Schließlich werden Sie feststellen, welches für Ihre Bedürfnisse besser geeignet ist.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-firefox-also-offers-a-similar = { -brand-name-firefox } bietet auch eine ähnliche Synchronisierungsfunktion, wenn Sie sich für eine kostenlose <a { $attrs }>{ -brand-name-firefox-account }</a> anmelden, mit der Benutzer ihre Lesezeichen, den Browserverlauf, Einstellungen, Kennwörter, ausgefüllte Formulare, Add-Ons und die letzten 25 geöffneten Registerkarten auf mehrere Arten einfach synchronisieren können Computers. Was { -brand-name-firefox } von { -brand-name-safari } ist, dass es auf jedem Desktop oder jeder mobilen Plattform verfügbar ist, { -brand-name-ios } , { -brand-name-android } , { -brand-name-windows } oder { -brand-name-macos } , wodurch die Portabilität auf jedem Gerät, das Sie besitzen, verbessert wird.

# Variables:
#   $ios (string) - link to TODO with additional attributes for analytics
#   $android (string) - link to TODO with additional attributes for analytics
compare-safari-the-firefox-app-for-ios-and = Die { -brand-name-firefox } App für <a { $ios }>{ -brand-name-ios }</a> und <a { $android }>{ -brand-name-android }</a> ist einer der schnellsten verfügbaren Browser und bietet außerdem solide Sicherheits- und Anti-Tracking-Funktionen - ein großes Plus, wenn Sie ständig zwischen einem Laptop und mobilen Geräten wechseln.
compare-safari-since-safari-is-apples-proprietary = Da { -brand-name-safari } proprietäre Webbrowser von { -brand-name-apple } , funktioniert die iCloud-Synchronisierung ausschließlich mit { -brand-name-apple } -Produkten. Dies kann etwas einschränkend sein, wenn Sie beispielsweise sowohl ein { -brand-name-android } Benutzer als auch ein { -brand-name-iphone } Benutzer sind oder wenn Sie einen { -brand-name-windows } -basierten PC für die Arbeit haben, aber einen { -brand-name-iphone } als Ihr persönliches Gerät verwenden.

# Variables:
#   $attrs (string) - link to TODO with additional attributes for analytics
compare-safari-safari-does-a-great-job-of = { -brand-name-safari } macht das Surfen einfach, schnell und nahtlos, wenn Sie ein { -brand-name-apple } Benutzer mit mehreren { -brand-name-apple } Produkten sind. Wie { -brand-name-safari } ist { -brand-name-firefox } ein schneller und nützlicher Browser, aber Datenschutz und plattformübergreifende Kompatibilität sind unsere bestimmenden Merkmale. { -brand-name-firefox } jeden Monat mit neuen Features und Funktionen aktualisiert. Beispielsweise hat ein kürzlich durchgeführtes Update unseren <a { $attrs }>erweiterten Verfolgungsschutz (Enhanced Tracking Protection, ETP)</a> standardmäßig für neue Benutzer aktiviert, wodurch Cookies und standortübergreifende Tracker effektiv blockiert werden.
compare-safari-in-the-end-it-just-boils = Am Ende läuft es nur darauf hinaus, was Sie in Ihrem Browser schätzen. Wenn Sie in das { -brand-name-apple } -Ökosystem integriert sind, ist { -brand-name-safari } immer noch eine gute Wahl. Wenn Sie jedoch Wert auf den neuesten und besten Schutz der Privatsphäre legen und in der Lage sind, über mehrere Betriebssysteme hinweg zu arbeiten, ist { -brand-name-firefox } unserer Meinung nach die beste Wahl. { -brand-name-firefox } ist auch eine solide Option als sekundärer Browser für { -brand-name-apple } -exklusive Benutzer, die für Online-Momente, in denen zusätzliche Ebenen des Datenschutzes erforderlich sind, möglicherweise in einen anderen Browser wechseln möchten.
