# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/chrome/

# HTML page title
compare-chrome-firefox-vs-chrome-which-is = { -brand-name-firefox } - { -brand-name-chrome } : Hangisi daha iyi?

# HTML page description
compare-chrome-we-compare-mozilla-firefox = Gizlilik, kullanışlılık ve taşınabilirlik açısından { -brand-name-mozilla } { -brand-name-firefox } { -brand-name-google } { -brand-name-chrome } ile karşılaştırıyoruz

# Main title.
compare-chrome-comparing-firefox-browser = { -brand-name-firefox-browser } ile { -brand-name-google } { -brand-name-chrome }

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge = { -brand-name-firefox } , çevrimiçi gizliliğe olan bağlılığımızı takdir eden çok sayıda sadık kullanıcımız var. Örneğin, { -brand-name-firefox } ürününün en son sürümü, dünya genelindeki tüm kullanıcılar için varsayılan olarak açık olan Gelişmiş İzleme Koruması (ETP) adlı bir özellik içerir. ETP, { -brand-name-facebook } , { -brand-name-twitter } ve LinkedIn gibi şirketlerin sosyal izleyicileri de dahil olmak üzere 2.000'den fazla izleyiciyi engeller. Ayrıca, şifrenizin ihlal edildiğini veya güncellenmesi gerektiğini size otomatik olarak bildiren <a { $attrs }>{ -brand-name-firefox-monitor }</a> adlı entegre bir özelliği vardır. Bu korumalara ek olarak, { -brand-name-firefox } içindeki Özel Tarama modu, geçmiş ve çerezler gibi göz atma bilgilerinizi otomatik olarak siler ve siz oturumunuzu bitirdikten sonra hiçbir iz bırakmaz.

# Variables:
#   $attrs (string) - link to https://monitor.firefox.com with additional attributes for analytics
compare-chrome-at-firefox-we-have-a-huge-fallback = { -brand-name-firefox } , çevrimiçi gizliliğe olan bağlılığımızı takdir eden çok sayıda sadık kullanıcımız var. Örneğin, { -brand-name-firefox } ürününün en son sürümü, dünya genelindeki tüm kullanıcılar için varsayılan olarak açık olan Gelişmiş İzleme Koruması (ETP) adlı bir özellik içerir. ETP, { -brand-name-facebook } , { -brand-name-twitter } ve LinkedIn gibi şirketlerin sosyal izleyicileri de dahil olmak üzere 2.000'den fazla izleyiciyi engeller. Ayrıca, şifrenizin ihlal edildiğini veya güncellenmesi gerektiğini size otomatik olarak bildiren <a { $attrs }>{ -brand-name-firefox-monitor }</a> adlı entegre bir özelliği vardır. Bu korumalara ek olarak, { -brand-name-firefox } 'nın Gizli Tarama modu geçmiş ve tanımlama bilgileri gibi göz atma bilgilerinizi otomatik olarak siler ve siz oturumunuzu bitirdikten sonra hiçbir iz bırakmaz.

# Variables:
#   $attrs (string) - link to mozilla.org/privacy/firefox/ with additional attributes for analytics
compare-chrome-weve-also-recently-restated = Ayrıca kısa süre önce, &quot;Mozilla'da gizliliğin sağlıklı bir internet için temel olduğuna inanıyoruz&quot; şeklinde en son <a { $attrs }>Gizlilik Bildirimimizde</a> kullanıcı verileriyle ilgili gizlilik ve şeffaflık taahhüdümüzü yeniden ifade ettik.
compare-chrome-google-chrome-is-by-all-accounts = { -brand-name-google } { -brand-name-chrome } , tüm hesaplar itibarıyla güvenli bir tarayıcıdır ve { -brand-name-google } Güvenli Tarama gibi özelliklere sahiptir. Bu, kullanıcıları tehlikeli sitelere gitmeye veya tehlikeli dosyaları indirmeye çalıştıklarında kaçırılması imkansız bir uyarı görüntüleyerek korumaya yardımcı olur.

# To "draw the line" is to establish a boundary that should not be crossed. Alternative: "it's up to you to decide whether or not or where your limit is with sharing things (...)".
compare-chrome-ultimately-its-up-to-you = Sonuçta, arama geçmişiniz ve alışveriş geçmişiniz gibi şeyleri paylaşarak çizgiyi çizip çizmemeye karar vermek size kalmıştır. Ancak çoğu insan gibi biriyseniz, muhtemelen internette gizli kalmayı tercih edeceğiniz bazı şeyler aradınız.

# "we've been heads down" means we've been hard at work. Alternative: "we've been hard at work." "Heads down" is when someone is looking down to avoid distractions and focus on the immediate task in front of them.
compare-chrome-fast-forward-to-today-the = Günümüze hızlı bir şekilde gidersek, tarayıcılar için rekabet ortamı, birçok insanın tarama geçmişi, şifreler ve diğer hassas bilgiler gibi çevrimiçi verilerine ne olduğunu sorgulamaya başlamasıyla değişti. { -brand-name-chrome } sahneye çıktığında 2008'den bu yana çok şey değişti. { -brand-name-firefox } olarak, arayüzümüzü yeniden tasarlamak ve kullanıcılara giderek artan sayıda gizlilik ve performans geliştirmelerinin yanı sıra çok sayıda kullanışlı tarayıcı aracı sağlamak için çalışıyoruz.
compare-chrome-and-so-here-we-are-the-browser = Ve işte buradayız, tarayıcı savaşları bir kez daha tırmanıyor ve { -brand-name-firefox-browser } ile { -brand-name-google } { -brand-name-chrome } arasında yeniden değerlendirme ve karşılaştırma yapma zamanı.
compare-chrome-in-2008-google-introduced = 2008'de { -brand-name-google } tanıtıldı { -brand-name-chrome } ve tarayıcı teknolojisindeki bir yenilik olarak etkisi hemen oldu. Siteleri yüklemek için daha hızlıydı, minimum ekran alanı kaplıyordu ve inkar edilemez derecede basit bir kullanıcı arayüzü sunuyordu.

# "Beside the point" means that a subject might be worth noting, but isn't the main focus (the point) of the discussion. Alternative: "but that's not the real issue."
compare-chrome-while-chrome-proves-to-be = { -brand-name-chrome } güvenli bir web tarayıcısı olduğunu kanıtlasa da, gizlilik kaydı sorgulanabilir. { -brand-name-google } aslında kullanıcılarından konum, arama geçmişi ve site ziyaretleri gibi rahatsız edici derecede büyük miktarda veri topluyor. { -brand-name-google } , daha önce satın aldığınız veya ziyaret ettiğiniz gibi bir süveter veya kahve dükkanı bulmanıza yardımcı olmak gibi, hizmetlerini iyileştirmek için yaptığını söyleyerek veri toplamayı savunur. Ancak, diğerleri buna katılmayabilir ve { -brand-name-google } aslında kendi pazarlama amaçları için eşi görülmemiş miktarda veri toplamaktadır. Bilgilerinizi bilgisayar korsanlarından gizli tuttuklarını söylediler, ama asıl mesele bu. { -brand-name-google } , büyük ölçüde kullanıcılarından topladıkları veriler sayesinde, dünyanın en büyük reklamcılık ağını kendisi işletmektedir.

compare-chrome-firefox-also-has-a-sync-feature = { -brand-name-firefox } ayrıca tüm cihazlarınızda açık ve son sekmelerinizi, tarama geçmişinizi ve yer işaretlerinizi görmek için bir senkronizasyon özelliğine sahiptir.
compare-chrome-while-chrome-gets-the-nod = { -brand-name-chrome } eklentiler ve uzantılarla başını sallasa da, { -brand-name-firefox } inanılmaz derecede kullanışlı ekran yakalama aracı ve sayfadaki her şeyi kaldıran okuma modu özelliği gibi güzelce seçilmiş yerleşik özelliklere sahiptir. okuduğunuz makaleden metin.
compare-chrome-although-not-as-extensive = { -brand-name-chrome } eklenti kitaplığı kadar kapsamlı olmasa da, { -brand-name-firefox } , çok sayıda aktif katılımcının bulunduğu açık kaynaklı bir yazılım olarak, inanılmaz sayıda yararlı uzantı da içerir.
compare-chrome-if-having-tons-of-open-tabs = Tonlarca açık sekmeye sahip olmak sizin işinizse, o zaman gerçekten UI tercihinize gelir. { -brand-name-firefox } , her yeni sekmeyle küçültmek yerine tüm açık sekmelerinizde yatay bir kaydırma sunar. { -brand-name-google } { -brand-name-chrome } yalnızca site simgesi görünecek şekilde bunları küçültmeyi tercih eder. Bununla ilgili tek sorun, aynı web sitesinde birden fazla sekme açtığınızda, sekmelerinizde aynı favicon'u görmenizdir.
compare-chrome-almost-needless-to-say-versions = Söylemeye gerek Neredeyse gereksiz, hem sürümleri { -brand-name-firefox } ve { -brand-name-chrome } en popüler masaüstü ve mobil işletim sistemleri (mevcuttur { -brand-name-windows } , { -brand-name-mac } , { -brand-name-linux } , { -brand-name-android } , { -brand-name-ios } ).
compare-chrome-both-chrome-and-firefox-also = Hem { -brand-name-chrome } hem de { -brand-name-firefox } , tüm cihazlarınız arasında şifreler, yer imleri ve açık sekmeler gibi şeyleri senkronize etmenize de olanak tanır. Bir { -brand-name-firefox } hesabınız varsa, masaüstünüzdeki açık bir sekmeyi manuel olarak mobil cihazınıza gönderebilir veya tersini yapabilirsiniz. { -brand-name-chrome } , tercihlerinizde bu ayarı seçtiyseniz, bu otomatik olarak yapılır. Daha önce bitirmediğiniz bir makaleyi okumaya devam etmek gibi bir şey yapmak istediğinizde sekmeyi bir cihazdan diğerine manuel olarak göndermek zorunda kalmamak kullanışlıdır. Ancak, birden çok kullanıcının { -brand-name-google } hesabınızda oturum açarken göz atma ihtimali varsa, otomatik senkronizasyonun ideal olmayabileceği zamanlar olabilir.

# "Neck and neck" means they are evenly matched. Alternative: "evenly matched". "Baked-in" means it's included, not added in later. Alternatives: "built-in" or "included".
compare-chrome-we-think-its-fair-to-say = Geniş uzantı kitaplığı ve eklenti özellikleri nedeniyle, { -brand-name-firefox } ve { -brand-name-chrome } nin taşınabilirlik ve kullanışlılık açısından gerçekten boyun ve boyun olduğunu söylemenin adil olduğunu düşünüyoruz. { -brand-name-chrome } Ancak, Gizlilik açısından, { -brand-name-firefox } , kullanıcılarımızın çevrimiçi verilerini koruma ve kimlik bilgilerinizle ilgili bir veri ihlali olması durumunda sizi uyaran şifre yöneticileri gibi ücretsiz hazır hizmetler sunma taahhüdümüzle günü kazanır.
compare-chrome-for-practical-purposes-theres = Pratik amaçlar için, açıkça her iki tarayıcıyı da kullanmaktan sizi alıkoyan hiçbir şey yoktur - { -brand-name-firefox } hayattaki gizliliğin gerçekten önemli olduğu anlar için ve { -brand-name-chrome } hâlâ { -brand-name-google } ekosisteme yatırım yapıyorsanız. Yine de kişisel verilerimize yönelik artan sayıda saldırı ile, { -brand-name-firefox } çevrimiçi kişisel gizliliğimizi korumaya değer veren bizler için uzun vadede doğru seçim olabilir.
