# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

### URL: https://www-dev.allizom.org/firefox/browsers/compare/

# HTML page title, also used for the main title
compare-index-seven-of-the-best-browsers-in = Doğrudan karşılaştırmada en iyi yedi tarayıcı
compare-index-six-of-the-best-browsers-fallback = Doğrudan karşılaştırmada en iyi altı tarayıcı

# Sub-headline
compare-index-privacy-utility-portability = Gizlilik. Yarar. Taşınabilirlik.

# HTML page description
compare-index-a-great-internet-browser-should = Harika bir internet tarayıcısı ihtiyacınız olan işlevselliğe, cihazlar arasında taşınabilirliğe ve hak ettiğiniz gizliliğe sahip olmalıdır.
compare-index-which-browser-is-best-at-keeping = İşleri gizli tutmada en iyi tarayıcı hangisidir?
compare-index-its-not-unreasonable-to-expect = Çevrimiçi olmak için düzenli olarak kullandığımız ürünlerden yüksek düzeyde veri koruması ve gizlilik beklemek mantıksız değildir. Bir tarayıcı, en azından, aynı bilgisayardaki diğer kullanıcıların erişememesi için geçmişinizi ve arama geçmişinizi otomatik olarak silen bir "özel tarama modu" sürümü sunmalıdır. Bu alanda, burada karşılaştırılan yedi tarayıcının tümü puan alıyor.
compare-index-its-not-unreasonable-to-expect-fallback = Çevrimiçi olmak için düzenli olarak kullandığımız ürünlerden yüksek düzeyde veri koruması ve gizlilik beklemek mantıksız değildir. Bir tarayıcı, en azından, aynı bilgisayardaki diğer kullanıcıların erişememesi için geçmişinizi ve arama geçmişinizi otomatik olarak silen bir "özel tarama modu" sürümü sunmalıdır. Bu alanda, burada karşılaştırılan altı tarayıcının tümü puan alıyor.
compare-index-what-you-do-online-literally = Çevrimiçi yaptığınız şey, kelimenin tam anlamıyla başkalarının işi olmamalıdır.
compare-index-another-browser-feature-that = Verilmesi gereken diğer bir tarayıcı özelliği, web sitelerinin ve şirketlerin tarama ve alışveriş verilerinizi normal tarama modunda bile izlemesini engelleme yeteneğidir.
compare-index-another-browser-feature-fallback = Verilmesi gereken diğer bir tarayıcı özelliği, web sitelerinin ve şirketlerin tarama ve alışveriş verilerinizi normal tarama modunda bile izlemesini engelleme yeteneğidir. Ancak aslında durum bu değil: Aslında, üçüncü taraf izleme çerezlerini varsayılan olarak engelleyen tek tarayıcılar { -brand-name-firefox } ve { -brand-name-safari } .
compare-index-using-a-browser-that-blocks = Üçüncü taraf izleyicileri engelleyen bir tarayıcı kullanmak sadece gizlilik için önemli değildir - genellikle çok daha hızlı çalıştığı anlamına gelir. Çoğu izleyici, birkaç web sitesinde arka planda çalışan komut dosyalarıdır. Onları göremezsiniz, ancak tarayıcınızı yavaşlattıklarını hissedebilirsiniz. { -brand-name-firefox } sürüm 67'den itibaren parmak izi ve kripto madenciler de engellendi. Kripto madencilere aşina değilseniz, işte sizi nasıl etkileyebileceklerine dair bir örnek: belki bilgisayarınızın aniden daha fazla ısındığını veya pilin normalden daha hızlı tükendiğini deneyimlemişsinizdir. Bu genellikle cihazınızda dolaşan kripto madencilerin yan ürünüdür.
compare-index-what-has-your-browser-done = Tarayıcınız son zamanlarda sizin için ne yaptı?
compare-index-in-addition-to-privacy-protection = Büyük ölçüde tarayıcının arka planında yer alan gizlilik korumasına ek olarak, iyi yapılmış bir tarayıcının diğer bir önemli bileşeni de gerçek kullanıcı arayüzü ve işlevselliğidir. Sekmeli gezinme, yer imi yönetimi, otomatik tamamlama, düzeltme okuması ve uzantılar söz konusu olduğunda neredeyse yedi tarayıcının tümü eşittir. { -brand-name-firefox } , { -brand-name-edge } ve { -brand-name-opera } ayrıca oldukça kullanışlı olduğunu kanıtlayan ve bu olmadan bir tarayıcıya geçtiğinizde kesinlikle eksik olduğunu fark ettiğiniz hızlı bir ekran görüntüsü işlevi sunar.
compare-index-in-addition-to-privacy-protection-fallback = Büyük ölçüde tarayıcının arka planında yer alan gizlilik korumasına ek olarak, iyi yapılmış bir tarayıcının diğer bir önemli bileşeni de gerçek kullanıcı arayüzü ve işlevselliğidir. Sekme tarama, yer imi yönetimi, otomatik tamamlama, düzeltme okuması ve uzantılar söz konusu olduğunda altı tarayıcının neredeyse tamamı eşittir. { -brand-name-firefox } , { -brand-name-edge } ve { -brand-name-opera } ayrıca oldukça kullanışlı olduğunu kanıtlayan ve bu olmadan bir tarayıcıya geçtiğinizde kesinlikle eksik olduğunu fark ettiğiniz hızlı bir ekran görüntüsü işlevi sunar.
compare-index-how-well-does-your-browser = Tarayıcınız cihazlarınız arasında ne kadar iyi çalışıyor?
compare-index-almost-all-of-the-browsers = Burada karşılaştırılan tarayıcıların neredeyse tamamı, masaüstü ve mobil cihazlar arasında senkronizasyona izin verir. Bunu yapmak için, tüm cihazlarda tarayıcıda oturum açmak ve parolalar, tarama geçmişi, yer imleri ve ayarlar gibi şeyleri senkronize etmek için kullanabileceğiniz bir hesaba ihtiyacınız olacak.
compare-index-conclusion = Sonuç:
compare-index-and-the-winner-is = Ve kazanan…
compare-index-find-out-how-firefox-chrome = Gizlilik, fayda ve taşınabilirlik açısından { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } ve { -brand-name-ie } farkları öğrenin.
compare-index-find-out-how-firefox-fallback = Gizlilik, kullanışlılık ve taşınabilirlik açısından { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } ve { -brand-name-ie } farkları öğrenin.
compare-index-looking-for-a-better-browser = Daha iyi bir tarayıcı mı arıyorsunuz? Karar vermenize yardımcı olmak için { -brand-name-firefox } ile { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } ve { -brand-name-ie } karşılaştıracağız.
compare-index-looking-for-a-better-fallback = Daha iyi bir tarayıcı mı arıyorsunuz? Karar vermenize yardımcı olmak için { -brand-name-firefox } ile { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-safari } , { -brand-name-opera } ve { -brand-name-ie } karşılaştırırız.
compare-index-so-is-your-browser-the-best = Tarayıcınız çevrimiçi yaptığınız şeyler için en iyisi mi? Doğru tarayıcı, web deneyiminizde büyük bir fark yaratabilir. Yani, daha fazla uzatmadan, { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-brave } , { -brand-name-microsoft } { -brand-name-ie } ve { -brand-name-edge } ve hangisinin ihtiyaçlarınıza en uygun olduğunu görelim.
compare-index-so-is-your-browser-the-fallback = Tarayıcınız çevrimiçi yaptığınız şeyler için en iyisi mi? Doğru tarayıcı, web deneyiminizde büyük bir fark yaratabilir. Bu yüzden, daha fazla uzatmadan { -brand-name-google } { -brand-name-chrome } , { -brand-name-firefox } , { -brand-name-safari } , { -brand-name-opera } , { -brand-name-microsoft } { -brand-name-ie } ve { -brand-name-edge } ve hangisinin ihtiyaçlarınıza en uygun olduğunu görelim.
compare-index-since-your-browser-is-your = Tarayıcınız internete açılan kapınız olduğundan, hız, güvenlik, gizlilik ve yardımcı program her şeyden önemlidir. Son yıllarda, { -brand-name-google } { -brand-name-chrome } birçokları için tercih edilen tarayıcı olmuştur. Ancak, çevrimiçi reklamların bizi her yerde takip ettiği ve veri ihlallerinin haber başlıklarının bir parçası olduğu bir zamanda, birçok insan tarayıcılarından daha fazla gizlilik ve saygı talep etmeye başlıyor.
compare-index-the-first-thing-to-point-out = Taşınabilirlik konusunda dikkat edilmesi gereken ilk şey, tüm tarayıcıların tüm işletim sistemlerinde çalışmamasıdır. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } , { -brand-name-brave } ve { -brand-name-opera } tüm büyük sistemlerde çalışırken ve yüklemeleri kolay olsa da, { -brand-name-ie } ve { -brand-name-safari } yalnızca { -brand-name-microsoft } ve Apple'ın kendi sistemlerinde çalışır. { -brand-name-safari } mobil sürümü Apple'ın mobil cihazlarına önceden yüklenmiştir ve çoğu { -brand-name-android } cihaz, cihaz için üretici tarafından değiştirilen önceden yüklenmiş bir tarayıcıyla birlikte gelir. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-brave } , { -brand-name-edge } ve { -brand-name-opera } kolayca kurulabilir ve hatta yan yana kullanılabilir.
compare-index-the-first-thing-to-point-fallback = Taşınabilirlik konusunda dikkat edilmesi gereken ilk şey, tüm tarayıcıların tüm işletim sistemlerinde çalışmamasıdır. { -brand-name-firefox } , { -brand-name-chrome } ve { -brand-name-opera } tüm büyük sistemlerde çalışırken ve yüklemeleri kolaydır, { -brand-name-ie } , { -brand-name-edge } ve { -brand-name-safari } yalnızca { -brand-name-microsoft } ve Apple'ın kendi sistemlerinde çalışır. { -brand-name-safari } mobil sürümü Apple'ın mobil cihazlarına önceden yüklenmiştir ve çoğu { -brand-name-android } cihaz, cihaz için üretici tarafından değiştirilen önceden yüklenmiş bir tarayıcıyla birlikte gelir. { -brand-name-firefox } , { -brand-name-chrome } , { -brand-name-edge } ve { -brand-name-opera } kolayca kurulabilir ve hatta yan yana kullanılabilir.
compare-index-browsers-have-come-a-long = Tarayıcılar, { -brand-name-chrome } piyasaya sunulduğundan beri uzun bir yol kat etti ve pazar payını devraldı. Modern tarayıcıların çoğu, taşınabilirlik ve işlevsellik konusundaki boşluğu kapatmış ve hız ve gizlilik gibi bazı alanlarda aslında { -brand-name-chrome } aşmıştır. Yine de, hangi tarayıcının sizin için doğru olduğunu belirlemek, her zaman kişisel ihtiyaçlarınıza ve çevrimiçi gezinirken en çok neye değer verdiğinize bağlı olacaktır.
compare-index-firefox-is-backed-by-the-not = { -brand-name-firefox } , kâr amacı gütmeyen kuruluş tarafından desteklenmektedir { -brand-name-mozilla } .
compare-index-firefox-puts-your-privacy = { -brand-name-firefox } yaptığımız ve yaptığımız her şeyde gizliliğinize öncelik verir. Kişisel bilgilerinizi nasıl ve kiminle paylaşacağınıza karar verme hakkına sahip olduğunuza inanıyoruz. { -brand-name-firefox } olabildiğince az veri toplar ve asla satmaz. Topladığımız küçük veriler yalnızca ürünleri ve özellikleri daha iyi hale getirmek için kullanılır. Sırlar yok. Ancak çok fazla şeffaflık ve gerçek mahremiyet.
compare-index-based-on-the-criteria-we-outlined = Özetlediğimiz kriterlere (gizlilik, yardımcı program ve taşınabilirlik) dayanarak, işareti karşılayan gerçekten tek bir tarayıcı var ve bu { -brand-name-firefox } . Gerçek farklılık alanı işlevsellik değil, mahremiyettir. { -brand-name-firefox } sizi bir ekosisteme kilitlemeyen en özel tarayıcıdır. Herhangi bir işletim sisteminde, tüm cihazlarınızda kullanın ve bunu yaparken kendinizi güvende hissedin.
